/**
 * Maps catalogue item ids → Simple Icons slug (when a real brand mark exists).
 * Nature / food without a public icon use generated silhouettes instead.
 */
export const MARK_ICONS = {
  // cars
  "cars__toyota": "toyota",
  "cars__honda": "honda",
  "cars__nissan": "nissan",
  "cars__mazda": "mazda",
  "cars__subaru": "subaru",
  "cars__mitsubishi": "mitsubishi",
  "cars__suzuki": "suzuki",
  "cars__lexus": "lexus",
  "cars__ford": "ford",
  "cars__chevrolet": "chevrolet",
  "cars__tesla": "tesla",
  "cars__jeep": "jeep",
  "cars__cadillac": "cadillac",
  "cars__bmw": "bmw",
  "cars__mercedes-benz": "mercedes",
  "cars__audi": "audi",
  "cars__volkswagen": "volkswagen",
  "cars__porsche": "porsche",
  "cars__opel": "opel",
  "cars__ferrari": "ferrari",
  "cars__lamborghini": "lamborghini",
  "cars__fiat": "fiat",
  "cars__alfa-romeo": "alfaromeo",
  "cars__maserati": "maserati",
  "cars__volvo": "volvo",
  "cars__skoda": "skoda",
  "cars__hyundai": "hyundai",
  "cars__kia": "kia",
  "cars__genesis": "genesis",
  "cars__peugeot": "peugeot",
  "cars__renault": "renault",
  "cars__citroen": "citroen",
  "cars__jaguar": "jaguar",
  "cars__land-rover": "landrover",
  "cars__mini": "mini",
  "cars__rolls-royce": "rollsroyce",
  "cars__bentley": "bentley",
  "cars__aston-martin": "astonmartin",
  "cars__byd": "byd",
  "cars__geely": "geely",
  // beer / drinks / food / fashion (common)
  "beer__heineken": "heineken",
  "beer__guinness": "guinness",
  "beer__carlsberg": "carlsberg",
  "coffee__starbucks": "starbucks",
  "coffee__dunkin": "dunkindonuts",
  "coffee__nespresso": "nespresso",
  "clothes__nike": "nike",
  "clothes__adidas": "adidas",
  "clothes__puma": "puma",
  "clothes__under-armour": "underarmour",
  "clothes__uniqlo": "uniqlo",
  "clothes__zara": "zara",
  "clothes__h-and-m": "hm",
  "clothes__new-balance": "newbalance",
  "clothes__vans": "vans",
  "clothes__converse": "converse",
  "clothes__patagonia": "patagonia",
  "clothes__north-face": "thenorthface",
  "clothes__lululemon": "lululemon",
  "luxury__louis-vuitton": "louisvuitton",
  "luxury__chanel": "chanel",
  "luxury__hermes": "hermes",
  "luxury__dior": "dior",
  "luxury__cartier": "cartier",
  "luxury__tiffany": "tiffany",
  "luxury__rolex": "rolex",
  "luxury__gucci": "gucci",
  "luxury__prada": "prada",
  "food__coca-cola": "cocacola",
  "food__pepsi": "pepsi",
  "food__red-bull": "redbull",
  "food__nestle": "nestle",
  "liquor__jack-daniels": "jackdaniels",
  "tea__lipton": "lipton",
};

/** Nature / generic glyphs used when no brand icon is available */
export const MARK_GLYPHS = {
  trees: "🌲",
  flowers: "❀",
  animals: "◉",
  food: "◎",
  cigarettes: "○",
  liquor: "◇",
  wine: "♤",
  sake: "☆",
  beer: "▢",
  coffee: "☕",
  tea: "♨",
  clothes: "◇",
  luxury: "✦",
  cars: "◎",
};
