import type { MessageKey } from "../lib/i18n/messages";

/** Simplified Chinese strings missing from the inline zh-CN block in messages.ts */
export const zhCNExtra: Partial<Record<MessageKey, string>> = {
  "nav.menu": "菜单",
  "nav.close": "关闭",
  "dossier.back": "← 返回账本",
  "common.people": "{count} 人",
  "common.yes": "是",
  "common.notYet": "尚未",
  "common.play": "路径",
  "common.source": "来源",
  "common.scanned": "扫描于",
  "strategy.localize_asia": "本地化到亚洲市场",
  "strategy.new_age_group": "转向其他年龄群体",
  "strategy.partner_founders": "寻求创始团队合作",
  "strategy.franchise_local": "在你的城市/国家加盟",
  "strategy.license_tech": "授权底层技术",
  "strategy.vertical_spinout": "拆分垂直细分赛道",
  "strategy.b2b_pivot": "向现有企业提供 B2B 方案",
  "dossier.name": "(i) 创意名称",
  "dossier.description": "(ii) 完整描述",
  "dossier.howMoney": "如何赚钱：",
  "dossier.location": "(iii) 团队所在地",
  "dossier.teamSize": "(iv) 团队规模",
  "dossier.industry": "(v) 行业",
  "dossier.sector": "(vi) 赛道",
  "dossier.fundraising": "(vii) 是否已获融资？",
  "dossier.website": "(viii) 官网",
  "dossier.social": "(ix) 社交媒体",
  "dossier.goForward": "(x) 前进路径",
  "sourceKind.news": "新闻",
  "sourceKind.registry": "注册库",
  "sourceKind.fundraising": "融资",
  "sourceKind.community": "社区",
  "sourceKind.government": "政府",
  "sourceKind.aggregator": "聚合",
  "time.justNow": "刚刚",
  "time.minutesAgo": "{count} 分钟前",
  "time.hoursAgo": "{count} 小时前",
  "time.daysAgo": "{count} 天前",
};
