import {
  Activity,
  Bell,
  BookOpen,
  Brain,
  Building2,
  CircuitBoard,
  ClipboardCheck,
  Compass,
  Database,
  FileText,
  GitBranch,
  Globe2,
  LayoutDashboard,
  Library,
  LineChart,
  ListTree,
  MessageSquare,
  MessagesSquare,
  Network,
  Radio,
  ScrollText,
  Settings,
  Shield,
  SlidersHorizontal,
  Sparkles,
  UserCheck,
  Users,
  Waypoints,
  Workflow,
} from "lucide-react";

export const NAV_ITEMS = [
  { href: "/admin", label: "Admin Home", icon: LayoutDashboard, permission: "admin.access" },
  { href: "/admin/dashboard", label: "Daily Performance", icon: LineChart, permission: "dashboard.read" },
  { href: "/admin/risk-log", label: "Risk Log Analytics", icon: ScrollText, permission: "monitor.read" },
  { href: "/admin/market-intel", label: "Market Intelligence", icon: Radio, permission: "monitor.read" },
  { href: "/admin/detectors", label: "Detectors", icon: CircuitBoard, permission: "detectors.read" },
  { href: "/admin/alerts", label: "Live Alerts", icon: Bell, permission: "monitor.read" },
  { href: "/admin/ai-analyses", label: "AI Analyses", icon: Brain, permission: "ai.read" },
  { href: "/admin/ai-admin", label: "AI Admin", icon: SlidersHorizontal, permission: "ai.admin" },
  { href: "/admin/interventions", label: "Human Intervention", icon: UserCheck, permission: "intervene.operate" },
  { href: "/admin/spine", label: "Spine Log", icon: Workflow, permission: "spine.read" },
  { href: "/admin/rag", label: "RAG Knowledge Base", icon: Library, permission: "rag.read" },
  { href: "/admin/knowledge-tree", label: "Knowledge Tree", icon: Network, permission: "rag.read" },
  { href: "/admin/skills", label: "AI Skills", icon: Sparkles, permission: "skills.read" },
  { href: "/admin/messenger", label: "Demo Messenger", icon: MessagesSquare, permission: "lark.read" },
  { href: "/admin/docs/urls", label: "URL Catalog", icon: ListTree, permission: "admin.access" },
  { href: "/admin/docs/user-guide", label: "User Guide", icon: BookOpen, permission: "admin.access" },
  { href: "/admin/docs/prd", label: "PRD", icon: FileText, permission: "admin.access" },
  { href: "/admin/docs/tsd", label: "TSD", icon: FileText, permission: "admin.access" },
  { href: "/admin/docs/uat", label: "UAT Checklist", icon: ClipboardCheck, permission: "admin.access" },
  { href: "/admin/docs/ecosystem", label: "Ecosystem Eval", icon: Globe2, permission: "admin.access" },
  { href: "/admin/docs/roadmap", label: "Improvement Roadmap", icon: Compass, permission: "admin.access" },
  { href: "/admin/security/ai-access", label: "AI Access Security", icon: Shield, permission: "audit.read" },
  { href: "/admin/departments", label: "Departments", icon: Building2, permission: "teams.read" },
  { href: "/admin/teams", label: "Teams", icon: Users, permission: "teams.read" },
  { href: "/admin/roles", label: "Roles & Permissions", icon: Shield, permission: "users.read" },
  { href: "/admin/users", label: "Users", icon: Users, permission: "users.read" },
  { href: "/admin/risk-domains", label: "Risk Domains", icon: Waypoints, permission: "monitor.read" },
  { href: "/admin/data-sources", label: "Data Sources", icon: Database, permission: "sources.read" },
  { href: "/admin/monitor-2", label: "Monitor 2.0", icon: Activity, permission: "monitor.read" },
  { href: "/admin/lark", label: "Lark Integration", icon: MessageSquare, permission: "lark.read" },
  { href: "/admin/escalation", label: "Escalation Routes", icon: GitBranch, permission: "escalation.read" },
  { href: "/admin/audit", label: "Audit Log", icon: BookOpen, permission: "audit.read" },
  { href: "/admin/settings", label: "Platform Settings", icon: Settings, permission: "settings.manage" },
] as const;
