/**
 * Canonical permission codes for the Roles & Permissions editor.
 * Keep in sync with ROLE_DEFS seeds in lib/db.ts.
 */
export const ALL_PERMISSIONS: string[] = [
  "*",
  "admin.access",
  "users.read",
  "users.manage",
  "teams.read",
  "teams.manage",
  "sources.read",
  "sources.manage",
  "monitor.read",
  "monitor.operate",
  "monitor.manage",
  "lark.read",
  "lark.manage",
  "cs.read",
  "cs.operate",
  "escalation.read",
  "escalation.manage",
  "audit.read",
  "settings.manage",
  "risk.intervene",
  "dashboard.read",
  "dashboard.full",
  "dashboard.ops",
  "dashboard.system",
  "rag.read",
  "rag.manage",
  "rag.approve",
  "skills.read",
  "skills.manage",
  "skills.approve",
  "ai.read",
  "ai.operate",
  "ai.admin",
  "ai.propose",
  "ai.approve",
  "detectors.read",
  "detectors.operate",
  "models.manage",
  "intervene.operate",
  "spine.read",
];

export const PERMISSION_GROUPS: Array<{ en: string; zh: string; keys: string[] }> = [
  { en: "Wildcard", zh: "萬用", keys: ["*"] },
  {
    en: "Identity & org",
    zh: "身分與組織",
    keys: ["admin.access", "users.read", "users.manage", "teams.read", "teams.manage"],
  },
  {
    en: "Monitor & risk",
    zh: "監控與風險",
    keys: [
      "monitor.read",
      "monitor.operate",
      "monitor.manage",
      "detectors.read",
      "detectors.operate",
      "risk.intervene",
      "intervene.operate",
    ],
  },
  {
    en: "Messenger & escalation",
    zh: "通訊與升級",
    keys: ["lark.read", "lark.manage", "cs.read", "cs.operate", "escalation.read", "escalation.manage", "spine.read"],
  },
  {
    en: "AI & knowledge",
    zh: "AI 與知識",
    keys: [
      "ai.read",
      "ai.operate",
      "ai.admin",
      "ai.propose",
      "ai.approve",
      "rag.read",
      "rag.manage",
      "rag.approve",
      "skills.read",
      "skills.manage",
      "skills.approve",
      "models.manage",
    ],
  },
  {
    en: "Platform",
    zh: "平台",
    keys: [
      "sources.read",
      "sources.manage",
      "settings.manage",
      "audit.read",
      "dashboard.read",
      "dashboard.full",
      "dashboard.ops",
      "dashboard.system",
    ],
  },
];
