/**
 * Explicit multi-alert / multi-party correlation patterns for the Risk scenarios doc.
 * Complements CHAIN-* timelines with fan-in / fan-out shapes operators ask about.
 */

export type CorrelationPattern =
  | "one_account_many_alerts"
  | "one_alert_many_users"
  | "cross_team"
  | "cross_book"
  | "multi_indicator_sequence"
  | "kyc_cluster"
  | "vendor_cascade";

export type CorrelationDoc = {
  id: string;
  pattern: CorrelationPattern;
  bucket: "admin_system" | "pricing" | "risk_ops" | "cs_tr";
  domain: string;
  product: string;
  editions: Array<"plus" | "classic">;
  name_en: string;
  name_zh: string;
  description_en: string;
  description_zh: string;
  indicators: string[];
  dimensions: string;
  dimensions_zh: string;
  warn: string;
  breach: string;
  frequency_en: string;
  frequency_zh: string;
  severity: "P0" | "P1" | "P2" | "P3";
  escalation_en: string;
  escalation_zh: string;
  investigation_en: string[];
  investigation_zh: string[];
  solution_en: string[];
  solution_zh: string[];
  skill_href?: string;
};

export const CORRELATION_SCENARIOS: CorrelationDoc[] = [
  {
    id: "CORR-ONE-ACCT-CREDIT-STORM",
    pattern: "one_account_many_alerts",
    bucket: "risk_ops",
    domain: "CREDIT_CLIENT",
    product: "CFD",
    editions: ["plus", "classic"],
    name_en: "One login fires margin + stop-out + NBP + equity alerts",
    name_zh: "單一登入同時觸發保證金、強平、負餘額與權益警報",
    description_en:
      "A single UID/login crosses M2-MRG-014, M2-STOP-018, M2-NBP-016 and contributes to M2-EQ-001 within one session — often a VIP, contest, or mis-leveraged book rather than a desk-wide event.",
    description_zh:
      "同一 UID／登入在同一時段跨越 M2-MRG-014、M2-STOP-018、M2-NBP-016 並貢獻 M2-EQ-001 — 常見於 VIP、競賽或錯槓桿，而非全台事件。",
    indicators: ["M2-MRG-014", "M2-STOP-018", "M2-NBP-016", "M2-EQ-001", "login.uid"],
    dimensions: "per-login alert fan-out count + util% + NBP flag",
    dimensions_zh: "每登入警報扇出數＋使用率％＋負餘額旗標",
    warn: "Same UID on ≥2 credit monitors WARN",
    breach: "Same UID on ≥3 credit monitors or any NBP+equity BREACH",
    frequency_en: "Every 1 min join on UID",
    frequency_zh: "每 1 分鐘依 UID 關聯",
    severity: "P1",
    escalation_en: "ESC-MARGIN-BREACH → Credit Risk → Ops (client) → do not mass-cut group leverage",
    escalation_zh: "ESC-MARGIN-BREACH → 信貸風險 → 營運（客戶）→ 勿大量下調組別槓桿",
    investigation_en: [
      "Confirm one UID vs shared device cluster",
      "Check entity leverage pack and open symbols",
      "See if copy provider mirrors the same login",
    ],
    investigation_zh: ["確認單一 UID 或共用裝置叢集", "核對實體槓桿包與未平商品", "確認是否為跟單提供者鏡像"],
    solution_en: [
      "Contain that login (close-only / leverage) via human gate",
      "Avoid book-wide halt unless M2-MRG-014 population also breaches",
      "Link past cases on the skill playbooks for that UID",
    ],
    solution_zh: ["對該登入人工關卡控制（close-only／槓桿）", "除非全台保證金人口也違規，勿全商品停牌", "在技能劇本連結該 UID 歷史個案"],
    skill_href: "/admin/skills/SKILL-MARGIN-SPIKE",
  },
  {
    id: "CORR-ONE-ACCT-CRYPTO-STACK",
    pattern: "one_account_many_alerts",
    bucket: "risk_ops",
    domain: "CRYPTO_EXCHANGE",
    product: "Crypto",
    editions: ["plus", "classic"],
    name_en: "One whale account: OI + funding + withdrawal + wallet float",
    name_zh: "單一巨鯨：OI＋資金費率＋出金＋熱錢包浮額",
    description_en:
      "One account holds top OI (M2-CRYPTO-OI), pays extreme funding (M2-FUNDING-RATE), queues large withdrawals (M2-WD-015) while hot float rises (M2-CRYPTO-WALLET).",
    description_zh:
      "單一帳戶佔據頭部 OI（M2-CRYPTO-OI）、支付極端資金費率（M2-FUNDING-RATE）、排隊大額出金（M2-WD-015）且熱錢包浮額上升（M2-CRYPTO-WALLET）。",
    indicators: ["M2-CRYPTO-OI", "M2-FUNDING-RATE", "M2-WD-015", "M2-CRYPTO-WALLET", "M2-CRYPTO-DEP"],
    dimensions: "OI share % + funding abs + WD USD + hot float %",
    dimensions_zh: "OI 佔比％＋資金費率絕對值＋出金美元＋熱浮額％",
    warn: "Same account on OI WARN + WD WARN",
    breach: "OI BREACH + (wallet BREACH or WD BREACH)",
    frequency_en: "Every 30 sec join on account_id",
    frequency_zh: "每 30 秒依 account_id 關聯",
    severity: "P0",
    escalation_en: "ESC-WALLET-FLOAT → Crypto Risk + System → human gate pause WD / high-lev perps",
    escalation_zh: "ESC-WALLET-FLOAT → 加密風險＋系統 → 人工關卡暫停出金／高槓桿永續",
    investigation_en: [
      "Mark vs index oracle lag on the whale’s contracts",
      "Cold-sweep capacity vs withdrawal queue",
      "Insurance fund DD if liquidation backlog also up",
    ],
    investigation_zh: ["巨鯨合約之標記價與指數預言機延遲", "冷錢包歸集能力與出金排隊", "若強平積壓上升則看保險基金回撤"],
    solution_en: [
      "Human-gated withdrawal pause / perp leverage pause",
      "Do not auto-ADL from chat",
      "Page oc_crypto_exchange_risk + oc_exec if wallet+OI both BREACH",
    ],
    solution_zh: ["人工關卡暫停出金／永續槓桿", "勿由聊天自動 ADL", "錢包＋OI 雙違規時呼叫 oc_crypto_exchange_risk 與高管橋"],
    skill_href: "/admin/skills/SKILL-CRYPTO-OI-CONC",
  },
  {
    id: "CORR-ONE-ALERT-MANY-USERS-COPY",
    pattern: "one_alert_many_users",
    bucket: "risk_ops",
    domain: "CREDIT_CLIENT",
    product: "CFD",
    editions: ["plus", "classic"],
    name_en: "One copy-concentration alert fans out to many copier logins",
    name_zh: "單一跟單集中度警報扇出至大量跟單登入",
    description_en:
      "M2-COPY-009 breach is one monitor tick, but hundreds of copier UIDs share margin/stop-out stress — one alert, many users.",
    description_zh:
      "M2-COPY-009 違規是單一監控跳動，但數百跟單 UID 同時承受保證金／強平壓力 — 一警多人。",
    indicators: ["M2-COPY-009", "M2-MRG-014", "M2-STOP-018", "M2-COPY-CHURN"],
    dimensions: "provider concentration % + distinct copier UID count",
    dimensions_zh: "提供者集中度％＋不重複跟單 UID 數",
    warn: "Top provider ≥15% with ≥50 stressed copiers",
    breach: "Top provider ≥25% or churn ≥ warn with margin BREACH",
    frequency_en: "Every 1 min",
    frequency_zh: "每 1 分鐘",
    severity: "P1",
    escalation_en: "ESC-COPY-CONC → Risk → Ops client ops → pause new copies (human)",
    escalation_zh: "ESC-COPY-CONC → 風險 → 營運客戶 → 暫停新跟單（人工）",
    investigation_en: [
      "List top copier UIDs under the provider",
      "Separate organic news vol from provider style break",
      "Check M2-FRAUD-011 for witch / multi-account copies",
    ],
    investigation_zh: ["列出該提供者下頭部跟單 UID", "區分宏觀波動與提供者風格破裂", "檢查 M2-FRAUD-011 女巫／多帳戶跟單"],
    solution_en: [
      "Cap per-provider equity; pause new copies",
      "Group leverage cut only if population margin also breaches",
      "Messenger card should list fan-out user count",
    ],
    solution_zh: ["設定每提供者權益上限；暫停新跟單", "僅在全台保證金也違規時下調組別槓桿", "Messenger 卡片應列出扇出使用者數"],
    skill_href: "/admin/skills/SKILL-COPY-CONCENTRATION",
  },
  {
    id: "CORR-ONE-ALERT-MANY-USERS-STOPOUT",
    pattern: "one_alert_many_users",
    bucket: "risk_ops",
    domain: "CREDIT_CLIENT",
    product: "CFD",
    editions: ["plus", "classic"],
    name_en: "Stop-out velocity: one monitor, many accounts liquidated",
    name_zh: "強平速度：單一監控、大量帳戶被強平",
    description_en:
      "M2-STOP-018 is one time-series, but each event is a distinct login — investigate shared symbol, LP reject, or copy provider.",
    description_zh:
      "M2-STOP-018 是單一時間序列，但每個事件是不同登入 — 調查共用商品、LP 拒絕或跟單提供者。",
    indicators: ["M2-STOP-018", "M2-FEED-003", "M2-LP-022", "M2-COPY-009"],
    dimensions: "stop-outs / 5m + distinct UID count + top symbol share",
    dimensions_zh: "每 5 分鐘強平數＋不重複 UID＋頭部商品佔比",
    warn: "≥20 stop-outs / 5m across ≥10 UIDs",
    breach: "≥40 / 5m or ≥50% from one symbol/provider",
    frequency_en: "Every 1 min (5m window)",
    frequency_zh: "每 1 分鐘（5 分鐘窗）",
    severity: "P1",
    escalation_en: "ESC-MARGIN-BREACH → Risk war-room; System if feed/LP; Ops for NBP",
    escalation_zh: "ESC-MARGIN-BREACH → 風險戰情；饋送／LP 找系統；負餘額找營運",
    investigation_en: [
      "Histogram UIDs vs symbols vs providers",
      "Confirm feed not stale before blaming toxicity",
      "Check economic calendar ±60m",
    ],
    investigation_zh: ["UID／商品／提供者直方圖", "歸咎毒性前確認饋送未過期", "檢查經濟日曆 ±60 分"],
    solution_en: [
      "Symbol close-only / pre-widen if feed OK and toxic",
      "Page LP path if rejects co-fire",
      "NBP policy via Ops — not AI auto",
    ],
    solution_zh: ["饋送正常且有毒時商品 close-only／預先拉闊", "LP 拒絕共鳴則呼叫 LP 路徑", "負餘額政策由營運 — 非 AI 自動"],
    skill_href: "/admin/skills/SKILL-STOPOUT-VELOCITY",
  },
  {
    id: "CORR-ONE-ALERT-MANY-USERS-COMPLAINT",
    pattern: "one_alert_many_users",
    bucket: "risk_ops",
    domain: "REPUTATION_COMMS",
    product: "CFD+Crypto",
    editions: ["plus", "classic"],
    name_en: "Complaint velocity alert covers many distinct clients",
    name_zh: "投訴速度警報涵蓋眾多不同客戶",
    description_en:
      "M2-COMPLAINT is one counter, but tickets reference many UIDs — often after slippage, swap, or weekend gap; fan-out to CS/TR/Risk.",
    description_zh:
      "M2-COMPLAINT 是單一計數，但工單指向多個 UID — 常在滑點、隔夜利息或週末缺口後；扇出至 CS／TR／風險。",
    indicators: ["M2-COMPLAINT", "M2-SLIP-021", "M2-SWAP-027", "M2-GAP-012"],
    dimensions: "tickets / 24h + distinct UID + theme tag",
    dimensions_zh: "每 24 小時工單＋不重複 UID＋主題標籤",
    warn: "≥30 tickets / 24h across ≥20 UIDs",
    breach: "≥80 / 24h or ≥50% same theme (slip/swap/gap)",
    frequency_en: "Hourly",
    frequency_zh: "每小時",
    severity: "P2",
    escalation_en: "Ops Lead + CS Lead; TR if fill theme; Risk if book controls needed",
    escalation_zh: "營運主管＋客服主管；成交主題交 TR；需帳簿控制則交風險",
    investigation_en: [
      "Cluster tickets by theme and symbol",
      "Do not auto-ban; separate goodwill vs control",
      "Link Monitor ticks in the same window",
    ],
    investigation_zh: ["依主題與商品叢集工單", "勿自動封禁；區分善意與控制", "連結同時段 Monitor 跳動"],
    solution_en: [
      "Comms template via Ops/CS",
      "TR owns tape; Risk owns halt/leverage",
      "Update FAQ RAG if swap/hours theme",
    ],
    solution_zh: ["由營運／客服發溝通範本", "TR 管成交帶；風險管停牌／槓桿", "若為利息／時段主題則更新 FAQ RAG"],
  },
  {
    id: "CORR-CROSS-TEAM-WAR-ROOM",
    pattern: "cross_team",
    bucket: "risk_ops",
    domain: "SYSTEMIC_FIRM",
    product: "CFD+Crypto",
    editions: ["plus", "classic"],
    name_en: "Cross-team war-room: Risk + System + Ops + AI on one incident",
    name_zh: "跨團隊戰情：風險＋系統＋營運＋AI 共處一事",
    description_en:
      "Escalation hops land on multiple BUs for one fingerprint — e.g. LP reject + bridge latency + funding exceptions + detector noise. Each team sees a different card; correlation is the incident.",
    description_zh:
      "同一指紋的升級躍點落在多個 BU — 例如 LP 拒絕＋橋接延遲＋資金例外＋偵測器噪音。各隊看到不同卡片；相關性即事件本身。",
    indicators: ["M2-LP-022", "M2-BRIDGE-LAT", "M2-FUND-010", "M2-MODEL-006", "spine.fingerprint"],
    dimensions: "distinct BU hops + open cards for same fingerprint",
    dimensions_zh: "不重複 BU 躍點＋同指紋未結卡片數",
    warn: "≥2 BUs paged for one fingerprint",
    breach: "≥3 BUs or Exec bridge + any CRITICAL",
    frequency_en: "On each escalation hop",
    frequency_zh: "每次升級躍點時",
    severity: "P0",
    escalation_en: "Bird-eye messenger relay; Risk Owner chairs; System executes armed switches",
    escalation_zh: "鳥瞰 Messenger 轉傳；風險負責人主持；系統執行已武裝開關",
    investigation_en: [
      "Group messenger threads by fingerprint",
      "Assign single incident commander",
      "AI recommends only — no dual makers across BUs",
    ],
    investigation_zh: ["依指紋合併 Messenger 討論串", "指定單一事件指揮官", "AI 僅建議 — 禁止跨 BU 雙 Maker"],
    solution_en: [
      "One spine ticket; multiple BU tasks",
      "Human gates stay with Risk checker",
      "Post-mortem in Risk Log pack",
    ],
    solution_zh: ["單一脊柱票；多個 BU 任務", "人工關卡仍由風險 Checker", "事後在風險日誌包檢討"],
  },
  {
    id: "CORR-CROSS-TEAM-CS-TR-RISK",
    pattern: "cross_team",
    bucket: "cs_tr",
    domain: "CS_SERVICE",
    product: "CFD+Crypto",
    editions: ["plus"],
    name_en: "CS intake + TR tape + Risk spine on the same client story",
    name_zh: "同一客戶故事同時走 CS 進件、TR 成交帶與風險脊柱",
    description_en:
      "Client starts in C1/form/email (CS), fill dispute goes to TR, then book-risk escalate lands on Demo Messenger — three teams, one narrative.",
    description_zh:
      "客戶自 C1／表單／郵件進 CS，成交爭議交 TR，再以帳簿風險升級到示範 Messenger — 三隊同一敘事。",
    indicators: ["M2-CS-UNCLEAR", "M2-TR-EXEC", "M2-CS-ESC", "M2-SLIP-021", "M2-FRAUD-011"],
    dimensions: "ticket skill_code transitions + teams touched",
    dimensions_zh: "工單 skill_code 轉換＋觸及團隊數",
    warn: "Same request_id touches CS+TR",
    breach: "Same request_id reaches ESCALATED_RISK with open TR+CS",
    frequency_en: "On each CS/TR status change",
    frequency_zh: "每次 CS／TR 狀態變更時",
    severity: "P1",
    escalation_en: "ESC-CS-24-7 → ESC-TR-DEAL → ESC-CS-RISK; stop CS/TR negotiating controls",
    escalation_zh: "ESC-CS-24-7 → ESC-TR-DEAL → ESC-CS-RISK；CS／TR 停止協商控制項",
    investigation_en: [
      "Follow CHAIN-CS-TR-INTAKE timeline",
      "Keep one request_id; no duplicate tickets",
      "Risk owns halt/WD pause; TR owns tape only",
    ],
    investigation_zh: ["跟隨 CHAIN-CS-TR-INTAKE 時序", "維持單一 request_id；勿重複開票", "風險管停牌／出金暫停；TR 只管成交帶"],
    solution_en: [
      "Stamp skill_code on every hop",
      "Resolve blocked while WAITING mail",
      "Human gate on Risk messenger for controls",
    ],
    solution_zh: ["每躍點蓋 skill_code", "WAITING 郵件期間禁止結案", "控制項經風險 Messenger 人工關卡"],
    skill_href: "/admin/skills/SKILL-CS-ESCALATE-RISK",
  },
  {
    id: "CORR-CROSS-BOOK-CFD-CRYPTO",
    pattern: "cross_book",
    bucket: "risk_ops",
    domain: "SYSTEMIC_FIRM",
    product: "CFD+Crypto",
    editions: ["plus", "classic"],
    name_en: "Cross-book contagion: CFD credit alerts with crypto custody stress",
    name_zh: "跨帳簿傳染：CFD 信貸警報與加密託管壓力同時",
    description_en:
      "M2-CROSS-BOOK scores when CFD margin/stop-out cluster co-fires with crypto wallet/OI/insurance — house liquidity and client confidence both hit.",
    description_zh:
      "當 CFD 保證金／強平叢集與加密錢包／OI／保險共鳴時 M2-CROSS-BOOK 計分 — 公司流動性與客戶信心同時受創。",
    indicators: ["M2-CROSS-BOOK", "M2-MRG-014", "M2-CRYPTO-WALLET", "M2-CRYPTO-OI", "M2-EQ-001"],
    dimensions: "cross-book score + CFD util count + hot float %",
    dimensions_zh: "跨帳簿分數＋CFD 使用率帳戶數＋熱浮額％",
    warn: "Cross-book score ≥0.55",
    breach: "Score ≥0.75 or CFD BREACH + wallet BREACH",
    frequency_en: "Every 1 min",
    frequency_zh: "每 1 分鐘",
    severity: "P0",
    escalation_en: "oc_exec_risk_bridge + CFD Risk + Crypto Risk; dual human gates",
    escalation_zh: "高管風險橋＋CFD 風險＋加密風險；雙人工關卡",
    investigation_en: [
      "Separate fiat funding run vs crypto on-chain drain",
      "Check stablecoin depeg exposure",
      "Confirm not just correlated BTC/gold beta",
    ],
    investigation_zh: ["區分法幣資金擠兌與鏈上加密抽離", "檢查穩定幣脫鉤曝險", "確認非僅 BTC／黃金 beta 相關"],
    solution_en: [
      "Coordinate WD pause and CFD close-only — never AI-only",
      "One commander across books",
      "See SCN-CROSS-BOOK-CONTAGION on Risk Domains",
    ],
    solution_zh: ["協調出金暫停與 CFD close-only — 絕非僅 AI", "跨帳簿單一指揮官", "見風險領域 SCN-CROSS-BOOK-CONTAGION"],
  },
  {
    id: "CORR-KYC-MULTI-UID",
    pattern: "kyc_cluster",
    bucket: "risk_ops",
    domain: "FRAUD_CONDUCT",
    product: "CFD+Crypto",
    editions: ["plus", "classic"],
    name_en: "One KYC/device cluster triggers fraud + bonus + wash + IB alerts",
    name_zh: "同一 KYC／裝置叢集觸發詐欺、贈金、對倒與 IB 警報",
    description_en:
      "Many UIDs share device/email/selfie cluster — M2-FRAUD-011 leads, then M2-BONUS-013, M2-WASH-020, M2-IB-PAYOUT co-fire on the ring.",
    description_zh:
      "多個 UID 共用裝置／郵件／自拍叢集 — M2-FRAUD-011 領先，隨後 M2-BONUS-013、M2-WASH-020、M2-IB-PAYOUT 對該團共鳴。",
    indicators: ["M2-FRAUD-011", "M2-BONUS-013", "M2-WASH-020", "M2-IB-PAYOUT", "M2-PAY-017"],
    dimensions: "cluster score + UID count in cluster + bonus USD",
    dimensions_zh: "叢集分數＋叢集內 UID 數＋贈金美元",
    warn: "Cluster score ≥0.7 with ≥3 UIDs",
    breach: "Score ≥0.85 or bonus BREACH inside cluster",
    frequency_en: "Hourly cluster job + on funding",
    frequency_zh: "每小時叢集作業＋入金時",
    severity: "P1",
    escalation_en: "ESC-MARGIN-BREACH path for risk; Ops Lead for bans; CS ID_VERIFY if login disputes",
    escalation_zh: "風險走 ESC-MARGIN-BREACH；封禁交營運主管；登入爭議交 CS ID_VERIFY",
    investigation_en: [
      "Map UID graph; freeze bonus conversion first",
      "Do not auto-ban without Ops Lead",
      "If CS ticket claims ‘it’s me’, hold ID_VERIFY",
    ],
    investigation_zh: ["繪製 UID 圖；先凍結贈金兌換", "無營運主管勿自動封禁", "若 CS 工單稱「是我本人」則留在 ID_VERIFY"],
    solution_en: [
      "Freeze payouts; link CRM KYC",
      "Escalate ring to Risk messenger if book P&L impacted",
      "Payment fraud rail separate (M2-PAY-017)",
    ],
    solution_zh: ["凍結出金；連結 CRM KYC", "若衝擊帳簿損益則升級風險 Messenger", "支付詐欺軌道分開（M2-PAY-017）"],
    skill_href: "/admin/skills/SKILL-FRAUD-CLUSTER",
  },
  {
    id: "CORR-VENDOR-CASCADE",
    pattern: "vendor_cascade",
    bucket: "admin_system",
    domain: "TECH_INFRA",
    product: "CFD+Crypto",
    editions: ["plus", "classic"],
    name_en: "Critical vendor outage cascades feed + LP + payment + Lark",
    name_zh: "關鍵供應商中斷連鎖饋送、LP、支付與 Lark",
    description_en:
      "M2-VENDOR-OUT ≥1 critical vendor down fans into M2-FEED-003, M2-LP-022, M2-FUND-010 and Lark delivery fails — one root, many monitors and teams.",
    description_zh:
      "M2-VENDOR-OUT ≥1 關鍵供應商中斷扇入 M2-FEED-003、M2-LP-022、M2-FUND-010 與 Lark 投遞失敗 — 一根因、多監控與多團隊。",
    indicators: ["M2-VENDOR-OUT", "M2-FEED-003", "M2-LP-022", "M2-FUND-010", "lark.delivery_fail_rate"],
    dimensions: "degraded vendor count + dependent monitor BREACH count",
    dimensions_zh: "降級供應商數＋相依監控違規數",
    warn: "≥1 critical vendor degraded",
    breach: "≥2 vendors or vendor + any book CRITICAL",
    frequency_en: "Every 1 min",
    frequency_zh: "每 1 分鐘",
    severity: "P0",
    escalation_en: "System on-call chairs; Risk for trading impact; Ops for funding; RM-01 phone bridge if Lark dead",
    escalation_zh: "系統值班主持；交易影響交風險；資金交營運；Lark 死則 RM-01 電話橋",
    investigation_en: [
      "Identify vendor (LP, bridge, feed, PSP, Lark)",
      "Pause dependent detectors with banner — avoid false calm",
      "Failover data source where possible",
    ],
    investigation_zh: ["識別供應商（LP、橋、饋送、支付、Lark）", "暫停相依偵測器並掛橫幅 — 避免假平靜", "盡可能切換備援資料來源"],
    solution_en: [
      "Vendor status page + internal banner",
      "Human-gated symbol halt only if toxicity confirmed",
      "Track SCN-VENDOR-DEGRADED",
    ],
    solution_zh: ["供應商狀態頁＋內部橫幅", "僅在確認有毒時人工關卡停牌", "追蹤 SCN-VENDOR-DEGRADED"],
  },
  {
    id: "CORR-PRICING-STACK",
    pattern: "multi_indicator_sequence",
    bucket: "pricing",
    domain: "MARKET_PRICING",
    product: "CFD",
    editions: ["plus", "classic"],
    name_en: "Pricing stack: stale feed → slippage → LP reject → complaints",
    name_zh: "報價堆疊：過期饋送 → 滑點 → LP 拒絕 → 投訴",
    description_en:
      "Sequence within minutes: M2-FEED-003 rises, M2-SLIP-021 spikes, M2-LP-022 rejects, then M2-COMPLAINT — classic toxic or sick-bridge path.",
    description_zh:
      "數分鐘內時序：M2-FEED-003 上升、M2-SLIP-021 暴衝、M2-LP-022 拒絕，然後 M2-COMPLAINT — 典型有毒或病橋路徑。",
    indicators: ["M2-FEED-003", "M2-SLIP-021", "M2-LP-022", "M2-BRIDGE-LAT", "M2-COMPLAINT"],
    dimensions: "sequence timing (minutes) + severity ladder",
    dimensions_zh: "時序（分鐘）＋嚴重度階梯",
    warn: "Feed WARN then slip WARN <10m",
    breach: "Feed/slip BREACH with LP BREACH same 15m",
    frequency_en: "Every 1 min correlation window",
    frequency_zh: "每 1 分鐘相關窗",
    severity: "P1",
    escalation_en: "ESC-FEED-STALE → System/Trading Infra + Risk; TR for ticket variance",
    escalation_zh: "ESC-FEED-STALE → 系統／交易基建＋風險；單票偏差交 TR",
    investigation_en: [
      "Follow CHAIN-EXECUTION-DEGRADE / CHAIN-FEED-LIQUIDATION-ERROR",
      "Distinguish news spread blowout from stale picks",
      "Manager API vs LP feed divergence",
    ],
    investigation_zh: ["跟隨 CHAIN-EXECUTION-DEGRADE／CHAIN-FEED-LIQUIDATION-ERROR", "區分新聞點差爆炸與過期撿價", "Manager API 與 LP 饋送分歧"],
    solution_en: [
      "Close-only / widen / switch LP (human)",
      "Do not treat EA speed alone as fraud",
      "CS FAQ must not quote goodwill pips",
    ],
    solution_zh: ["close-only／拉闊／切 LP（人工）", "勿僅因 EA 速度當詐欺", "CS FAQ 不得報善意 pips"],
    skill_href: "/admin/skills/SKILL-STALE-FEED",
  },
  {
    id: "CORR-MACRO-MULTI-DESK",
    pattern: "cross_team",
    bucket: "pricing",
    domain: "MARKET_PRICING",
    product: "CFD+Crypto",
    editions: ["plus", "classic"],
    name_en: "Tier-1 macro: intel + news gross + margin + gap + VaR together",
    name_zh: "一級宏觀：情報＋新聞名目＋保證金＋缺口＋VaR 同時",
    description_en:
      "Around NFP/FOMC/CPI, M2-MKT-INTEL, M2-NEWS-GROSS, M2-MRG-014, M2-GAP-012 and M2-VAR-002 co-fire — Risk, Pricing, and Comms must not treat flow as toxic by default.",
    description_zh:
      "NFP／FOMC／CPI 前後，M2-MKT-INTEL、M2-NEWS-GROSS、M2-MRG-014、M2-GAP-012 與 M2-VAR-002 共鳴 — 風險、報價與溝通預設不可當有毒流量。",
    indicators: ["M2-MKT-INTEL", "M2-NEWS-GROSS", "M2-MRG-014", "M2-GAP-012", "M2-VAR-002"],
    dimensions: "calendar ±60m flag + multi-monitor co-fire count",
    dimensions_zh: "日曆 ±60 分旗標＋多監控共鳴數",
    warn: "≥3 of these monitors WARN inside event window",
    breach: "≥4 BREACH or gap+equity BREACH in window",
    frequency_en: "Every 5 min pre-event; 1 min in window",
    frequency_zh: "事件前每 5 分鐘；窗內每 1 分鐘",
    severity: "P1",
    escalation_en: "Monitor + notify first; human gate only if toxic cluster after event",
    escalation_zh: "先監控＋通知；僅在事件後確認有毒叢集才人工關卡",
    investigation_en: [
      "Check Market Intel article URLs",
      "Prefer pre-widen over halt into the print",
      "Re-evaluate toxicity 30m after release",
    ],
    investigation_zh: ["檢查市場情報文章網址", "進發布前寧可預先拉闊而非停牌", "發布後 30 分再評估毒性"],
    solution_en: [
      "Comms to clients via Ops if needed",
      "Avoid punitive leverage cuts during pure event risk",
      "See CHAIN-MKT-INTEL-VOL / CHAIN-NEWS-GROSS-GAP",
    ],
    solution_zh: ["必要時由營運對客溝通", "純事件風險期間避免懲罰性降槓桿", "見 CHAIN-MKT-INTEL-VOL／CHAIN-NEWS-GROSS-GAP"],
    skill_href: "/admin/skills/SKILL-MARKET-INTEL",
  },
  {
    id: "CORR-ADMIN-FALSE-CALM",
    pattern: "cross_team",
    bucket: "admin_system",
    domain: "MODEL_AI",
    product: "CFD+Crypto",
    editions: ["plus", "classic"],
    name_en: "Model false calm while LP/feed/vendor actually breach",
    name_zh: "模型假平靜但 LP／饋送／供應商實際違規",
    description_en:
      "M2-MODEL-006 looks healthy or silent while M2-LP-022 / M2-FEED-003 / M2-VENDOR-OUT breach — AI confidence diverges from book reality; Risk and AI BUs both wrong if they Ack silence.",
    description_zh:
      "M2-MODEL-006 看似健康或沉默，但 M2-LP-022／M2-FEED-003／M2-VENDOR-OUT 已違規 — AI 信心與帳簿現實分歧；風險與 AI 若 Ack 沉默則雙方皆錯。",
    indicators: ["M2-MODEL-006", "M2-LP-022", "M2-FEED-003", "M2-VENDOR-OUT"],
    dimensions: "detector precision vs live BREACH count mismatch",
    dimensions_zh: "偵測精準度與即時違規數落差",
    warn: "Precision OK but ≥1 infra BREACH unacked 10m",
    breach: "Precision OK/silent with ≥2 infra BREACH or CRITICAL",
    frequency_en: "Every 5 min reconcile",
    frequency_zh: "每 5 分鐘對帳",
    severity: "P1",
    escalation_en: "ESC-MODEL-DRIFT + ESC-FEED-STALE; challenger mandatory; do not trust quiet RCA",
    escalation_zh: "ESC-MODEL-DRIFT＋ESC-FEED-STALE；強制挑戰者；勿信安靜 RCA",
    investigation_en: [
      "Compare CHAIN-MODEL-FALSE-CALM",
      "Force human review skill",
      "Pause promotion of detectors",
    ],
    investigation_zh: ["比對 CHAIN-MODEL-FALSE-CALM", "強制人工覆核技能", "暫停偵測器晉升"],
    solution_en: [
      "Banner: monitors degraded",
      "Retrain / shadow only",
      "Risk Owner checker on any control suggestion",
    ],
    solution_zh: ["橫幅：監控降級", "僅再訓練／影子", "任何控制建議需風險負責人 Checker"],
    skill_href: "/admin/skills/SKILL-DETECTOR-DRIFT",
  },
  {
    id: "CORR-REG-CAPITAL-MULTI",
    pattern: "multi_indicator_sequence",
    bucket: "risk_ops",
    domain: "REG_CAPITAL",
    product: "CFD+Crypto",
    editions: ["plus", "classic"],
    name_en: "Capital + segregation + recon + withdrawals co-fire",
    name_zh: "資本＋隔離＋對帳＋出金同時觸發",
    description_en:
      "M2-CAP-024, M2-SEG-025, M2-RECON-BRK and M2-WD-015 together — regulatory and liquidity crisis pattern spanning Risk, Ops, Finance.",
    description_zh:
      "M2-CAP-024、M2-SEG-025、M2-RECON-BRK 與 M2-WD-015 同時 — 橫跨風險、營運、財務的監管與流動性危機型態。",
    indicators: ["M2-CAP-024", "M2-SEG-025", "M2-RECON-BRK", "M2-WD-015"],
    dimensions: "capital buffer % + segregation USD gap + WD USD",
    dimensions_zh: "資本緩衝％＋隔離美元缺口＋出金美元",
    warn: "Any two WARN concurrently",
    breach: "Segregation BREACH or capital BREACH with WD WARN",
    frequency_en: "Daily EOD + intraday flash",
    frequency_zh: "每日日終＋盤中快閃",
    severity: "P0",
    escalation_en: "ESC-MARGIN-BREACH / ESC-FUNDING → Risk Owner + Ops + Finance + Exec bridge",
    escalation_zh: "ESC-MARGIN-BREACH／ESC-FUNDING → 風險負責人＋營運＋財務＋高管橋",
    investigation_en: [
      "Bank letters and chain recon evidence",
      "AI pause-WD must not be sole response to segregation",
      "Entity-by-entity capital view",
    ],
    investigation_zh: ["銀行函與鏈上對帳證據", "隔離缺口不得僅靠 AI 暫停出金", "逐實體檢視資本"],
    solution_en: [
      "Ops owns recon clear; Risk owns trading containment",
      "See CHAIN-REG-CAPITAL / CHAIN-SEGREGATION-FUNDING",
      "Comms carefully — reputation risk",
    ],
    solution_zh: ["營運清算對帳；風險負責交易遏制", "見 CHAIN-REG-CAPITAL／CHAIN-SEGREGATION-FUNDING", "溝通謹慎 — 聲譽風險"],
  },
  {
    id: "CORR-SYMBOL-MULTI-ALERT",
    pattern: "one_alert_many_users",
    bucket: "pricing",
    domain: "PRODUCT_CONFIG",
    product: "CFD",
    editions: ["plus", "classic"],
    name_en: "One symbol kill/halt with many client sessions impacted",
    name_zh: "單一商品停牌／緊急開關影響大量客戶連線",
    description_en:
      "M2-KILL-COUNT or symbol halt is one control event; M2-MT-DISC and complaints show many users — coordinate Risk (armed) and System (execute).",
    description_zh:
      "M2-KILL-COUNT 或商品停牌是單一控制事件；M2-MT-DISC 與投訴顯示許多使用者 — 需風險（武裝）與系統（執行）協調。",
    indicators: ["M2-KILL-COUNT", "M2-MT-DISC", "M2-COMPLAINT", "M2-SPREAD-005"],
    dimensions: "halted symbol count + disconnect % + complaint UIDs",
    dimensions_zh: "停牌商品數＋斷線％＋投訴 UID",
    warn: "≥1 kill with disconnect WARN",
    breach: "≥3 kills or kill without Risk Owner audit",
    frequency_en: "Every 30 sec",
    frequency_zh: "每 30 秒",
    severity: "P0",
    escalation_en: "Risk arms; System executes; Ops/CS client notice",
    escalation_zh: "風險武裝；系統執行；營運／客服客戶通知",
    investigation_en: [
      "Verify kill was maker/checker approved",
      "List affected groups/entities",
      "AI blocked from halt — confirm no service role write",
    ],
    investigation_zh: ["確認停牌已經 Maker／Checker", "列出受影響組別／實體", "AI 不得停牌 — 確認無服務角色寫入"],
    solution_en: [
      "Lift kill only with Risk Owner",
      "Comms template for status page",
      "Audit + spine must show EXECUTED_AFTER_APPROVAL",
    ],
    solution_zh: ["僅風險負責人可解除停牌", "狀態頁溝通範本", "稽核＋脊柱須顯示 EXECUTED_AFTER_APPROVAL"],
    skill_href: "/admin/skills/SKILL-SYMBOL-HALTS",
  },
  {
    id: "CORR-WEEKEND-METALS",
    pattern: "multi_indicator_sequence",
    bucket: "pricing",
    domain: "PRODUCT_CONFIG",
    product: "CFD",
    editions: ["plus", "classic"],
    name_en: "Weekend metals: XAU247 exposure + gap + NBP + promo cashback",
    name_zh: "週末貴金屬：XAU247 曝險＋缺口＋負餘額＋活動返現",
    description_en:
      "Weekend gold path: M2-XAU-247, M2-GAP-012, M2-NBP-016 and promo-driven volume — many accounts, correlated weekend risk.",
    description_zh:
      "週末黃金路徑：M2-XAU-247、M2-GAP-012、M2-NBP-016 與活動帶量 — 多帳戶、相關週末風險。",
    indicators: ["M2-XAU-247", "M2-GAP-012", "M2-NBP-016", "M2-BONUS-013", "M2-STOP-018"],
    dimensions: "net lots + gap USD + NBP accounts",
    dimensions_zh: "淨手數＋缺口美元＋負餘額帳戶",
    warn: "XAU247 WARN into weekend with gap WARN",
    breach: "XAU247 BREACH or NBP BREACH post-gap",
    frequency_en: "Every 5 min Fri–Sun",
    frequency_zh: "週五至週日每 5 分鐘",
    severity: "P1",
    escalation_en: "Risk + Product; Ops for NBP; see CHAIN-METALS-WEEKEND",
    escalation_zh: "風險＋產品；負餘額交營運；見 CHAIN-METALS-WEEKEND",
    investigation_en: [
      "Exposure limits 15k/30k lots",
      "Cashback promo uplift check",
      "Close-only when limit hit",
    ],
    investigation_zh: ["曝險上限 15k／30k 手", "檢查返現活動增量", "觸限時 close-only"],
    solution_en: [
      "Pre-widen / reduce promo if needed",
      "Human gate on limit breach actions",
      "Do not confuse with weekday XAUUSD 100oz",
    ],
    solution_zh: ["必要時預先拉闊／縮活動", "觸限動作人工關卡", "勿與平日 XAUUSD 100oz 混淆"],
    skill_href: "/admin/skills/SKILL-XAU247-EXPOSURE",
  },
  {
    id: "CORR-PAYMENT-WD-RUN",
    pattern: "one_alert_many_users",
    bucket: "risk_ops",
    domain: "OPS_PROCESS",
    product: "CFD+Crypto",
    editions: ["plus", "classic"],
    name_en: "Withdrawal run: one WD velocity alert, many clients queuing",
    name_zh: "出金潮：單一出金速度警報、大量客戶排隊",
    description_en:
      "M2-WD-015 one series; many UIDs in queue — correlate with chargebacks, fraud cluster, or crypto deposit spike (run/exploit).",
    description_zh:
      "M2-WD-015 單一序列；排隊多 UID — 關聯退單、詐欺叢集或加密入金暴衝（擠兌／攻擊）。",
    indicators: ["M2-WD-015", "M2-CHARGEBACK", "M2-FRAUD-011", "M2-CRYPTO-DEP", "M2-CRYPTO-WALLET"],
    dimensions: "WD USD / 1h + distinct UID + hot float %",
    dimensions_zh: "每小時出金美元＋不重複 UID＋熱浮額％",
    warn: "WD WARN with ≥20 UIDs",
    breach: "WD BREACH + (fraud WARN or wallet WARN)",
    frequency_en: "Every 5 min",
    frequency_zh: "每 5 分鐘",
    severity: "P0",
    escalation_en: "ESC-WALLET-FLOAT / ESC-FUNDING → Risk + Ops; human pause large WD",
    escalation_zh: "ESC-WALLET-FLOAT／ESC-FUNDING → 風險＋營運；人工暫停大額出金",
    investigation_en: [
      "Split fiat vs crypto rails",
      "Cold sweep if hot float elevated",
      "Never AI-only pause",
    ],
    investigation_zh: ["區分法幣與加密軌道", "熱浮額高則冷歸集", "絕非僅 AI 暫停"],
    solution_en: [
      "Human-gated pause + client comms",
      "See CHAIN-WITHDRAWAL-RUN / CHAIN-DEPOSIT-FLOAT",
      "Chargeback ring to Ops Lead",
    ],
    solution_zh: ["人工關卡暫停＋客戶溝通", "見 CHAIN-WITHDRAWAL-RUN／CHAIN-DEPOSIT-FLOAT", "退單團交營運主管"],
    skill_href: "/admin/skills/SKILL-WITHDRAWAL-VELOCITY",
  },
  {
    id: "CORR-MESSENGER-FANOUT",
    pattern: "cross_team",
    bucket: "admin_system",
    domain: "TECH_INFRA",
    product: "CFD+Crypto",
    editions: ["plus", "classic"],
    name_en: "One messenger card fans out to multiple POC hops",
    name_zh: "單一 Messenger 卡片扇出至多個 POC 躍點",
    description_en:
      "Demo Messenger bird-eye relay: one alert card, multiple POC chat windows along the escalation path — Ack by one must sync state for all hops.",
    description_zh:
      "示範 Messenger 鳥瞰轉傳：一張警報卡、升級路徑上多個 POC 視窗 — 一人 Ack 須同步所有躍點狀態。",
    indicators: ["messenger.card_id", "escalation.hops", "spine.stage"],
    dimensions: "POC windows open + hop index + ack state",
    dimensions_zh: "開啟的 POC 視窗＋躍點序＋Ack 狀態",
    warn: "≥2 POC windows without shared ack state",
    breach: "Conflicting Ack/Escalate on same card or SLA breach without sync",
    frequency_en: "Realtime on card actions",
    frequency_zh: "卡片動作即時",
    severity: "P2",
    escalation_en: "System fixes sync; Risk Owner resolves conflict; audit both actions",
    escalation_zh: "系統修復同步；風險負責人解決衝突；兩邊動作皆稽核",
    investigation_en: [
      "Replay card action log",
      "Ensure spine single stage transition",
      "Check Lark mock vs live delivery",
    ],
    investigation_zh: ["重放卡片動作日誌", "確保脊柱單一階段轉換", "檢查 Lark mock 與正式投遞"],
    solution_en: [
      "Authoritative ack in spine",
      "Close duplicate POC threads",
      "UAT covers multi-POC relay",
    ],
    solution_zh: ["脊柱為 Ack 權威", "關閉重複 POC 討論串", "UAT 覆蓋多 POC 轉傳"],
  },
];

export function correlationPatternLabel(pattern: CorrelationPattern, zh: boolean): string {
  const map: Record<CorrelationPattern, { en: string; zh: string }> = {
    one_account_many_alerts: { en: "One account → many alerts", zh: "一帳戶 → 多警報" },
    one_alert_many_users: { en: "One alert → many users", zh: "一警報 → 多使用者" },
    cross_team: { en: "Cross-team", zh: "跨團隊" },
    cross_book: { en: "Cross-book", zh: "跨帳簿" },
    multi_indicator_sequence: { en: "Multi-indicator sequence", zh: "多指標時序" },
    kyc_cluster: { en: "KYC / device cluster", zh: "KYC／裝置叢集" },
    vendor_cascade: { en: "Vendor cascade", zh: "供應商連鎖" },
  };
  return zh ? map[pattern].zh : map[pattern].en;
}
