export type UatSeverity = "Critical" | "High" | "Medium" | "Low";

export type UatCase = {
  seq: number;
  id: string;
  /** Suggested start offset from UAT T0, in minutes */
  t_start_min: number;
  /** Suggested max duration for the case, in minutes */
  duration_min: number;
  severity: UatSeverity;
  bu: string;
  dependency: string;
  en: {
    title: string;
    objective: string;
    steps: string[];
    pass: string;
    evidence: string;
  };
  zh: {
    title: string;
    objective: string;
    steps: string[];
    pass: string;
    evidence: string;
  };
};

/** Full Risk Owner UAT log — execute in sequence; do not skip Critical predecessors. */
export const UAT_CASES: UatCase[] = [
  {
    seq: 1,
    id: "UAT-01",
    t_start_min: 0,
    duration_min: 10,
    severity: "Critical",
    bu: "System + Risk Owner",
    dependency: "Seeded users; app running",
    en: {
      title: "Login & RBAC gate",
      objective: "Confirm Risk Owner can enter admin; least-privilege roles are blocked from AI Admin.",
      steps: [
        "Open /login and sign in as risk.owner@vantagemarkets.com / risk123.",
        "Confirm Admin Home loads with department RACI visible.",
        "Sign out; sign in as viewer@vantagemarkets.com / view123.",
        "Attempt to open /admin/ai-admin — expect redirect or forbidden.",
        "Sign back in as Risk Owner (or Super Admin for remaining cases if delegated).",
      ],
      pass: "Risk Owner reaches Admin Home; Viewer cannot operate AI Admin.",
      evidence: "Screenshot of Admin Home + Viewer denied state; note in Audit LOGIN events.",
    },
    zh: {
      title: "登入與 RBAC 閘道",
      objective: "確認風險負責人可進入管理後台；低權限角色無法進入 AI Admin。",
      steps: [
        "開啟 /login，以 risk.owner@vantagemarkets.com / risk123 登入。",
        "確認管理首頁載入且可見部門 RACI。",
        "登出後以 viewer@vantagemarkets.com / view123 登入。",
        "嘗試開啟 /admin/ai-admin — 應被導向或拒絕。",
        "改回風險負責人（或授權之超級管理員）繼續後續案例。",
      ],
      pass: "風險負責人可進首頁；Viewer 無法操作 AI Admin。",
      evidence: "首頁與拒絕狀態截圖；稽核 LOGIN 事件。",
    },
  },
  {
    seq: 2,
    id: "UAT-02",
    t_start_min: 10,
    duration_min: 10,
    severity: "Critical",
    bu: "Risk",
    dependency: "UAT-01; Monitor indicators seeded",
    en: {
      title: "Monitor 2.0 indicator registry",
      objective: "Verify CFD/Crypto indicators required for demo alarms exist.",
      steps: [
        "Open /admin/monitor-2.",
        "Locate M2-EQ-001, M2-MRG-014, M2-COPY-009 (and note product/domain).",
        "Open /admin/alerts and confirm live/open alerts list renders.",
        "Record current open-alert count as baseline.",
      ],
      pass: "≥1 indicator for equity, margin, copy concentration; alerts page loads.",
      evidence: "Indicator IDs listed in UAT notes; baseline open count.",
    },
    zh: {
      title: "Monitor 2.0 指標登錄",
      objective: "確認示範警報所需 CFD/Crypto 指標存在。",
      steps: [
        "開啟 /admin/monitor-2。",
        "找到 M2-EQ-001、M2-MRG-014、M2-COPY-009 並記錄產品／領域。",
        "開啟 /admin/alerts 確認列表可顯示。",
        "記錄目前 OPEN 警報數作為基線。",
      ],
      pass: "股權／保證金／跟單集中度各至少 1 個指標；警報頁可載入。",
      evidence: "UAT 筆記中的指標 ID 與基線數量。",
    },
  },
  {
    seq: 3,
    id: "UAT-03",
    t_start_min: 20,
    duration_min: 15,
    severity: "Critical",
    bu: "AI + Risk",
    dependency: "UAT-02; AI skills seeded; ai.operate permission",
    en: {
      title: "Skill-path RCA on COPY breach",
      objective: "Prove certain skill match executes playbook and stores evidence.",
      steps: [
        "Open /admin/ai-analyses.",
        "Click “Simulate COPY breach (skill path)”.",
        "Wait for navigation/refresh to the new analysis detail.",
        "Confirm mode = SKILL_MATCH and confidence shows 100% (or skill certainty).",
        "In Evidence vault, confirm SKILL + MONITOR rows exist.",
        "Note analysis_id for later messenger/audit cases.",
      ],
      pass: "Mode SKILL_MATCH; evidence includes SKILL and MONITOR; analysis_id recorded.",
      evidence: "analysis_id; screenshot of mode badge + evidence types.",
    },
    zh: {
      title: "COPY breach 技能路徑 RCA",
      objective: "證明確定技能匹配會執行劇本並寫入證據。",
      steps: [
        "開啟 /admin/ai-analyses。",
        "點「Simulate COPY breach (skill path)」。",
        "等待導向或重新整理至新分析詳情。",
        "確認 mode = SKILL_MATCH，信心為技能確定值。",
        "於證據庫確認有 SKILL 與 MONITOR。",
        "記下 analysis_id 供後續 messenger／稽核使用。",
      ],
      pass: "Mode 為 SKILL_MATCH；證據含 SKILL 與 MONITOR；已記錄 analysis_id。",
      evidence: "analysis_id；模式徽章與證據類型截圖。",
    },
  },
  {
    seq: 4,
    id: "UAT-04",
    t_start_min: 35,
    duration_min: 15,
    severity: "Critical",
    bu: "AI + Risk Owner",
    dependency: "UAT-03 or any BREACH/CRITICAL analysis; challenger enabled",
    en: {
      title: "Independent second-AI challenger",
      objective: "High-severity RCA must include challenger verdict and improvements.",
      steps: [
        "From AI Analyses, open a BREACH or CRITICAL analysis (or run Simulate CRITICAL).",
        "Confirm list badge shows “2nd AI · {verdict}”.",
        "On detail, locate Second AI challenger panel (crmp-challenger-v0).",
        "Read critique, recommended improvements, alternative hypotheses.",
        "If verdict is PARTIAL or DISAGREE, confirm needs_human is indicated.",
        "Confirm Evidence vault contains a CHALLENGER row.",
      ],
      pass: "Challenger panel present with verdict; ≥1 HIGH improvement; CHALLENGER evidence row.",
      evidence: "challenge_id; verdict; screenshot of improvements column.",
    },
    zh: {
      title: "獨立第二 AI 挑戰者",
      objective: "高嚴重度 RCA 必須含挑戰者結論與改進建議。",
      steps: [
        "於 AI 分析開啟 BREACH／CRITICAL（或執行 Simulate CRITICAL）。",
        "確認列表有「2nd AI · {verdict}」徽章。",
        "詳情頁找到第二 AI 挑戰者面板（crmp-challenger-v0）。",
        "閱讀批評、改進建議、替代假說。",
        "若為 PARTIAL／DISAGREE，確認標示 needs_human。",
        "證據庫含 CHALLENGER 列。",
      ],
      pass: "有挑戰面板與 verdict；≥1 項 HIGH 改進；有 CHALLENGER 證據。",
      evidence: "challenge_id、verdict、改進欄截圖。",
    },
  },
  {
    seq: 5,
    id: "UAT-05",
    t_start_min: 50,
    duration_min: 10,
    severity: "High",
    bu: "AI",
    dependency: "UAT-02; ai.second_opinion_severity=BREACH (default)",
    en: {
      title: "WARN path does not invoke challenger",
      objective: "Second AI only runs at/above configured severity threshold.",
      steps: [
        "On AI Analyses, click “Simulate EQ drawdown (RAG path)” with WARN severity.",
        "Open the resulting analysis.",
        "Confirm Second AI panel shows Not run / no challenge badge for 2nd AI verdict.",
        "Confirm challenged flag is not set (or challenge absent).",
      ],
      pass: "No challenge row for WARN-only sample under default BREACH threshold.",
      evidence: "analysis_id; screenshot of “Not run” challenger panel.",
    },
    zh: {
      title: "WARN 路徑不觸發挑戰者",
      objective: "第二 AI 僅在達到設定嚴重度門檻時執行。",
      steps: [
        "於 AI 分析點「Simulate EQ drawdown」WARN。",
        "開啟產生的分析。",
        "確認第二 AI 面板為 Not run／無 2nd AI 結論徽章。",
        "確認未寫入 challenge。",
      ],
      pass: "預設 BREACH 門檻下，純 WARN 樣本無 challenge。",
      evidence: "analysis_id；Not run 面板截圖。",
    },
  },
  {
    seq: 6,
    id: "UAT-06",
    t_start_min: 60,
    duration_min: 15,
    severity: "High",
    bu: "AI + Risk",
    dependency: "RAG corpus seeded",
    en: {
      title: "RAG reasoning path",
      objective: "Uncertain/no-skill path produces RAG RCA with external/internal evidence candidates.",
      steps: [
        "Use Simulate EQ WARN/RAG path or an indicator without certain skill match.",
        "Open analysis and confirm mode = RAG_REASONING.",
        "Confirm at least one explanation hypothesis is present.",
        "Confirm evidence vault has non-empty rows (MONITOR and/or EXTERNAL/RAG).",
      ],
      pass: "Mode RAG_REASONING; ≥1 explanation; evidence present.",
      evidence: "analysis_id; mode badge; evidence list screenshot.",
    },
    zh: {
      title: "RAG 推理路徑",
      objective: "不確定／無技能路徑產出 RAG RCA 與證據。",
      steps: [
        "使用 EQ WARN／RAG 模擬或無確定技能之指標。",
        "開啟分析確認 mode = RAG_REASONING。",
        "確認至少一則說明假說。",
        "證據庫非空（MONITOR 與／或 EXTERNAL／RAG）。",
      ],
      pass: "Mode 為 RAG_REASONING；≥1 說明；有證據。",
      evidence: "analysis_id；模式與證據截圖。",
    },
  },
  {
    seq: 7,
    id: "UAT-07",
    t_start_min: 75,
    duration_min: 10,
    severity: "High",
    bu: "Risk",
    dependency: "UAT-03/04; messenger schema; lark.read",
    en: {
      title: "Messenger — show evidence",
      objective: "Inline evidence action posts vault + challenger summary into chat.",
      steps: [
        "Open /admin/messenger.",
        "Click Sync alerts if thread list is empty/stale.",
        "Select an OPEN BREACH thread linked to an analysis.",
        "Click Show evidence.",
        "Confirm an EVIDENCE message appears with vault lines and admin link.",
      ],
      pass: "EVIDENCE message in thread within 10s; includes admin deep-link when analysis linked.",
      evidence: "thread_id; screenshot of EVIDENCE message.",
    },
    zh: {
      title: "Messenger — 顯示證據",
      objective: "內嵌證據操作將證據庫與挑戰摘要貼入聊天。",
      steps: [
        "開啟 /admin/messenger。",
        "若列表空白／過舊，點 Sync alerts。",
        "選擇已連結分析的 OPEN BREACH 執行緒。",
        "點 Show evidence。",
        "確認出現 EVIDENCE 訊息與管理連結。",
      ],
      pass: "10 秒內出現 EVIDENCE；有分析時含管理深連結。",
      evidence: "thread_id；EVIDENCE 截圖。",
    },
  },
  {
    seq: 8,
    id: "UAT-08",
    t_start_min: 85,
    duration_min: 10,
    severity: "High",
    bu: "Risk Analyst + Risk Owner",
    dependency: "UAT-07; open messenger thread",
    en: {
      title: "Messenger — chatbot challenge",
      objective: "Operator can challenge AI narrative; system flags human review.",
      steps: [
        "In the same OPEN thread, type: “I disagree with the AI — please review feed integrity”.",
        "Send via chatbot composer.",
        "Confirm USER + CHATBOT messages appear.",
        "Confirm bot acknowledges challenge and analysis is flagged needs_human when linked.",
      ],
      pass: "Chatbot reply recorded; linked analysis needs_human=1 (or explicit human-review language).",
      evidence: "Screenshot of USER/CHATBOT pair; analysis needs_human state.",
    },
    zh: {
      title: "Messenger — 聊天挑戰",
      objective: "操作者可挑戰 AI 敘事；系統標記人工覆核。",
      steps: [
        "於同一 OPEN 執行緒輸入：「我不同意 AI，請覆核報價完整性」。",
        "送出。",
        "確認出現 USER 與 CHATBOT 訊息。",
        "確認機器人承認挑戰，且連結分析標記 needs_human。",
      ],
      pass: "聊天回應已記錄；連結分析 needs_human=1（或明確人工覆核用語）。",
      evidence: "USER／CHATBOT 截圖；needs_human 狀態。",
    },
  },
  {
    seq: 9,
    id: "UAT-09",
    t_start_min: 95,
    duration_min: 10,
    severity: "High",
    bu: "Risk",
    dependency: "Escalation routes seeded; open thread",
    en: {
      title: "Messenger — escalate path",
      objective: "Escalate advances the predefined decision-maker chain.",
      steps: [
        "On an OPEN thread, click Escalate once.",
        "Read ESCALATION message: step index, target team, SLA, full path.",
        "Click Escalate again.",
        "Confirm step increments and next team changes toward Risk Owner / Exec.",
      ],
      pass: "Two escalations produce increasing step numbers and path text includes next owners.",
      evidence: "Screenshots after step 1 and step 2; route name noted.",
    },
    zh: {
      title: "Messenger — 升級路徑",
      objective: "升級沿預設決策鏈前進。",
      steps: [
        "於 OPEN 執行緒點 Escalate 一次。",
        "閱讀 ESCALATION：步驟、目標團隊、SLA、完整路徑。",
        "再點 Escalate。",
        "確認步驟遞增，下一個團隊朝 Risk Owner／Exec 前進。",
      ],
      pass: "兩次升級步驟遞增，路徑文字含下一負責人。",
      evidence: "步驟 1／2 截圖；路線名稱。",
    },
  },
  {
    seq: 10,
    id: "UAT-10",
    t_start_min: 105,
    duration_min: 8,
    severity: "Medium",
    bu: "Risk",
    dependency: "Separate OPEN WARN test thread (do not use Critical sample)",
    en: {
      title: "Messenger — dismiss false alarm",
      objective: "False alarms can be dismissed with alert closure.",
      steps: [
        "Select a disposable OPEN WARN thread.",
        "Click Dismiss (false alarm).",
        "Confirm thread status becomes DISMISSED.",
        "Confirm related monitor alert moves to CLOSED (or equivalent).",
      ],
      pass: "Thread DISMISSED; linked alert closed; action audited.",
      evidence: "thread_id before/after; Audit MESSENGER_DISMISS.",
    },
    zh: {
      title: "Messenger — 排除誤報",
      objective: "誤報可排除並關閉警報。",
      steps: [
        "選擇可拋棄的 OPEN WARN 執行緒。",
        "點 Dismiss (false alarm)。",
        "確認執行緒狀態為 DISMISSED。",
        "確認關聯警報關閉。",
      ],
      pass: "執行緒 DISMISSED；警報關閉；有稽核。",
      evidence: "前後 thread_id；Audit MESSENGER_DISMISS。",
    },
  },
  {
    seq: 11,
    id: "UAT-11",
    t_start_min: 115,
    duration_min: 10,
    severity: "Critical",
    bu: "Risk Owner",
    dependency: "UAT-04 dual-AI pack reviewed on a BREACH thread",
    en: {
      title: "Messenger — close accept AI",
      objective: "Risk Owner can accept dual-AI pack and close the case.",
      steps: [
        "Open a BREACH thread whose dual-AI pack was reviewed (not the dismissed WARN).",
        "Click Close (accept AI).",
        "Confirm thread CLOSED.",
        "Confirm evidence/challenger artifacts remain available on the AI analysis page.",
      ],
      pass: "Thread CLOSED; analysis evidence retained; Audit MESSENGER_CLOSE.",
      evidence: "thread_id; analysis detail still shows challenger panel.",
    },
    zh: {
      title: "Messenger — 結案接受 AI",
      objective: "風險負責人可接受雙 AI 包並結案。",
      steps: [
        "開啟已覆核雙 AI 包的 BREACH 執行緒（非已排除之 WARN）。",
        "點 Close (accept AI)。",
        "確認執行緒 CLOSED。",
        "確認 AI 分析頁仍可看見證據／挑戰者產物。",
      ],
      pass: "執行緒 CLOSED；證據保留；有 Audit MESSENGER_CLOSE。",
      evidence: "thread_id；分析詳情仍顯示挑戰面板。",
    },
  },
  {
    seq: 12,
    id: "UAT-12",
    t_start_min: 125,
    duration_min: 15,
    severity: "Critical",
    bu: "Ops + Risk Owner",
    dependency: "OPEN thread; interventions page",
    en: {
      title: "Recommended control + double confirm + checker",
      objective: "Non-escalation controls require explicit confirm and may need checker.",
      steps: [
        "On an OPEN thread, under Recommended actions, click Block user account.",
        "Confirm ACTION_PROPOSAL appears.",
        "Click Double-confirm… then Yes, send to Vantage admin.",
        "Confirm ACTION_RESULT with admin_ref and link to /admin/interventions.",
        "If AWAITING_CHECKER, open Interventions / follow checker instruction message.",
        "Risk Owner or designated checker completes approval path (prototype note acceptable).",
      ],
      pass: "Admin ref created; confirm gate shown before send; checker follow-up when required.",
      evidence: "admin_ref; screenshots of proposal → confirm → result.",
    },
    zh: {
      title: "建議控制＋雙重確認＋Checker",
      objective: "非升級控制須明確確認，且可能需要 Checker。",
      steps: [
        "於 OPEN 執行緒建議控制點 Block user account。",
        "確認出現 ACTION_PROPOSAL。",
        "點 Double-confirm… 再 Yes, send to Vantage admin。",
        "確認 ACTION_RESULT 含 admin_ref 與 /admin/interventions 連結。",
        "若 AWAITING_CHECKER，依系統訊息至 Interventions。",
        "風險負責人或指定 Checker 完成核准（原型說明可接受）。",
      ],
      pass: "已產生 admin_ref；送出前有確認閘道；需要時有 Checker 後續。",
      evidence: "admin_ref；提案→確認→結果截圖。",
    },
  },
  {
    seq: 13,
    id: "UAT-13",
    t_start_min: 140,
    duration_min: 20,
    severity: "Critical",
    bu: "AI Engineer + Risk Owner",
    dependency: "Two distinct users with ai.admin / checker capability",
    en: {
      title: "AI Admin maker ≠ checker",
      objective: "Configuration changes cannot be self-approved.",
      steps: [
        "Sign in as AI Engineer (ai.engineer@… / ai123).",
        "Open /admin/ai-admin; propose a harmless setting/model change (maker).",
        "Attempt to approve as the same user — expect block/failure.",
        "Sign in as a different checker-capable user (e.g. Risk Owner or Super Admin per RBAC).",
        "Approve the pending change.",
        "Confirm change applied only after checker approval.",
      ],
      pass: "Self-approve blocked; distinct checker succeeds; audit shows maker and checker.",
      evidence: "Change request id; Audit entries for propose + approve.",
    },
    zh: {
      title: "AI Admin Maker ≠ Checker",
      objective: "設定變更不可自我核准。",
      steps: [
        "以 AI 工程師登入（ai.engineer@… / ai123）。",
        "開啟 /admin/ai-admin，提出無害設定／模型變更（Maker）。",
        "同一使用者嘗試核准 — 應被阻擋。",
        "改以不同 Checker 能力使用者登入。",
        "核准待審變更。",
        "確認僅在 Checker 核准後生效。",
      ],
      pass: "自我核准被擋；不同 Checker 成功；稽核含 Maker 與 Checker。",
      evidence: "變更單號；提出＋核准稽核。",
    },
  },
  {
    seq: 14,
    id: "UAT-14",
    t_start_min: 160,
    duration_min: 15,
    severity: "Medium",
    bu: "Risk + AI",
    dependency: "market_intel.enabled=true",
    en: {
      title: "Market Intelligence 5-minute scan",
      objective: "Intel scanner produces findings/outbox suitable for messenger push.",
      steps: [
        "Open /admin/market-intel.",
        "Run scan (or wait for scheduler).",
        "Open Findings and Messenger outbox tabs.",
        "Confirm a scan id is logged even if zero new findings.",
        "Spot-check card formatting fields if a finding exists.",
      ],
      pass: "Scan completes without error; outbox or scan history updated.",
      evidence: "scan_id; screenshot of findings or empty-scan log.",
    },
    zh: {
      title: "市場情報 5 分鐘掃描",
      objective: "情報掃描產出可供推送之發現／outbox。",
      steps: [
        "開啟 /admin/market-intel。",
        "執行掃描（或等待排程）。",
        "開啟 Findings 與 Messenger outbox。",
        "即使零新增，亦應有 scan 紀錄。",
        "若有發現，抽查卡片欄位格式。",
      ],
      pass: "掃描無錯誤完成；outbox 或掃描歷史更新。",
      evidence: "scan_id；發現或空掃描截圖。",
    },
  },
  {
    seq: 15,
    id: "UAT-15",
    t_start_min: 175,
    duration_min: 10,
    severity: "High",
    bu: "System + Security",
    dependency: "AI access blocklist seeded",
    en: {
      title: "AI access blocklist review",
      objective: "Human-only surfaces are listed with reasons for AI denial.",
      steps: [
        "Open /admin/security/ai-access.",
        "Filter/search for users.password or equivalent sensitive field.",
        "Confirm pages, functions, and fields sections are populated.",
        "Record that AI must not be granted these in production IAM.",
      ],
      pass: "Blocklist UI lists human-only items with reason text; sensitive examples present.",
      evidence: "Screenshot of blocklist rows; count of page/function/field items.",
    },
    zh: {
      title: "AI 存取黑名單覆核",
      objective: "僅限人類介面須列出並說明拒絕 AI 之理由。",
      steps: [
        "開啟 /admin/security/ai-access。",
        "搜尋 users.password 或同等敏感欄位。",
        "確認頁面／功能／欄位分區有資料。",
        "記錄正式 IAM 不得授予 AI 這些權限。",
      ],
      pass: "黑名單 UI 含理由；可見敏感範例。",
      evidence: "黑名單列截圖；各區數量。",
    },
  },
  {
    seq: 16,
    id: "UAT-16",
    t_start_min: 185,
    duration_min: 15,
    severity: "High",
    bu: "System",
    dependency: "UAT-07 through UAT-12 performed",
    en: {
      title: "Audit Log & Spine correlation",
      objective: "Messenger and AI actions leave correlatable audit/spine events.",
      steps: [
        "Open /admin/audit; filter recent MESSENGER_* / AI_* events.",
        "Open /admin/spine; locate AI_RCA, ESCALATION, INTERVENTION stages.",
        "Match at least one messenger escalate and one confirm-action to spine/audit.",
        "Confirm timestamps within ~1 minute of the UAT actions.",
      ],
      pass: "≥1 escalate and ≥1 control confirm visible in Audit and/or Spine with matching refs.",
      evidence: "Event ids; screenshot pair Audit + Spine.",
    },
    zh: {
      title: "稽核日誌與脊柱對應",
      objective: "Messenger 與 AI 操作留下可對應之稽核／脊柱事件。",
      steps: [
        "開啟 /admin/audit，篩選近期 MESSENGER_*／AI_*。",
        "開啟 /admin/spine，找到 AI_RCA、ESCALATION、INTERVENTION。",
        "至少對上一次升級與一次確認控制。",
        "確認時間戳與 UAT 操作約 1 分鐘內。",
      ],
      pass: "Audit 與／或 Spine 可見≥1 次升級與≥1 次控制確認。",
      evidence: "事件 id；Audit＋Spine 截圖。",
    },
  },
  {
    seq: 17,
    id: "UAT-17",
    t_start_min: 200,
    duration_min: 10,
    severity: "Low",
    bu: "All",
    dependency: "Docs published under /admin/docs/*",
    en: {
      title: "Bilingual documentation toggle",
      objective: "PRD, TSD, User Guide, UAT, Ecosystem render in EN and zh-Hant.",
      steps: [
        "Open /admin/docs/user-guide?lang=en then ?lang=zh-Hant.",
        "Repeat for /admin/docs/prd, /admin/docs/tsd, /admin/docs/ecosystem, this UAT page.",
        "Confirm language toggle buttons switch content without 404.",
      ],
      pass: "Both languages render for each listed doc; no missing-file stub.",
      evidence: "Checklist of URLs tested EN/ZH.",
    },
    zh: {
      title: "雙語文件切換",
      objective: "PRD、TSD、使用手冊、UAT、生態評估可以英／繁中顯示。",
      steps: [
        "開啟使用手冊 en 與 zh-Hant。",
        "對 PRD、TSD、生態評估、本 UAT 頁重複。",
        "確認語言切換無 404。",
      ],
      pass: "所列文件兩語皆可渲染；非缺檔 stub。",
      evidence: "已測 URL 清單。",
    },
  },
  {
    seq: 18,
    id: "UAT-18",
    t_start_min: 210,
    duration_min: 15,
    severity: "Medium",
    bu: "All",
    dependency: "Responsive admin shell",
    en: {
      title: "Mobile smoke (≈390px)",
      objective: "Risk Owner can operate messenger and AI detail on phone width.",
      steps: [
        "Resize browser to ~390px width (or device emulation).",
        "Open Admin Home — hamburger opens drawer; no horizontal page overflow.",
        "Open Messenger — see thread list; open a thread; use Threads back.",
        "Open an AI analysis detail — challenger sections stack; primary CTAs usable.",
      ],
      pass: "Drawer works; messenger master-detail works; no document-level horizontal overflow.",
      evidence: "Mobile screenshots of drawer, messenger list, messenger thread, AI detail.",
    },
    zh: {
      title: "行動裝置煙測（≈390px）",
      objective: "風險負責人可在手機寬度操作 messenger 與 AI 詳情。",
      steps: [
        "瀏覽器寬度約 390px（或裝置模擬）。",
        "開啟管理首頁 — 漢堡開啟抽屜；無整頁橫向溢出。",
        "開啟 Messenger — 先列表再進執行緒；Threads 返回。",
        "開啟 AI 分析詳情 — 挑戰區塊直向堆疊；主要 CTA 可用。",
      ],
      pass: "抽屜可用；messenger 主從可用；無文件級橫向溢出。",
      evidence: "抽屜／列表／執行緒／AI 詳情手機截圖。",
    },
  },
  {
    seq: 19,
    id: "UAT-19",
    t_start_min: 225,
    duration_min: 10,
    severity: "Medium",
    bu: "Risk Owner",
    dependency: "UAT-04 samples in window",
    en: {
      title: "Dual-AI coverage gate",
      objective: "Every BREACH/CRITICAL analysis in the UAT window has a challenger.",
      steps: [
        "On AI Analyses, filter/scan items with severity BREACH or CRITICAL created during UAT.",
        "Confirm each shows 2nd AI badge (not “pending”).",
        "If any pending, run Backfill 2nd AI challenges and re-check.",
      ],
      pass: "100% of BREACH/CRITICAL samples in UAT window have challenger verdict.",
      evidence: "Count of BREACH/CRITICAL vs challenged count.",
    },
    zh: {
      title: "雙 AI 覆蓋閘道",
      objective: "UAT 期間每個 BREACH／CRITICAL 分析皆有挑戰者。",
      steps: [
        "於 AI 分析檢視 UAT 期間 BREACH／CRITICAL。",
        "確認皆有 2nd AI 徽章（非 pending）。",
        "若有 pending，執行 Backfill 2nd AI challenges 後再查。",
      ],
      pass: "UAT 視窗內 BREACH／CRITICAL 100% 有挑戰結論。",
      evidence: "BREACH／CRITICAL 數量 vs 已挑戰數量。",
    },
  },
  {
    seq: 20,
    id: "UAT-20",
    t_start_min: 235,
    duration_min: 15,
    severity: "Critical",
    bu: "Risk Owner",
    dependency: "UAT-01–19 results recorded",
    en: {
      title: "Risk Owner exit sign-off",
      objective: "Formal accept/reject of the UAT window against exit criteria.",
      steps: [
        "Tally Critical cases: all must be Pass.",
        "Tally High cases: ≤2 deferred only with written risk acceptance.",
        "Confirm dual-AI coverage gate (UAT-19) passed.",
        "Record overall decision: ACCEPT / ACCEPT WITH WAIVERS / REJECT.",
        "File evidence pack link in Audit notes / share with PM.",
      ],
      pass: "Signed decision recorded; Critical 100% Pass; High waivers ≤2 if any.",
      evidence: "Sign-off note with date, Risk Owner name, waiver list (if any).",
    },
    zh: {
      title: "風險負責人退出簽核",
      objective: "依退出標準正式接受／拒絕本輪 UAT。",
      steps: [
        "統計 Critical：必須全部 Pass。",
        "統計 High：僅允許≤2 項書面風險接受後暫緩。",
        "確認雙 AI 覆蓋（UAT-19）通過。",
        "記錄總決：ACCEPT／ACCEPT WITH WAIVERS／REJECT。",
        "將證據包連結記入稽核備註／交给 PM。",
      ],
      pass: "已簽署決策；Critical 100% Pass；High 豁免≤2。",
      evidence: "簽核註記（日期、風險負責人、豁免清單）。",
    },
  },
];

export function uatSummary() {
  const bySev = { Critical: 0, High: 0, Medium: 0, Low: 0 } as Record<UatSeverity, number>;
  let totalMin = 0;
  for (const c of UAT_CASES) {
    bySev[c.severity] += 1;
    totalMin += c.duration_min;
  }
  return {
    count: UAT_CASES.length,
    totalMin,
    bySev,
    windowEndMin: Math.max(...UAT_CASES.map((c) => c.t_start_min + c.duration_min)),
  };
}
