import type { LinkedScenario, SkillScenario } from "@/lib/ai/scenario-types";
import { EXTRA_LINKED_SCENARIOS, EXTRA_SKILL_SCENARIOS } from "@/lib/ai/risk-scenarios-extra";
import { COVERAGE_LINKED_SCENARIOS, COVERAGE_SKILL_SCENARIOS } from "@/lib/ai/risk-scenarios-coverage";
import { CS_LINKED_SCENARIOS, CS_SKILL_SCENARIOS } from "@/lib/ai/risk-scenarios-cs";

/** Single-indicator skill scenarios — rich RCA playbooks */
const BASE_SKILL_SCENARIOS: SkillScenario[] = [
  {
    code: "SKILL-MARGIN-SPIKE",
    name: "Margin utilisation spike (≥100 accounts >90%)",
    description:
      "Credit cascade risk when many accounts sit above 90% margin utilisation into a volatile session.",
    indicator: {
      monitor_id: "M2-MRG-014",
      name: "Accounts >90% Margin Utilisation",
      product: "CFD",
      domain: "CREDIT_CLIENT",
      warn: 50,
      breach: 100,
      unit: "count",
      comparator: "gte",
      why: "At ≥100 stressed accounts, liquidation clustering can move company equity and LP fills simultaneously; 50 is early warning for desk staffing.",
    },
    related_indicators: ["M2-COPY-009", "M2-EQ-001", "M2-HEDGE-007", "M2-FEED-003"],
    conditions: { severity_in: ["BREACH", "CRITICAL"], min_observed: 100 },
    fault_areas: [
      "Copy-provider leverage contagion",
      "Stale quote → delayed stop-outs",
      "Weekend gap / news spike without A-book widen",
      "Bonus abuse increasing notional vs equity",
    ],
    escalation: {
      sla_minutes: 15,
      path: [
        { after_minutes: 0, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Lark + ticket" },
        { after_minutes: 15, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Secondary page" },
        { after_minutes: 30, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "CRITICAL bridge if equity DD also WARN" },
      ],
    },
    corrections: [
      { action: "check_copy_overlap", bu: "RISK_CONTROL", description: "Map stressed accounts to top signal providers" },
      { action: "group_leverage_tighten", bu: "RISK_CONTROL", description: "Temporary group leverage cut on toxic symbols", requires_human: true },
      { action: "pause_new_high_risk_accounts", bu: "OPERATIONS", description: "Freeze new account leverage upgrades" },
    ],
    past_cases: [
      {
        case_id: "CASE-MRG-1001",
        date: "2026-10-01",
        alert_id: "ALT-1001",
        analysis_href: "/admin/ai-analyses",
        outcome: "PREVENTED ~$380k",
        summary: "US-open spike; skill matched; human approved leverage tighten; prevented cascade.",
      },
      {
        case_id: "CASE-MRG-0920",
        date: "2026-09-20",
        outcome: "NEAR_MISS",
        summary: "NFP week — 142 accounts >90%; copy overlap 40%; resolved after provider pause.",
      },
    ],
    owner_department: "RISK_CONTROL",
    owner_role: "Risk Owner / Credit Desk",
    when_to_use: [
      "Use when M2-MRG-014 shows ≥100 accounts above 90% margin utilisation (BREACH), or ≥50 as a staffing WARN that is still climbing.",
      "Prefer this skill over generic RCA when copy concentration or stop-out velocity is also moving — that is a credit cascade, not a one-off VIP.",
      "Trigger from a live Monitor alert or messenger ALERT card, not from a historic dashboard print.",
    ],
    when_not_to_use: [
      "Do not tighten group leverage on a single test book, contest account, or known UAT print.",
      "Do not treat an isolated VIP override as a cascade — check copy overlap first.",
      "Do not skip the economic calendar: NFP/FOMC/CPI within ±60 minutes is often organic vol, not toxic flow.",
      "Do not auto-execute irreversible leverage cuts; the human gate is mandatory.",
    ],
    prechecks: [
      "Confirm M2-MRG-014 last_checked is within 2 minutes and observed_value is still ≥ warn.",
      "Check M2-FEED-003 — stale quotes can fake a margin spike.",
      "Check M2-COPY-009 — if one provider dominates, this is a linked timeline.",
      "Confirm a live OPEN alert exists before paging Exec.",
    ],
    evidence_to_collect: [
      "Monitor snapshot for M2-MRG-014 (observed vs warn 50 / breach 100).",
      "Top copy-provider overlap table for stressed logins.",
      "Messenger ALERT + AI_REPORT + challenger verdict.",
      "Macro calendar window ±60 minutes.",
    ],
    stop_conditions: [
      "Stop paging if utilisation falls below 50 accounts for 15 minutes and no linked BREACH remains.",
      "Abort leverage tighten if second AI DISAGREEs and Risk Owner has not overridden.",
      "Do not proceed while feed health is independently in BREACH — fix quotes first.",
    ],
    success_criteria: [
      "Named Credit Desk owner within 15 minutes SLA.",
      "Copy-overlap check recorded on the spine even if the result is 'none'.",
      "Any leverage tighten has maker + checker (or Risk Owner) in audit.",
      "Looks like CASE-MRG-1001: cascade contained, residual risk accepted in writing if any.",
    ],
    steps: [
      { action: "lark_notify", description: "Notify Credit & Client Risk", params: { channel: "oc_credit_client_risk" }, bu: "RISK_CONTROL" },
      { action: "check_copy_overlap", description: "Check margin spike vs top copy providers", bu: "RISK_CONTROL" },
      {
        action: "flag_for_human_review",
        description: "If not explained by macro calendar, consider group leverage tighten",
        requires_human: true,
        bu: "RISK_CONTROL",
      },
    ],
  },
  {
    code: "SKILL-COPY-CONCENTRATION",
    name: "Copy provider concentration breach (>25%)",
    description: "Single signal provider dominates copier equity — correlated stop-outs and toxic flow.",
    indicator: {
      monitor_id: "M2-COPY-009",
      name: "Top Signal Provider Copier Concentration",
      product: "CFD",
      domain: "CREDIT_CLIENT",
      warn: 15,
      breach: 25,
      unit: "%",
      comparator: "gte",
      why: "Above 25% one provider can move book PnL and margin utilisation in lockstep; 15% triggers capacity review.",
    },
    related_indicators: ["M2-MRG-014", "M2-EQ-001", "M2-FRAUD-011"],
    conditions: { severity_in: ["BREACH"], min_observed: 25 },
    fault_areas: ["Provider marketing surge", "Missing per-provider equity cap", "Mirrors on high-leverage symbols", "Sybil / multi-account copiers"],
    escalation: {
      sla_minutes: 20,
      path: [
        { after_minutes: 0, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Ticket + Lark" },
        { after_minutes: 20, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Approve pause new copies" },
      ],
    },
    corrections: [
      { action: "suggest_copier_cap", bu: "RISK_CONTROL", description: "Cap per-provider copier equity at 20%" },
      { action: "pause_new_copies", bu: "RISK_CONTROL", description: "Pause new allocations to top provider", requires_human: true },
      { action: "kyc_cluster_review", bu: "OPERATIONS", description: "Check multi-account concentration among copiers" },
    ],
    past_cases: [
      {
        case_id: "CASE-COPY-1002",
        date: "2026-10-01",
        alert_id: "ALT-1002",
        outcome: "NEAR_MISS / residual $95k",
        summary: "31% concentration; pause deferred once; residual PnL drag logged.",
      },
      { case_id: "CASE-COPY-0812", date: "2026-08-12", outcome: "PREVENTED", summary: "Cap applied within 18m; provider share fell to 19%." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Credit & Client Risk", params: { channel: "oc_credit_client_risk" }, bu: "RISK_CONTROL" },
      { action: "suggest_copier_cap", description: "Propose 20% per-provider cap", params: { cap_pct: 20 }, bu: "RISK_CONTROL" },
      { action: "pause_new_copies", description: "Pause new copies to top provider", requires_human: true, bu: "RISK_CONTROL" },
      { action: "flag_for_human_review", description: "Risk Owner confirms before lifting cap", bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-CRYPTO-HOT-WALLET",
    name: "Hot wallet float elevated (≥15%)",
    description: "Custody control when hot wallet holds too much of total float.",
    indicator: {
      monitor_id: "M2-CRYPTO-WALLET",
      name: "Hot Wallet Float Ratio",
      product: "Crypto",
      domain: "CRYPTO_EXCHANGE",
      warn: 15,
      breach: 25,
      unit: "%",
      comparator: "gte",
      why: "Industry custody practice: keep hot float low; ≥25% is operational/security breach requiring withdrawal throttle.",
    },
    related_indicators: ["M2-CRYPTO-LIQ"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 15 },
    fault_areas: ["Delayed cold sweep job", "Deposit surge before auto-sweep", "Manual ops override", "Bridge congestion delaying cold moves"],
    escalation: {
      sla_minutes: 30,
      path: [
        { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Notify" },
        { after_minutes: 15, team: "Trading Infra", channel: "oc_trading_infra", action: "Cold sweep ops" },
        { after_minutes: 30, team: "System Admin", channel: "oc_trading_infra", action: "Withdrawal pause proposal" },
      ],
    },
    corrections: [
      { action: "suggest_cold_wallet_sweep", bu: "SYSTEM", description: "Sweep to target ≤12% float" },
      { action: "pause_large_withdrawals", bu: "OPERATIONS", description: "Throttle large withdrawals until float normal", requires_human: true },
    ],
    past_cases: [
      {
        case_id: "CASE-WALLET-1003",
        date: "2026-10-01",
        alert_id: "ALT-1003",
        outcome: "PREVENTED ~$520k",
        summary: "Cold sweep + throttle avoided custody exposure breach.",
      },
    ],
    owner_department: "SYSTEM",
    steps: [
      { action: "lark_notify", description: "Notify Crypto Risk + Infra", params: { channel: "oc_crypto_exchange_risk" }, bu: "SYSTEM" },
      { action: "suggest_cold_wallet_sweep", description: "Recommend cold sweep to <12%", params: { target_float_pct: 12 }, bu: "SYSTEM" },
      { action: "flag_for_human_review", description: "Approve withdrawal pause if float ≥25%", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-LP-REJECT-STORM",
    name: "LP reject rate storm (≥5%)",
    description: "Liquidity path when oneZero / LP reject rate breaches.",
    indicator: {
      monitor_id: "M2-LP-022",
      name: "LP Reject Rate (oneZero)",
      product: "CFD",
      domain: "LP_HEDGE",
      warn: 2,
      breach: 5,
      unit: "%",
      comparator: "gte",
      why: "Reject storms widen client slippage and leave residual inventory; ≥5% usually means endpoint or risk limit issue at LP.",
    },
    related_indicators: ["M2-HEDGE-007", "M2-FEED-003", "M2-EQ-001"],
    conditions: { severity_in: ["BREACH", "CRITICAL"], min_observed: 5 },
    fault_areas: ["LP credit line exhausted", "Bridge session flap", "Symbol mapping mismatch", "Toxic flow routing to wrong LP"],
    escalation: {
      sla_minutes: 5,
      path: [
        { after_minutes: 0, team: "Trading Infra P1", channel: "oc_trading_infra", action: "Page on-call" },
        { after_minutes: 5, team: "Risk Control", channel: "oc_risk_control_desk", action: "Inventory / B-book review" },
      ],
    },
    corrections: [
      { action: "check_bridge_health", bu: "SYSTEM", description: "oneZero bridge health checklist" },
      { action: "suggest_lp_disable", bu: "SYSTEM", description: "Disable top rejecting LP endpoint", requires_human: true },
      { action: "reroute_abook", bu: "RISK_CONTROL", description: "Shift toxic symbols to alternate LP" },
    ],
    past_cases: [
      { case_id: "CASE-LP-0711", date: "2026-07-11", outcome: "PREVENTED", summary: "Disabled LP-B within 7m; reject rate back to 0.9%." },
    ],
    owner_department: "SYSTEM",
    steps: [
      { action: "lark_notify", description: "Page Trading Infra P1", params: { channel: "oc_trading_infra" }, bu: "SYSTEM" },
      { action: "check_bridge_health", description: "Bridge health checklist", bu: "SYSTEM" },
      { action: "suggest_lp_disable", description: "Propose disable top rejecting LP", requires_human: true, bu: "SYSTEM" },
    ],
  },
  {
    code: "SKILL-HEDGE-COVERAGE",
    name: "Hedge coverage below target (<85%)",
    description: "Book risk when hedge coverage slips under warn threshold.",
    indicator: {
      monitor_id: "M2-HEDGE-007",
      name: "Hedge Coverage Ratio",
      product: "CFD",
      domain: "LP_HEDGE",
      warn: 85,
      breach: 70,
      unit: "%",
      comparator: "lte",
      why: "Coverage <85% leaves material directional risk; <70% is breach requiring inventory / A-book intervention.",
    },
    related_indicators: ["M2-LP-022", "M2-EQ-001", "M2-XAU-247"],
    conditions: { severity_in: ["WARN", "BREACH"], max_observed: 85 },
    fault_areas: ["LP reject storm reducing fills", "A-book shrink on metals", "Manual B-book override", "Holiday LP capacity"],
    escalation: {
      sla_minutes: 15,
      path: [
        { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Notify" },
        { after_minutes: 15, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Approve A-book increase" },
      ],
    },
    corrections: [
      { action: "suggest_abook_increase", bu: "RISK_CONTROL", description: "Increase A-book on toxic symbols" },
      { action: "validate_inventory_skew", bu: "RISK_CONTROL", description: "Analyst validates skew", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-HEDGE-1005", date: "2026-10-01", alert_id: "ALT-1005", outcome: "PREVENTED ~$210k", summary: "Coverage restored after skew validation." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Risk Control Desk", params: { channel: "oc_risk_control_desk" }, bu: "RISK_CONTROL" },
      { action: "suggest_abook_increase", description: "Propose A-book increase on toxic symbols", bu: "RISK_CONTROL" },
      { action: "flag_for_human_review", description: "Validate inventory skew", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-FRAUD-CLUSTER",
    name: "Multi-account fraud cluster (≥0.85)",
    description: "Abuse path when multi-account cluster score breaches.",
    indicator: {
      monitor_id: "M2-FRAUD-011",
      name: "Multi-account Cluster Score",
      product: "CFD",
      domain: "FRAUD_CONDUCT",
      warn: 0.7,
      breach: 0.85,
      unit: "score",
      comparator: "gte",
      why: "Model score ≥0.85 historically correlates with linked KYC / device / funding abuse rings.",
    },
    related_indicators: ["M2-COPY-009", "M2-MRG-014"],
    conditions: { severity_in: ["BREACH", "WARN"], min_observed: 0.7 },
    fault_areas: ["Shared device / IP farms", "Bonus hunting rings", "Synthetic identities", "Payment instrument reuse"],
    escalation: {
      sla_minutes: 30,
      path: [
        { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Case open" },
        { after_minutes: 30, team: "Risk Control", channel: "oc_credit_client_risk", action: "Trading restriction review" },
      ],
    },
    corrections: [
      { action: "suggest_bonus_freeze", bu: "OPERATIONS", description: "Freeze promo/bonus for cluster", requires_human: true },
      { action: "kyc_linkage_review", bu: "OPERATIONS", description: "Ops Lead reviews KYC before bans" },
      { action: "restrict_trading", bu: "RISK_CONTROL", description: "Close-only on confirmed abuse accounts", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-FRAUD-0618", date: "2026-06-18", outcome: "PREVENTED", summary: "Bonus freeze stopped $210k promo drain across 37 accounts." },
    ],
    owner_department: "OPERATIONS",
    steps: [
      { action: "lark_notify", description: "Notify Ops War Room", params: { channel: "oc_ops_funding_recon" }, bu: "OPERATIONS" },
      { action: "suggest_bonus_freeze", description: "Freeze promo/bonus for cluster", requires_human: true, bu: "OPERATIONS" },
      { action: "flag_for_human_review", description: "KYC linkage before bans", bu: "OPERATIONS" },
    ],
  },
  {
    code: "SKILL-XAU247-EXPOSURE",
    name: "XAUUSD247 net exposure near limit (≥10k lots)",
    description: "Product control when 24/7 gold net exposure approaches hard limit.",
    indicator: {
      monitor_id: "M2-XAU-247",
      name: "XAUUSD247 Net Exposure",
      product: "CFD",
      domain: "PRODUCT_CONFIG",
      warn: 10000,
      breach: 15000,
      unit: "lots",
      comparator: "gte",
      why: "Hard product limit 15k net / soft 10k — weekend promo + thin LP books amplify gap risk.",
    },
    related_indicators: ["M2-HEDGE-007", "M2-EQ-001", "M2-LP-022"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 10000 },
    fault_areas: ["Weekend promo without hedge capacity", "LP reject on gold", "Client one-way positioning", "Delayed close-only mode"],
    escalation: {
      sla_minutes: 20,
      path: [
        { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Notify" },
        { after_minutes: 20, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Close-only decision" },
      ],
    },
    corrections: [
      { action: "suggest_close_only_prepare", bu: "RISK_CONTROL", description: "Prepare close-only messaging" },
      { action: "pause_weekend_promo", bu: "OPERATIONS", description: "Pause gold promo acquisition", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-XAU-051", date: "2026-05-01", outcome: "PREVENTED", summary: "Close-only armed at 12.4k lots ahead of holiday." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Risk Control Desk", params: { channel: "oc_risk_control_desk" }, bu: "RISK_CONTROL" },
      { action: "suggest_close_only_prepare", description: "Prepare close-only for 15k approach", bu: "RISK_CONTROL" },
      { action: "flag_for_human_review", description: "Confirm weekend promo not amplifying exposure", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-EQUITY-DRAWDOWN",
    name: "Company equity drawdown rising (≥3%)",
    description: "Firm-wide PnL / equity stress — often co-moves with hedge gaps and credit spikes.",
    indicator: {
      monitor_id: "M2-EQ-001",
      name: "Company Equity Drawdown",
      product: "CFD",
      domain: "MARKET_PRICING",
      warn: 3,
      breach: 5,
      unit: "%",
      comparator: "gte",
      why: "3% warn aligns with internal daily VaR band; 5% breach triggers exec visibility and trading condition review.",
    },
    related_indicators: ["M2-HEDGE-007", "M2-MRG-014", "M2-LP-022", "M2-COPY-009"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 3 },
    fault_areas: ["Directional inventory", "Hedge under-coverage", "Toxic copy flow", "Mispriced feed on majors"],
    escalation: {
      sla_minutes: 15,
      path: [
        { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "AI RCA + desk" },
        { after_minutes: 15, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Intervention authority" },
        { after_minutes: 45, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If ≥5% CRITICAL" },
      ],
    },
    corrections: [
      { action: "inventory_flatten_plan", bu: "RISK_CONTROL", description: "Flatten top contributors", requires_human: true },
      { action: "widen_spreads_toxic", bu: "RISK_CONTROL", description: "Widen spreads on toxic symbols" },
      { action: "rag_macro_check", bu: "AI", description: "Confirm macro calendar contribution" },
    ],
    past_cases: [
      { case_id: "CASE-EQ-1004", date: "2026-10-01", alert_id: "ALT-1004", outcome: "LOSS ~$180k", summary: "Metals session drawdown before hedge rebalance completed." },
    ],
    owner_department: "RISK_CONTROL",
    auto_execute: true,
    steps: [
      { action: "lark_notify", description: "Notify Risk Control Desk", params: { channel: "oc_risk_control_desk" }, bu: "RISK_CONTROL" },
      { action: "rag_macro_check", description: "Pull RAG + macro for equity DD drivers", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve flatten / widen plan", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-STALE-FEED",
    name: "Stale quote symbols (≥3)",
    description: "Pricing integrity — stale quotes cause wrong liquidations and arb.",
    indicator: {
      monitor_id: "M2-FEED-003",
      name: "Stale Quote Symbols",
      product: "CFD",
      domain: "MARKET_PRICING",
      warn: 3,
      breach: 10,
      unit: "symbols",
      comparator: "gte",
      why: "≥3 stale symbols indicates feed/venue issue; ≥10 is systemic — halt candidates.",
    },
    related_indicators: ["M2-MRG-014", "M2-LP-022", "M2-EQ-001"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 3 },
    fault_areas: ["Venue disconnect", "Symbol map drift", "Aggregator lag", "DST / session config error"],
    escalation: {
      sla_minutes: 10,
      path: [
        { after_minutes: 0, team: "Trading Infra", channel: "oc_trading_infra", action: "Page" },
        { after_minutes: 10, team: "Risk Control", channel: "oc_risk_control_desk", action: "Trading halt candidates" },
      ],
    },
    corrections: [
      { action: "suggest_symbol_halt", bu: "SYSTEM", description: "Temporary halt on stale symbols", requires_human: true },
      { action: "failover_feed", bu: "SYSTEM", description: "Failover to secondary feed" },
    ],
    past_cases: [
      { case_id: "CASE-FEED-0303", date: "2026-03-03", outcome: "PREVENTED", summary: "Halted 6 FX pairs; avoided wrong liquidations during venue blip." },
    ],
    owner_department: "SYSTEM",
    steps: [
      { action: "lark_notify", description: "Notify Trading Infra P1", params: { channel: "oc_trading_infra" }, bu: "SYSTEM" },
      { action: "failover_feed", description: "Attempt secondary feed failover", bu: "SYSTEM" },
      { action: "suggest_symbol_halt", description: "Propose halt on stale symbols", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-CRYPTO-LIQ-BACKLOG",
    name: "Crypto liquidation engine backlog (≥50)",
    description: "Exchange stack risk when liquidation orders queue.",
    indicator: {
      monitor_id: "M2-CRYPTO-LIQ",
      name: "Liquidation Engine Backlog",
      product: "Crypto",
      domain: "CRYPTO_EXCHANGE",
      warn: 50,
      breach: 200,
      unit: "orders",
      comparator: "gte",
      why: "Backlog ≥50 delays insurance fund protection; ≥200 risks socialised losses / negative balances.",
    },
    related_indicators: ["M2-CRYPTO-WALLET"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 50 },
    fault_areas: ["Matching engine CPU saturation", "Oracle lag", "Cascade liquidations", "Worker pool undersized"],
    escalation: {
      sla_minutes: 10,
      path: [
        { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Notify" },
        { after_minutes: 10, team: "Trading Infra", channel: "oc_trading_infra", action: "Scale workers / pause new perps" },
      ],
    },
    corrections: [
      { action: "scale_liq_workers", bu: "SYSTEM", description: "Autoscale liquidation workers" },
      { action: "pause_new_perp_listings", bu: "RISK_CONTROL", description: "Pause new high-leverage perps", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-LIQ-0221", date: "2026-02-21", outcome: "NEAR_MISS", summary: "Backlog peaked 180; scaled workers; insurance fund intact." },
    ],
    owner_department: "SYSTEM",
    steps: [
      { action: "lark_notify", description: "Notify Crypto Risk", params: { channel: "oc_crypto_exchange_risk" }, bu: "SYSTEM" },
      { action: "scale_liq_workers", description: "Scale liquidation workers", bu: "SYSTEM" },
      { action: "flag_for_human_review", description: "Pause new high-leverage perps if backlog ≥200", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-GENERIC-HUMAN-REVIEW",
    name: "Generic human RCA review (fallback)",
    description: "Fallback when no certainty skill matches — force human confirmation of RAG explanations.",
    indicator: {
      monitor_id: "__NEVER_AUTO_MATCH__",
      name: "Fallback / unmatched indicator",
      product: "CFD+Crypto",
      domain: "MODEL_AI",
      warn: 0,
      breach: 0,
      unit: "n/a",
      comparator: "gte",
      why: "Safety net: unknown patterns must not auto-execute high-impact actions.",
    },
    related_indicators: [],
    conditions: { severity_in: ["CRITICAL"] },
    fault_areas: ["Unknown / novel failure mode", "Model gap", "Missing playbook"],
    escalation: {
      sla_minutes: 30,
      path: [{ after_minutes: 0, team: "AI + Risk", channel: "oc_risk_control_desk", action: "Human RCA" }],
    },
    corrections: [
      { action: "flag_for_human_review", bu: "RISK_CONTROL", description: "Confirm AI/RAG root-cause", requires_human: true },
      { action: "propose_new_skill", bu: "AI", description: "If pattern recurs, draft new skill via AI Admin" },
    ],
    past_cases: [
      { case_id: "CASE-RAG-MANY", date: "2026-09", outcome: "NEEDS_HUMAN", summary: "Equity DD and fraud WARN paths frequently use RAG + human gate." },
    ],
    owner_department: "RISK_CONTROL",
    auto_execute: false,
    steps: [
      { action: "flag_for_human_review", description: "Confirm AI/RAG root-cause before acting", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
];

export const SKILL_SCENARIOS: SkillScenario[] = [
  ...BASE_SKILL_SCENARIOS,
  ...EXTRA_SKILL_SCENARIOS,
  ...COVERAGE_SKILL_SCENARIOS,
  ...CS_SKILL_SCENARIOS,
];

/** Multi-indicator linked timeline scenarios */
const BASE_LINKED_SCENARIOS: LinkedScenario[] = [
  {
    code: "CHAIN-CREDIT-CASCADE",
    name: "Copy concentration → margin spike → equity drawdown",
    description: "Classic CFD credit contagion: one provider dominates, copiers hit margin, company equity dips.",
    product: "CFD",
    domain: "CREDIT_CLIENT",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-COPY-009", severity: "WARN", signal: "Provider share crosses 15%" },
      { t_minutes: 25, monitor_id: "M2-COPY-009", severity: "BREACH", signal: "Provider share ≥25%" },
      { t_minutes: 40, monitor_id: "M2-MRG-014", severity: "WARN", signal: "Accounts >90% margin ≥50" },
      { t_minutes: 55, monitor_id: "M2-MRG-014", severity: "BREACH", signal: "Accounts >90% margin ≥100" },
      { t_minutes: 70, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Equity drawdown ≥3%" },
    ],
    causes: [
      "Correlated copy stops on same symbols",
      "Provider signal lag / news fade",
      "Insufficient per-provider equity cap",
      "Liquidations amplifying slippage into book",
    ],
    escalation_plan: [
      { after_minutes: 0, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Activate SKILL-COPY-CONCENTRATION" },
      { after_minutes: 15, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Join margin spike playbook" },
      { after_minutes: 45, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Approve pause copies + leverage tighten" },
      { after_minutes: 60, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If EQ ≥5%" },
    ],
    corrections: [
      { action: "pause_new_copies", bu: "RISK_CONTROL", description: "Stop new allocations to top provider", requires_human: true },
      { action: "group_leverage_tighten", bu: "RISK_CONTROL", description: "Cut leverage on provider symbols", requires_human: true },
      { action: "inventory_flatten_plan", bu: "RISK_CONTROL", description: "Flatten residual inventory" },
    ],
    linked_skills: ["SKILL-COPY-CONCENTRATION", "SKILL-MARGIN-SPIKE", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-1001", date: "2026-10-01", alert_id: "ALT-1001", outcome: "PREVENTED", summary: "Chain detected; human gates cleared; ~$380k prevented." },
      { case_id: "CASE-CHAIN-0920", date: "2026-09-20", outcome: "NEAR_MISS", summary: "NFP week full chain; pause delayed 12m." },
    ],
  },
  {
    code: "CHAIN-LP-HEDGE-GAP",
    name: "LP reject storm → hedge coverage gap → equity stress",
    description: "Liquidity failure leaves the book unhedged into volatility.",
    product: "CFD",
    domain: "LP_HEDGE",
    severity: "CRITICAL",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-LP-022", severity: "WARN", signal: "Reject rate ≥2%" },
      { t_minutes: 8, monitor_id: "M2-LP-022", severity: "BREACH", signal: "Reject rate ≥5%" },
      { t_minutes: 15, monitor_id: "M2-HEDGE-007", severity: "WARN", signal: "Coverage <85%" },
      { t_minutes: 30, monitor_id: "M2-HEDGE-007", severity: "BREACH", signal: "Coverage <70%" },
      { t_minutes: 45, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Equity DD ≥3%" },
    ],
    causes: ["LP credit line hit", "Bridge flap", "Concentrated metals inventory", "No alternate LP failover"],
    escalation_plan: [
      { after_minutes: 0, team: "Trading Infra P1", channel: "oc_trading_infra", action: "Page + bridge checklist" },
      { after_minutes: 5, team: "Risk Control", channel: "oc_risk_control_desk", action: "Coverage / A-book actions" },
      { after_minutes: 20, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Approve LP disable" },
    ],
    corrections: [
      { action: "suggest_lp_disable", bu: "SYSTEM", description: "Disable failing LP", requires_human: true },
      { action: "suggest_abook_increase", bu: "RISK_CONTROL", description: "Reroute toxic symbols" },
      { action: "failover_lp", bu: "SYSTEM", description: "Enable secondary LP" },
    ],
    linked_skills: ["SKILL-LP-REJECT-STORM", "SKILL-HEDGE-COVERAGE", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-LP-0711", date: "2026-07-11", outcome: "PREVENTED", summary: "LP-B disabled in 7m; coverage recovered to 88%." },
    ],
  },
  {
    code: "CHAIN-FEED-LIQUIDATION-ERROR",
    name: "Stale feed → false margin stress → equity noise",
    description: "Bad prices create artificial margin utilisation and wrong liquidations.",
    product: "CFD",
    domain: "MARKET_PRICING",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-FEED-003", severity: "WARN", signal: "≥3 stale symbols" },
      { t_minutes: 10, monitor_id: "M2-FEED-003", severity: "BREACH", signal: "≥10 stale symbols" },
      { t_minutes: 12, monitor_id: "M2-MRG-014", severity: "WARN", signal: "Spike in >90% margin (false)" },
      { t_minutes: 20, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Equity DD noise from bad marks" },
    ],
    causes: ["Venue disconnect", "Aggregator lag", "Session config error", "No secondary feed failover"],
    escalation_plan: [
      { after_minutes: 0, team: "Trading Infra", channel: "oc_trading_infra", action: "Feed failover" },
      { after_minutes: 10, team: "Risk Control", channel: "oc_risk_control_desk", action: "Symbol halt candidates" },
    ],
    corrections: [
      { action: "failover_feed", bu: "SYSTEM", description: "Switch to secondary feed" },
      { action: "suggest_symbol_halt", bu: "RISK_CONTROL", description: "Halt stale symbols", requires_human: true },
      { action: "suppress_auto_liq", bu: "RISK_CONTROL", description: "Pause auto-liq on affected symbols", requires_human: true },
    ],
    linked_skills: ["SKILL-STALE-FEED", "SKILL-MARGIN-SPIKE", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-FEED-0303", date: "2026-03-03", outcome: "PREVENTED", summary: "Halted 6 pairs; avoided wrong liquidations." },
    ],
  },
  {
    code: "CHAIN-CRYPTO-CUSTODY-STRESS",
    name: "Hot wallet float → withdrawal pressure → liq backlog risk",
    description: "Custody and exchange stack stress often appear together in crypto volatility.",
    product: "Crypto",
    domain: "CRYPTO_EXCHANGE",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-CRYPTO-WALLET", severity: "WARN", signal: "Hot float ≥15%" },
      { t_minutes: 30, monitor_id: "M2-CRYPTO-WALLET", severity: "BREACH", signal: "Hot float ≥25%" },
      { t_minutes: 45, monitor_id: "M2-CRYPTO-LIQ", severity: "WARN", signal: "Liq backlog ≥50" },
      { t_minutes: 90, monitor_id: "M2-CRYPTO-LIQ", severity: "BREACH", signal: "Liq backlog ≥200" },
    ],
    causes: ["Deposit surge", "Delayed cold sweep", "Perp cascade", "Worker under-provisioning"],
    escalation_plan: [
      { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Cold sweep" },
      { after_minutes: 20, team: "Trading Infra", channel: "oc_trading_infra", action: "Scale liq workers" },
      { after_minutes: 40, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Withdrawal throttle / pause perps" },
    ],
    corrections: [
      { action: "suggest_cold_wallet_sweep", bu: "SYSTEM", description: "Sweep to ≤12%" },
      { action: "pause_large_withdrawals", bu: "OPERATIONS", description: "Throttle withdrawals", requires_human: true },
      { action: "scale_liq_workers", bu: "SYSTEM", description: "Scale liquidation workers" },
    ],
    linked_skills: ["SKILL-CRYPTO-HOT-WALLET", "SKILL-CRYPTO-LIQ-BACKLOG"],
    past_cases: [
      { case_id: "CASE-CHAIN-CRYPTO-1003", date: "2026-10-01", alert_id: "ALT-1003", outcome: "PREVENTED ~$520k", summary: "Sweep + throttle before backlog breach." },
    ],
  },
  {
    code: "CHAIN-FRAUD-COPY-ABUSE",
    name: "Fraud cluster + copy concentration (sybil copiers)",
    description: "Linked accounts inflate a provider's share and harvest bonuses.",
    product: "CFD",
    domain: "FRAUD_CONDUCT",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-FRAUD-011", severity: "WARN", signal: "Cluster score ≥0.70" },
      { t_minutes: 35, monitor_id: "M2-COPY-009", severity: "WARN", signal: "Provider share ≥15%" },
      { t_minutes: 80, monitor_id: "M2-FRAUD-011", severity: "BREACH", signal: "Cluster score ≥0.85" },
      { t_minutes: 100, monitor_id: "M2-COPY-009", severity: "BREACH", signal: "Provider share ≥25%" },
    ],
    causes: ["Device farms", "Bonus hunting", "Synthetic KYC", "Provider collusion"],
    escalation_plan: [
      { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "KYC linkage" },
      { after_minutes: 30, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Copier cap / pause" },
    ],
    corrections: [
      { action: "suggest_bonus_freeze", bu: "OPERATIONS", description: "Freeze promo payouts", requires_human: true },
      { action: "pause_new_copies", bu: "RISK_CONTROL", description: "Pause provider copies", requires_human: true },
      { action: "restrict_trading", bu: "RISK_CONTROL", description: "Close-only on confirmed sybils", requires_human: true },
    ],
    linked_skills: ["SKILL-FRAUD-CLUSTER", "SKILL-COPY-CONCENTRATION"],
    past_cases: [
      { case_id: "CASE-CHAIN-FRAUD-0618", date: "2026-06-18", outcome: "PREVENTED", summary: "Bonus freeze + pause stopped $210k promo drain." },
    ],
  },
  {
    code: "CHAIN-METALS-WEEKEND",
    name: "XAUUSD247 build-up → hedge gap into Monday open",
    description: "Weekend gold promo accumulates net exposure while LP books are thin.",
    product: "CFD",
    domain: "PRODUCT_CONFIG",
    severity: "WARN",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-XAU-247", severity: "WARN", signal: "Net lots ≥10k" },
      { t_minutes: 120, monitor_id: "M2-HEDGE-007", severity: "WARN", signal: "Coverage <85% on metals book" },
      { t_minutes: 180, monitor_id: "M2-LP-022", severity: "WARN", signal: "Gold LP rejects rising" },
      { t_minutes: 240, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Gap risk into Monday" },
    ],
    causes: ["Promo without hedge capacity", "Thin weekend LP", "One-way client positioning"],
    escalation_plan: [
      { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Close-only prepare" },
      { after_minutes: 60, team: "Ops", channel: "oc_ops_funding_recon", action: "Pause gold promo" },
    ],
    corrections: [
      { action: "suggest_close_only_prepare", bu: "RISK_CONTROL", description: "Arm close-only" },
      { action: "pause_weekend_promo", bu: "OPERATIONS", description: "Stop gold acquisition promo", requires_human: true },
      { action: "prehedge_metals", bu: "RISK_CONTROL", description: "Pre-hedge before Monday open", requires_human: true },
    ],
    linked_skills: ["SKILL-XAU247-EXPOSURE", "SKILL-HEDGE-COVERAGE", "SKILL-LP-REJECT-STORM"],
    past_cases: [
      { case_id: "CASE-CHAIN-XAU-051", date: "2026-05-01", outcome: "PREVENTED", summary: "Close-only at 12.4k lots before holiday." },
    ],
  },
  {
    code: "CHAIN-VOL-TRIPLE",
    name: "News vol: feed warn + margin + hedge simultaneous",
    description: "High-impact macro often trips pricing, credit, and hedge indicators within one hour.",
    product: "CFD",
    domain: "MARKET_PRICING",
    severity: "CRITICAL",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-FEED-003", severity: "WARN", signal: "Quote quality degrades pre-news" },
      { t_minutes: 5, monitor_id: "M2-MRG-014", severity: "BREACH", signal: "Margin utilisation spike at release" },
      { t_minutes: 8, monitor_id: "M2-HEDGE-007", severity: "WARN", signal: "Coverage dips on rejects" },
      { t_minutes: 20, monitor_id: "M2-EQ-001", severity: "BREACH", signal: "Equity DD ≥5% if uncontrolled" },
    ],
    causes: ["CPI/NFP/FOMC", "Widening spreads too late", "LP reject under load", "Copy pile-in"],
    escalation_plan: [
      { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "War-room mode" },
      { after_minutes: 10, team: "Infra + Credit", channel: "oc_trading_infra", action: "Feed/LP + margin actions" },
      { after_minutes: 30, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If EQ breach" },
    ],
    corrections: [
      { action: "pre_widen_spreads", bu: "RISK_CONTROL", description: "Pre-widen before high-impact news" },
      { action: "temp_leverage_cut", bu: "RISK_CONTROL", description: "Session leverage cut", requires_human: true },
      { action: "failover_feed", bu: "SYSTEM", description: "Ensure secondary feed ready" },
    ],
    linked_skills: ["SKILL-STALE-FEED", "SKILL-MARGIN-SPIKE", "SKILL-HEDGE-COVERAGE", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-NFP-0920", date: "2026-09-20", outcome: "NEAR_MISS", summary: "Triple trip; war-room contained EQ at 4.1%." },
    ],
  },
  {
    code: "CHAIN-MODEL-DRIFT-SHADOW",
    name: "AI skill miss → RAG path flood → human queue backlog",
    description: "When skill certainty drops, RAG volume rises and human gates backlog — model/ops risk.",
    product: "CFD+Crypto",
    domain: "MODEL_AI",
    severity: "WARN",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Unfamiliar pattern → RAG_REASONING" },
      { t_minutes: 15, monitor_id: "M2-FRAUD-011", severity: "WARN", signal: "Second RAG path opens" },
      { t_minutes: 60, monitor_id: "M2-MRG-014", severity: "BREACH", signal: "Human queue still PENDING while credit worsens" },
    ],
    causes: ["Missing playbook", "Threshold drift", "Novel product behaviour", "Checker capacity"],
    escalation_plan: [
      { after_minutes: 0, team: "AI Engineering", channel: "oc_risk_control_desk", action: "Review skill coverage" },
      { after_minutes: 30, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Clear human queue / approve new skill CR" },
    ],
    corrections: [
      { action: "propose_new_skill", bu: "AI", description: "Draft skill via AI Admin maker flow" },
      { action: "boost_oncall_risk", bu: "RISK_CONTROL", description: "Add checker capacity", requires_human: true },
      { action: "retrain_skill_matcher", bu: "AI", description: "Queue training run", requires_human: true },
    ],
    linked_skills: ["SKILL-GENERIC-HUMAN-REVIEW", "SKILL-EQUITY-DRAWDOWN", "SKILL-FRAUD-CLUSTER"],
    past_cases: [
      { case_id: "CASE-CHAIN-AI-ADMIN", date: "2026-10-01", outcome: "GOVERNANCE", summary: "AI Admin maker/checker used to land SKILL-DEMO-LIQ." },
    ],
  },
  {
    code: "CHAIN-OPS-FUNDING-STRESS",
    name: "Fraud WARN + margin WARN during funding exception surge",
    description: "Ops process stress: abuse signals coincide with funding exceptions and credit heat.",
    product: "CFD",
    domain: "OPS_PROCESS",
    severity: "WARN",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-FRAUD-011", severity: "WARN", signal: "Cluster score rising" },
      { t_minutes: 40, monitor_id: "M2-MRG-014", severity: "WARN", signal: "Margin utilisation climbing" },
      { t_minutes: 90, monitor_id: "M2-COPY-009", severity: "WARN", signal: "Provider share edging up via bonus accounts" },
    ],
    causes: ["Promo campaign", "Funding channel abuse", "Slow KYC", "Copy onboarding without velocity checks"],
    escalation_plan: [
      { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Funding exception triage" },
      { after_minutes: 45, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Trading / bonus controls" },
    ],
    corrections: [
      { action: "suggest_bonus_freeze", bu: "OPERATIONS", description: "Freeze bonuses", requires_human: true },
      { action: "slow_onboarding", bu: "OPERATIONS", description: "Tighten onboarding velocity" },
      { action: "suggest_copier_cap", bu: "RISK_CONTROL", description: "Pre-emptive provider cap" },
    ],
    linked_skills: ["SKILL-FRAUD-CLUSTER", "SKILL-MARGIN-SPIKE", "SKILL-COPY-CONCENTRATION"],
    past_cases: [
      { case_id: "CASE-OPS-0410", date: "2026-04-10", outcome: "PREVENTED", summary: "Promo freeze within 40m; funding exceptions normalised." },
    ],
  },
  {
    code: "CHAIN-FULL-STACK-CRYPTO-CFD",
    name: "Cross-product stress: crypto custody + CFD credit same day",
    description: "Risk Owner view when both books heat — allocate desks without double-counting capital.",
    product: "CFD+Crypto",
    domain: "REG_CAPITAL",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-CRYPTO-WALLET", severity: "WARN", signal: "Crypto hot float WARN" },
      { t_minutes: 20, monitor_id: "M2-COPY-009", severity: "BREACH", signal: "CFD copy breach" },
      { t_minutes: 50, monitor_id: "M2-MRG-014", severity: "BREACH", signal: "CFD margin breach" },
      { t_minutes: 80, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Firm equity DD WARN" },
    ],
    causes: ["Global risk-off", "Correlated client behaviour", "Capital dual-use across products"],
    escalation_plan: [
      { after_minutes: 0, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Dual-book war room" },
      { after_minutes: 30, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "Capital / communications" },
    ],
    corrections: [
      { action: "dual_book_limits", bu: "RISK_CONTROL", description: "Tighten both CFD and crypto risk budgets", requires_human: true },
      { action: "suggest_cold_wallet_sweep", bu: "SYSTEM", description: "Crypto custody first" },
      { action: "pause_new_copies", bu: "RISK_CONTROL", description: "CFD credit first", requires_human: true },
    ],
    linked_skills: ["SKILL-CRYPTO-HOT-WALLET", "SKILL-COPY-CONCENTRATION", "SKILL-MARGIN-SPIKE", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CROSS-1001", date: "2026-10-01", outcome: "MIXED", summary: "Same-day crypto prevented + CFD credit actions; firm DD contained." },
    ],
  },
];

export const LINKED_SCENARIOS: LinkedScenario[] = [
  ...BASE_LINKED_SCENARIOS,
  ...EXTRA_LINKED_SCENARIOS,
  ...COVERAGE_LINKED_SCENARIOS,
  ...CS_LINKED_SCENARIOS,
];
