import type { LinkedScenario, SkillScenario } from "@/lib/ai/scenario-types";

/**
 * Extra coverage pass: indicators / skills / chains that desk review showed
 * were thin or missing for a CFD + crypto exchange book.
 */
export const COVERAGE_SKILL_SCENARIOS: SkillScenario[] = [
  {
    code: "SKILL-PERP-BASIS",
    name: "Perp mark–index basis (≥60 bps)",
    description: "Perpetual futures mark price diverges from index — liquidation fairness and IF risk.",
    indicator: {
      monitor_id: "M2-PERP-BASIS",
      name: "Perp Mark–Index Basis",
      product: "Crypto",
      domain: "CRYPTO_EXCHANGE",
      warn: 25,
      breach: 60,
      unit: "bps",
      comparator: "gte",
      why: "Basis ≥60 bps means marks are detached from index; forced liqs become unfair and insurance fund bleeds.",
    },
    related_indicators: ["M2-CRYPTO-ORACLE", "M2-CRYPTO-LIQ", "M2-CRYPTO-INS", "M2-CRYPTO-OI"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 25 },
    fault_areas: ["Oracle lag", "Thin index constituents", "Manipulated mark", "Matching halt mid-move"],
    escalation: {
      sla_minutes: 10,
      path: [
        { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Basis war-room" },
        { after_minutes: 10, team: "Trading Infra", channel: "oc_trading_infra", action: "Oracle / mark review" },
        { after_minutes: 25, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Pause perps if persistent" },
      ],
    },
    corrections: [
      { action: "switch_mark_source", bu: "SYSTEM", description: "Failover mark to secondary index basket" },
      { action: "pause_perp_new_risk", bu: "RISK_CONTROL", description: "Reduce-only on affected contracts", requires_human: true },
      { action: "review_if_drain", bu: "RISK_CONTROL", description: "Check insurance fund path with M2-CRYPTO-INS" },
    ],
    past_cases: [
      { case_id: "CASE-BASIS-0912", date: "2026-09-12", outcome: "PREVENTED", summary: "Secondary mark basket cut basis from 72→18 bps in 8m." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Crypto Risk", params: { channel: "oc_crypto_exchange_risk" }, bu: "RISK_CONTROL" },
      { action: "correlate_oracle", description: "Check M2-CRYPTO-ORACLE lag", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve reduce-only / mark failover", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-FUNDING-EXTREME",
    name: "Perp funding rate extreme (≥0.5% / 8h)",
    description: "Extreme funding squeezes one side and can force liquidations / OI churn.",
    indicator: {
      monitor_id: "M2-FUNDING-RATE",
      name: "Perp Funding Rate Abs (8h)",
      product: "Crypto",
      domain: "CRYPTO_EXCHANGE",
      warn: 0.15,
      breach: 0.5,
      unit: "%",
      comparator: "gte",
      why: "Absolute 8h funding ≥0.5% is a squeeze regime; inventory and liq backlog usually follow within the hour.",
    },
    related_indicators: ["M2-CRYPTO-OI", "M2-CRYPTO-LIQ", "M2-PERP-BASIS", "M2-CRYPTO-INS"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 0.15 },
    fault_areas: ["One-sided retail pile-in", "MM withdrawal", "Oracle/basis stress", "Campaign incentives"],
    escalation: {
      sla_minutes: 20,
      path: [
        { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Funding review" },
        { after_minutes: 20, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "OI / leverage caps" },
      ],
    },
    corrections: [
      { action: "cap_leverage_perps", bu: "RISK_CONTROL", description: "Temporary leverage cap on hot contracts", requires_human: true },
      { action: "raise_mm_incentives", bu: "OPERATIONS", description: "Call MMs for opposite side" },
      { action: "monitor_if", bu: "RISK_CONTROL", description: "Watch insurance fund drawdown" },
    ],
    past_cases: [
      { case_id: "CASE-FUND-0622", date: "2026-06-22", outcome: "NEAR_MISS", summary: "0.62% funding; delayed cap cost IF 1.8%." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Crypto Risk", params: { channel: "oc_crypto_exchange_risk" }, bu: "RISK_CONTROL" },
      { action: "check_oi_liq", description: "Correlate OI share and liq backlog", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve leverage cap", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-STABLE-DEPEG",
    name: "Stablecoin inventory depeg exposure (≥$2m)",
    description: "House stablecoin inventory at risk when peg slips — custody and withdrawal fairness.",
    indicator: {
      monitor_id: "M2-STABLE-EXP",
      name: "Stablecoin Depeg Exposure (USD)",
      product: "Crypto",
      domain: "CRYPTO_EXCHANGE",
      warn: 500000,
      breach: 2000000,
      unit: "USD",
      comparator: "gte",
      why: "Mark-to-market gap on USDT/USDC inventory ≥$2m is a capital and client-withdrawal event.",
    },
    related_indicators: ["M2-CRYPTO-WALLET", "M2-CRYPTO-DEP", "M2-WD-015", "M2-CAP-024"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 500000 },
    fault_areas: ["Issuer stress", "Chain congestion", "Concentrated USDT inventory", "Delayed conversion"],
    escalation: {
      sla_minutes: 15,
      path: [
        { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Inventory triage" },
        { after_minutes: 15, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Capital / convert plan" },
        { after_minutes: 40, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If BREACH + WD surge" },
      ],
    },
    corrections: [
      { action: "convert_stable_mix", bu: "SYSTEM", description: "Rebalance to healthier stables", requires_human: true },
      { action: "pause_stable_deposits", bu: "OPERATIONS", description: "Pause weak-stable deposits", requires_human: true },
      { action: "priority_wd_queue", bu: "OPERATIONS", description: "Fair withdrawal queue rules" },
    ],
    past_cases: [
      { case_id: "CASE-STABLE-0312", date: "2026-03-12", outcome: "PREVENTED", summary: "Converted $1.4m USDT inventory before depeg deepened." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Crypto Risk", params: { channel: "oc_crypto_exchange_risk" }, bu: "RISK_CONTROL" },
      { action: "inventory_snapshot", description: "Stable inventory by chain", bu: "SYSTEM" },
      { action: "flag_for_human_review", description: "Approve conversion / deposit pause", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-PLATFORM-DISCONNECT",
    name: "Trading platform disconnect rate (≥5%)",
    description: "MT4/MT5/App session drops — clients cannot manage risk; stop-outs and complaints follow.",
    indicator: {
      monitor_id: "M2-MT-DISC",
      name: "Trading Platform Disconnect Rate",
      product: "CFD+Crypto",
      domain: "TECH_INFRA",
      warn: 1,
      breach: 5,
      unit: "%",
      comparator: "gte",
      why: "≥5% concurrent disconnects means systemic platform failure; credit risk rises if clients cannot close.",
    },
    related_indicators: ["M2-API-023", "M2-STOP-018", "M2-MRG-014", "M2-EQ-001"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 1 },
    fault_areas: ["Bad deploy", "DC network blip", "Certificate expiry", "DDoS / capacity"],
    escalation: {
      sla_minutes: 5,
      path: [
        { after_minutes: 0, team: "Trading Infra P1", channel: "oc_trading_infra", action: "Page on-call" },
        { after_minutes: 10, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Client status" },
        { after_minutes: 20, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Inventory freeze options" },
      ],
    },
    corrections: [
      { action: "failover_gateway", bu: "SYSTEM", description: "Failover trade gateway" },
      { action: "rollback_platform", bu: "SYSTEM", description: "Rollback last platform deploy", requires_human: true },
      { action: "status_page_notice", bu: "OPERATIONS", description: "Client communications" },
    ],
    past_cases: [
      { case_id: "CASE-DISC-0819", date: "2026-08-19", outcome: "PREVENTED", summary: "Gateway failover in 4m; no EQ WARN." },
    ],
    owner_department: "SYSTEM",
    steps: [
      { action: "lark_notify", description: "Page Trading Infra P1", params: { channel: "oc_trading_infra" }, bu: "SYSTEM" },
      { action: "correlate_api", description: "Check M2-API-023 in parallel", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve rollback if needed", requires_human: true, bu: "SYSTEM" },
    ],
  },
  {
    code: "SKILL-RECON-BREAKS",
    name: "Reconciliation breaks (≥20)",
    description: "Internal ledger vs bank/chain recon exceptions — ops and segregation risk.",
    indicator: {
      monitor_id: "M2-RECON-BRK",
      name: "Reconciliation Breaks (open)",
      product: "CFD+Crypto",
      domain: "OPS_PROCESS",
      warn: 5,
      breach: 20,
      unit: "count",
      comparator: "gte",
      why: "≥20 open breaks usually precedes client-money segregation gaps and delayed withdrawals.",
    },
    related_indicators: ["M2-SEG-025", "M2-FUND-010", "M2-WD-015", "M2-CAP-024"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 5 },
    fault_areas: ["Feed file delay", "Chain reorg", "Manual override without ticket", "Timezone cut-off miss"],
    escalation: {
      sla_minutes: 45,
      path: [
        { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Break queue" },
        { after_minutes: 45, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Segregation check" },
      ],
    },
    corrections: [
      { action: "assign_break_owners", bu: "OPERATIONS", description: "Owner per break category" },
      { action: "freeze_affected_wd", bu: "OPERATIONS", description: "Hold withdrawals tied to open breaks", requires_human: true },
      { action: "segregation_recalc", bu: "RISK_CONTROL", description: "Recalc M2-SEG-025" },
    ],
    past_cases: [
      { case_id: "CASE-RECON-0502", date: "2026-05-02", outcome: "PREVENTED", summary: "22 breaks cleared before SEG WARN." },
    ],
    owner_department: "OPERATIONS",
    steps: [
      { action: "lark_notify", description: "Notify Ops War Room", params: { channel: "oc_ops_funding_recon" }, bu: "OPERATIONS" },
      { action: "break_aging", description: "Age open breaks >4h", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve withdrawal holds", requires_human: true, bu: "OPERATIONS" },
    ],
  },
  {
    code: "SKILL-SYMBOL-HALTS",
    name: "Active symbol kill-switches (≥5)",
    description: "Too many symbols halted — product config / feed failure cascading.",
    indicator: {
      monitor_id: "M2-KILL-COUNT",
      name: "Active Symbol Kill-Switches",
      product: "CFD+Crypto",
      domain: "TECH_INFRA",
      warn: 2,
      breach: 5,
      unit: "symbols",
      comparator: "gte",
      why: "≥5 concurrent halts means clients cannot trade; hedge coverage and LP rejects usually worsen.",
    },
    related_indicators: ["M2-FEED-003", "M2-HEDGE-007", "M2-LP-022", "M2-API-023"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 2 },
    fault_areas: ["Stale feed auto-halt", "Manual over-halt", "Bridge outage", "Holiday liquidity script"],
    escalation: {
      sla_minutes: 10,
      path: [
        { after_minutes: 0, team: "Trading Infra P1", channel: "oc_trading_infra", action: "Halt board review" },
        { after_minutes: 10, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Inventory / reopen plan" },
      ],
    },
    corrections: [
      { action: "review_halt_board", bu: "SYSTEM", description: "Validate each kill-switch reason" },
      { action: "reopen_safe_symbols", bu: "RISK_CONTROL", description: "Reopen when feed healthy", requires_human: true },
      { action: "hedge_orphans", bu: "RISK_CONTROL", description: "Hedge stranded inventory" },
    ],
    past_cases: [
      { case_id: "CASE-KILL-0711", date: "2026-07-11", outcome: "PREVENTED", summary: "False auto-halts rolled back; hedge restored." },
    ],
    owner_department: "SYSTEM",
    steps: [
      { action: "lark_notify", description: "Notify Trading Infra", params: { channel: "oc_trading_infra" }, bu: "SYSTEM" },
      { action: "correlate_feed", description: "Map halts to M2-FEED-003", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve reopen list", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-NEWS-GROSS",
    name: "Gross notional into Tier-1 news (≥$120m)",
    description: "Client + house gross into NFP/FOMC/CPI window — gap and stop-out risk.",
    indicator: {
      monitor_id: "M2-NEWS-GROSS",
      name: "Gross Notional into Tier-1 News (USD)",
      product: "CFD",
      domain: "MARKET_PRICING",
      warn: 50000000,
      breach: 120000000,
      unit: "USD",
      comparator: "gte",
      why: "≥$120m gross into a Tier-1 print historically precedes stop-out velocity and gap USD BREACH.",
    },
    related_indicators: ["M2-MKT-INTEL", "M2-GAP-012", "M2-STOP-018", "M2-SPREAD-005", "M2-EQ-001"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 50000000 },
    fault_areas: ["No pre-widen", "Copy pile-in", "Max leverage into print", "LP thinning"],
    escalation: {
      sla_minutes: 15,
      path: [
        { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Pre-event desk" },
        { after_minutes: 0, team: "Market Intelligence", channel: "oc_market_intelligence", action: "Confirm calendar" },
        { after_minutes: 30, team: "Credit Desk", channel: "oc_credit_client_risk", action: "If stop-outs accelerate" },
      ],
    },
    corrections: [
      { action: "pre_widen_spreads", bu: "RISK_CONTROL", description: "Pre-widen majors" },
      { action: "temp_leverage_cut", bu: "RISK_CONTROL", description: "Cut leverage into event", requires_human: true },
      { action: "pause_new_copies", bu: "RISK_CONTROL", description: "Pause new copy entries", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-NEWS-1001", date: "2026-10-01", outcome: "PREVENTED", summary: "Pre-widen before CPI; stop-outs stayed <20/5m." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Risk Desk", params: { channel: "oc_risk_control_desk" }, bu: "RISK_CONTROL" },
      { action: "calendar_confirm", description: "Confirm Tier-1 window with intel", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve leverage cut", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-CHARGEBACK-SPIKE",
    name: "Payment chargebacks (≥40 / 24h)",
    description: "Card / APM disputes surge — fraud + ops funding risk.",
    indicator: {
      monitor_id: "M2-CHARGEBACK",
      name: "Payment Chargebacks (24h)",
      product: "CFD",
      domain: "FRAUD_CONDUCT",
      warn: 15,
      breach: 40,
      unit: "count/24h",
      comparator: "gte",
      why: "≥40 chargebacks/24h usually means organised dispute rings or processor rule breach.",
    },
    related_indicators: ["M2-PAY-017", "M2-FRAUD-011", "M2-WD-015", "M2-FUND-010"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 15 },
    fault_areas: ["Friendly fraud ring", "Processor BIN attack", "Slow KYC", "Bonus cash-out disputes"],
    escalation: {
      sla_minutes: 30,
      path: [
        { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Processor bridge" },
        { after_minutes: 30, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Fraud case" },
      ],
    },
    corrections: [
      { action: "bin_block", bu: "OPERATIONS", description: "Temporary BIN / method block", requires_human: true },
      { action: "evidence_pack", bu: "AI", description: "Chargeback evidence pack" },
      { action: "pause_bonus_cashout", bu: "OPERATIONS", description: "Pause bonus conversion", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-CB-0418", date: "2026-04-18", outcome: "PREVENTED", summary: "BIN block cut chargebacks 48→9 next day." },
    ],
    owner_department: "OPERATIONS",
    steps: [
      { action: "lark_notify", description: "Notify Ops", params: { channel: "oc_ops_funding_recon" }, bu: "OPERATIONS" },
      { action: "correlate_pay_fraud", description: "Check M2-PAY-017 and clusters", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve BIN block", requires_human: true, bu: "OPERATIONS" },
    ],
  },
  {
    code: "SKILL-IB-REBATE-ANOMALY",
    name: "IB rebate anomaly score (≥0.8)",
    description: "Introducing-broker payout pattern looks abusive or circular.",
    indicator: {
      monitor_id: "M2-IB-PAYOUT",
      name: "IB Rebate Anomaly Score",
      product: "CFD",
      domain: "FRAUD_CONDUCT",
      warn: 0.6,
      breach: 0.8,
      unit: "score",
      comparator: "gte",
      why: "Score ≥0.8 flags circular rebate / wash volume designed to extract IB payouts.",
    },
    related_indicators: ["M2-WASH-020", "M2-BONUS-013", "M2-FRAUD-011", "M2-COPY-009"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 0.6 },
    fault_areas: ["Circular IB trees", "Self-trading volume", "Bonus + rebate stack", "Thin symbol churn"],
    escalation: {
      sla_minutes: 45,
      path: [
        { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "IB conduct case" },
        { after_minutes: 45, team: "Ops", channel: "oc_ops_funding_recon", action: "Hold IB payouts" },
      ],
    },
    corrections: [
      { action: "hold_ib_payouts", bu: "OPERATIONS", description: "Hold suspect IB payouts", requires_human: true },
      { action: "evidence_pack", bu: "AI", description: "Volume / rebate graph" },
      { action: "restrict_ib_tree", bu: "RISK_CONTROL", description: "Freeze IB tree", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-IB-0228", date: "2026-02-28", outcome: "PREVENTED", summary: "Held $180k rebate; wash confirmed." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Risk Desk", params: { channel: "oc_risk_control_desk" }, bu: "RISK_CONTROL" },
      { action: "ib_graph", description: "Build IB rebate graph", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve payout hold", requires_human: true, bu: "OPERATIONS" },
    ],
  },
  {
    code: "SKILL-COPY-CHURN",
    name: "Copy follower net exit (≥25% / 1h)",
    description: "Mass unfollow / pause on a provider — cascade into margin and equity when positions unwind.",
    indicator: {
      monitor_id: "M2-COPY-CHURN",
      name: "Copy Follower Net Exit (1h)",
      product: "CFD",
      domain: "CREDIT_CLIENT",
      warn: 12,
      breach: 25,
      unit: "%",
      comparator: "gte",
      why: "≥25% net follower exit in 1h forces rapid de-risking; often co-moves with provider concentration BREACH.",
    },
    related_indicators: ["M2-COPY-009", "M2-MRG-014", "M2-STOP-018", "M2-EQ-001"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 12 },
    fault_areas: ["Provider drawdown", "Rumour / social panic", "Forced pause", "Platform disconnect"],
    escalation: {
      sla_minutes: 15,
      path: [
        { after_minutes: 0, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Copy war-room" },
        { after_minutes: 15, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Inventory hedge" },
      ],
    },
    corrections: [
      { action: "pause_new_copies", bu: "RISK_CONTROL", description: "Pause new follows on provider", requires_human: true },
      { action: "staged_unwind", bu: "RISK_CONTROL", description: "Stage unwind to avoid dump", requires_human: true },
      { action: "hedge_orphans", bu: "RISK_CONTROL", description: "Hedge residual inventory" },
    ],
    past_cases: [
      { case_id: "CASE-CHURN-0910", date: "2026-09-10", outcome: "PREVENTED ~$210k", summary: "Staged unwind after 31% exit hour." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Credit Desk", params: { channel: "oc_credit_client_risk" }, bu: "RISK_CONTROL" },
      { action: "provider_pnl", description: "Map provider PnL vs churn", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve staged unwind", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
];

export const COVERAGE_LINKED_SCENARIOS: LinkedScenario[] = [
  {
    code: "CHAIN-PERP-BASIS-ORACLE",
    name: "Oracle lag → basis → liquidation → insurance",
    description: "Crypto mark integrity failure cascade across oracle, basis, liq engine and insurance fund.",
    product: "Crypto",
    domain: "CRYPTO_EXCHANGE",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-CRYPTO-ORACLE", severity: "WARN", signal: "Oracle lag ≥1s" },
      { t_minutes: 5, monitor_id: "M2-PERP-BASIS", severity: "WARN", signal: "Basis ≥25 bps" },
      { t_minutes: 15, monitor_id: "M2-PERP-BASIS", severity: "BREACH", signal: "Basis ≥60 bps" },
      { t_minutes: 25, monitor_id: "M2-CRYPTO-LIQ", severity: "WARN", signal: "Liq backlog climbing" },
      { t_minutes: 40, monitor_id: "M2-CRYPTO-INS", severity: "WARN", signal: "Insurance fund DD" },
    ],
    causes: ["Index constituent outage", "Manipulated mark", "Matching pause", "MM withdrawal"],
    escalation_plan: [
      { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Mark integrity desk" },
      { after_minutes: 15, team: "Trading Infra", channel: "oc_trading_infra", action: "Oracle failover" },
      { after_minutes: 35, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Reduce-only / pause" },
    ],
    corrections: [
      { action: "switch_mark_source", bu: "SYSTEM", description: "Failover mark basket" },
      { action: "pause_perp_new_risk", bu: "RISK_CONTROL", description: "Reduce-only", requires_human: true },
      { action: "review_if_drain", bu: "RISK_CONTROL", description: "Insurance fund path" },
    ],
    linked_skills: ["SKILL-CRYPTO-ORACLE", "SKILL-PERP-BASIS", "SKILL-CRYPTO-LIQ-BACKLOG", "SKILL-CRYPTO-INSURANCE"],
    past_cases: [
      { case_id: "CASE-CHAIN-BASIS-0912", date: "2026-09-12", outcome: "PREVENTED", summary: "Failover before IF WARN." },
    ],
  },
  {
    code: "CHAIN-FUNDING-SQUEEZE",
    name: "Extreme funding → OI concentration → liq backlog",
    description: "Funding squeeze packs OI into one side then overwhelms the liquidation engine.",
    product: "Crypto",
    domain: "CRYPTO_EXCHANGE",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-FUNDING-RATE", severity: "WARN", signal: "|funding| ≥0.15%" },
      { t_minutes: 30, monitor_id: "M2-CRYPTO-OI", severity: "WARN", signal: "Top account OI share rising" },
      { t_minutes: 60, monitor_id: "M2-FUNDING-RATE", severity: "BREACH", signal: "|funding| ≥0.5%" },
      { t_minutes: 75, monitor_id: "M2-CRYPTO-LIQ", severity: "WARN", signal: "Backlog ≥50" },
    ],
    causes: ["Retail FOMO", "MM pullback", "Incentive campaign", "Thin book"],
    escalation_plan: [
      { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Funding / OI desk" },
      { after_minutes: 30, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Leverage caps" },
    ],
    corrections: [
      { action: "cap_leverage_perps", bu: "RISK_CONTROL", description: "Leverage cap", requires_human: true },
      { action: "enforce_oi_cap", bu: "RISK_CONTROL", description: "OI cap", requires_human: true },
      { action: "raise_mm_incentives", bu: "OPERATIONS", description: "Call MMs" },
    ],
    linked_skills: ["SKILL-FUNDING-EXTREME", "SKILL-CRYPTO-OI-CONC", "SKILL-CRYPTO-LIQ-BACKLOG"],
    past_cases: [
      { case_id: "CASE-CHAIN-FUND-0622", date: "2026-06-22", outcome: "NEAR_MISS", summary: "Cap delayed; IF took 1.8%." },
    ],
  },
  {
    code: "CHAIN-STABLE-CUSTODY",
    name: "Stable depeg exposure → hot float → withdrawals",
    description: "Stablecoin stress hits custody float and withdrawal fairness together.",
    product: "Crypto",
    domain: "CRYPTO_EXCHANGE",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-STABLE-EXP", severity: "WARN", signal: "Depeg exposure ≥$500k" },
      { t_minutes: 20, monitor_id: "M2-CRYPTO-WALLET", severity: "WARN", signal: "Hot float ≥15%" },
      { t_minutes: 40, monitor_id: "M2-WD-015", severity: "WARN", signal: "Withdrawal surge" },
      { t_minutes: 70, monitor_id: "M2-STABLE-EXP", severity: "BREACH", signal: "Exposure ≥$2m" },
    ],
    causes: ["Issuer stress", "Concentrated USDT", "Delayed convert", "Social panic WD"],
    escalation_plan: [
      { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Inventory + WD queue" },
      { after_minutes: 20, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Convert plan" },
      { after_minutes: 45, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If BREACH" },
    ],
    corrections: [
      { action: "convert_stable_mix", bu: "SYSTEM", description: "Rebalance stables", requires_human: true },
      { action: "suggest_cold_wallet_sweep", bu: "SYSTEM", description: "Cold sweep" },
      { action: "priority_wd_queue", bu: "OPERATIONS", description: "Fair WD rules" },
    ],
    linked_skills: ["SKILL-STABLE-DEPEG", "SKILL-CRYPTO-HOT-WALLET", "SKILL-WITHDRAWAL-VELOCITY"],
    past_cases: [
      { case_id: "CASE-CHAIN-STABLE-0312", date: "2026-03-12", outcome: "PREVENTED", summary: "Convert + queue rules held WD fair." },
    ],
  },
  {
    code: "CHAIN-PLATFORM-CREDIT",
    name: "Platform disconnect → API errors → stop-outs → equity",
    description: "Infra outage becomes credit cascade when clients cannot manage positions.",
    product: "CFD+Crypto",
    domain: "TECH_INFRA",
    severity: "CRITICAL",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-MT-DISC", severity: "WARN", signal: "Disconnects ≥1%" },
      { t_minutes: 3, monitor_id: "M2-API-023", severity: "WARN", signal: "API errors ≥2%" },
      { t_minutes: 10, monitor_id: "M2-MT-DISC", severity: "BREACH", signal: "Disconnects ≥5%" },
      { t_minutes: 20, monitor_id: "M2-STOP-018", severity: "WARN", signal: "Stop-outs accelerate" },
      { t_minutes: 35, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Equity DD from stranded risk" },
    ],
    causes: ["Bad deploy", "DC blip", "DDoS", "Gateway cert expiry"],
    escalation_plan: [
      { after_minutes: 0, team: "Trading Infra P1", channel: "oc_trading_infra", action: "Failover" },
      { after_minutes: 10, team: "Ops", channel: "oc_ops_funding_recon", action: "Status page" },
      { after_minutes: 20, team: "Risk Control", channel: "oc_risk_control_desk", action: "Inventory review" },
    ],
    corrections: [
      { action: "failover_gateway", bu: "SYSTEM", description: "Failover gateway" },
      { action: "rollback_platform", bu: "SYSTEM", description: "Rollback", requires_human: true },
      { action: "status_page_notice", bu: "OPERATIONS", description: "Client comms" },
    ],
    linked_skills: ["SKILL-PLATFORM-DISCONNECT", "SKILL-API-ERROR-RATE", "SKILL-STOPOUT-VELOCITY", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-DISC-0819", date: "2026-08-19", outcome: "PREVENTED", summary: "Failover before stop-out WARN." },
    ],
  },
  {
    code: "CHAIN-NEWS-GROSS-GAP",
    name: "Intel + news gross → spread → stop-outs → gap USD",
    description: "Tier-1 macro window with oversized gross notional becomes a gap / NBP event.",
    product: "CFD",
    domain: "MARKET_PRICING",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-MKT-INTEL", severity: "WARN", signal: "High-impact intel" },
      { t_minutes: 10, monitor_id: "M2-NEWS-GROSS", severity: "WARN", signal: "Gross ≥$50m into window" },
      { t_minutes: 20, monitor_id: "M2-SPREAD-005", severity: "WARN", signal: "Spreads widening" },
      { t_minutes: 35, monitor_id: "M2-STOP-018", severity: "WARN", signal: "Stop-out velocity" },
      { t_minutes: 50, monitor_id: "M2-GAP-012", severity: "BREACH", signal: "Gap USD ≥$2m" },
    ],
    causes: ["No pre-widen", "Max leverage into print", "Copy pile-in", "LP thinning"],
    escalation_plan: [
      { after_minutes: 0, team: "Market Intelligence", channel: "oc_market_intelligence", action: "Confirm calendar" },
      { after_minutes: 5, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Pre-widen / leverage" },
      { after_minutes: 30, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Stop-out desk" },
    ],
    corrections: [
      { action: "pre_widen_spreads", bu: "RISK_CONTROL", description: "Pre-widen" },
      { action: "temp_leverage_cut", bu: "RISK_CONTROL", description: "Leverage cut", requires_human: true },
      { action: "pause_new_copies", bu: "RISK_CONTROL", description: "Pause copies", requires_human: true },
    ],
    linked_skills: ["SKILL-MARKET-INTEL", "SKILL-NEWS-GROSS", "SKILL-STOPOUT-VELOCITY", "SKILL-GAP-RISK"],
    past_cases: [
      { case_id: "CASE-CHAIN-NEWS-1001", date: "2026-10-01", outcome: "PREVENTED", summary: "Pre-widen held gap under WARN." },
    ],
  },
  {
    code: "CHAIN-RECON-SEGREGATION",
    name: "Recon breaks → segregation gap → capital buffer",
    description: "Ops recon debt becomes regulatory client-money and capital pressure.",
    product: "CFD+Crypto",
    domain: "REG_CAPITAL",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-RECON-BRK", severity: "WARN", signal: "≥5 open breaks" },
      { t_minutes: 120, monitor_id: "M2-RECON-BRK", severity: "BREACH", signal: "≥20 open breaks" },
      { t_minutes: 180, monitor_id: "M2-SEG-025", severity: "WARN", signal: "Segregation gap rising" },
      { t_minutes: 300, monitor_id: "M2-CAP-024", severity: "WARN", signal: "Capital buffer compressing" },
    ],
    causes: ["Cut-off miss", "Chain reorg", "Manual override", "Bank file delay"],
    escalation_plan: [
      { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Break owners" },
      { after_minutes: 120, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Segregation recalc" },
      { after_minutes: 240, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If SEG BREACH" },
    ],
    corrections: [
      { action: "assign_break_owners", bu: "OPERATIONS", description: "Own each break" },
      { action: "freeze_affected_wd", bu: "OPERATIONS", description: "Hold tied WDs", requires_human: true },
      { action: "segregation_recalc", bu: "RISK_CONTROL", description: "Recalc segregation" },
    ],
    linked_skills: ["SKILL-RECON-BREAKS", "SKILL-SEGREGATION-GAP", "SKILL-ENTITY-CAPITAL"],
    past_cases: [
      { case_id: "CASE-CHAIN-RECON-0502", date: "2026-05-02", outcome: "PREVENTED", summary: "Breaks cleared before SEG WARN." },
    ],
  },
  {
    code: "CHAIN-IB-FRAUD-RING",
    name: "IB rebate anomaly → wash → bonus → withdrawals",
    description: "Circular IB economics stacked with wash and bonus cash-out.",
    product: "CFD",
    domain: "FRAUD_CONDUCT",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-IB-PAYOUT", severity: "WARN", signal: "IB anomaly ≥0.6" },
      { t_minutes: 60, monitor_id: "M2-WASH-020", severity: "WARN", signal: "Wash score rising" },
      { t_minutes: 120, monitor_id: "M2-BONUS-013", severity: "WARN", signal: "Bonus cash-out climbing" },
      { t_minutes: 180, monitor_id: "M2-WD-015", severity: "WARN", signal: "Withdrawal velocity" },
      { t_minutes: 240, monitor_id: "M2-IB-PAYOUT", severity: "BREACH", signal: "IB anomaly ≥0.8" },
    ],
    causes: ["Circular IB trees", "Self-trading", "Bonus stacking", "Weak KYC"],
    escalation_plan: [
      { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Conduct case" },
      { after_minutes: 60, team: "Ops", channel: "oc_ops_funding_recon", action: "Hold payouts / WDs" },
    ],
    corrections: [
      { action: "hold_ib_payouts", bu: "OPERATIONS", description: "Hold IB payouts", requires_human: true },
      { action: "suggest_bonus_freeze", bu: "OPERATIONS", description: "Freeze bonus", requires_human: true },
      { action: "restrict_ib_tree", bu: "RISK_CONTROL", description: "Freeze IB tree", requires_human: true },
    ],
    linked_skills: ["SKILL-IB-REBATE-ANOMALY", "SKILL-WASH-TRADE", "SKILL-BONUS-BURN", "SKILL-WITHDRAWAL-VELOCITY"],
    past_cases: [
      { case_id: "CASE-CHAIN-IB-0228", date: "2026-02-28", outcome: "PREVENTED", summary: "Held rebate + bonus before WD BREACH." },
    ],
  },
  {
    code: "CHAIN-COPY-PANIC-UNWIND",
    name: "Copy churn → concentration → margin → equity",
    description: "Follower panic exit forces unwind through concentration and margin into firm equity.",
    product: "CFD",
    domain: "CREDIT_CLIENT",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-COPY-CHURN", severity: "WARN", signal: "Net exit ≥12%/1h" },
      { t_minutes: 20, monitor_id: "M2-COPY-009", severity: "BREACH", signal: "Provider still ≥25% of remaining book" },
      { t_minutes: 40, monitor_id: "M2-MRG-014", severity: "WARN", signal: "Margin utilisation spike on unwind" },
      { t_minutes: 70, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Firm equity DD from dump" },
    ],
    causes: ["Provider crash", "Social rumour", "Platform disconnect", "Forced pause"],
    escalation_plan: [
      { after_minutes: 0, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Copy war-room" },
      { after_minutes: 20, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Staged unwind" },
      { after_minutes: 50, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If EQ BREACH" },
    ],
    corrections: [
      { action: "pause_new_copies", bu: "RISK_CONTROL", description: "Pause follows", requires_human: true },
      { action: "staged_unwind", bu: "RISK_CONTROL", description: "Stage unwind", requires_human: true },
      { action: "hedge_orphans", bu: "RISK_CONTROL", description: "Hedge residual" },
    ],
    linked_skills: ["SKILL-COPY-CHURN", "SKILL-COPY-CONCENTRATION", "SKILL-MARGIN-SPIKE", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-CHURN-0910", date: "2026-09-10", outcome: "PREVENTED ~$210k", summary: "Staged unwind avoided dump." },
    ],
  },
  {
    code: "CHAIN-KILL-FEED-HEDGE",
    name: "Stale feed → kill-switches → hedge / LP stress",
    description: "Feed health forces halts that strand hedge coverage and spike LP rejects.",
    product: "CFD",
    domain: "LP_HEDGE",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-FEED-003", severity: "WARN", signal: "Stale symbols ≥3" },
      { t_minutes: 5, monitor_id: "M2-KILL-COUNT", severity: "WARN", signal: "Kill-switches ≥2" },
      { t_minutes: 15, monitor_id: "M2-HEDGE-007", severity: "WARN", signal: "Coverage slips" },
      { t_minutes: 25, monitor_id: "M2-LP-022", severity: "WARN", signal: "LP rejects rise" },
      { t_minutes: 40, monitor_id: "M2-KILL-COUNT", severity: "BREACH", signal: "Kill-switches ≥5" },
    ],
    causes: ["LP feed gap", "Auto-halt overfire", "Bridge latency", "Holiday script"],
    escalation_plan: [
      { after_minutes: 0, team: "Trading Infra P1", channel: "oc_trading_infra", action: "Feed + halt board" },
      { after_minutes: 15, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Hedge orphans" },
    ],
    corrections: [
      { action: "review_halt_board", bu: "SYSTEM", description: "Validate halts" },
      { action: "reopen_safe_symbols", bu: "RISK_CONTROL", description: "Reopen safe symbols", requires_human: true },
      { action: "hedge_orphans", bu: "RISK_CONTROL", description: "Cover stranded risk" },
    ],
    linked_skills: ["SKILL-STALE-FEED", "SKILL-SYMBOL-HALTS", "SKILL-HEDGE-COVERAGE", "SKILL-LP-REJECT-STORM"],
    past_cases: [
      { case_id: "CASE-CHAIN-KILL-0711", date: "2026-07-11", outcome: "PREVENTED", summary: "False halts rolled back; hedge restored." },
    ],
  },
  {
    code: "CHAIN-CHARGEBACK-FUNDING",
    name: "Payment fraud → chargebacks → funding exceptions → withdrawals",
    description: "Inbound payment abuse becomes processor chargebacks and ops funding stress.",
    product: "CFD",
    domain: "OPS_PROCESS",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-PAY-017", severity: "WARN", signal: "Payment fraud score rising" },
      { t_minutes: 180, monitor_id: "M2-CHARGEBACK", severity: "WARN", signal: "Chargebacks ≥15/24h" },
      { t_minutes: 360, monitor_id: "M2-FUND-010", severity: "WARN", signal: "Funding exceptions" },
      { t_minutes: 480, monitor_id: "M2-CHARGEBACK", severity: "BREACH", signal: "Chargebacks ≥40/24h" },
      { t_minutes: 520, monitor_id: "M2-WD-015", severity: "WARN", signal: "WD velocity as ring cashes out" },
    ],
    causes: ["BIN attack", "Friendly fraud", "Bonus abuse", "Slow KYC"],
    escalation_plan: [
      { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Processor + funding" },
      { after_minutes: 60, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Fraud pack" },
    ],
    corrections: [
      { action: "bin_block", bu: "OPERATIONS", description: "BIN block", requires_human: true },
      { action: "evidence_pack", bu: "AI", description: "Chargeback pack" },
      { action: "pause_bonus_cashout", bu: "OPERATIONS", description: "Pause bonus cash-out", requires_human: true },
    ],
    linked_skills: ["SKILL-PAYMENT-FRAUD", "SKILL-CHARGEBACK-SPIKE", "SKILL-FUNDING-EXCEPTION", "SKILL-WITHDRAWAL-VELOCITY"],
    past_cases: [
      { case_id: "CASE-CHAIN-CB-0418", date: "2026-04-18", outcome: "PREVENTED", summary: "BIN block before BREACH day-2." },
    ],
  },
];
