import type { LinkedScenario, SkillScenario } from "@/lib/ai/scenario-types";

/** Additional single-indicator skills — expand coverage across all risk domains */
export const EXTRA_SKILL_SCENARIOS: SkillScenario[] = [
  {
    code: "SKILL-STOPOUT-VELOCITY",
    name: "Stop-out velocity spike (≥40 / 5m)",
    description: "Liquidation clustering when stop-outs accelerate — often precedes equity DD and toxic LP fills.",
    indicator: {
      monitor_id: "M2-STOP-018",
      name: "Stop-out Count (5m window)",
      product: "CFD",
      domain: "CREDIT_CLIENT",
      warn: 20,
      breach: 40,
      unit: "count/5m",
      comparator: "gte",
      why: "Historical cascades start near 40 stop-outs/5m; 20 is staffing WARN for Credit Desk ahead of US open.",
    },
    related_indicators: ["M2-MRG-014", "M2-EQ-001", "M2-SLIP-021", "M2-FEED-003"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 20 },
    fault_areas: ["News spike without pre-widen", "Stale stop prices", "Copy pile-in same side", "LP reject delaying hedges"],
    escalation: {
      sla_minutes: 10,
      path: [
        { after_minutes: 0, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Lark + ticket" },
        { after_minutes: 10, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Join war-room if still rising" },
        { after_minutes: 25, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If EQ also WARN" },
      ],
    },
    corrections: [
      { action: "temp_leverage_cut", bu: "RISK_CONTROL", description: "Session leverage cut on hottest symbols", requires_human: true },
      { action: "pre_widen_spreads", bu: "RISK_CONTROL", description: "Widen spreads to slow new risk" },
      { action: "suppress_auto_liq_review", bu: "RISK_CONTROL", description: "Review false liqs if feed also WARN", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-STOP-0814", date: "2026-08-14", outcome: "PREVENTED ~$260k", summary: "CPI release; leverage cut at T+8m contained cascade." },
      { case_id: "CASE-STOP-0311", date: "2026-03-11", outcome: "NEAR_MISS", summary: "52 stop-outs/5m; delayed widen cost residual PnL." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Credit Desk", params: { channel: "oc_credit_client_risk" }, bu: "RISK_CONTROL" },
      { action: "check_feed_and_margin", description: "Correlate with M2-FEED-003 and M2-MRG-014", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve session leverage cut", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-NEGATIVE-BALANCE",
    name: "Negative-balance accounts (≥5)",
    description: "Client equity below zero after gap/liq failure — NBP exposure and OPS recovery path.",
    indicator: {
      monitor_id: "M2-NBP-016",
      name: "Negative Balance Account Count",
      product: "CFD",
      domain: "CREDIT_CLIENT",
      warn: 2,
      breach: 5,
      unit: "accounts",
      comparator: "gte",
      why: "≥5 concurrent NBP accounts usually means systemic gap/feed/liq failure, not isolated client error.",
    },
    related_indicators: ["M2-STOP-018", "M2-FEED-003", "M2-EQ-001", "M2-GAP-012"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 2 },
    fault_areas: ["Weekend gap", "Delayed stop-out", "Wrong mark-to-market", "Insurance/NBP policy mis-applied"],
    escalation: {
      sla_minutes: 20,
      path: [
        { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Case queue" },
        { after_minutes: 20, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "NBP write-off authority" },
      ],
    },
    corrections: [
      { action: "apply_nbp_policy", bu: "OPERATIONS", description: "Apply entity NBP rules", requires_human: true },
      { action: "freeze_affected_symbols", bu: "RISK_CONTROL", description: "Close-only until marks validated", requires_human: true },
      { action: "reconcile_equity", bu: "OPERATIONS", description: "Rebuild account equity ledger" },
    ],
    past_cases: [
      { case_id: "CASE-NBP-0526", date: "2026-05-26", outcome: "LOSS ~$90k written off", summary: "Holiday gap on indices; NBP policy applied; symbols close-only 2h." },
    ],
    owner_department: "OPERATIONS",
    steps: [
      { action: "lark_notify", description: "Notify Ops + Risk", params: { channel: "oc_ops_funding_recon" }, bu: "OPERATIONS" },
      { action: "list_nbp_accounts", description: "Export negative equity list", bu: "OPERATIONS" },
      { action: "flag_for_human_review", description: "Approve NBP application", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-SLIPPAGE-SPIKE",
    name: "Client slippage spike (≥3.5 pips avg)",
    description: "Execution quality degradation — complaint surge and toxic flow feedback loop.",
    indicator: {
      monitor_id: "M2-SLIP-021",
      name: "Avg Client Slippage (majors, 15m)",
      product: "CFD",
      domain: "MARKET_PRICING",
      warn: 2,
      breach: 3.5,
      unit: "pips",
      comparator: "gte",
      why: "≥3.5 pips on majors historically precedes complaint spikes and LP reject storms; 2 pips is early desk WARN.",
    },
    related_indicators: ["M2-LP-022", "M2-FEED-003", "M2-BRIDGE-LAT"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 2 },
    fault_areas: ["LP reject / partial fills", "Bridge latency", "Stale aggregator", "B-book inventory skew"],
    escalation: {
      sla_minutes: 15,
      path: [
        { after_minutes: 0, team: "Trading Infra", channel: "oc_trading_infra", action: "Bridge/LP check" },
        { after_minutes: 15, team: "Risk Control", channel: "oc_risk_control_desk", action: "Routing / A-book review" },
      ],
    },
    corrections: [
      { action: "check_bridge_health", bu: "SYSTEM", description: "Bridge latency & session health" },
      { action: "reroute_abook", bu: "RISK_CONTROL", description: "Shift majors to healthier LP" },
      { action: "temp_widen_spreads", bu: "RISK_CONTROL", description: "Widen until fill quality recovers", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-SLIP-0702", date: "2026-07-02", outcome: "PREVENTED", summary: "Rerouted EURUSD off LP-C; slippage back to 1.1 pips." },
    ],
    owner_department: "SYSTEM",
    steps: [
      { action: "lark_notify", description: "Page Trading Infra", params: { channel: "oc_trading_infra" }, bu: "SYSTEM" },
      { action: "check_bridge_health", description: "Bridge + LP latency checklist", bu: "SYSTEM" },
      { action: "flag_for_human_review", description: "Approve reroute / widen", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-BRIDGE-LATENCY",
    name: "oneZero bridge latency (≥250ms p95)",
    description: "Infra path when bridge p95 latency threatens fills and hedge timing.",
    indicator: {
      monitor_id: "M2-BRIDGE-LAT",
      name: "Bridge Fill Latency p95",
      product: "CFD",
      domain: "TECH_INFRA",
      warn: 120,
      breach: 250,
      unit: "ms",
      comparator: "gte",
      why: "p95 ≥250ms correlates with reject storms and slippage BREACH; 120ms is capacity WARN.",
    },
    related_indicators: ["M2-LP-022", "M2-SLIP-021", "M2-HEDGE-007"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 120 },
    fault_areas: ["Network path congestion", "Bridge process GC", "LP endpoint degradation", "Symbol storm volume"],
    escalation: {
      sla_minutes: 5,
      path: [
        { after_minutes: 0, team: "Trading Infra P1", channel: "oc_trading_infra", action: "Page on-call" },
        { after_minutes: 10, team: "Risk Control", channel: "oc_risk_control_desk", action: "If rejects also BREACH" },
      ],
    },
    corrections: [
      { action: "restart_bridge_worker", bu: "SYSTEM", description: "Controlled bridge worker recycle", requires_human: true },
      { action: "failover_bridge_path", bu: "SYSTEM", description: "Failover network path" },
      { action: "throttle_noncrit_symbols", bu: "RISK_CONTROL", description: "Throttle exotic symbols temporarily" },
    ],
    past_cases: [
      { case_id: "CASE-BRIDGE-0915", date: "2026-09-15", outcome: "PREVENTED", summary: "Failover path cut p95 from 310→95ms before reject BREACH." },
    ],
    owner_department: "SYSTEM",
    steps: [
      { action: "lark_notify", description: "Page Trading Infra P1", params: { channel: "oc_trading_infra" }, bu: "SYSTEM" },
      { action: "failover_bridge_path", description: "Attempt path failover", bu: "SYSTEM" },
      { action: "flag_for_human_review", description: "Approve worker recycle if needed", requires_human: true, bu: "SYSTEM" },
    ],
  },
  {
    code: "SKILL-ABOOK-RATIO",
    name: "A-book ratio drift (<40% or >90%)",
    description: "Book construction risk — too little A-book leaves inventory; too much stresses LP credit.",
    indicator: {
      monitor_id: "M2-ABOOK-008",
      name: "A-book Volume Ratio (session)",
      product: "CFD",
      domain: "LP_HEDGE",
      warn: 40,
      breach: 30,
      unit: "%",
      comparator: "lte",
      why: "A-book <40% means heavy B-book inventory risk into vol; <30% is breach requiring forced A-book on toxic flow.",
    },
    related_indicators: ["M2-HEDGE-007", "M2-EQ-001", "M2-LP-022"],
    conditions: { severity_in: ["WARN", "BREACH"], max_observed: 40 },
    fault_areas: ["Manual B-book override left on", "LP credit full → silent B-book", "Toxic symbol mis-classification"],
    escalation: {
      sla_minutes: 20,
      path: [
        { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Notify" },
        { after_minutes: 20, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Approve A-book force" },
      ],
    },
    corrections: [
      { action: "suggest_abook_increase", bu: "RISK_CONTROL", description: "Force A-book on top toxic symbols", requires_human: true },
      { action: "review_bbook_overrides", bu: "RISK_CONTROL", description: "Audit manual overrides" },
    ],
    past_cases: [
      { case_id: "CASE-ABOOK-0612", date: "2026-06-12", outcome: "PREVENTED ~$150k", summary: "Override left on overnight; forced A-book restored ratio to 55%." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Risk Control Desk", params: { channel: "oc_risk_control_desk" }, bu: "RISK_CONTROL" },
      { action: "review_bbook_overrides", description: "List active B-book overrides", bu: "RISK_CONTROL" },
      { action: "flag_for_human_review", description: "Approve A-book force", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-VAR-BREACH",
    name: "1-day VaR utilisation (≥95%)",
    description: "Capital / market risk when firm VaR approaches limit — often co-moves with equity DD.",
    indicator: {
      monitor_id: "M2-VAR-002",
      name: "1-day VaR Utilisation",
      product: "CFD",
      domain: "MARKET_PRICING",
      warn: 85,
      breach: 95,
      unit: "%",
      comparator: "gte",
      why: "95% VaR utilisation is hard internal limit buffer; 85% triggers desk de-risk before limit breach.",
    },
    related_indicators: ["M2-EQ-001", "M2-HEDGE-007", "M2-CORR-004"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 85 },
    fault_areas: ["Concentrated metals/FX inventory", "Correlation shock", "Hedge under-coverage", "Holiday thin books"],
    escalation: {
      sla_minutes: 15,
      path: [
        { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "De-risk plan" },
        { after_minutes: 30, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If ≥95%" },
      ],
    },
    corrections: [
      { action: "inventory_flatten_plan", bu: "RISK_CONTROL", description: "Flatten top VaR contributors", requires_human: true },
      { action: "reduce_gross_limits", bu: "RISK_CONTROL", description: "Temporary gross limit cut", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-VAR-0418", date: "2026-04-18", outcome: "PREVENTED", summary: "Flattened XAU/USD book; VaR util 97%→78%." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Risk Control Desk", params: { channel: "oc_risk_control_desk" }, bu: "RISK_CONTROL" },
      { action: "rank_var_contributors", description: "Rank positions by VaR contribution", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve flatten plan", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-CORRELATION-BREAK",
    name: "FX correlation regime break (≥0.35 Δ)",
    description: "Risk models mis-hedge when realised correlations jump vs assumed matrix.",
    indicator: {
      monitor_id: "M2-CORR-004",
      name: "Corr Matrix Drift vs Baseline",
      product: "CFD",
      domain: "MARKET_PRICING",
      warn: 0.2,
      breach: 0.35,
      unit: "Δρ",
      comparator: "gte",
      why: "Δρ ≥0.35 invalidates netting assumptions in VaR/hedge; 0.2 prompts model refresh.",
    },
    related_indicators: ["M2-VAR-002", "M2-EQ-001", "M2-HEDGE-007"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 0.2 },
    fault_areas: ["Risk-off USD spike", "Stale corr matrix", "Cross-asset contagion", "Wrong hedge ratios"],
    escalation: {
      sla_minutes: 30,
      path: [
        { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Model review" },
        { after_minutes: 30, team: "AI + Risk", channel: "oc_ai_detection_lab", action: "Refresh corr inputs" },
      ],
    },
    corrections: [
      { action: "refresh_corr_matrix", bu: "AI", description: "Recompute rolling correlations" },
      { action: "widen_var_buffer", bu: "RISK_CONTROL", description: "Temporary VaR buffer +10%", requires_human: true },
      { action: "rebalance_hedges", bu: "RISK_CONTROL", description: "Adjust hedge ratios", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-CORR-0228", date: "2026-02-28", outcome: "PREVENTED", summary: "Refreshed matrix during USD spike; avoided false VaR comfort." },
    ],
    owner_department: "AI",
    steps: [
      { action: "lark_notify", description: "Notify Risk + AI", params: { channel: "oc_risk_control_desk" }, bu: "AI" },
      { action: "refresh_corr_matrix", description: "Kick rolling corr job", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve VaR buffer widen", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-GAP-RISK",
    name: "Weekend / holiday gap exposure (≥$2m)",
    description: "Open risk into closed markets — metals, indices, crypto-correlated FX.",
    indicator: {
      monitor_id: "M2-GAP-012",
      name: "Estimated Gap Exposure (USD)",
      product: "CFD",
      domain: "PRODUCT_CONFIG",
      warn: 1000000,
      breach: 2000000,
      unit: "USD",
      comparator: "gte",
      why: "$2m stress gap is internal capital buffer; $1m warn triggers close-only / promo pause before weekend.",
    },
    related_indicators: ["M2-XAU-247", "M2-HEDGE-007", "M2-NBP-016", "M2-EQ-001"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 1000000 },
    fault_areas: ["Weekend promo", "Thin LP books", "One-way client positioning", "No pre-hedge"],
    escalation: {
      sla_minutes: 30,
      path: [
        { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Gap pack review" },
        { after_minutes: 60, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Close-only / promo pause" },
      ],
    },
    corrections: [
      { action: "suggest_close_only_prepare", bu: "RISK_CONTROL", description: "Arm close-only on gap symbols" },
      { action: "pause_weekend_promo", bu: "OPERATIONS", description: "Pause acquisition promos", requires_human: true },
      { action: "prehedge_metals", bu: "RISK_CONTROL", description: "Pre-hedge metals/indices", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-GAP-051", date: "2026-05-01", outcome: "PREVENTED", summary: "Gap pack armed; Monday open contained within buffer." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Risk Control Desk", params: { channel: "oc_risk_control_desk" }, bu: "RISK_CONTROL" },
      { action: "run_gap_pack", description: "Generate weekend gap pack", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve close-only / pre-hedge", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-SPREAD-ANOMALY",
    name: "Abnormal client spread (≥3× median)",
    description: "Pricing / product misconfig — spreads too wide (complaints) or too tight (toxic).",
    indicator: {
      monitor_id: "M2-SPREAD-005",
      name: "Spread vs Session Median Ratio",
      product: "CFD",
      domain: "PRODUCT_CONFIG",
      warn: 2,
      breach: 3,
      unit: "x",
      comparator: "gte",
      why: "≥3× median indicates feed/markup bug or crisis mode left on; ≥2× needs desk confirmation.",
    },
    related_indicators: ["M2-FEED-003", "M2-SLIP-021", "M2-EQ-001"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 2 },
    fault_areas: ["Markup table deploy error", "Crisis widen left on", "Feed failover to backup venue", "Symbol session mismatch"],
    escalation: {
      sla_minutes: 15,
      path: [
        { after_minutes: 0, team: "Trading Infra", channel: "oc_trading_infra", action: "Pricing check" },
        { after_minutes: 15, team: "Risk Control", channel: "oc_risk_control_desk", action: "Product condition fix" },
      ],
    },
    corrections: [
      { action: "rollback_markup", bu: "SYSTEM", description: "Rollback last markup deploy", requires_human: true },
      { action: "restore_session_spreads", bu: "RISK_CONTROL", description: "Restore standard spreads" },
    ],
    past_cases: [
      { case_id: "CASE-SPREAD-0819", date: "2026-08-19", outcome: "PREVENTED", summary: "Markup deploy rolled back in 11m; complaint ticket avoided." },
    ],
    owner_department: "SYSTEM",
    steps: [
      { action: "lark_notify", description: "Notify Infra + Risk", params: { channel: "oc_trading_infra" }, bu: "SYSTEM" },
      { action: "diff_markup_table", description: "Diff last markup deploy", bu: "SYSTEM" },
      { action: "flag_for_human_review", description: "Approve rollback", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-LEVERAGE-ONBOARD",
    name: "High-leverage new accounts (≥200 / day)",
    description: "Product / credit control when many new accounts get max leverage — toxic cohort risk.",
    indicator: {
      monitor_id: "M2-LEV-019",
      name: "New Accounts at Max Leverage (24h)",
      product: "CFD",
      domain: "PRODUCT_CONFIG",
      warn: 100,
      breach: 200,
      unit: "accounts",
      comparator: "gte",
      why: "≥200 max-leverage onboardings/day historically precedes margin spikes within 48h of promo.",
    },
    related_indicators: ["M2-MRG-014", "M2-FRAUD-011", "M2-BONUS-013"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 100 },
    fault_areas: ["Aggressive promo", "KYC velocity too high", "Default leverage misconfig", "Affiliate abuse"],
    escalation: {
      sla_minutes: 45,
      path: [
        { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Onboarding review" },
        { after_minutes: 45, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Leverage default cut" },
      ],
    },
    corrections: [
      { action: "cut_default_leverage", bu: "RISK_CONTROL", description: "Lower default leverage for new accounts", requires_human: true },
      { action: "slow_onboarding", bu: "OPERATIONS", description: "Tighten KYC velocity" },
      { action: "pause_leverage_promo", bu: "OPERATIONS", description: "Pause max-leverage promo", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-LEV-0722", date: "2026-07-22", outcome: "PREVENTED", summary: "Default cut 1:500→1:200; next-day margin WARN avoided." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Ops + Credit", params: { channel: "oc_ops_funding_recon" }, bu: "OPERATIONS" },
      { action: "cohort_toxicity_score", description: "Score new cohort toxicity", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve default leverage cut", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-BONUS-BURN",
    name: "Bonus conversion abuse (≥$150k / day)",
    description: "Promo P&L drain when bonus-to-withdrawable conversion spikes.",
    indicator: {
      monitor_id: "M2-BONUS-013",
      name: "Bonus Converted to Cash (24h USD)",
      product: "CFD",
      domain: "FRAUD_CONDUCT",
      warn: 75000,
      breach: 150000,
      unit: "USD",
      comparator: "gte",
      why: "$150k/day conversion is above promo ROI break-even; $75k warn for Ops/Fraud review.",
    },
    related_indicators: ["M2-FRAUD-011", "M2-COPY-009", "M2-WD-015"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 75000 },
    fault_areas: ["Bonus hunting rings", "Volume wash to meet turnover", "Affiliate collusion", "Weak turnover rules"],
    escalation: {
      sla_minutes: 30,
      path: [
        { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Promo freeze review" },
        { after_minutes: 30, team: "Risk Control", channel: "oc_credit_client_risk", action: "Trading restriction" },
      ],
    },
    corrections: [
      { action: "suggest_bonus_freeze", bu: "OPERATIONS", description: "Freeze bonus conversions", requires_human: true },
      { action: "tighten_turnover_rules", bu: "OPERATIONS", description: "Increase turnover multiple" },
      { action: "restrict_trading", bu: "RISK_CONTROL", description: "Close-only on abuse cluster", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-BONUS-0618", date: "2026-06-18", outcome: "PREVENTED ~$210k", summary: "Freeze stopped ring mid-conversion." },
    ],
    owner_department: "OPERATIONS",
    steps: [
      { action: "lark_notify", description: "Notify Ops War Room", params: { channel: "oc_ops_funding_recon" }, bu: "OPERATIONS" },
      { action: "suggest_bonus_freeze", description: "Propose freeze", requires_human: true, bu: "OPERATIONS" },
      { action: "flag_for_human_review", description: "KYC linkage before bans", bu: "OPERATIONS" },
    ],
  },
  {
    code: "SKILL-WITHDRAWAL-VELOCITY",
    name: "Withdrawal velocity surge (≥$5m / hour)",
    description: "Liquidity / custody / fraud stress when outflows accelerate.",
    indicator: {
      monitor_id: "M2-WD-015",
      name: "Withdrawal Volume (1h USD)",
      product: "CFD+Crypto",
      domain: "OPS_PROCESS",
      warn: 2000000,
      breach: 5000000,
      unit: "USD",
      comparator: "gte",
      why: "$5m/h exceeds normal treasury buffer; $2m warn for Ops funding + crypto float check.",
    },
    related_indicators: ["M2-CRYPTO-WALLET", "M2-FRAUD-011", "M2-FUND-010", "M2-BONUS-013"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 2000000 },
    fault_areas: ["Bank run rumour", "Promo cash-out", "Fraud ring exit", "Hot wallet undersized"],
    escalation: {
      sla_minutes: 15,
      path: [
        { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Treasury + KYC triage" },
        { after_minutes: 15, team: "Crypto Risk", channel: "oc_crypto_exchange_risk", action: "If crypto float WARN" },
        { after_minutes: 30, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Throttle decision" },
      ],
    },
    corrections: [
      { action: "pause_large_withdrawals", bu: "OPERATIONS", description: "Throttle large withdrawals", requires_human: true },
      { action: "suggest_cold_wallet_sweep", bu: "SYSTEM", description: "If crypto float elevated — opposite: ensure hot liquidity" },
      { action: "enhanced_kyc_queue", bu: "OPERATIONS", description: "Enhanced review on top outflows" },
    ],
    past_cases: [
      { case_id: "CASE-WD-0901", date: "2026-09-01", outcome: "PREVENTED", summary: "Throttle + KYC stopped $3.2m suspicious cluster." },
    ],
    owner_department: "OPERATIONS",
    steps: [
      { action: "lark_notify", description: "Notify Ops War Room", params: { channel: "oc_ops_funding_recon" }, bu: "OPERATIONS" },
      { action: "rank_withdrawal_clusters", description: "Cluster by device/KYC", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve throttle", requires_human: true, bu: "OPERATIONS" },
    ],
  },
  {
    code: "SKILL-FUNDING-EXCEPTION",
    name: "Funding exception surge (≥80 / hour)",
    description: "Ops process risk — deposit/withdrawal exceptions overwhelm recon.",
    indicator: {
      monitor_id: "M2-FUND-010",
      name: "Funding Exceptions (1h)",
      product: "CFD",
      domain: "OPS_PROCESS",
      warn: 30,
      breach: 80,
      unit: "count/h",
      comparator: "gte",
      why: "≥80/h exceeds Ops SLA capacity; unworked exceptions create client credit risk and fraud blind spots.",
    },
    related_indicators: ["M2-FRAUD-011", "M2-WD-015", "M2-PAY-017"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 30 },
    fault_areas: ["PSP outage", "Bank file delay", "Manual override backlog", "Promo deposit flood"],
    escalation: {
      sla_minutes: 45,
      path: [
        { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Exception triage" },
        { after_minutes: 45, team: "Risk Control", channel: "oc_credit_client_risk", action: "If credit impacted" },
      ],
    },
    corrections: [
      { action: "boost_ops_queue", bu: "OPERATIONS", description: "Add recon staff / overtime", requires_human: true },
      { action: "pause_psp", bu: "OPERATIONS", description: "Pause failing PSP channel", requires_human: true },
      { action: "auto_match_rules", bu: "SYSTEM", description: "Enable stricter auto-match temporarily" },
    ],
    past_cases: [
      { case_id: "CASE-FUND-0410", date: "2026-04-10", outcome: "PREVENTED", summary: "PSP pause + queue boost cleared backlog in 2h." },
    ],
    owner_department: "OPERATIONS",
    steps: [
      { action: "lark_notify", description: "Notify Ops War Room", params: { channel: "oc_ops_funding_recon" }, bu: "OPERATIONS" },
      { action: "triage_exception_codes", description: "Group by PSP/error code", bu: "OPERATIONS" },
      { action: "flag_for_human_review", description: "Approve PSP pause", requires_human: true, bu: "OPERATIONS" },
    ],
  },
  {
    code: "SKILL-PAYMENT-FRAUD",
    name: "Payment fraud score (≥0.8)",
    description: "Card/PSP abuse — chargebacks and stolen instruments.",
    indicator: {
      monitor_id: "M2-PAY-017",
      name: "Payment Fraud Model Score",
      product: "CFD",
      domain: "FRAUD_CONDUCT",
      warn: 0.65,
      breach: 0.8,
      unit: "score",
      comparator: "gte",
      why: "Score ≥0.8 historically maps to >40% chargeback on that cohort; 0.65 is enhanced KYC WARN.",
    },
    related_indicators: ["M2-FRAUD-011", "M2-FUND-010", "M2-WD-015"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 0.65 },
    fault_areas: ["Stolen cards", "3DS bypass gaps", "Velocity attacks", "Mule accounts"],
    escalation: {
      sla_minutes: 20,
      path: [
        { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Payment hold" },
        { after_minutes: 20, team: "Risk Control", channel: "oc_credit_client_risk", action: "Trading freeze review" },
      ],
    },
    corrections: [
      { action: "hold_deposits", bu: "OPERATIONS", description: "Hold deposits from scored cohort", requires_human: true },
      { action: "force_3ds", bu: "SYSTEM", description: "Force 3DS on channel" },
      { action: "restrict_trading", bu: "RISK_CONTROL", description: "Close-only until cleared", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-PAY-0319", date: "2026-03-19", outcome: "PREVENTED ~$120k", summary: "Hold + 3DS stopped card-testing ring." },
    ],
    owner_department: "OPERATIONS",
    steps: [
      { action: "lark_notify", description: "Notify Ops War Room", params: { channel: "oc_ops_funding_recon" }, bu: "OPERATIONS" },
      { action: "hold_deposits", description: "Propose deposit hold", requires_human: true, bu: "OPERATIONS" },
      { action: "flag_for_human_review", description: "Risk confirms trading freeze", bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-WASH-TRADE",
    name: "Wash / collusion score (≥0.75)",
    description: "Market integrity — wash trading or client collusion on CFD/crypto.",
    indicator: {
      monitor_id: "M2-WASH-020",
      name: "Wash/Collusion Detection Score",
      product: "CFD+Crypto",
      domain: "FRAUD_CONDUCT",
      warn: 0.55,
      breach: 0.75,
      unit: "score",
      comparator: "gte",
      why: "≥0.75 indicates likely matched opposing accounts; regulatory / conduct exposure.",
    },
    related_indicators: ["M2-FRAUD-011", "M2-COPY-009", "M2-CRYPTO-OI"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 0.55 },
    fault_areas: ["Matched accounts", "Self-trading bots", "Copy mirror abuse", "Crypto wash on thin pairs"],
    escalation: {
      sla_minutes: 30,
      path: [
        { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Conduct case" },
        { after_minutes: 30, team: "Ops", channel: "oc_ops_funding_recon", action: "Account freeze pack" },
      ],
    },
    corrections: [
      { action: "restrict_trading", bu: "RISK_CONTROL", description: "Close-only / suspend suspects", requires_human: true },
      { action: "evidence_pack", bu: "AI", description: "Build trade-match evidence pack" },
      { action: "report_conduct", bu: "RISK_CONTROL", description: "Escalate to compliance owner", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-WASH-0112", date: "2026-01-12", outcome: "PREVENTED", summary: "Suspended 6 accounts; evidence pack filed." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Risk Control Desk", params: { channel: "oc_risk_control_desk" }, bu: "RISK_CONTROL" },
      { action: "evidence_pack", description: "Generate match evidence", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve suspensions", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-API-ERROR-RATE",
    name: "Trading API error rate (≥5%)",
    description: "Platform tech risk — client orders failing, silent risk build-up.",
    indicator: {
      monitor_id: "M2-API-023",
      name: "Trading API Error Rate (5m)",
      product: "CFD+Crypto",
      domain: "TECH_INFRA",
      warn: 2,
      breach: 5,
      unit: "%",
      comparator: "gte",
      why: "≥5% error rate means clients cannot manage risk; firm inventory drifts without client closes.",
    },
    related_indicators: ["M2-BRIDGE-LAT", "M2-MRG-014", "M2-CRYPTO-LIQ"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 2 },
    fault_areas: ["Deploy regression", "DB connection pool", "Rate limiter misconfig", "Upstream LP timeout"],
    escalation: {
      sla_minutes: 5,
      path: [
        { after_minutes: 0, team: "Trading Infra P1", channel: "oc_trading_infra", action: "Page" },
        { after_minutes: 10, team: "Risk Control", channel: "oc_risk_control_desk", action: "Inventory drift review" },
      ],
    },
    corrections: [
      { action: "rollback_api_deploy", bu: "SYSTEM", description: "Rollback last trading API deploy", requires_human: true },
      { action: "scale_api_pods", bu: "SYSTEM", description: "Scale API / DB pool" },
      { action: "status_page_notice", bu: "OPERATIONS", description: "Client status communication" },
    ],
    past_cases: [
      { case_id: "CASE-API-0827", date: "2026-08-27", outcome: "PREVENTED", summary: "Rollback in 6m; error rate 7%→0.4%." },
    ],
    owner_department: "SYSTEM",
    steps: [
      { action: "lark_notify", description: "Page Trading Infra P1", params: { channel: "oc_trading_infra" }, bu: "SYSTEM" },
      { action: "scale_api_pods", description: "Autoscale attempt", bu: "SYSTEM" },
      { action: "flag_for_human_review", description: "Approve rollback", requires_human: true, bu: "SYSTEM" },
    ],
  },
  {
    code: "SKILL-DETECTOR-DRIFT",
    name: "Detector precision drift (<70%)",
    description: "Model/AI risk — detectors flooding false positives or missing true breaches.",
    indicator: {
      monitor_id: "M2-MODEL-006",
      name: "Detector Precision (7d rolling)",
      product: "CFD+Crypto",
      domain: "MODEL_AI",
      warn: 80,
      breach: 70,
      unit: "%",
      comparator: "lte",
      why: "Precision <70% overwhelms human checkers and erodes trust; shadow disable candidate.",
    },
    related_indicators: ["M2-EQ-001", "M2-FRAUD-011"],
    conditions: { severity_in: ["WARN", "BREACH"], max_observed: 80 },
    fault_areas: ["Feature drift", "Threshold too tight", "Label delay", "Regime change"],
    escalation: {
      sla_minutes: 60,
      path: [
        { after_minutes: 0, team: "AI Engineering", channel: "oc_ai_detection_lab", action: "Drift review" },
        { after_minutes: 60, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Approve shadow / retrain CR" },
      ],
    },
    corrections: [
      { action: "disable_detector_shadow", bu: "AI", description: "Shadow-disable noisy detector", requires_human: true },
      { action: "propose_threshold_cr", bu: "AI", description: "Propose threshold change via AI Admin" },
      { action: "retrain_skill_matcher", bu: "AI", description: "Queue retrain", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-MODEL-1001", date: "2026-10-01", outcome: "GOVERNANCE", summary: "AI Admin maker/checker landed SKILL-DEMO-LIQ after drift review." },
    ],
    owner_department: "AI",
    auto_execute: false,
    steps: [
      { action: "lark_notify", description: "Notify AI Detection Lab", params: { channel: "oc_ai_detection_lab" }, bu: "AI" },
      { action: "propose_threshold_cr", description: "Draft CR in AI Admin", bu: "AI" },
      { action: "flag_for_human_review", description: "Risk Owner checks CR", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-ENTITY-CAPITAL",
    name: "Entity capital buffer thin (<15%)",
    description: "Regulatory / entity capital headroom below policy buffer.",
    indicator: {
      monitor_id: "M2-CAP-024",
      name: "Entity Capital Buffer Ratio",
      product: "CFD+Crypto",
      domain: "REG_CAPITAL",
      warn: 20,
      breach: 15,
      unit: "%",
      comparator: "lte",
      why: "Policy requires ≥15% buffer above regulatory minimum; 20% is early treasury/risk WARN.",
    },
    related_indicators: ["M2-EQ-001", "M2-VAR-002", "M2-SEG-025"],
    conditions: { severity_in: ["WARN", "BREACH"], max_observed: 20 },
    fault_areas: ["P&L drawdown", "Dividend / intercompany transfer", "Crypto custody mark", "Stress add-on"],
    escalation: {
      sla_minutes: 60,
      path: [
        { after_minutes: 0, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Capital pack" },
        { after_minutes: 60, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If <15%" },
      ],
    },
    corrections: [
      { action: "reduce_gross_limits", bu: "RISK_CONTROL", description: "Cut entity risk limits", requires_human: true },
      { action: "capital_injection_request", bu: "EXEC", description: "Request capital top-up", requires_human: true },
      { action: "dual_book_limits", bu: "RISK_CONTROL", description: "Tighten CFD+crypto budgets" },
    ],
    past_cases: [
      { case_id: "CASE-CAP-0510", date: "2026-05-10", outcome: "PREVENTED", summary: "Limit cut bought 48h for capital top-up." },
    ],
    owner_department: "RISK_CONTROL",
    auto_execute: false,
    steps: [
      { action: "lark_notify", description: "Notify Risk Owner", params: { channel: "oc_risk_control_desk" }, bu: "RISK_CONTROL" },
      { action: "build_capital_pack", description: "Entity capital pack", bu: "AI" },
      { action: "flag_for_human_review", description: "Exec/Risk approve limit cut", requires_human: true, bu: "EXEC" },
    ],
  },
  {
    code: "SKILL-SEGREGATION-GAP",
    name: "Client money segregation gap (≥$250k)",
    description: "Trust / regulatory risk when client money reconciliation shows shortfall.",
    indicator: {
      monitor_id: "M2-SEG-025",
      name: "Client Money Segregation Gap (USD)",
      product: "CFD",
      domain: "REG_CAPITAL",
      warn: 50000,
      breach: 250000,
      unit: "USD",
      comparator: "gte",
      why: "Any material segregation gap is regulatory-critical; $250k is hard breach for immediate freeze of non-essential flows.",
    },
    related_indicators: ["M2-FUND-010", "M2-WD-015", "M2-CAP-024"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 50000 },
    fault_areas: ["Bank file delay", "Wrong entity booking", "Crypto conversion lag", "Manual journal error"],
    escalation: {
      sla_minutes: 30,
      path: [
        { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Immediate recon" },
        { after_minutes: 15, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Segregation war-room" },
        { after_minutes: 30, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If gap ≥$250k" },
      ],
    },
    corrections: [
      { action: "freeze_nonessential_flows", bu: "OPERATIONS", description: "Pause non-essential transfers", requires_human: true },
      { action: "topup_seg_account", bu: "EXEC", description: "Top-up segregation account", requires_human: true },
      { action: "full_cm_recon", bu: "OPERATIONS", description: "Full client-money recon" },
    ],
    past_cases: [
      { case_id: "CASE-SEG-0220", date: "2026-02-20", outcome: "PREVENTED", summary: "Bank file delay; top-up within 40m; gap closed." },
    ],
    owner_department: "OPERATIONS",
    auto_execute: false,
    steps: [
      { action: "lark_notify", description: "Notify Ops + Risk Owner + Exec channel readiness", params: { channel: "oc_ops_funding_recon" }, bu: "OPERATIONS" },
      { action: "full_cm_recon", description: "Start full CM recon", bu: "OPERATIONS" },
      { action: "flag_for_human_review", description: "Approve freeze / top-up", requires_human: true, bu: "EXEC" },
    ],
  },
  {
    code: "SKILL-CRYPTO-ORACLE",
    name: "Oracle / index lag (≥2s)",
    description: "Crypto pricing integrity — lagged oracle causes wrong liquidations and arb.",
    indicator: {
      monitor_id: "M2-CRYPTO-ORACLE",
      name: "Mark Price Oracle Lag",
      product: "Crypto",
      domain: "CRYPTO_EXCHANGE",
      warn: 1,
      breach: 2,
      unit: "seconds",
      comparator: "gte",
      why: "≥2s lag on mark price can liquidate wrongly in high vol; 1s is failover WARN.",
    },
    related_indicators: ["M2-CRYPTO-LIQ", "M2-CRYPTO-INS", "M2-FEED-003"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 1 },
    fault_areas: ["Oracle provider outage", "Websocket stall", "Matching engine clock skew", "Composite weight bug"],
    escalation: {
      sla_minutes: 5,
      path: [
        { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Notify" },
        { after_minutes: 5, team: "Trading Infra", channel: "oc_trading_infra", action: "Oracle failover" },
      ],
    },
    corrections: [
      { action: "failover_oracle", bu: "SYSTEM", description: "Switch to secondary oracle" },
      { action: "pause_new_perp_listings", bu: "RISK_CONTROL", description: "Pause high-leverage perps", requires_human: true },
      { action: "suppress_auto_liq", bu: "RISK_CONTROL", description: "Pause auto-liq on affected pairs", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-ORACLE-0611", date: "2026-06-11", outcome: "PREVENTED", summary: "Failover at 1.6s lag; avoided cascade wrong liqs." },
    ],
    owner_department: "SYSTEM",
    steps: [
      { action: "lark_notify", description: "Notify Crypto Risk + Infra", params: { channel: "oc_crypto_exchange_risk" }, bu: "SYSTEM" },
      { action: "failover_oracle", description: "Secondary oracle", bu: "SYSTEM" },
      { action: "flag_for_human_review", description: "Approve auto-liq pause", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-CRYPTO-INSURANCE",
    name: "Insurance fund drawdown (≥8% day)",
    description: "Exchange solvency buffer eroding under liquidation shortfalls.",
    indicator: {
      monitor_id: "M2-CRYPTO-INS",
      name: "Insurance Fund Daily Drawdown",
      product: "Crypto",
      domain: "CRYPTO_EXCHANGE",
      warn: 4,
      breach: 8,
      unit: "%",
      comparator: "gte",
      why: "≥8% daily IF drawdown threatens ADL; 4% warn to cut leverage / pause listings.",
    },
    related_indicators: ["M2-CRYPTO-LIQ", "M2-CRYPTO-ORACLE", "M2-CRYPTO-OI"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 4 },
    fault_areas: ["Liq backlog", "Oracle lag", "Concentrated OI", "Insufficient maintenance margin"],
    escalation: {
      sla_minutes: 15,
      path: [
        { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "War-room" },
        { after_minutes: 15, team: "Risk Owner", channel: "oc_risk_control_desk", action: "ADL / leverage cut" },
        { after_minutes: 45, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If ≥8%" },
      ],
    },
    corrections: [
      { action: "cut_perp_leverage", bu: "RISK_CONTROL", description: "Cut max leverage on affected perps", requires_human: true },
      { action: "scale_liq_workers", bu: "SYSTEM", description: "Clear liq backlog" },
      { action: "prepare_adl", bu: "RISK_CONTROL", description: "Prepare ADL ladder", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-INS-0221", date: "2026-02-21", outcome: "NEAR_MISS", summary: "IF DD 7.2%; leverage cut avoided ADL." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Crypto Risk", params: { channel: "oc_crypto_exchange_risk" }, bu: "RISK_CONTROL" },
      { action: "scale_liq_workers", description: "Scale liq workers", bu: "SYSTEM" },
      { action: "flag_for_human_review", description: "Approve leverage cut / ADL prep", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-CRYPTO-OI-CONC",
    name: "Perp OI concentration (≥35% one account)",
    description: "Single account / cluster dominates open interest — liquidation cliff risk.",
    indicator: {
      monitor_id: "M2-CRYPTO-OI",
      name: "Top Account OI Share (per contract)",
      product: "Crypto",
      domain: "CRYPTO_EXCHANGE",
      warn: 20,
      breach: 35,
      unit: "%",
      comparator: "gte",
      why: "≥35% one account can cascade the book on liq; 20% triggers position limit review.",
    },
    related_indicators: ["M2-CRYPTO-LIQ", "M2-CRYPTO-INS", "M2-WASH-020"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 20 },
    fault_areas: ["Missing position limits", "Whale onboarding", "Multi-account aggregation gap", "Incentive campaign"],
    escalation: {
      sla_minutes: 30,
      path: [
        { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Position limit review" },
        { after_minutes: 30, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Force reduce" },
      ],
    },
    corrections: [
      { action: "enforce_oi_cap", bu: "RISK_CONTROL", description: "Enforce per-account OI cap", requires_human: true },
      { action: "force_reduce_only", bu: "RISK_CONTROL", description: "Reduce-only on whale", requires_human: true },
      { action: "kyc_cluster_review", bu: "OPERATIONS", description: "Check sybil aggregation" },
    ],
    past_cases: [
      { case_id: "CASE-OI-0719", date: "2026-07-19", outcome: "PREVENTED", summary: "Reduce-only at 36% OI; IF untouched in later dump." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Crypto Risk", params: { channel: "oc_crypto_exchange_risk" }, bu: "RISK_CONTROL" },
      { action: "kyc_cluster_review", description: "Sybil check", bu: "OPERATIONS" },
      { action: "flag_for_human_review", description: "Approve reduce-only", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-CRYPTO-DEPOSIT-SPIKE",
    name: "Crypto deposit spike (≥$8m / hour)",
    description: "Custody ops — deposit surge before cold sweep can breach hot float.",
    indicator: {
      monitor_id: "M2-CRYPTO-DEP",
      name: "Crypto Deposits (1h USD)",
      product: "Crypto",
      domain: "CRYPTO_EXCHANGE",
      warn: 3000000,
      breach: 8000000,
      unit: "USD",
      comparator: "gte",
      why: "$8m/h deposit spike without sweep pushes hot float past 15% warn within one hour.",
    },
    related_indicators: ["M2-CRYPTO-WALLET", "M2-WD-015", "M2-CRYPTO-LIQ"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 3000000 },
    fault_areas: ["Listing hype", "Delayed sweep job", "Bridge congestion", "Market-maker deposit"],
    escalation: {
      sla_minutes: 20,
      path: [
        { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Sweep now" },
        { after_minutes: 20, team: "Trading Infra", channel: "oc_trading_infra", action: "Cold sweep ops" },
      ],
    },
    corrections: [
      { action: "suggest_cold_wallet_sweep", bu: "SYSTEM", description: "Immediate cold sweep" },
      { action: "raise_sweep_frequency", bu: "SYSTEM", description: "Temporarily raise sweep cadence" },
      { action: "pause_large_withdrawals", bu: "OPERATIONS", description: "If float still rising", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-DEP-1003", date: "2026-10-01", outcome: "PREVENTED", summary: "Sweep after deposit spike kept float under 25%." },
    ],
    owner_department: "SYSTEM",
    steps: [
      { action: "lark_notify", description: "Notify Crypto Risk", params: { channel: "oc_crypto_exchange_risk" }, bu: "SYSTEM" },
      { action: "suggest_cold_wallet_sweep", description: "Trigger sweep recommendation", bu: "SYSTEM" },
      { action: "flag_for_human_review", description: "Approve withdrawal throttle if needed", requires_human: true, bu: "OPERATIONS" },
    ],
  },
  {
    code: "SKILL-LATENCY-ARB",
    name: "Latency arb score (≥0.7)",
    description: "Toxic flow — clients systematically picking off stale quotes.",
    indicator: {
      monitor_id: "M2-ARB-026",
      name: "Latency Arb Toxicity Score",
      product: "CFD",
      domain: "CREDIT_CLIENT",
      warn: 0.5,
      breach: 0.7,
      unit: "score",
      comparator: "gte",
      why: "Score ≥0.7 identifies accounts with statistically significant last-look wins; desk must widen/reject.",
    },
    related_indicators: ["M2-FEED-003", "M2-SLIP-021", "M2-EQ-001", "M2-BRIDGE-LAT"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 0.5 },
    fault_areas: ["Stale feed to client", "Slow last-look", "Colo advantage abuse", "Symbol map lag"],
    escalation: {
      sla_minutes: 20,
      path: [
        { after_minutes: 0, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Toxic list" },
        { after_minutes: 20, team: "Risk Control", channel: "oc_risk_control_desk", action: "Reject / A-book force" },
      ],
    },
    corrections: [
      { action: "force_abook_toxic", bu: "RISK_CONTROL", description: "Force A-book + reject on toxic accounts", requires_human: true },
      { action: "widen_toxic_spreads", bu: "RISK_CONTROL", description: "Account-level widen" },
      { action: "failover_feed", bu: "SYSTEM", description: "Ensure primary feed freshness" },
    ],
    past_cases: [
      { case_id: "CASE-ARB-0505", date: "2026-05-05", outcome: "PREVENTED ~$175k", summary: "Toxic list A-booked; PnL drag stopped." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Credit Desk", params: { channel: "oc_credit_client_risk" }, bu: "RISK_CONTROL" },
      { action: "build_toxic_list", description: "Rank accounts by arb score", bu: "AI" },
      { action: "flag_for_human_review", description: "Approve A-book force", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-SWAP-MISCONFIG",
    name: "Swap / financing misconfig (≥10 symbols)",
    description: "Product config — wrong swap rates create overnight P&L leaks or client disputes.",
    indicator: {
      monitor_id: "M2-SWAP-027",
      name: "Symbols with Swap vs Benchmark Δ",
      product: "CFD",
      domain: "PRODUCT_CONFIG",
      warn: 5,
      breach: 10,
      unit: "symbols",
      comparator: "gte",
      why: "≥10 symbols off benchmark indicates bad deploy or holiday table miss — systemic overnight risk.",
    },
    related_indicators: ["M2-EQ-001", "M2-SPREAD-005", "M2-XAU-247"],
    conditions: { severity_in: ["WARN", "BREACH"], min_observed: 5 },
    fault_areas: ["Holiday swap table", "Deploy of rates file", "Triple-swap day miss", "Symbol rename map"],
    escalation: {
      sla_minutes: 30,
      path: [
        { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Rates review" },
        { after_minutes: 30, team: "Ops", channel: "oc_ops_funding_recon", action: "Client adjustment pack if needed" },
      ],
    },
    corrections: [
      { action: "rollback_swap_table", bu: "SYSTEM", description: "Rollback swap rates file", requires_human: true },
      { action: "client_adjustment_pack", bu: "OPERATIONS", description: "Prepare goodwill / correction", requires_human: true },
    ],
    past_cases: [
      { case_id: "CASE-SWAP-1201", date: "2025-12-01", outcome: "LOSS ~$40k adjusted", summary: "Triple-swap miss; rolled back + client adjustments." },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      { action: "lark_notify", description: "Notify Risk Control Desk", params: { channel: "oc_risk_control_desk" }, bu: "RISK_CONTROL" },
      { action: "diff_swap_table", description: "Diff vs benchmark", bu: "SYSTEM" },
      { action: "flag_for_human_review", description: "Approve rollback", requires_human: true, bu: "RISK_CONTROL" },
    ],
  },
  {
    code: "SKILL-MARKET-INTEL",
    name: "Market intelligence high-impact hits (≥1 / 5m)",
    description:
      "External news / social / official publications that can move LP prices on Vantage forex, index, commodity, futures and crypto. Scanner runs every 5 minutes and pushes to oc_market_intelligence.",
    indicator: {
      monitor_id: "M2-MKT-INTEL",
      name: "Market Intelligence High-Impact Hits (5m)",
      product: "CFD+Crypto",
      domain: "MARKET_PRICING",
      warn: 1,
      breach: 3,
      unit: "hits/5m",
      comparator: "gte",
      why: "≥1 WARN+ intel hit warrants desk awareness and optional pre-widen; ≥3 concurrent hits usually means a macro/geo cluster requiring war-room posture.",
    },
    related_indicators: ["M2-EQ-001", "M2-MRG-014", "M2-HEDGE-007", "M2-FEED-003", "M2-VAR-002", "M2-XAU-247"],
    conditions: { severity_in: ["WARN", "BREACH", "CRITICAL"], min_observed: 1 },
    fault_areas: [
      "Unhedged inventory into surprise headline",
      "Late spread widen / leverage cut",
      "LP reject storm under news",
      "Weekend XAUUSD247 gap after geo headlines",
      "Crypto regulatory headline without leverage cut",
    ],
    escalation: {
      sla_minutes: 10,
      path: [
        {
          after_minutes: 0,
          team: "Market Intelligence",
          channel: "oc_market_intelligence",
          action: "Push formatted card (event, geography, severity, products+direction, timestamp, sources)",
        },
        { after_minutes: 5, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Pre-widen / inventory check" },
        { after_minutes: 15, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If CRITICAL geo or ≥3 hits" },
      ],
    },
    corrections: [
      { action: "lark_notify", bu: "AI", description: "Ensure Market Intelligence messenger group received the card" },
      { action: "pre_widen_spreads", bu: "RISK_CONTROL", description: "Pre-widen affected Vantage products" },
      { action: "temp_leverage_cut", bu: "RISK_CONTROL", description: "Session leverage cut on hottest symbols", requires_human: true },
      { action: "rag_macro_check", bu: "AI", description: "Cross-check RAG + macro calendar vs intel card" },
    ],
    past_cases: [
      {
        case_id: "CASE-MI-1001",
        date: "2026-10-01",
        outcome: "PREVENTED",
        summary: "FOMC hawkish cluster pushed to messenger; pre-widen before US open avoided cascade.",
      },
      {
        case_id: "CASE-MI-0912",
        date: "2026-09-12",
        outcome: "NEAR_MISS",
        summary: "OPEC rumour hit oil CFDs; intel card arrived 4m before LP rejects rose.",
      },
    ],
    owner_department: "RISK_CONTROL",
    steps: [
      {
        action: "lark_notify",
        description: "Notify Market Intelligence dedicated group with standard card format",
        params: { channel: "oc_market_intelligence" },
        bu: "AI",
      },
      { action: "map_products_to_book", description: "Map affected Vantage products to open inventory / hedge coverage", bu: "RISK_CONTROL" },
      {
        action: "pre_widen_spreads",
        description: "Propose pre-widen on products with UP/DOWN direction in intel card",
        bu: "RISK_CONTROL",
      },
      {
        action: "flag_for_human_review",
        description: "Approve leverage cut if severity BREACH/CRITICAL or hits ≥3",
        requires_human: true,
        bu: "RISK_CONTROL",
      },
    ],
  },
];

/** Additional multi-indicator linked timeline scenarios */
export const EXTRA_LINKED_SCENARIOS: LinkedScenario[] = [
  {
    code: "CHAIN-STOPOUT-CASCADE",
    name: "Stop-out velocity → margin BREACH → equity WARN",
    description: "Classic liquidation cascade under news: stop-outs accelerate, margin heat, firm equity dips.",
    product: "CFD",
    domain: "CREDIT_CLIENT",
    severity: "CRITICAL",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-STOP-018", severity: "WARN", signal: "Stop-outs ≥20 / 5m" },
      { t_minutes: 5, monitor_id: "M2-STOP-018", severity: "BREACH", signal: "Stop-outs ≥40 / 5m" },
      { t_minutes: 12, monitor_id: "M2-MRG-014", severity: "BREACH", signal: "Accounts >90% margin ≥100" },
      { t_minutes: 18, monitor_id: "M2-SLIP-021", severity: "WARN", signal: "Slippage ≥2 pips as book absorbs" },
      { t_minutes: 30, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Equity DD ≥3%" },
    ],
    causes: ["High-impact news", "Copy pile-in", "Late spread widen", "LP rejects under load"],
    escalation_plan: [
      { after_minutes: 0, team: "Credit Desk", channel: "oc_credit_client_risk", action: "SKILL-STOPOUT-VELOCITY" },
      { after_minutes: 10, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "War-room + leverage cut" },
      { after_minutes: 25, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If EQ WARN persists" },
    ],
    corrections: [
      { action: "temp_leverage_cut", bu: "RISK_CONTROL", description: "Session leverage cut", requires_human: true },
      { action: "pre_widen_spreads", bu: "RISK_CONTROL", description: "Widen hottest symbols" },
      { action: "inventory_flatten_plan", bu: "RISK_CONTROL", description: "Flatten residual", requires_human: true },
    ],
    linked_skills: ["SKILL-STOPOUT-VELOCITY", "SKILL-MARGIN-SPIKE", "SKILL-SLIPPAGE-SPIKE", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-STOP-0814", date: "2026-08-14", outcome: "PREVENTED ~$260k", summary: "CPI cascade contained at T+8m leverage cut." },
    ],
  },
  {
    code: "CHAIN-EXECUTION-DEGRADE",
    name: "Bridge latency → slippage → LP rejects",
    description: "Infra degradation becomes market risk within minutes.",
    product: "CFD",
    domain: "TECH_INFRA",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-BRIDGE-LAT", severity: "WARN", signal: "p95 ≥120ms" },
      { t_minutes: 6, monitor_id: "M2-BRIDGE-LAT", severity: "BREACH", signal: "p95 ≥250ms" },
      { t_minutes: 10, monitor_id: "M2-SLIP-021", severity: "WARN", signal: "Slippage ≥2 pips" },
      { t_minutes: 15, monitor_id: "M2-LP-022", severity: "BREACH", signal: "Reject rate ≥5%" },
      { t_minutes: 25, monitor_id: "M2-HEDGE-007", severity: "WARN", signal: "Coverage <85%" },
    ],
    causes: ["Network congestion", "Bridge GC", "LP endpoint slow", "Volume spike"],
    escalation_plan: [
      { after_minutes: 0, team: "Trading Infra P1", channel: "oc_trading_infra", action: "Failover path" },
      { after_minutes: 5, team: "Risk Control", channel: "oc_risk_control_desk", action: "LP disable / reroute" },
    ],
    corrections: [
      { action: "failover_bridge_path", bu: "SYSTEM", description: "Network path failover" },
      { action: "suggest_lp_disable", bu: "SYSTEM", description: "Disable failing LP", requires_human: true },
      { action: "suggest_abook_increase", bu: "RISK_CONTROL", description: "Protect coverage" },
    ],
    linked_skills: ["SKILL-BRIDGE-LATENCY", "SKILL-SLIPPAGE-SPIKE", "SKILL-LP-REJECT-STORM", "SKILL-HEDGE-COVERAGE"],
    past_cases: [
      { case_id: "CASE-CHAIN-BRIDGE-0915", date: "2026-09-15", outcome: "PREVENTED", summary: "Failover before hedge BREACH." },
    ],
  },
  {
    code: "CHAIN-GAP-NBP",
    name: "Gap exposure → NBP accounts → equity hit",
    description: "Weekend/holiday gap materialises into negative balances and firm loss.",
    product: "CFD",
    domain: "PRODUCT_CONFIG",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-GAP-012", severity: "WARN", signal: "Gap exposure ≥$1m pre-close" },
      { t_minutes: 60, monitor_id: "M2-XAU-247", severity: "WARN", signal: "Metals net still elevated" },
      { t_minutes: 1200, monitor_id: "M2-NBP-016", severity: "BREACH", signal: "≥5 negative balance accounts at open" },
      { t_minutes: 1215, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Equity DD from write-offs / gaps" },
    ],
    causes: ["No close-only", "Promo into weekend", "Thin LP", "NBP policy delay"],
    escalation_plan: [
      { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Gap pack (pre-weekend)" },
      { after_minutes: 1200, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "NBP application at open" },
    ],
    corrections: [
      { action: "suggest_close_only_prepare", bu: "RISK_CONTROL", description: "Pre-weekend close-only" },
      { action: "apply_nbp_policy", bu: "OPERATIONS", description: "Apply NBP", requires_human: true },
      { action: "pause_weekend_promo", bu: "OPERATIONS", description: "Stop promos", requires_human: true },
    ],
    linked_skills: ["SKILL-GAP-RISK", "SKILL-XAU247-EXPOSURE", "SKILL-NEGATIVE-BALANCE", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-GAP-0526", date: "2026-05-26", outcome: "LOSS ~$90k", summary: "Gap pack incomplete; NBP write-offs logged." },
    ],
  },
  {
    code: "CHAIN-PROMO-TOXICITY",
    name: "Leverage onboard surge → bonus burn → fraud WARN",
    description: "Aggressive acquisition creates toxic cohort that burns promo and trips fraud models.",
    product: "CFD",
    domain: "FRAUD_CONDUCT",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-LEV-019", severity: "WARN", signal: "≥100 max-leverage new accounts/day" },
      { t_minutes: 360, monitor_id: "M2-BONUS-013", severity: "WARN", signal: "Bonus conversion ≥$75k/day" },
      { t_minutes: 720, monitor_id: "M2-FRAUD-011", severity: "BREACH", signal: "Cluster score ≥0.85" },
      { t_minutes: 800, monitor_id: "M2-MRG-014", severity: "WARN", signal: "Margin heat in promo cohort" },
    ],
    causes: ["Affiliate abuse", "Weak turnover rules", "Default leverage too high", "Slow KYC"],
    escalation_plan: [
      { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Promo / KYC review" },
      { after_minutes: 120, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Default leverage cut" },
      { after_minutes: 360, team: "Risk Control", channel: "oc_risk_control_desk", action: "Bonus freeze + restrictions" },
    ],
    corrections: [
      { action: "cut_default_leverage", bu: "RISK_CONTROL", description: "Cut new-account leverage", requires_human: true },
      { action: "suggest_bonus_freeze", bu: "OPERATIONS", description: "Freeze conversions", requires_human: true },
      { action: "slow_onboarding", bu: "OPERATIONS", description: "KYC velocity tighten" },
    ],
    linked_skills: ["SKILL-LEVERAGE-ONBOARD", "SKILL-BONUS-BURN", "SKILL-FRAUD-CLUSTER", "SKILL-MARGIN-SPIKE"],
    past_cases: [
      { case_id: "CASE-CHAIN-PROMO-0722", date: "2026-07-22", outcome: "PREVENTED", summary: "Leverage cut + freeze before margin BREACH." },
    ],
  },
  {
    code: "CHAIN-WITHDRAWAL-RUN",
    name: "Withdrawal surge + funding exceptions + fraud score",
    description: "Liquidity stress with possible abuse — Ops and Risk must act in parallel.",
    product: "CFD+Crypto",
    domain: "OPS_PROCESS",
    severity: "CRITICAL",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-WD-015", severity: "WARN", signal: "Withdrawals ≥$2m/h" },
      { t_minutes: 20, monitor_id: "M2-FUND-010", severity: "WARN", signal: "Exceptions ≥30/h" },
      { t_minutes: 35, monitor_id: "M2-PAY-017", severity: "BREACH", signal: "Payment fraud score ≥0.8 on subset" },
      { t_minutes: 50, monitor_id: "M2-WD-015", severity: "BREACH", signal: "Withdrawals ≥$5m/h" },
      { t_minutes: 70, monitor_id: "M2-CRYPTO-WALLET", severity: "WARN", signal: "Hot float pressure if crypto outflows" },
    ],
    causes: ["Rumour / market shock", "Fraud exit", "PSP issues", "Insufficient treasury buffer"],
    escalation_plan: [
      { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Triage + holds" },
      { after_minutes: 20, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Throttle authority" },
      { after_minutes: 45, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If BREACH persists" },
    ],
    corrections: [
      { action: "pause_large_withdrawals", bu: "OPERATIONS", description: "Throttle large WDs", requires_human: true },
      { action: "hold_deposits", bu: "OPERATIONS", description: "Hold risky payment cohort", requires_human: true },
      { action: "enhanced_kyc_queue", bu: "OPERATIONS", description: "Enhanced KYC on top outflows" },
    ],
    linked_skills: ["SKILL-WITHDRAWAL-VELOCITY", "SKILL-FUNDING-EXCEPTION", "SKILL-PAYMENT-FRAUD", "SKILL-CRYPTO-HOT-WALLET"],
    past_cases: [
      { case_id: "CASE-CHAIN-WD-0901", date: "2026-09-01", outcome: "PREVENTED", summary: "Throttle stopped $3.2m suspicious cluster." },
    ],
  },
  {
    code: "CHAIN-CRYPTO-ORACLE-LIQ",
    name: "Oracle lag → liq backlog → insurance fund DD",
    description: "Pricing integrity failure cascades into exchange solvency buffer.",
    product: "Crypto",
    domain: "CRYPTO_EXCHANGE",
    severity: "CRITICAL",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-CRYPTO-ORACLE", severity: "WARN", signal: "Oracle lag ≥1s" },
      { t_minutes: 3, monitor_id: "M2-CRYPTO-ORACLE", severity: "BREACH", signal: "Oracle lag ≥2s" },
      { t_minutes: 8, monitor_id: "M2-CRYPTO-LIQ", severity: "WARN", signal: "Liq backlog ≥50" },
      { t_minutes: 20, monitor_id: "M2-CRYPTO-LIQ", severity: "BREACH", signal: "Liq backlog ≥200" },
      { t_minutes: 35, monitor_id: "M2-CRYPTO-INS", severity: "WARN", signal: "IF DD ≥4%" },
    ],
    causes: ["Oracle outage", "Vol spike", "Worker under-provision", "Concentrated OI"],
    escalation_plan: [
      { after_minutes: 0, team: "Trading Infra", channel: "oc_trading_infra", action: "Oracle failover" },
      { after_minutes: 5, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Pause auto-liq / scale workers" },
      { after_minutes: 20, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Leverage cut / ADL prep" },
    ],
    corrections: [
      { action: "failover_oracle", bu: "SYSTEM", description: "Secondary oracle" },
      { action: "suppress_auto_liq", bu: "RISK_CONTROL", description: "Pause wrong-mark liqs", requires_human: true },
      { action: "cut_perp_leverage", bu: "RISK_CONTROL", description: "Cut leverage", requires_human: true },
      { action: "scale_liq_workers", bu: "SYSTEM", description: "Clear backlog" },
    ],
    linked_skills: ["SKILL-CRYPTO-ORACLE", "SKILL-CRYPTO-LIQ-BACKLOG", "SKILL-CRYPTO-INSURANCE"],
    past_cases: [
      { case_id: "CASE-CHAIN-ORACLE-0611", date: "2026-06-11", outcome: "PREVENTED", summary: "Failover + pause avoided IF BREACH." },
    ],
  },
  {
    code: "CHAIN-WHALE-OI-INS",
    name: "OI concentration → liq cliff → insurance stress",
    description: "Whale position becomes the market on a thin perp.",
    product: "Crypto",
    domain: "CRYPTO_EXCHANGE",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-CRYPTO-OI", severity: "WARN", signal: "Top account OI ≥20%" },
      { t_minutes: 90, monitor_id: "M2-CRYPTO-OI", severity: "BREACH", signal: "Top account OI ≥35%" },
      { t_minutes: 120, monitor_id: "M2-CRYPTO-LIQ", severity: "WARN", signal: "Backlog rises as whale approaches liq" },
      { t_minutes: 150, monitor_id: "M2-CRYPTO-INS", severity: "WARN", signal: "IF DD ≥4% if cliff hits" },
    ],
    causes: ["Missing OI caps", "Sybil aggregation", "Incentive campaign", "Thin order book"],
    escalation_plan: [
      { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "OI cap review" },
      { after_minutes: 60, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Force reduce-only" },
    ],
    corrections: [
      { action: "enforce_oi_cap", bu: "RISK_CONTROL", description: "Per-account OI cap", requires_human: true },
      { action: "force_reduce_only", bu: "RISK_CONTROL", description: "Whale reduce-only", requires_human: true },
      { action: "kyc_cluster_review", bu: "OPERATIONS", description: "Sybil check" },
    ],
    linked_skills: ["SKILL-CRYPTO-OI-CONC", "SKILL-CRYPTO-LIQ-BACKLOG", "SKILL-CRYPTO-INSURANCE"],
    past_cases: [
      { case_id: "CASE-CHAIN-OI-0719", date: "2026-07-19", outcome: "PREVENTED", summary: "Reduce-only at 36% OI before dump." },
    ],
  },
  {
    code: "CHAIN-VAR-CORR-EQ",
    name: "Correlation break → VaR utilisation → equity DD",
    description: "Model assumptions break; VaR rises; firm equity follows if inventory not cut.",
    product: "CFD",
    domain: "MARKET_PRICING",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-CORR-004", severity: "WARN", signal: "Δρ ≥0.20" },
      { t_minutes: 30, monitor_id: "M2-CORR-004", severity: "BREACH", signal: "Δρ ≥0.35" },
      { t_minutes: 45, monitor_id: "M2-VAR-002", severity: "WARN", signal: "VaR util ≥85%" },
      { t_minutes: 75, monitor_id: "M2-VAR-002", severity: "BREACH", signal: "VaR util ≥95%" },
      { t_minutes: 100, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Equity DD ≥3%" },
    ],
    causes: ["Risk-off shock", "Stale corr matrix", "Concentrated inventory", "Hedge ratio wrong"],
    escalation_plan: [
      { after_minutes: 0, team: "AI + Risk", channel: "oc_ai_detection_lab", action: "Refresh corr" },
      { after_minutes: 30, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "VaR buffer + flatten" },
      { after_minutes: 75, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If VaR BREACH" },
    ],
    corrections: [
      { action: "refresh_corr_matrix", bu: "AI", description: "Recompute correlations" },
      { action: "widen_var_buffer", bu: "RISK_CONTROL", description: "Temporary buffer", requires_human: true },
      { action: "inventory_flatten_plan", bu: "RISK_CONTROL", description: "Flatten contributors", requires_human: true },
    ],
    linked_skills: ["SKILL-CORRELATION-BREAK", "SKILL-VAR-BREACH", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-VAR-0418", date: "2026-04-18", outcome: "PREVENTED", summary: "Flatten + matrix refresh cut VaR util to 78%." },
    ],
  },
  {
    code: "CHAIN-ABOOK-HEDGE-EQ",
    name: "A-book ratio collapse → hedge gap → equity",
    description: "Silent B-book override leaves inventory unhedged into volatility.",
    product: "CFD",
    domain: "LP_HEDGE",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-ABOOK-008", severity: "WARN", signal: "A-book ratio ≤40%" },
      { t_minutes: 40, monitor_id: "M2-ABOOK-008", severity: "BREACH", signal: "A-book ratio ≤30%" },
      { t_minutes: 55, monitor_id: "M2-HEDGE-007", severity: "WARN", signal: "Coverage <85%" },
      { t_minutes: 80, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Equity DD ≥3%" },
    ],
    causes: ["Manual B-book override", "LP credit full", "Toxic mis-class", "Holiday capacity"],
    escalation_plan: [
      { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Override audit" },
      { after_minutes: 20, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Force A-book" },
    ],
    corrections: [
      { action: "review_bbook_overrides", bu: "RISK_CONTROL", description: "Clear stale overrides" },
      { action: "suggest_abook_increase", bu: "RISK_CONTROL", description: "Force A-book toxic", requires_human: true },
      { action: "inventory_flatten_plan", bu: "RISK_CONTROL", description: "Flatten residual", requires_human: true },
    ],
    linked_skills: ["SKILL-ABOOK-RATIO", "SKILL-HEDGE-COVERAGE", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-ABOOK-0612", date: "2026-06-12", outcome: "PREVENTED ~$150k", summary: "Override cleared; ratio restored." },
    ],
  },
  {
    code: "CHAIN-SPREAD-MARKUP-BUG",
    name: "Spread anomaly → slippage noise → client ops surge",
    description: "Bad markup deploy looks like market stress but is product config.",
    product: "CFD",
    domain: "PRODUCT_CONFIG",
    severity: "WARN",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-SPREAD-005", severity: "BREACH", signal: "Spread ≥3× median on majors" },
      { t_minutes: 10, monitor_id: "M2-SLIP-021", severity: "WARN", signal: "Apparent slippage spike" },
      { t_minutes: 25, monitor_id: "M2-FUND-010", severity: "WARN", signal: "Complaint / adjustment exceptions rise" },
    ],
    causes: ["Markup deploy error", "Crisis widen left on", "Session mismatch"],
    escalation_plan: [
      { after_minutes: 0, team: "Trading Infra", channel: "oc_trading_infra", action: "Diff markup" },
      { after_minutes: 15, team: "Risk Control", channel: "oc_risk_control_desk", action: "Approve rollback" },
      { after_minutes: 30, team: "Ops", channel: "oc_ops_funding_recon", action: "Client adjustments if needed" },
    ],
    corrections: [
      { action: "rollback_markup", bu: "SYSTEM", description: "Rollback markup table", requires_human: true },
      { action: "restore_session_spreads", bu: "RISK_CONTROL", description: "Restore standards" },
      { action: "client_adjustment_pack", bu: "OPERATIONS", description: "Goodwill if required", requires_human: true },
    ],
    linked_skills: ["SKILL-SPREAD-ANOMALY", "SKILL-SLIPPAGE-SPIKE", "SKILL-FUNDING-EXCEPTION"],
    past_cases: [
      { case_id: "CASE-CHAIN-SPREAD-0819", date: "2026-08-19", outcome: "PREVENTED", summary: "Rollback in 11m." },
    ],
  },
  {
    code: "CHAIN-TOXIC-ARB",
    name: "Stale feed → latency arb → equity drip",
    description: "Feed freshness gap enables arb accounts to pick off the book.",
    product: "CFD",
    domain: "CREDIT_CLIENT",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-FEED-003", severity: "WARN", signal: "≥3 stale symbols" },
      { t_minutes: 8, monitor_id: "M2-ARB-026", severity: "WARN", signal: "Arb score ≥0.5" },
      { t_minutes: 20, monitor_id: "M2-ARB-026", severity: "BREACH", signal: "Arb score ≥0.7" },
      { t_minutes: 40, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Slow equity drip from toxic fills" },
    ],
    causes: ["Stale aggregator", "Slow last-look", "No toxic list force A-book"],
    escalation_plan: [
      { after_minutes: 0, team: "Trading Infra", channel: "oc_trading_infra", action: "Feed failover" },
      { after_minutes: 10, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Toxic list" },
      { after_minutes: 25, team: "Risk Control", channel: "oc_risk_control_desk", action: "Force A-book / widen" },
    ],
    corrections: [
      { action: "failover_feed", bu: "SYSTEM", description: "Secondary feed" },
      { action: "force_abook_toxic", bu: "RISK_CONTROL", description: "A-book toxic accounts", requires_human: true },
      { action: "widen_toxic_spreads", bu: "RISK_CONTROL", description: "Account-level widen" },
    ],
    linked_skills: ["SKILL-STALE-FEED", "SKILL-LATENCY-ARB", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-ARB-0505", date: "2026-05-05", outcome: "PREVENTED ~$175k", summary: "Toxic list A-booked." },
    ],
  },
  {
    code: "CHAIN-REG-CAPITAL",
    name: "Equity DD → capital buffer thin → segregation WARN",
    description: "P&L stress threatens regulatory capital and client-money headroom.",
    product: "CFD+Crypto",
    domain: "REG_CAPITAL",
    severity: "CRITICAL",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-EQ-001", severity: "BREACH", signal: "Equity DD ≥5%" },
      { t_minutes: 60, monitor_id: "M2-CAP-024", severity: "WARN", signal: "Capital buffer ≤20%" },
      { t_minutes: 120, monitor_id: "M2-CAP-024", severity: "BREACH", signal: "Capital buffer ≤15%" },
      { t_minutes: 180, monitor_id: "M2-SEG-025", severity: "WARN", signal: "CM gap rising with funding stress" },
    ],
    causes: ["Market loss", "Intercompany transfer timing", "Funding recon lag", "Dual-product capital use"],
    escalation_plan: [
      { after_minutes: 0, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Limit cut + capital pack" },
      { after_minutes: 60, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "Capital / communications" },
      { after_minutes: 120, team: "Ops", channel: "oc_ops_funding_recon", action: "CM recon priority" },
    ],
    corrections: [
      { action: "reduce_gross_limits", bu: "RISK_CONTROL", description: "Cut entity limits", requires_human: true },
      { action: "capital_injection_request", bu: "EXEC", description: "Top-up request", requires_human: true },
      { action: "full_cm_recon", bu: "OPERATIONS", description: "Priority CM recon" },
    ],
    linked_skills: ["SKILL-EQUITY-DRAWDOWN", "SKILL-ENTITY-CAPITAL", "SKILL-SEGREGATION-GAP"],
    past_cases: [
      { case_id: "CASE-CHAIN-CAP-0510", date: "2026-05-10", outcome: "PREVENTED", summary: "Limit cut bought time for top-up." },
    ],
  },
  {
    code: "CHAIN-API-OUTAGE-RISK",
    name: "API errors → clients cannot close → margin / equity drift",
    description: "Platform outage becomes credit risk when clients cannot manage positions.",
    product: "CFD+Crypto",
    domain: "TECH_INFRA",
    severity: "CRITICAL",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-API-023", severity: "WARN", signal: "API errors ≥2%" },
      { t_minutes: 5, monitor_id: "M2-API-023", severity: "BREACH", signal: "API errors ≥5%" },
      { t_minutes: 15, monitor_id: "M2-MRG-014", severity: "WARN", signal: "Margin utilisation climbs (cannot close)" },
      { t_minutes: 30, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Inventory drifts against firm" },
    ],
    causes: ["Bad deploy", "DB pool exhaustion", "Upstream timeout", "Rate limiter bug"],
    escalation_plan: [
      { after_minutes: 0, team: "Trading Infra P1", channel: "oc_trading_infra", action: "Rollback / scale" },
      { after_minutes: 10, team: "Ops", channel: "oc_ops_funding_recon", action: "Status page" },
      { after_minutes: 20, team: "Risk Control", channel: "oc_risk_control_desk", action: "Inventory review" },
    ],
    corrections: [
      { action: "rollback_api_deploy", bu: "SYSTEM", description: "Rollback API", requires_human: true },
      { action: "scale_api_pods", bu: "SYSTEM", description: "Scale pods" },
      { action: "status_page_notice", bu: "OPERATIONS", description: "Client comms" },
    ],
    linked_skills: ["SKILL-API-ERROR-RATE", "SKILL-MARGIN-SPIKE", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-API-0827", date: "2026-08-27", outcome: "PREVENTED", summary: "Rollback in 6m before EQ BREACH." },
    ],
  },
  {
    code: "CHAIN-WASH-COPY",
    name: "Wash score + copy concentration (mirrored collusion)",
    description: "Collusive accounts inflate copy provider share while matching each other.",
    product: "CFD",
    domain: "FRAUD_CONDUCT",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-WASH-020", severity: "WARN", signal: "Wash score ≥0.55" },
      { t_minutes: 45, monitor_id: "M2-COPY-009", severity: "WARN", signal: "Provider share ≥15%" },
      { t_minutes: 90, monitor_id: "M2-WASH-020", severity: "BREACH", signal: "Wash score ≥0.75" },
      { t_minutes: 110, monitor_id: "M2-FRAUD-011", severity: "BREACH", signal: "Cluster score ≥0.85" },
    ],
    causes: ["Mirrored bots", "Provider collusion", "Sybil copiers", "Thin symbol abuse"],
    escalation_plan: [
      { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Conduct case + evidence" },
      { after_minutes: 30, team: "Ops", channel: "oc_ops_funding_recon", action: "Freeze pack" },
      { after_minutes: 60, team: "Credit Desk", channel: "oc_credit_client_risk", action: "Pause copies" },
    ],
    corrections: [
      { action: "evidence_pack", bu: "AI", description: "Trade-match pack" },
      { action: "restrict_trading", bu: "RISK_CONTROL", description: "Suspend suspects", requires_human: true },
      { action: "pause_new_copies", bu: "RISK_CONTROL", description: "Pause provider", requires_human: true },
    ],
    linked_skills: ["SKILL-WASH-TRADE", "SKILL-COPY-CONCENTRATION", "SKILL-FRAUD-CLUSTER"],
    past_cases: [
      { case_id: "CASE-CHAIN-WASH-0112", date: "2026-01-12", outcome: "PREVENTED", summary: "6 accounts suspended; provider paused." },
    ],
  },
  {
    code: "CHAIN-SWAP-OVERNIGHT",
    name: "Swap misconfig → overnight equity drip → ops adjustments",
    description: "Bad swap table silently moves P&L overnight then floods Ops with disputes.",
    product: "CFD",
    domain: "PRODUCT_CONFIG",
    severity: "WARN",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-SWAP-027", severity: "BREACH", signal: "≥10 symbols off benchmark at rollover" },
      { t_minutes: 480, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Overnight equity drip unexplained" },
      { t_minutes: 600, monitor_id: "M2-FUND-010", severity: "WARN", signal: "Client adjustment exceptions surge" },
    ],
    causes: ["Holiday table miss", "Rates file deploy", "Triple-swap day", "Symbol rename"],
    escalation_plan: [
      { after_minutes: 0, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Diff swap table" },
      { after_minutes: 30, team: "Trading Infra", channel: "oc_trading_infra", action: "Rollback rates" },
      { after_minutes: 120, team: "Ops", channel: "oc_ops_funding_recon", action: "Adjustment pack" },
    ],
    corrections: [
      { action: "rollback_swap_table", bu: "SYSTEM", description: "Rollback rates", requires_human: true },
      { action: "client_adjustment_pack", bu: "OPERATIONS", description: "Corrections", requires_human: true },
    ],
    linked_skills: ["SKILL-SWAP-MISCONFIG", "SKILL-EQUITY-DRAWDOWN", "SKILL-FUNDING-EXCEPTION"],
    past_cases: [
      { case_id: "CASE-CHAIN-SWAP-1201", date: "2025-12-01", outcome: "LOSS ~$40k adjusted", summary: "Triple-swap miss corrected next day." },
    ],
  },
  {
    code: "CHAIN-DEPOSIT-FLOAT",
    name: "Crypto deposit spike → hot float WARN → withdrawal pressure",
    description: "Inflows without sweep create custody risk just as outflows may also rise.",
    product: "Crypto",
    domain: "CRYPTO_EXCHANGE",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-CRYPTO-DEP", severity: "WARN", signal: "Deposits ≥$3m/h" },
      { t_minutes: 30, monitor_id: "M2-CRYPTO-DEP", severity: "BREACH", signal: "Deposits ≥$8m/h" },
      { t_minutes: 45, monitor_id: "M2-CRYPTO-WALLET", severity: "WARN", signal: "Hot float ≥15%" },
      { t_minutes: 90, monitor_id: "M2-CRYPTO-WALLET", severity: "BREACH", signal: "Hot float ≥25% if sweep delayed" },
      { t_minutes: 120, monitor_id: "M2-WD-015", severity: "WARN", signal: "Parallel withdrawal interest" },
    ],
    causes: ["Listing hype", "Sweep job delay", "Bridge congestion", "MM deposit"],
    escalation_plan: [
      { after_minutes: 0, team: "Crypto Exchange Risk", channel: "oc_crypto_exchange_risk", action: "Sweep now" },
      { after_minutes: 30, team: "Trading Infra", channel: "oc_trading_infra", action: "Raise sweep cadence" },
      { after_minutes: 60, team: "Ops", channel: "oc_ops_funding_recon", action: "WD throttle if needed" },
    ],
    corrections: [
      { action: "suggest_cold_wallet_sweep", bu: "SYSTEM", description: "Immediate sweep" },
      { action: "raise_sweep_frequency", bu: "SYSTEM", description: "Higher cadence" },
      { action: "pause_large_withdrawals", bu: "OPERATIONS", description: "Throttle if float BREACH", requires_human: true },
    ],
    linked_skills: ["SKILL-CRYPTO-DEPOSIT-SPIKE", "SKILL-CRYPTO-HOT-WALLET", "SKILL-WITHDRAWAL-VELOCITY"],
    past_cases: [
      { case_id: "CASE-CHAIN-DEP-1003", date: "2026-10-01", outcome: "PREVENTED", summary: "Sweep kept float under 25%." },
    ],
  },
  {
    code: "CHAIN-MODEL-FALSE-CALM",
    name: "Detector drift + missed margin → late human scramble",
    description: "Noisy/low-precision detectors hide real credit stress until BREACH is obvious.",
    product: "CFD+Crypto",
    domain: "MODEL_AI",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-MODEL-006", severity: "WARN", signal: "Precision ≤80%" },
      { t_minutes: 120, monitor_id: "M2-MODEL-006", severity: "BREACH", signal: "Precision ≤70% — alert fatigue" },
      { t_minutes: 180, monitor_id: "M2-MRG-014", severity: "BREACH", signal: "True margin BREACH finally noticed" },
      { t_minutes: 200, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Equity already slipping" },
    ],
    causes: ["Feature drift", "Threshold too tight", "Checker backlog", "Missing skill"],
    escalation_plan: [
      { after_minutes: 0, team: "AI Engineering", channel: "oc_ai_detection_lab", action: "Shadow noisy detectors" },
      { after_minutes: 60, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Approve CR + clear queue" },
      { after_minutes: 180, team: "Credit Desk", channel: "oc_credit_client_risk", action: "True credit actions" },
    ],
    corrections: [
      { action: "disable_detector_shadow", bu: "AI", description: "Shadow noisy detectors", requires_human: true },
      { action: "propose_threshold_cr", bu: "AI", description: "AI Admin CR" },
      { action: "boost_oncall_risk", bu: "RISK_CONTROL", description: "Add checker capacity", requires_human: true },
      { action: "group_leverage_tighten", bu: "RISK_CONTROL", description: "Credit response", requires_human: true },
    ],
    linked_skills: ["SKILL-DETECTOR-DRIFT", "SKILL-MARGIN-SPIKE", "SKILL-GENERIC-HUMAN-REVIEW", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-MODEL-1001", date: "2026-10-01", outcome: "GOVERNANCE", summary: "Maker/checker CR improved skill coverage." },
    ],
  },
  {
    code: "CHAIN-SEGREGATION-FUNDING",
    name: "Funding exceptions → segregation gap → capital WARN",
    description: "Ops recon failure becomes regulatory client-money event.",
    product: "CFD",
    domain: "REG_CAPITAL",
    severity: "CRITICAL",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-FUND-010", severity: "BREACH", signal: "Exceptions ≥80/h" },
      { t_minutes: 90, monitor_id: "M2-SEG-025", severity: "WARN", signal: "CM gap ≥$50k" },
      { t_minutes: 180, monitor_id: "M2-SEG-025", severity: "BREACH", signal: "CM gap ≥$250k" },
      { t_minutes: 240, monitor_id: "M2-CAP-024", severity: "WARN", signal: "Capital buffer pressure" },
    ],
    causes: ["Bank file delay", "PSP outage", "Wrong entity booking", "Manual journal error"],
    escalation_plan: [
      { after_minutes: 0, team: "Ops War Room", channel: "oc_ops_funding_recon", action: "Priority recon" },
      { after_minutes: 30, team: "Risk Owner", channel: "oc_risk_control_desk", action: "Segregation war-room" },
      { after_minutes: 90, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "Top-up / freeze flows" },
    ],
    corrections: [
      { action: "full_cm_recon", bu: "OPERATIONS", description: "Full CM recon" },
      { action: "freeze_nonessential_flows", bu: "OPERATIONS", description: "Freeze transfers", requires_human: true },
      { action: "topup_seg_account", bu: "EXEC", description: "Top-up segregation", requires_human: true },
    ],
    linked_skills: ["SKILL-FUNDING-EXCEPTION", "SKILL-SEGREGATION-GAP", "SKILL-ENTITY-CAPITAL"],
    past_cases: [
      { case_id: "CASE-CHAIN-SEG-0220", date: "2026-02-20", outcome: "PREVENTED", summary: "Top-up within 40m closed gap." },
    ],
  },
  {
    code: "CHAIN-MKT-INTEL-VOL",
    name: "Market intel hits → equity / margin heat",
    description: "High-impact external intel precedes book stress when desks do not pre-widen or cut leverage.",
    product: "CFD+Crypto",
    domain: "MARKET_PRICING",
    severity: "BREACH",
    sequence: [
      { t_minutes: 0, monitor_id: "M2-MKT-INTEL", severity: "WARN", signal: "≥1 high-impact intel hit in 5m scan" },
      { t_minutes: 5, monitor_id: "M2-MKT-INTEL", severity: "BREACH", signal: "≥3 high-impact intel hits" },
      { t_minutes: 15, monitor_id: "M2-MRG-014", severity: "WARN", signal: "Margin utilisation rising into event" },
      { t_minutes: 25, monitor_id: "M2-EQ-001", severity: "WARN", signal: "Equity DD if unhedged into move" },
    ],
    causes: ["Macro / geo surprise", "No pre-widen", "LP rejects under news", "Copy pile-in"],
    escalation_plan: [
      { after_minutes: 0, team: "Market Intelligence", channel: "oc_market_intelligence", action: "Publish card" },
      { after_minutes: 5, team: "Risk Control Desk", channel: "oc_risk_control_desk", action: "Pre-widen / leverage review" },
      { after_minutes: 20, team: "Exec Risk Bridge", channel: "oc_exec_risk_bridge", action: "If CRITICAL geo + EQ WARN" },
    ],
    corrections: [
      { action: "pre_widen_spreads", bu: "RISK_CONTROL", description: "Pre-widen affected products" },
      { action: "temp_leverage_cut", bu: "RISK_CONTROL", description: "Session leverage cut", requires_human: true },
      { action: "lark_notify", bu: "AI", description: "Keep Market Intelligence group updated" },
    ],
    linked_skills: ["SKILL-MARKET-INTEL", "SKILL-MARGIN-SPIKE", "SKILL-EQUITY-DRAWDOWN"],
    past_cases: [
      { case_id: "CASE-CHAIN-MI-1001", date: "2026-10-01", outcome: "PREVENTED", summary: "Intel → pre-widen before US open cascade." },
    ],
  },
];
