/**
 * Explicit skill → escalation route_code binding.
 * Every skill binds exactly one path; unbound skills fall back to ESC-DEFAULT
 * so no event lacks an escalation path.
 */
export const SKILL_ESCALATION_ROUTE: Record<string, string> = {
  "SKILL-MARGIN-SPIKE": "ESC-MARGIN-BREACH",
  "SKILL-COPY-CONCENTRATION": "ESC-COPY-CONC",
  "SKILL-CRYPTO-HOT-WALLET": "ESC-WALLET-FLOAT",
  "SKILL-LP-REJECT-STORM": "ESC-LP-REJECT",
  "SKILL-HEDGE-COVERAGE": "ESC-LP-REJECT",
  "SKILL-FRAUD-CLUSTER": "ESC-MARGIN-BREACH",
  "SKILL-XAU247-EXPOSURE": "ESC-MARGIN-BREACH",
  "SKILL-EQUITY-DRAWDOWN": "ESC-MARGIN-BREACH",
  "SKILL-STALE-FEED": "ESC-FEED-STALE",
  "SKILL-STALE-FEED-HALT": "ESC-FEED-STALE",
  "SKILL-CRYPTO-LIQ-BACKLOG": "ESC-WALLET-FLOAT",
  "SKILL-GENERIC-HUMAN-REVIEW": "ESC-DEFAULT",
  "SKILL-FUNDING-EXCEPTION": "ESC-FUNDING",
  "SKILL-FUNDING-EXTREME": "ESC-FUNDING",
  "SKILL-DETECTOR-DRIFT": "ESC-MODEL-DRIFT",
  "SKILL-BRIDGE-LATENCY": "ESC-FEED-STALE",
  "SKILL-NEGATIVE-BALANCE": "ESC-MARGIN-BREACH",
  "SKILL-STOPOUT-VELOCITY": "ESC-MARGIN-BREACH",
  "SKILL-WITHDRAWAL-VELOCITY": "ESC-WALLET-FLOAT",
  "SKILL-CRYPTO-DEPOSIT-SPIKE": "ESC-WALLET-FLOAT",
  "SKILL-CRYPTO-ORACLE": "ESC-WALLET-FLOAT",
  "SKILL-CRYPTO-INSURANCE": "ESC-WALLET-FLOAT",
  "SKILL-CRYPTO-OI-CONC": "ESC-WALLET-FLOAT",
  "SKILL-RECON-BREAKS": "ESC-FUNDING",
  "SKILL-API-ERROR-RATE": "ESC-FEED-STALE",
  "SKILL-PLATFORM-DISCONNECT": "ESC-FEED-STALE",
  "SKILL-SYMBOL-HALTS": "ESC-FEED-STALE",
  "SKILL-MARKET-INTEL": "ESC-DEFAULT",
};

/** Domain → route when a skill has no explicit bind. */
const DOMAIN_ROUTE_FALLBACK: Record<string, string> = {
  CREDIT_CLIENT: "ESC-MARGIN-BREACH",
  LP_HEDGE: "ESC-LP-REJECT",
  CRYPTO_EXCHANGE: "ESC-WALLET-FLOAT",
  MARKET_PRICING: "ESC-FEED-STALE",
  OPS_PROCESS: "ESC-FUNDING",
  MODEL_AI: "ESC-MODEL-DRIFT",
  TECH_INFRA: "ESC-FEED-STALE",
};

export function escalationRouteForSkill(
  skillCode: string,
  opts?: { domain?: string; defaultCode?: string }
): string {
  if (SKILL_ESCALATION_ROUTE[skillCode]) return SKILL_ESCALATION_ROUTE[skillCode];
  if (opts?.domain && DOMAIN_ROUTE_FALLBACK[opts.domain]) return DOMAIN_ROUTE_FALLBACK[opts.domain];
  return opts?.defaultCode || "ESC-DEFAULT";
}
