/**
 * Builds src/i18n/messages/dictionaries.ts from locale packs in scripts/i18n-packs/.
 * English is the source of truth (imported at runtime); other locales must cover every MessageKey.
 *
 * Packs are complete JSON dictionaries (156 keys each). Helpers used when authoring:
 *   - zh-Hant derived from zh-Hans (OpenCC s2t + Taiwan wording overrides)
 *   - romance languages authored fully (not Spanish clones)
 *   - egy/akk use scholarly transliteration + English glosses where unavoidable
 *
 * Run: node atlas/scripts/generate-i18n.mjs
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const packsDir = join(__dirname, "i18n-packs");
const enPath = join(__dirname, "../src/i18n/messages/en.ts");
const out = join(__dirname, "../src/i18n/messages/dictionaries.ts");

/** Extract MessageKey list from en.ts without a TS loader. */
function loadEnKeys() {
  const src = readFileSync(enPath, "utf8");
  const keys = [...src.matchAll(/^\s*"([^"]+)":/gm)].map((m) => m[1]);
  if (keys.length < 100) {
    throw new Error(`Failed to parse en.ts keys (got ${keys.length})`);
  }
  return keys;
}

const enKeys = loadEnKeys();
/** @type {Record<string, Record<string, string>>} */
const packs = {};

for (const file of readdirSync(packsDir).filter((f) => f.endsWith(".json"))) {
  const code = file.replace(/\.json$/, "");
  /** @type {Record<string, string>} */
  const map = JSON.parse(readFileSync(join(packsDir, file), "utf8"));
  const missing = enKeys.filter((k) => !(k in map));
  const extra = Object.keys(map).filter((k) => !enKeys.includes(k));
  if (missing.length || extra.length) {
    throw new Error(
      `${code}: missing=${missing.length} extra=${extra.length}` +
        (missing.length ? ` firstMissing=${missing[0]}` : "") +
        (extra.length ? ` firstExtra=${extra[0]}` : ""),
    );
  }
  packs[code] = map;
}

const expected = [
  "zh-Hans",
  "zh-Hant",
  "es",
  "fr",
  "pt",
  "it",
  "de",
  "ja",
  "ko",
  "ar",
  "hi",
  "ru",
  "tr",
  "vi",
  "th",
  "id",
  "nl",
  "pl",
  "sv",
  "el",
  "he",
  "uk",
  "fa",
  "bn",
  "sw",
  "la",
  "grc",
  "sa",
  "egy",
  "akk",
  "non",
];
for (const code of expected) {
  if (!packs[code]) throw new Error(`Missing locale pack: ${code}`);
}

const body = `/* Auto-generated by scripts/generate-i18n.mjs — do not edit by hand */
import type { LocaleCode } from "../languages";
import type { MessageDict, MessageKey } from "./en";

export const dictionaries: Partial<Record<LocaleCode, Partial<MessageDict>>> = ${JSON.stringify(packs, null, 2)};

export function resolveMessage(
  locale: LocaleCode,
  key: MessageKey,
  enDict: MessageDict,
): string {
  return dictionaries[locale]?.[key] ?? enDict[key] ?? key;
}
`;

writeFileSync(out, body);
console.log(
  "Wrote",
  out,
  "locales:",
  Object.keys(packs).length,
  "keys each:",
  enKeys.length,
);
