import { glossary } from '../data/glossary'
import { getDay } from '../data/curriculum'
import { getProductionExample } from '../data/productionExamples'

const KEY_STORAGE = 'ownlab-openai-key'
const ENDPOINT_STORAGE = 'ownlab-openai-endpoint'
const MODEL_STORAGE = 'ownlab-openai-model'

export type ChatMessage = { role: 'system' | 'user' | 'assistant'; content: string }

export function getApiSettings() {
  return {
    apiKey: localStorage.getItem(KEY_STORAGE)?.trim() ?? '',
    endpoint:
      localStorage.getItem(ENDPOINT_STORAGE)?.trim() ||
      'https://api.openai.com/v1/chat/completions',
    model: localStorage.getItem(MODEL_STORAGE)?.trim() || 'gpt-4o-mini',
  }
}

export function saveApiSettings(input: {
  apiKey: string
  endpoint?: string
  model?: string
}) {
  localStorage.setItem(KEY_STORAGE, input.apiKey.trim())
  if (input.endpoint !== undefined) {
    localStorage.setItem(ENDPOINT_STORAGE, input.endpoint.trim())
  }
  if (input.model !== undefined) {
    localStorage.setItem(MODEL_STORAGE, input.model.trim())
  }
}

function localTutorExplain(selectedText: string, sourcePath?: string): string {
  const text = selectedText.trim()
  const lower = text.toLowerCase()
  const hits = glossary.filter(
    (g) =>
      lower.includes(g.term.toLowerCase()) ||
      g.term.toLowerCase().split(/\s+/).some((w) => w.length > 3 && lower.includes(w)),
  )

  const dayMatch = sourcePath?.match(/\/day\/(\d+)/)
  const dayNum = dayMatch ? Number(dayMatch[1]) : undefined
  const lesson = dayNum ? getDay(dayNum) : undefined
  const production = dayNum ? getProductionExample(dayNum) : undefined

  const parts: string[] = []
  parts.push(`**Plain-language take:** ${summarizeSelection(text)}`)

  if (hits.length) {
    parts.push('**Related OWNLAB terms**')
    for (const hit of hits.slice(0, 4)) {
      parts.push(`- **${hit.term}**: ${hit.short} ${hit.detail}`)
    }
  }

  if (lesson) {
    parts.push(
      `**From Day ${lesson.day} (${lesson.title}):** As a product owner, connect this to: ${lesson.outcomes[0] ?? lesson.subtitle}`,
    )
  }

  if (production) {
    parts.push(
      `**Production lens (${production.source}):** ${production.poLesson} Watch for: ${production.watchFor.slice(0, 2).join('; ')}.`,
    )
  }

  parts.push(
    '**PO move:** Rewrite this idea as a decision, metric, or risk in your PRD — not as an eng task list.',
  )
  parts.push(
    '_Generated by OWNLAB local tutor (no API key). Add an OpenAI-compatible API key in the chat settings for live model explanations._',
  )

  return parts.join('\n\n')
}

function summarizeSelection(text: string): string {
  const clean = text.replace(/\s+/g, ' ').trim()
  if (clean.length <= 180) {
    return `You highlighted: “${clean}”. In AI product work, treat this as a concept to operationalize — definition, owner, metric, and failure mode.`
  }
  return `You highlighted a longer passage starting with “${clean.slice(0, 140)}…”. Break it into: what it means, where it lives in the stack, how you’d measure it, and what breaks in production.`
}

export async function explainSelection(input: {
  selectedText: string
  sourcePath?: string
  sourceLabel?: string
  history?: ChatMessage[]
  userMessage?: string
}): Promise<{ content: string; model: string }> {
  const settings = getApiSettings()
  const system = [
    'You are OWNLAB tutor for AI Product Owners (not engineers).',
    'Explain clearly with production examples, PO decisions, metrics, and risks.',
    'Keep answers concise (120-220 words) unless asked for more.',
    'Use markdown lightly with short paragraphs and bullets.',
    input.sourceLabel ? `Learner is on: ${input.sourceLabel}.` : '',
  ]
    .filter(Boolean)
    .join(' ')

  if (!settings.apiKey) {
    if (input.userMessage && input.history?.length) {
      return {
        model: 'local-tutor',
        content: [
          localTutorExplain(input.selectedText, input.sourcePath),
          '',
          `**Follow-up (“${input.userMessage}”):** Without an API key I can only expand from OWNLAB materials. Rephrase your question around a glossary term, or add an API key for a full conversational tutor.`,
        ].join('\n'),
      }
    }
    return {
      model: 'local-tutor',
      content: localTutorExplain(input.selectedText, input.sourcePath),
    }
  }

  const messages: ChatMessage[] = [
    { role: 'system', content: system },
    {
      role: 'user',
      content: `Explain this selection for an AI Product Owner:\n\n"""${input.selectedText}"""`,
    },
    ...(input.history ?? []),
  ]
  if (input.userMessage) {
    messages.push({ role: 'user', content: input.userMessage })
  }

  const response = await fetch(settings.endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${settings.apiKey}`,
    },
    body: JSON.stringify({
      model: settings.model,
      messages,
      temperature: 0.4,
    }),
  })

  if (!response.ok) {
    const errText = await response.text()
    throw new Error(`API error ${response.status}: ${errText.slice(0, 280)}`)
  }

  const data = (await response.json()) as {
    choices?: { message?: { content?: string } }[]
  }
  const content = data.choices?.[0]?.message?.content?.trim()
  if (!content) throw new Error('Empty model response')
  return { content, model: settings.model }
}
