import { getDayLesson, getGlossary, getProductionLang } from '../data/content'
import type { Lang } from '../i18n/types'

const KEY_STORAGE = 'ownlab-openai-key'
const ENDPOINT_STORAGE = 'ownlab-openai-endpoint'
const MODEL_STORAGE = 'ownlab-openai-model'

export type ChatMessage = { role: 'system' | 'user' | 'assistant'; content: string }

export function getApiSettings() {
  return {
    apiKey: localStorage.getItem(KEY_STORAGE)?.trim() ?? '',
    endpoint:
      localStorage.getItem(ENDPOINT_STORAGE)?.trim() ||
      'https://api.openai.com/v1/chat/completions',
    model: localStorage.getItem(MODEL_STORAGE)?.trim() || 'gpt-4o-mini',
  }
}

export function saveApiSettings(input: {
  apiKey: string
  endpoint?: string
  model?: string
}) {
  localStorage.setItem(KEY_STORAGE, input.apiKey.trim())
  if (input.endpoint !== undefined) {
    localStorage.setItem(ENDPOINT_STORAGE, input.endpoint.trim())
  }
  if (input.model !== undefined) {
    localStorage.setItem(MODEL_STORAGE, input.model.trim())
  }
}

function localTutorExplain(selectedText: string, sourcePath: string | undefined, lang: Lang): string {
  const text = selectedText.trim()
  const lower = text.toLowerCase()
  const glossary = getGlossary(lang)
  const hits = glossary.filter(
    (g) =>
      lower.includes(g.term.toLowerCase()) ||
      g.term.toLowerCase().split(/\s+/).some((w) => w.length > 3 && lower.includes(w)),
  )

  const dayMatch = sourcePath?.match(/\/day\/(\d+)/)
  const dayNum = dayMatch ? Number(dayMatch[1]) : undefined
  const lesson = dayNum ? getDayLesson(lang, dayNum) : undefined
  const production = dayNum ? getProductionLang(lang, dayNum) : undefined

  if (lang === 'zh') {
    const parts: string[] = []
    parts.push(`**白话解释：** ${summarizeSelection(text, lang)}`)
    if (hits.length) {
      parts.push('**相关 OWNLAB 术语**')
      for (const hit of hits.slice(0, 4)) {
        parts.push(`- **${hit.term}**：${hit.short} ${hit.detail}`)
      }
    }
    if (lesson) {
      parts.push(
        `**来自第 ${lesson.day} 天（${lesson.title}）：** 作为产品负责人，把它连到：${lesson.outcomes[0] ?? lesson.subtitle}`,
      )
    }
    if (production) {
      parts.push(
        `**生产视角（${production.source}）：** ${production.poLesson} 留意：${production.watchFor.slice(0, 2).join('；')}。`,
      )
    }
    parts.push('**产品动作：** 把这个想法改写成 PRD 里的决策、指标或风险——而不是工程任务清单。')
    parts.push('_由 OWNLAB 本地导师生成（无 API 密钥）。可在聊天设置中添加 OpenAI 兼容密钥以获得实时模型讲解。_')
    return parts.join('\n\n')
  }

  const parts: string[] = []
  parts.push(`**Plain-language take:** ${summarizeSelection(text, lang)}`)
  if (hits.length) {
    parts.push('**Related OWNLAB terms**')
    for (const hit of hits.slice(0, 4)) {
      parts.push(`- **${hit.term}**: ${hit.short} ${hit.detail}`)
    }
  }
  if (lesson) {
    parts.push(
      `**From Day ${lesson.day} (${lesson.title}):** As a product owner, connect this to: ${lesson.outcomes[0] ?? lesson.subtitle}`,
    )
  }
  if (production) {
    parts.push(
      `**Production lens (${production.source}):** ${production.poLesson} Watch for: ${production.watchFor.slice(0, 2).join('; ')}.`,
    )
  }
  parts.push(
    '**PO move:** Rewrite this idea as a decision, metric, or risk in your PRD — not as an eng task list.',
  )
  parts.push(
    '_Generated by OWNLAB local tutor (no API key). Add an OpenAI-compatible API key in the chat settings for live model explanations._',
  )
  return parts.join('\n\n')
}

function summarizeSelection(text: string, lang: Lang): string {
  const clean = text.replace(/\s+/g, ' ').trim()
  if (lang === 'zh') {
    if (clean.length <= 180) {
      return `你选中了：“${clean}”。在 AI 产品工作中，把它当作需要落地的概念——定义、负责人、指标与失败模式。`
    }
    return `你选中了一段较长内容，开头是“${clean.slice(0, 80)}…”。拆成：含义、在栈中的位置、如何度量、生产里会坏什么。`
  }
  if (clean.length <= 180) {
    return `You highlighted: “${clean}”. In AI product work, treat this as a concept to operationalize — definition, owner, metric, and failure mode.`
  }
  return `You highlighted a longer passage starting with “${clean.slice(0, 140)}…”. Break it into: what it means, where it lives in the stack, how you’d measure it, and what breaks in production.`
}

export async function explainSelection(input: {
  selectedText: string
  sourcePath?: string
  sourceLabel?: string
  history?: ChatMessage[]
  userMessage?: string
  lang?: Lang
}): Promise<{ content: string; model: string }> {
  const lang = input.lang ?? 'en'
  const settings = getApiSettings()
  const system =
    lang === 'zh'
      ? [
          '你是面向 AI 产品负责人（不是工程师）的 OWNLAB 导师。',
          '用生产案例、产品决策、指标与风险清晰讲解。',
          '除非被要求更长，否则保持简洁（120–220 字）。',
          '轻度使用 markdown，短段落与要点。',
          '请用中文回答。',
          input.sourceLabel ? `学习者当前在：${input.sourceLabel}。` : '',
        ]
          .filter(Boolean)
          .join(' ')
      : [
          'You are OWNLAB tutor for AI Product Owners (not engineers).',
          'Explain clearly with production examples, PO decisions, metrics, and risks.',
          'Keep answers concise (120-220 words) unless asked for more.',
          'Use markdown lightly with short paragraphs and bullets.',
          input.sourceLabel ? `Learner is on: ${input.sourceLabel}.` : '',
        ]
          .filter(Boolean)
          .join(' ')

  if (!settings.apiKey) {
    if (input.userMessage && input.history?.length) {
      const follow =
        lang === 'zh'
          ? `**追问（“${input.userMessage}”）：** 没有 API 密钥时我只能基于 OWNLAB 材料扩展。请围绕术语表概念改问，或添加 API 密钥以获得完整对话导师。`
          : `**Follow-up (“${input.userMessage}”):** Without an API key I can only expand from OWNLAB materials. Rephrase your question around a glossary term, or add an API key for a full conversational tutor.`
      return {
        model: 'local-tutor',
        content: [localTutorExplain(input.selectedText, input.sourcePath, lang), '', follow].join(
          '\n',
        ),
      }
    }
    return {
      model: 'local-tutor',
      content: localTutorExplain(input.selectedText, input.sourcePath, lang),
    }
  }

  const promptUser =
    lang === 'zh'
      ? `请为 AI 产品负责人讲解这段选中内容：\n\n"""${input.selectedText}"""`
      : `Explain this selection for an AI Product Owner:\n\n"""${input.selectedText}"""`

  const messages: ChatMessage[] = [
    { role: 'system', content: system },
    { role: 'user', content: promptUser },
    ...(input.history ?? []),
  ]
  if (input.userMessage) {
    messages.push({ role: 'user', content: input.userMessage })
  }

  const response = await fetch(settings.endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${settings.apiKey}`,
    },
    body: JSON.stringify({
      model: settings.model,
      messages,
      temperature: 0.4,
    }),
  })

  if (!response.ok) {
    const errText = await response.text()
    throw new Error(`API error ${response.status}: ${errText.slice(0, 280)}`)
  }

  const data = (await response.json()) as {
    choices?: { message?: { content?: string } }[]
  }
  const content = data.choices?.[0]?.message?.content?.trim()
  if (!content) throw new Error('Empty model response')
  return { content, model: settings.model }
}
