export type SourceHealth = "healthy" | "degraded" | "stale" | "offline";

export type DataSource = {
  id: string;
  name: string;
  /** Primary language of the source */
  language: string;
  languageNative?: string;
  url: string;
  region: string;
  /** Countries / markets this source typically covers */
  countries: string[];
  kind: "news" | "registry" | "fundraising" | "community" | "government" | "aggregator";
  description: string;
  /** ISO timestamp of last successful ingest */
  lastSourcedAt: string;
  /** Optional note shown on the sources desk */
  notes?: string;
};

/** Wide worldwide coverage — includes major non-English desks. */
export const DATA_SOURCES: DataSource[] = [
  {
    id: "techcrunch",
    name: "TechCrunch",
    language: "English",
    url: "https://techcrunch.com",
    region: "Global / North America",
    countries: ["United States", "Canada", "United Kingdom", "India", "Singapore"],
    kind: "news",
    description: "Global startup and fundraising news wire.",
    lastSourcedAt: "2026-10-09T11:40:00.000Z",
  },
  {
    id: "crunchbase-news",
    name: "Crunchbase News",
    language: "English",
    url: "https://news.crunchbase.com",
    region: "Global",
    countries: [
      "United States",
      "United Kingdom",
      "Germany",
      "India",
      "Israel",
      "Brazil",
      "Singapore",
    ],
    kind: "fundraising",
    description: "Round announcements and investor activity feed.",
    lastSourcedAt: "2026-10-09T10:15:00.000Z",
  },
  {
    id: "36kr",
    name: "36氪",
    language: "Chinese",
    languageNative: "中文",
    url: "https://36kr.com",
    region: "Greater China",
    countries: ["China", "Hong Kong", "Singapore"],
    kind: "news",
    description: "Chinese-language startup and hard-tech coverage.",
    lastSourcedAt: "2026-10-09T09:50:00.000Z",
  },
  {
    id: "krasia",
    name: "KrASIA",
    language: "English",
    url: "https://kr-asia.com",
    region: "Asia",
    countries: ["Singapore", "Indonesia", "Vietnam", "Thailand", "Malaysia", "Philippines"],
    kind: "news",
    description: "Southeast and East Asia startup intelligence.",
    lastSourcedAt: "2026-10-09T08:20:00.000Z",
  },
  {
    id: "nikkei-asia",
    name: "Nikkei Asia",
    language: "English / Japanese",
    languageNative: "日本語",
    url: "https://asia.nikkei.com",
    region: "Asia-Pacific",
    countries: ["Japan", "South Korea", "Taiwan", "Singapore", "Australia"],
    kind: "news",
    description: "APAC business and venture coverage from Nikkei.",
    lastSourcedAt: "2026-10-08T22:10:00.000Z",
  },
  {
    id: "platum",
    name: "플래텀 (Platum)",
    language: "Korean",
    languageNative: "한국어",
    url: "https://platum.kr",
    region: "Korea",
    countries: ["South Korea"],
    kind: "news",
    description: "Korean startup and funding desk.",
    lastSourcedAt: "2026-10-09T07:05:00.000Z",
  },
  {
    id: "yourstory",
    name: "YourStory",
    language: "English / Hindi",
    languageNative: "हिन्दी",
    url: "https://yourstory.com",
    region: "South Asia",
    countries: ["India", "United Arab Emirates", "Singapore"],
    kind: "news",
    description: "India-focused entrepreneurship and funding stories.",
    lastSourcedAt: "2026-10-09T06:40:00.000Z",
  },
  {
    id: "startup-india",
    name: "Startup India",
    language: "English / Hindi",
    languageNative: "हिन्दी",
    url: "https://www.startupindia.gov.in",
    region: "India",
    countries: ["India"],
    kind: "government",
    description: "Government registry and recognition signals for Indian startups.",
    lastSourcedAt: "2026-10-07T14:00:00.000Z",
    notes: "Batch sync every 48h",
  },
  {
    id: "sifted",
    name: "Sifted",
    language: "English",
    url: "https://sifted.eu",
    region: "Europe",
    countries: [
      "United Kingdom",
      "Germany",
      "France",
      "Netherlands",
      "Sweden",
      "Spain",
      "Poland",
    ],
    kind: "news",
    description: "European startup and deep-tech fundraising coverage.",
    lastSourcedAt: "2026-10-09T11:05:00.000Z",
  },
  {
    id: "eu-startups",
    name: "EU-Startups",
    language: "English",
    url: "https://www.eu-startups.com",
    region: "Europe",
    countries: ["Germany", "France", "Spain", "Italy", "Portugal", "Poland", "Sweden"],
    kind: "aggregator",
    description: "Pan-European startup news aggregator.",
    lastSourcedAt: "2026-10-09T05:30:00.000Z",
  },
  {
    id: "les-echos-start",
    name: "Les Echos Start",
    language: "French",
    languageNative: "Français",
    url: "https://start.lesechos.fr",
    region: "Francophone Europe / Africa",
    countries: ["France", "Belgium", "Switzerland", "Morocco", "Senegal"],
    kind: "news",
    description: "French-language startup and scale-up desk.",
    lastSourcedAt: "2026-10-08T18:45:00.000Z",
  },
  {
    id: "gruenderszene",
    name: "Gründerszene",
    language: "German",
    languageNative: "Deutsch",
    url: "https://www.businessinsider.de/gruenderszene/",
    region: "DACH",
    countries: ["Germany", "Austria", "Switzerland"],
    kind: "news",
    description: "German-language founder and funding coverage.",
    lastSourcedAt: "2026-10-09T04:20:00.000Z",
  },
  {
    id: "africarena",
    name: "AfricArena / Disrupt Africa",
    language: "English / French",
    languageNative: "Français",
    url: "https://disrupt-africa.com",
    region: "Africa",
    countries: ["Kenya", "Nigeria", "South Africa", "Egypt", "Ghana", "Rwanda"],
    kind: "news",
    description: "African venture and ecosystem reporting.",
    lastSourcedAt: "2026-10-09T03:10:00.000Z",
  },
  {
    id: "wamda",
    name: "Wamda",
    language: "English / Arabic",
    languageNative: "العربية",
    url: "https://www.wamda.com",
    region: "MENA",
    countries: ["United Arab Emirates", "Saudi Arabia", "Egypt", "Jordan", "Lebanon"],
    kind: "news",
    description: "MENA entrepreneurship and funding desk.",
    lastSourcedAt: "2026-10-08T16:00:00.000Z",
  },
  {
    id: "contxto",
    name: "Contxto",
    language: "Spanish / Portuguese",
    languageNative: "Español / Português",
    url: "https://contxto.com",
    region: "Latin America",
    countries: ["Mexico", "Brazil", "Colombia", "Chile", "Argentina", "Peru"],
    kind: "news",
    description: "LatAm startup and venture capital coverage.",
    lastSourcedAt: "2026-10-09T02:00:00.000Z",
  },
  {
    id: "startupbase-br",
    name: "StartupBase / Distrito",
    language: "Portuguese",
    languageNative: "Português",
    url: "https://startupbase.com.br",
    region: "Brazil",
    countries: ["Brazil"],
    kind: "registry",
    description: "Brazilian startup registry and ecosystem map.",
    lastSourcedAt: "2026-10-06T12:00:00.000Z",
    notes: "Weekly registry crawl",
  },
  {
    id: "israel-tech",
    name: "Calcalist Tech / Geektime",
    language: "Hebrew / English",
    languageNative: "עברית",
    url: "https://www.geektime.com",
    region: "Israel",
    countries: ["Israel"],
    kind: "news",
    description: "Israeli deep-tech and cybersecurity funding signals.",
    lastSourcedAt: "2026-10-09T09:00:00.000Z",
  },
  {
    id: "afrilabs",
    name: "AfriLabs / VC4A",
    language: "English / French",
    url: "https://vc4a.com",
    region: "Africa",
    countries: ["Nigeria", "Kenya", "South Africa", "Senegal", "Ghana"],
    kind: "community",
    description: "African founder and investor deal flow community.",
    lastSourcedAt: "2026-10-05T09:00:00.000Z",
    notes: "Community digest lagging — degraded",
  },
  {
    id: "pitchbook-public",
    name: "PitchBook public briefs",
    language: "English",
    url: "https://pitchbook.com/news",
    region: "Global",
    countries: [
      "United States",
      "United Kingdom",
      "Canada",
      "Germany",
      "Australia",
      "Japan",
    ],
    kind: "fundraising",
    description: "Public fundraising briefs and market notes.",
    lastSourcedAt: "2026-10-09T11:55:00.000Z",
  },
  {
    id: "venturebeat",
    name: "VentureBeat",
    language: "English",
    url: "https://venturebeat.com",
    region: "Global / AI",
    countries: ["United States", "Canada", "United Kingdom", "Israel"],
    kind: "news",
    description: "AI and enterprise startup product/funding coverage.",
    lastSourcedAt: "2026-10-09T10:45:00.000Z",
  },
  {
    id: "rest-of-world",
    name: "Rest of World",
    language: "English",
    url: "https://restofworld.org",
    region: "Global South",
    countries: [
      "India",
      "Indonesia",
      "Nigeria",
      "Brazil",
      "Mexico",
      "Philippines",
      "Egypt",
    ],
    kind: "news",
    description: "Technology stories from outside Silicon Valley.",
    lastSourcedAt: "2026-10-08T12:30:00.000Z",
  },
  {
    id: "startupdaily-au",
    name: "Startup Daily / SmartCompany",
    language: "English",
    url: "https://www.smartcompany.com.au",
    region: "Oceania",
    countries: ["Australia", "New Zealand"],
    kind: "news",
    description: "Australian and NZ startup and capital markets desk.",
    lastSourcedAt: "2026-10-09T01:30:00.000Z",
  },
  {
    id: "nordic-startup-news",
    name: "Nordic Startup News / Breakit",
    language: "English / Swedish",
    languageNative: "Svenska",
    url: "https://www.nordicstartupnews.com",
    region: "Nordics",
    countries: ["Sweden", "Denmark", "Finland", "Norway", "Iceland"],
    kind: "news",
    description: "Nordic venture and scale-up coverage.",
    lastSourcedAt: "2026-10-09T08:55:00.000Z",
  },
  {
    id: "webrazzi",
    name: "Webrazzi",
    language: "Turkish",
    languageNative: "Türkçe",
    url: "https://webrazzi.com",
    region: "Türkiye / Eastern Europe",
    countries: ["Turkey", "Romania", "Bulgaria", "Greece"],
    kind: "news",
    description: "Turkish-language tech and startup funding desk.",
    lastSourcedAt: "2026-10-08T20:15:00.000Z",
  },
  {
    id: "vnexpress-startup",
    name: "VnExpress / CafeF Startup",
    language: "Vietnamese",
    languageNative: "Tiếng Việt",
    url: "https://vnexpress.net",
    region: "Vietnam",
    countries: ["Vietnam"],
    kind: "news",
    description: "Vietnamese startup and digital economy reporting.",
    lastSourcedAt: "2026-10-09T05:00:00.000Z",
  },
  {
    id: "technode",
    name: "TechNode",
    language: "English / Chinese",
    languageNative: "中文",
    url: "https://technode.com",
    region: "Greater China",
    countries: ["China", "Hong Kong", "Taiwan", "Singapore"],
    kind: "news",
    description: "Sino-global tech and venture bilingual feed.",
    lastSourcedAt: "2026-10-09T09:25:00.000Z",
  },
  {
    id: "pulse-ng",
    name: "TechCabal / Pulse Nigeria",
    language: "English",
    url: "https://techcabal.com",
    region: "West Africa",
    countries: ["Nigeria", "Ghana", "Kenya", "South Africa"],
    kind: "news",
    description: "West and Southern African startup capital coverage.",
    lastSourcedAt: "2026-10-09T06:10:00.000Z",
  },
  {
    id: "inc42",
    name: "Inc42",
    language: "English / Hindi",
    languageNative: "हिन्दी",
    url: "https://inc42.com",
    region: "India",
    countries: ["India"],
    kind: "fundraising",
    description: "Indian startup funding and policy signals.",
    lastSourcedAt: "2026-10-09T10:00:00.000Z",
  },
  {
    id: "startupchile",
    name: "Start-Up Chile / LatamList",
    language: "Spanish / English",
    languageNative: "Español",
    url: "https://www.startupchile.org",
    region: "Southern Cone",
    countries: ["Chile", "Argentina", "Peru", "Uruguay", "Colombia"],
    kind: "government",
    description: "LatAm accelerator and ecosystem program feed.",
    lastSourcedAt: "2026-10-07T09:00:00.000Z",
    notes: "Program batch sync ~48h",
  },
  {
    id: "offline-probe",
    name: "Legacy XML dump (retired)",
    language: "English",
    url: "https://example.com/legacy-dump",
    region: "Archive",
    countries: ["United States"],
    kind: "aggregator",
    description: "Retired ingest path kept for status monitoring.",
    lastSourcedAt: "2026-08-01T00:00:00.000Z",
    notes: "Connector disabled — offline",
  },
];

export function sourceHealth(
  source: DataSource,
  now = Date.now(),
): SourceHealth {
  if (source.id === "offline-probe" || /offline/i.test(source.notes ?? "")) {
    return "offline";
  }
  const ageMs = now - new Date(source.lastSourcedAt).getTime();
  const hour = 60 * 60 * 1000;
  if (ageMs <= 24 * hour) return "healthy";
  if (ageMs <= 7 * 24 * hour) return "degraded";
  return "stale";
}

export function allCoveredCountries(sources: DataSource[] = DATA_SOURCES): string[] {
  return [...new Set(sources.flatMap((s) => s.countries))].sort((a, b) =>
    a.localeCompare(b),
  );
}

export function sourcesSummary(now = Date.now()) {
  const healthCounts = { healthy: 0, degraded: 0, stale: 0, offline: 0 };
  for (const source of DATA_SOURCES) {
    healthCounts[sourceHealth(source, now)] += 1;
  }
  const lastSourcedAt = DATA_SOURCES.map((s) => s.lastSourcedAt).sort().at(-1) ?? null;
  return {
    total: DATA_SOURCES.length,
    countries: allCoveredCountries(),
    healthCounts,
    lastSourcedAt,
    languages: [...new Set(DATA_SOURCES.map((s) => s.language))].sort(),
  };
}
