import type { GoForwardStrategy, SocialAccount, StartupIdea } from "./types";

const scannedAt = "2026-10-10T08:00:00.000Z";

type IdeaDraft = {
  slug: string;
  name: string;
  description: string;
  businessModel: string;
  teamCountry: string;
  teamCity: string;
  teamSize: number;
  industry: string;
  sector: string;
  fundraisingSecured: boolean;
  fundingStage?: string;
  fundingAmountUsd?: number;
  fundingRoundNote?: string;
  website: string;
  social: SocialAccount[];
  strategy: GoForwardStrategy;
  goForwardSummary: string;
  source: string;
  tags: string[];
};

function draftToIdea(draft: IdeaDraft, index: number): StartupIdea {
  return {
    id: `idea_${String(index + 21).padStart(2, "0")}`,
    slug: draft.slug,
    name: draft.name,
    description: draft.description,
    businessModel: draft.businessModel,
    teamCountry: draft.teamCountry,
    teamCity: draft.teamCity,
    teamSize: draft.teamSize,
    industry: draft.industry,
    sector: draft.sector,
    fundraisingSecured: draft.fundraisingSecured,
    fundingStage: draft.fundingStage,
    fundingAmountUsd: draft.fundingAmountUsd,
    fundingRoundNote: draft.fundingRoundNote,
    website: draft.website,
    social: draft.social,
    goForward: {
      strategy: draft.strategy,
      summary: draft.goForwardSummary,
    },
    source: draft.source,
    scannedAt,
    tags: draft.tags,
  };
}

/** Additional worldwide signals beyond the featured 20 dossier set. */
const DRAFTS: IdeaDraft[] = [
  {
    slug: "stripe-atlas-rails",
    name: "Atlas Formation Rails",
    description:
      "Formation-as-a-service for cross-border founders incorporating in the US while banking and tax ops stay localized for SEA and LatAm teams.",
    businessModel: "Per-formation fee + annual compliance SaaS.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 120,
    industry: "FinTech",
    sector: "Startup Infrastructure",
    fundraisingSecured: true,
    fundingStage: "Series I+",
    fundingAmountUsd: 8_700_000_000,
    fundingRoundNote: "Public markets + prior private rounds",
    website: "https://stripe.com/atlas",
    social: [
      { platform: "x", handle: "@stripe", url: "https://x.com/stripe" },
      { platform: "linkedin", handle: "Stripe", url: "https://www.linkedin.com/company/stripe" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "White-label formation packs for regional accelerators under a local brand.",
    source: "scan:global-fintech",
    tags: ["fintech", "formation", "US"],
  },
  {
    slug: "notion-ops-stack",
    name: "Workspace Ops Stack",
    description:
      "Connected docs, projects, and AI Q&A for ops-heavy startups that outgrow slides and scattered chat threads.",
    businessModel: "Seat-based SaaS with AI add-ons.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 500,
    industry: "Productivity",
    sector: "Collaborative Software",
    fundraisingSecured: true,
    fundingStage: "Series C",
    fundingAmountUsd: 343_000_000,
    fundingRoundNote: "Growth equity syndicate",
    website: "https://www.notion.so/",
    social: [
      { platform: "x", handle: "@NotionHQ", url: "https://x.com/NotionHQ" },
      { platform: "linkedin", handle: "Notion", url: "https://www.linkedin.com/company/notionhq" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Spin a manufacturing SOP template pack and sell to factory ops teams.",
    source: "scan:global-saas",
    tags: ["saas", "productivity", "US"],
  },
  {
    slug: "canva-design-os",
    name: "Visual Design OS",
    description:
      "Browser design suite that lets SMBs ship localized creatives without a dedicated studio—templates, brand kits, and magic resize.",
    businessModel: "Freemium seats + Pro/Teams subscriptions.",
    teamCountry: "Australia",
    teamCity: "Sydney",
    teamSize: 4000,
    industry: "MarTech",
    sector: "Creative Tools",
    fundraisingSecured: true,
    fundingStage: "Series A+",
    fundingAmountUsd: 560_000_000,
    fundingRoundNote: "Late-stage private",
    website: "https://www.canva.com/",
    social: [
      { platform: "x", handle: "@canva", url: "https://x.com/canva" },
      { platform: "instagram", handle: "@canva", url: "https://www.instagram.com/canva/" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Partner with SEA agency networks on vernacular template marketplaces.",
    source: "scan:oceania-saas",
    tags: ["design", "SMB", "Australia"],
  },
  {
    slug: "shopify-merchant-os",
    name: "Merchant Commerce OS",
    description:
      "Composable storefront + payments stack for DTC brands expanding across borders with localized checkout and logistics apps.",
    businessModel: "Subscription + payments take-rate.",
    teamCountry: "Canada",
    teamCity: "Ottawa",
    teamSize: 8000,
    industry: "E-commerce",
    sector: "Merchant Platforms",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 1_500_000_000,
    fundingRoundNote: "Public company (cumulative private rounds)",
    website: "https://www.shopify.com/",
    social: [
      { platform: "x", handle: "@Shopify", url: "https://x.com/Shopify" },
      { platform: "linkedin", handle: "Shopify", url: "https://www.linkedin.com/company/shopify" },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Offer white-label storefront kits to regional conglomerates' SME brands.",
    source: "scan:na-commerce",
    tags: ["ecommerce", "Canada", "SMB"],
  },
  {
    slug: "revolut-neo-bank",
    name: "Borderless Neo Bank",
    description:
      "Multi-currency accounts, cards, and crypto rails for digital nomads and SMEs hopping between UK, EU, and Asia corridors.",
    businessModel: "Interchange + FX spread + premium plans.",
    teamCountry: "United Kingdom",
    teamCity: "London",
    teamSize: 7000,
    industry: "FinTech",
    sector: "Digital Banking",
    fundraisingSecured: true,
    fundingStage: "Series E",
    fundingAmountUsd: 1_700_000_000,
    fundingRoundNote: "SoftBank-led late stage",
    website: "https://www.revolut.com/",
    social: [
      { platform: "x", handle: "@RevolutApp", url: "https://x.com/RevolutApp" },
      { platform: "linkedin", handle: "Revolut", url: "https://www.linkedin.com/company/revolut" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "License card issuing stacks to ASEAN digital banks entering EU corridors.",
    source: "scan:eu-fintech",
    tags: ["neobank", "UK", "payments"],
  },
  {
    slug: "klarna-bnpl-rails",
    name: "Flexible Checkout Rails",
    description:
      "Buy-now-pay-later and installment rails embedded at merchant checkout with fraud and collections automation.",
    businessModel: "Merchant discount fee + consumer interest.",
    teamCountry: "Sweden",
    teamCity: "Stockholm",
    teamSize: 5000,
    industry: "FinTech",
    sector: "Consumer Credit",
    fundraisingSecured: true,
    fundingStage: "Late stage",
    fundingAmountUsd: 4_000_000_000,
    fundingRoundNote: "Late-stage private rounds",
    website: "https://www.klarna.com/",
    social: [
      { platform: "x", handle: "@Klarna", url: "https://x.com/Klarna" },
      { platform: "linkedin", handle: "Klarna", url: "https://www.linkedin.com/company/klarna" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Port installment UX to SEA marketplaces with local bank sponsors.",
    source: "scan:nordic-fintech",
    tags: ["BNPL", "Sweden", "checkout"],
  },
  {
    slug: "spotify-audio-graph",
    name: "Audio Discovery Graph",
    description:
      "Personalized audio graph that connects podcasts, music, and creator monetization for global listeners.",
    businessModel: "Premium subscriptions + ads.",
    teamCountry: "Sweden",
    teamCity: "Stockholm",
    teamSize: 9000,
    industry: "Media",
    sector: "Audio Streaming",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 2_500_000_000,
    fundingRoundNote: "Public company",
    website: "https://www.spotify.com/",
    social: [
      { platform: "x", handle: "@Spotify", url: "https://x.com/Spotify" },
      { platform: "instagram", handle: "@spotify", url: "https://www.instagram.com/spotify/" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Spin a vertical podcast network OS for education publishers.",
    source: "scan:nordic-media",
    tags: ["audio", "Sweden", "consumer"],
  },
  {
    slug: "industrial-climate-os",
    name: "Industrial Climate OS",
    description:
      "Software that maps plant energy loads, carbon intensity, and retrofit ROI for European manufacturers under CSRD pressure.",
    businessModel: "Plant SaaS seats + implementation.",
    teamCountry: "Germany",
    teamCity: "Munich",
    teamSize: 85,
    industry: "Climate Tech",
    sector: "Industrial Decarbonization",
    fundraisingSecured: true,
    fundingStage: "Series B",
    fundingAmountUsd: 75_000_000,
    fundingRoundNote: "Climate growth funds",
    website: "https://www.tado.com/",
    social: [
      { platform: "linkedin", handle: "tado°", url: "https://www.linkedin.com/company/tado-" },
      { platform: "x", handle: "@tado", url: "https://x.com/tado" },
    ],
    strategy: "franchise_local",
    goForwardSummary: "Franchise energy-audit crews using the same ROI calculator in secondary DE cities.",
    source: "scan:eu-climate",
    tags: ["climate", "Germany", "industrial"],
  },
  {
    slug: "wise-fx-corridor",
    name: "Transparent FX Corridor",
    description:
      "Low-fee international transfers with mid-market FX for freelancers and SMEs moving money across 40+ currencies.",
    businessModel: "FX margin + transfer fees.",
    teamCountry: "United Kingdom",
    teamCity: "London",
    teamSize: 5000,
    industry: "FinTech",
    sector: "Cross-border Payments",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 1_100_000_000,
    fundingRoundNote: "Public company",
    website: "https://wise.com/",
    social: [
      { platform: "x", handle: "@Wise", url: "https://x.com/Wise" },
      { platform: "linkedin", handle: "Wise", url: "https://www.linkedin.com/company/wiseaccount" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Build Asia–Africa SME payout lanes on the same transparency narrative.",
    source: "scan:uk-fintech",
    tags: ["FX", "UK", "SME"],
  },
  {
    slug: "rappi-super-app",
    name: "LatAm Super App",
    description:
      "On-demand delivery, payments, and fintech wallet spanning groceries, restaurants, and last-mile in major LatAm cities.",
    businessModel: "Delivery fees + ads + fintech take-rate.",
    teamCountry: "Colombia",
    teamCity: "Bogotá",
    teamSize: 3000,
    industry: "Mobility",
    sector: "On-demand Delivery",
    fundraisingSecured: true,
    fundingStage: "Series F",
    fundingAmountUsd: 2_100_000_000,
    fundingRoundNote: "SoftBank + others",
    website: "https://www.rappi.com/",
    social: [
      { platform: "instagram", handle: "@rappi", url: "https://www.instagram.com/rappi/" },
      { platform: "x", handle: "@rappiapp", url: "https://x.com/rappiapp" },
    ],
    strategy: "franchise_local",
    goForwardSummary: "Franchise city ops cells with shared logistics software in secondary markets.",
    source: "scan:latam-consumer",
    tags: ["delivery", "Colombia", "superapp"],
  },
  {
    slug: "nubank-digital-bank",
    name: "Purple Digital Bank",
    description:
      "Mobile-first banking for underbanked consumers across Brazil and LatAm with credit cards, accounts, and insurance.",
    businessModel: "Interchange + interest + fees.",
    teamCountry: "Brazil",
    teamCity: "São Paulo",
    teamSize: 8000,
    industry: "FinTech",
    sector: "Digital Banking",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 2_600_000_000,
    fundingRoundNote: "Public company",
    website: "https://nubank.com.br/",
    social: [
      { platform: "instagram", handle: "@nubank", url: "https://www.instagram.com/nubank/" },
      { platform: "x", handle: "@nubank", url: "https://x.com/nubank" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Copy the credit-card-first funnel for SEA underbanked corridors.",
    source: "scan:latam-fintech",
    tags: ["neobank", "Brazil", "credit"],
  },
  {
    slug: "mercadolibre-commerce",
    name: "LatAm Commerce Graph",
    description:
      "Marketplace + logistics + fintech ecosystem connecting sellers and buyers across Spanish- and Portuguese-speaking Americas.",
    businessModel: "Take-rate + ads + fintech.",
    teamCountry: "Argentina",
    teamCity: "Buenos Aires",
    teamSize: 50000,
    industry: "E-commerce",
    sector: "Marketplaces",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 2_000_000_000,
    fundingRoundNote: "Public company",
    website: "https://www.mercadolibre.com/",
    social: [
      { platform: "x", handle: "@MercadoLibre", url: "https://x.com/MercadoLibre" },
      {
        platform: "linkedin",
        handle: "Mercado Libre",
        url: "https://www.linkedin.com/company/mercadolibre",
      },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Offer logistics middleware to regional retailers as B2B only.",
    source: "scan:latam-commerce",
    tags: ["marketplace", "Argentina", "logistics"],
  },
  {
    slug: "grab-sea-superapp",
    name: "SEA Mobility Super App",
    description:
      "Ride-hailing, food, and payments network spanning Southeast Asia with driver and merchant ecosystems.",
    businessModel: "Take-rate + fintech + ads.",
    teamCountry: "Singapore",
    teamCity: "Singapore",
    teamSize: 10000,
    industry: "Mobility",
    sector: "Multi-service Platforms",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 10_000_000_000,
    fundingRoundNote: "Public company",
    website: "https://www.grab.com/",
    social: [
      { platform: "x", handle: "@grabsg", url: "https://x.com/grabsg" },
      { platform: "linkedin", handle: "Grab", url: "https://www.linkedin.com/company/grabapp" },
    ],
    strategy: "franchise_local",
    goForwardSummary: "Franchise micro-fleet hubs in tier-2 SEA cities under Grab software.",
    source: "scan:sea-mobility",
    tags: ["mobility", "Singapore", "superapp"],
  },
  {
    slug: "gojek-tokopedia",
    name: "Archipelago Super Platform",
    description:
      "Combined on-demand services and marketplace for Indonesian consumers spanning rides, food, and e-commerce.",
    businessModel: "Take-rate + ads + fintech.",
    teamCountry: "Indonesia",
    teamCity: "Jakarta",
    teamSize: 8000,
    industry: "Mobility",
    sector: "Multi-service Platforms",
    fundraisingSecured: true,
    fundingStage: "Late stage",
    fundingAmountUsd: 5_000_000_000,
    fundingRoundNote: "Goto Group consolidation",
    website: "https://www.gojek.com/",
    social: [
      { platform: "instagram", handle: "@gojekindonesia", url: "https://www.instagram.com/gojekindonesia/" },
      { platform: "x", handle: "@gojekindonesia", url: "https://x.com/gojekindonesia" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Spin logistics-only APIs for enterprise shippers.",
    source: "scan:sea-consumer",
    tags: ["Indonesia", "superapp", "logistics"],
  },
  {
    slug: "paytm-india-wallet",
    name: "India Payments Fabric",
    description:
      "Consumer wallet, UPI rails, and merchant acquiring stack connecting India's digital payments economy.",
    businessModel: "Payment fees + financial services.",
    teamCountry: "India",
    teamCity: "Noida",
    teamSize: 10000,
    industry: "FinTech",
    sector: "Payments",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 4_500_000_000,
    fundingRoundNote: "Public company",
    website: "https://paytm.com/",
    social: [
      { platform: "x", handle: "@Paytm", url: "https://x.com/Paytm" },
      { platform: "linkedin", handle: "Paytm", url: "https://www.linkedin.com/company/paytm" },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Sell merchant acquiring APIs to regional banks as white-label.",
    source: "scan:india-fintech",
    tags: ["payments", "India", "UPI"],
  },
  {
    slug: "razorpay-merchant",
    name: "India Merchant Stack",
    description:
      "Payment gateway, payroll, and banking APIs for Indian startups and SMEs going online.",
    businessModel: "Payment MDR + SaaS.",
    teamCountry: "India",
    teamCity: "Bengaluru",
    teamSize: 3000,
    industry: "FinTech",
    sector: "Merchant Payments",
    fundraisingSecured: true,
    fundingStage: "Series F",
    fundingAmountUsd: 740_000_000,
    fundingRoundNote: "Tiger + others",
    website: "https://razorpay.com/",
    social: [
      { platform: "x", handle: "@Razorpay", url: "https://x.com/Razorpay" },
      { platform: "linkedin", handle: "Razorpay", url: "https://www.linkedin.com/company/razorpay" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Clone merchant APIs for Bangladesh/Sri Lanka corridors.",
    source: "scan:india-fintech",
    tags: ["payments", "India", "SMB"],
  },
  {
    slug: "bytedance-creator-os",
    name: "Short-Video Creator OS",
    description:
      "Short-form video platform with creator funds, live commerce, and recommendation engines for global audiences.",
    businessModel: "Ads + live commerce take-rate.",
    teamCountry: "China",
    teamCity: "Beijing",
    teamSize: 100000,
    industry: "Media",
    sector: "Short Video",
    fundraisingSecured: true,
    fundingStage: "Late stage",
    fundingAmountUsd: 9_000_000_000,
    fundingRoundNote: "Private late stage",
    website: "https://www.tiktok.com/",
    social: [
      { platform: "x", handle: "@TikTok", url: "https://x.com/TikTok" },
      { platform: "instagram", handle: "@tiktok", url: "https://www.instagram.com/tiktok/" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Spin education-only short video rails for tutoring brands.",
    source: "scan:cn-consumer",
    tags: ["video", "China", "creators"],
  },
  {
    slug: "shein-fast-fashion",
    name: "On-Demand Fashion Graph",
    description:
      "Data-driven apparel design-to-consumer loop that tests micro-batches and scales winners globally.",
    businessModel: "DTC merchandise margin + marketplace.",
    teamCountry: "China",
    teamCity: "Guangzhou",
    teamSize: 10000,
    industry: "E-commerce",
    sector: "Fashion Retail",
    fundraisingSecured: true,
    fundingStage: "Late stage",
    fundingAmountUsd: 2_000_000_000,
    fundingRoundNote: "Private late stage",
    website: "https://www.shein.com/",
    social: [
      { platform: "instagram", handle: "@sheinofficial", url: "https://www.instagram.com/sheinofficial/" },
      { platform: "tiktok", handle: "@shein_official", url: "https://www.tiktok.com/@shein_official" },
    ],
    strategy: "license_tech",
    goForwardSummary: "License demand-sensing to regional apparel manufacturers.",
    source: "scan:cn-commerce",
    tags: ["fashion", "China", "DTC"],
  },
  {
    slug: "coupang-rocket",
    name: "Rocket Logistics Commerce",
    description:
      "E-commerce with owned logistics promising next-day delivery across South Korea and expanding abroad.",
    businessModel: "Merchandise + marketplace + membership.",
    teamCountry: "South Korea",
    teamCity: "Seoul",
    teamSize: 60000,
    industry: "E-commerce",
    sector: "Logistics Commerce",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 3_500_000_000,
    fundingRoundNote: "Public company",
    website: "https://www.coupang.com/",
    social: [
      { platform: "linkedin", handle: "Coupang", url: "https://www.linkedin.com/company/coupang" },
      { platform: "x", handle: "@Coupang", url: "https://x.com/Coupang" },
    ],
    strategy: "franchise_local",
    goForwardSummary: "Franchise rocket-delivery dark stores in secondary KR metros.",
    source: "scan:kr-commerce",
    tags: ["ecommerce", "Korea", "logistics"],
  },
  {
    slug: "tokopedia-market",
    name: "Nusantara Marketplace",
    description:
      "Indonesia-focused marketplace connecting MSMEs with consumers via logistics and payments partners.",
    businessModel: "Take-rate + ads + fintech.",
    teamCountry: "Indonesia",
    teamCity: "Jakarta",
    teamSize: 5000,
    industry: "E-commerce",
    sector: "Marketplaces",
    fundraisingSecured: true,
    fundingStage: "Late stage",
    fundingAmountUsd: 2_500_000_000,
    fundingRoundNote: "Goto Group",
    website: "https://www.tokopedia.com/",
    social: [
      { platform: "instagram", handle: "@tokopedia", url: "https://www.instagram.com/tokopedia/" },
      { platform: "x", handle: "@tokopedia", url: "https://x.com/tokopedia" },
    ],
    strategy: "partner_founders",
    goForwardSummary: "Partner as category operator for specialty MSME verticals.",
    source: "scan:sea-commerce",
    tags: ["marketplace", "Indonesia", "MSME"],
  },
  {
    slug: "sea-shopee",
    name: "SEA Social Commerce",
    description:
      "Marketplace and gaming-adjacent commerce network with strong Southeast Asian merchant penetration.",
    businessModel: "Take-rate + ads + fintech + gaming.",
    teamCountry: "Singapore",
    teamCity: "Singapore",
    teamSize: 40000,
    industry: "E-commerce",
    sector: "Marketplaces",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 6_000_000_000,
    fundingRoundNote: "Public company (Sea Limited)",
    website: "https://shopee.com/",
    social: [
      { platform: "instagram", handle: "@shopee_sg", url: "https://www.instagram.com/shopee_sg/" },
      { platform: "x", handle: "@Shopee", url: "https://x.com/Shopee" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Spin a B2B wholesale lane for neighborhood kirana-style shops.",
    source: "scan:sea-commerce",
    tags: ["shopee", "Singapore", "marketplace"],
  },
  {
    slug: "flutterwave-africa",
    name: "Africa Payments Fabric",
    description:
      "Payment APIs and checkout that help businesses accept and send money across African markets.",
    businessModel: "Payment fees + FX.",
    teamCountry: "Nigeria",
    teamCity: "Lagos",
    teamSize: 400,
    industry: "FinTech",
    sector: "Payments",
    fundraisingSecured: true,
    fundingStage: "Series D",
    fundingAmountUsd: 475_000_000,
    fundingRoundNote: "Avenir + others",
    website: "https://flutterwave.com/",
    social: [
      { platform: "x", handle: "@Flutterwave", url: "https://x.com/Flutterwave" },
      {
        platform: "linkedin",
        handle: "Flutterwave",
        url: "https://www.linkedin.com/company/flutterwave",
      },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Open Asia–Africa merchant corridors for diaspora e-commerce.",
    source: "scan:africa-fintech",
    tags: ["payments", "Nigeria", "Africa"],
  },
  {
    slug: "paystack-africa",
    name: "Simple Africa Checkout",
    description:
      "Developer-friendly payment APIs for African startups accepting cards and local methods online.",
    businessModel: "Payment MDR.",
    teamCountry: "Nigeria",
    teamCity: "Lagos",
    teamSize: 200,
    industry: "FinTech",
    sector: "Merchant Payments",
    fundraisingSecured: true,
    fundingStage: "Acquired",
    fundingAmountUsd: 200_000_000,
    fundingRoundNote: "Stripe acquisition",
    website: "https://paystack.com/",
    social: [
      { platform: "x", handle: "@paystack", url: "https://x.com/paystack" },
      { platform: "linkedin", handle: "Paystack", url: "https://www.linkedin.com/company/paystack" },
    ],
    strategy: "partner_founders",
    goForwardSummary: "Partner as East Africa reseller for Stripe/Paystack stack.",
    source: "scan:africa-fintech",
    tags: ["payments", "Nigeria", "developers"],
  },
  {
    slug: "andela-talent",
    name: "Distributed Engineering Talent",
    description:
      "Marketplace placing African software engineers with global product companies on long-term contracts.",
    businessModel: "Placement margin + managed teams.",
    teamCountry: "Nigeria",
    teamCity: "Lagos",
    teamSize: 500,
    industry: "HR Tech",
    sector: "Talent Marketplaces",
    fundraisingSecured: true,
    fundingStage: "Series E",
    fundingAmountUsd: 381_000_000,
    fundingRoundNote: "SoftBank Vision Fund",
    website: "https://andela.com/",
    social: [
      { platform: "x", handle: "@Andela", url: "https://x.com/Andela" },
      { platform: "linkedin", handle: "Andela", url: "https://www.linkedin.com/company/andela" },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Sell dedicated squads to EU scale-ups as staff-aug productized offer.",
    source: "scan:africa-talent",
    tags: ["talent", "Nigeria", "engineering"],
  },
  {
    slug: "yassir-maghreb",
    name: "Maghreb Super App",
    description:
      "Ride-hailing, delivery, and payments for North African cities with Arabic-first UX.",
    businessModel: "Take-rate + fintech.",
    teamCountry: "Algeria",
    teamCity: "Algiers",
    teamSize: 800,
    industry: "Mobility",
    sector: "On-demand Platforms",
    fundraisingSecured: true,
    fundingStage: "Series B",
    fundingAmountUsd: 150_000_000,
    fundingRoundNote: "Growth round",
    website: "https://yassir.com/",
    social: [
      { platform: "instagram", handle: "@yassir", url: "https://www.instagram.com/yassir/" },
      { platform: "linkedin", handle: "Yassir", url: "https://www.linkedin.com/company/yassir" },
    ],
    strategy: "franchise_local",
    goForwardSummary: "Franchise city ops across Francophone Africa.",
    source: "scan:mena-mobility",
    tags: ["mobility", "Algeria", "MENA"],
  },
  {
    slug: "careem-middle-east",
    name: "MENA Everything App",
    description:
      "Ride-hailing, delivery, and remittance services across Middle East and Pakistan corridors.",
    businessModel: "Take-rate + fintech.",
    teamCountry: "UAE",
    teamCity: "Dubai",
    teamSize: 4000,
    industry: "Mobility",
    sector: "Multi-service Platforms",
    fundraisingSecured: true,
    fundingStage: "Acquired",
    fundingAmountUsd: 3_100_000_000,
    fundingRoundNote: "Uber acquisition",
    website: "https://www.careem.com/",
    social: [
      { platform: "x", handle: "@Careem", url: "https://x.com/Careem" },
      { platform: "instagram", handle: "@careem", url: "https://www.instagram.com/careem/" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Spin remittance-only product for GCC–South Asia corridors.",
    source: "scan:mena-mobility",
    tags: ["mobility", "UAE", "MENA"],
  },
  {
    slug: "tabby-bnpl-gcc",
    name: "GCC Installments",
    description:
      "Sharia-friendly installment shopping for GCC consumers embedded at fashion and electronics checkout.",
    businessModel: "Merchant fees + consumer plans.",
    teamCountry: "UAE",
    teamCity: "Dubai",
    teamSize: 600,
    industry: "FinTech",
    sector: "Consumer Credit",
    fundraisingSecured: true,
    fundingStage: "Series D",
    fundingAmountUsd: 580_000_000,
    fundingRoundNote: "SoftBank + others",
    website: "https://tabby.ai/",
    social: [
      { platform: "instagram", handle: "@tabbyai", url: "https://www.instagram.com/tabbyai/" },
      { platform: "linkedin", handle: "Tabby", url: "https://www.linkedin.com/company/tabbyai" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Port installment UX to Muslim-majority SEA markets.",
    source: "scan:mena-fintech",
    tags: ["BNPL", "UAE", "GCC"],
  },
  {
    slug: "vtex-commerce",
    name: "Composable Commerce Cloud",
    description:
      "Enterprise commerce platform for retailers modernizing storefronts across LatAm and global markets.",
    businessModel: "GMV-linked SaaS.",
    teamCountry: "Brazil",
    teamCity: "São Paulo",
    teamSize: 1500,
    industry: "E-commerce",
    sector: "Commerce Platforms",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 575_000_000,
    fundingRoundNote: "Public company",
    website: "https://vtex.com/",
    social: [
      { platform: "linkedin", handle: "VTEX", url: "https://www.linkedin.com/company/vtex" },
      { platform: "x", handle: "@vtex", url: "https://x.com/vtex" },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Sell vertical commerce kits to grocery chains as packaged offer.",
    source: "scan:latam-saas",
    tags: ["commerce", "Brazil", "B2B"],
  },
  {
    slug: "dlocal-crossborder",
    name: "Emerging-Market Pay-ins",
    description:
      "Cross-border payment orchestration that lets global merchants collect in local methods across emerging markets.",
    businessModel: "Payment fees + FX.",
    teamCountry: "Uruguay",
    teamCity: "Montevideo",
    teamSize: 900,
    industry: "FinTech",
    sector: "Cross-border Payments",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 580_000_000,
    fundingRoundNote: "Public company",
    website: "https://dlocal.com/",
    social: [
      { platform: "linkedin", handle: "dLocal", url: "https://www.linkedin.com/company/dlocal" },
      { platform: "x", handle: "@dLocalGlobal", url: "https://x.com/dLocalGlobal" },
    ],
    strategy: "partner_founders",
    goForwardSummary: "Partner as Africa pay-in specialist under dLocal rails.",
    source: "scan:latam-fintech",
    tags: ["payments", "Uruguay", "cross-border"],
  },
  {
    slug: "pieter-patreon-creators",
    name: "Creator Membership Rails",
    description:
      "Membership and paid community tooling that lets creators monetize fans with recurring billing.",
    businessModel: "Platform fee on creator revenue.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 400,
    industry: "Media",
    sector: "Creator Economy",
    fundraisingSecured: true,
    fundingStage: "Series F",
    fundingAmountUsd: 413_000_000,
    fundingRoundNote: "SoftBank + others",
    website: "https://www.patreon.com/",
    social: [
      { platform: "x", handle: "@Patreon", url: "https://x.com/Patreon" },
      { platform: "instagram", handle: "@patreon", url: "https://www.instagram.com/patreon/" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Spin education-tutor membership packs for Asian tutoring brands.",
    source: "scan:us-creators",
    tags: ["creators", "US", "membership"],
  },
  {
    slug: "airtable-ops-db",
    name: "No-Code Ops Database",
    description:
      "Spreadsheet-database hybrid that lets ops teams model workflows without engineering tickets.",
    businessModel: "Seat SaaS.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 1000,
    industry: "Productivity",
    sector: "No-Code Platforms",
    fundraisingSecured: true,
    fundingStage: "Series F",
    fundingAmountUsd: 735_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://www.airtable.com/",
    social: [
      { platform: "x", handle: "@airtable", url: "https://x.com/airtable" },
      { platform: "linkedin", handle: "Airtable", url: "https://www.linkedin.com/company/airtable" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Ship a clinic ops base template and sell to outpatient groups.",
    source: "scan:us-saas",
    tags: ["nocode", "US", "ops"],
  },
  {
    slug: "figma-design-collab",
    name: "Realtime Design Collab",
    description:
      "Browser design system and prototyping suite used by product teams to ship UI together.",
    businessModel: "Seat SaaS.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 1500,
    industry: "Productivity",
    sector: "Design Tools",
    fundraisingSecured: true,
    fundingStage: "Acquired",
    fundingAmountUsd: 333_000_000,
    fundingRoundNote: "Adobe acquisition path",
    website: "https://www.figma.com/",
    social: [
      { platform: "x", handle: "@figma", url: "https://x.com/figma" },
      { platform: "linkedin", handle: "Figma", url: "https://www.linkedin.com/company/figma" },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Offer agency white-label design system kits as packaged SKUs.",
    source: "scan:us-saas",
    tags: ["design", "US", "collaboration"],
  },
  {
    slug: "databricks-lakehouse",
    name: "Lakehouse Analytics OS",
    description:
      "Unified data and AI platform for enterprises consolidating lakes and warehouses with governance.",
    businessModel: "Consumption + platform fees.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 6000,
    industry: "Enterprise Software",
    sector: "Data Platforms",
    fundraisingSecured: true,
    fundingStage: "Series I",
    fundingAmountUsd: 14_000_000_000,
    fundingRoundNote: "Mega late-stage rounds",
    website: "https://www.databricks.com/",
    social: [
      { platform: "x", handle: "@databricks", url: "https://x.com/databricks" },
      {
        platform: "linkedin",
        handle: "Databricks",
        url: "https://www.linkedin.com/company/databricks",
      },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Package industry lakehouse starters for banks and telcos.",
    source: "scan:us-enterprise",
    tags: ["data", "AI", "US"],
  },
  {
    slug: "openai-platform",
    name: "Foundation Model Platform",
    description:
      "API access to frontier models plus enterprise controls for product teams embedding generative AI.",
    businessModel: "API usage + enterprise seats.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 2000,
    industry: "AI",
    sector: "Foundation Models",
    fundraisingSecured: true,
    fundingStage: "Late stage",
    fundingAmountUsd: 13_000_000_000,
    fundingRoundNote: "Microsoft + others",
    website: "https://openai.com/",
    social: [
      { platform: "x", handle: "@OpenAI", url: "https://x.com/OpenAI" },
      { platform: "linkedin", handle: "OpenAI", url: "https://www.linkedin.com/company/openai" },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Build vertical agents on the API and sell to regulated industries.",
    source: "scan:us-ai",
    tags: ["AI", "US", "platform"],
  },
  {
    slug: "anthropic-claude",
    name: "Constitutional AI Suite",
    description:
      "Enterprise-safe large language models and tooling emphasizing controllability and long-context work.",
    businessModel: "API usage + enterprise contracts.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 1000,
    industry: "AI",
    sector: "Foundation Models",
    fundraisingSecured: true,
    fundingStage: "Series E",
    fundingAmountUsd: 7_300_000_000,
    fundingRoundNote: "Amazon + others",
    website: "https://www.anthropic.com/",
    social: [
      { platform: "x", handle: "@AnthropicAI", url: "https://x.com/AnthropicAI" },
      {
        platform: "linkedin",
        handle: "Anthropic",
        url: "https://www.linkedin.com/company/anthropicresearch",
      },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Ship compliance-review agents for legal and finance desks.",
    source: "scan:us-ai",
    tags: ["AI", "US", "enterprise"],
  },
  {
    slug: "mistral-europe-ai",
    name: "European Open Models",
    description:
      "Open-weight and commercial frontier models built in Europe for sovereignty-conscious buyers.",
    businessModel: "API + enterprise licenses.",
    teamCountry: "France",
    teamCity: "Paris",
    teamSize: 200,
    industry: "AI",
    sector: "Foundation Models",
    fundraisingSecured: true,
    fundingStage: "Series B",
    fundingAmountUsd: 600_000_000,
    fundingRoundNote: "European + US strategic",
    website: "https://mistral.ai/",
    social: [
      { platform: "x", handle: "@MistralAI", url: "https://x.com/MistralAI" },
      { platform: "linkedin", handle: "Mistral AI", url: "https://www.linkedin.com/company/mistralai" },
    ],
    strategy: "partner_founders",
    goForwardSummary: "Partner as APAC distributor for sovereign AI deployments.",
    source: "scan:eu-ai",
    tags: ["AI", "France", "open-weight"],
  },
  {
    slug: "deepmind-science",
    name: "Scientific AI Lab",
    description:
      "Research-driven AI applied to science, biology, and complex systems with enterprise partnerships.",
    businessModel: "Strategic partnerships + cloud.",
    teamCountry: "United Kingdom",
    teamCity: "London",
    teamSize: 2000,
    industry: "AI",
    sector: "Research Platforms",
    fundraisingSecured: true,
    fundingStage: "Acquired",
    fundingAmountUsd: 600_000_000,
    fundingRoundNote: "Google DeepMind",
    website: "https://deepmind.google/",
    social: [
      { platform: "x", handle: "@GoogleDeepMind", url: "https://x.com/GoogleDeepMind" },
      {
        platform: "linkedin",
        handle: "Google DeepMind",
        url: "https://www.linkedin.com/company/googledeepmind",
      },
    ],
    strategy: "license_tech",
    goForwardSummary: "License domain models into pharma discovery workflows.",
    source: "scan:uk-ai",
    tags: ["AI", "UK", "science"],
  },
  {
    slug: "personio-hr-eu",
    name: "European HR Cloud",
    description:
      "All-in-one HRIS for European SMEs covering hiring, payroll, and people ops with local compliance.",
    businessModel: "Seat SaaS.",
    teamCountry: "Germany",
    teamCity: "Munich",
    teamSize: 2000,
    industry: "HR Tech",
    sector: "HRIS",
    fundraisingSecured: true,
    fundingStage: "Series E",
    fundingAmountUsd: 722_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://www.personio.com/",
    social: [
      { platform: "linkedin", handle: "Personio", url: "https://www.linkedin.com/company/personio" },
      { platform: "x", handle: "@PersonioHR", url: "https://x.com/PersonioHR" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Localize payroll modules for SEA multi-entity startups.",
    source: "scan:eu-saas",
    tags: ["HR", "Germany", "SMB"],
  },
  {
    slug: "contentful-cms",
    name: "Composable Content Platform",
    description:
      "Headless CMS that lets global brands ship omnichannel content with structured models.",
    businessModel: "Seat + usage SaaS.",
    teamCountry: "Germany",
    teamCity: "Berlin",
    teamSize: 800,
    industry: "MarTech",
    sector: "CMS",
    fundraisingSecured: true,
    fundingStage: "Series F",
    fundingAmountUsd: 338_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://www.contentful.com/",
    social: [
      {
        platform: "linkedin",
        handle: "Contentful",
        url: "https://www.linkedin.com/company/contentful",
      },
      { platform: "x", handle: "@contentful", url: "https://x.com/contentful" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Ship a retail PDP content kit as a vertical SKU.",
    source: "scan:eu-saas",
    tags: ["CMS", "Germany", "content"],
  },
  {
    slug: "celonis-process",
    name: "Process Mining Twin",
    description:
      "Process mining platform that reconstructs how enterprises actually run and finds automation ROI.",
    businessModel: "Enterprise SaaS.",
    teamCountry: "Germany",
    teamCity: "Munich",
    teamSize: 3000,
    industry: "Enterprise Software",
    sector: "Process Intelligence",
    fundraisingSecured: true,
    fundingStage: "Series D",
    fundingAmountUsd: 1_000_000_000,
    fundingRoundNote: "Late-stage private",
    website: "https://www.celonis.com/",
    social: [
      { platform: "linkedin", handle: "Celonis", url: "https://www.linkedin.com/company/celonis" },
      { platform: "x", handle: "@Celonis", url: "https://x.com/Celonis" },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Package process kits for banks' KYC/ops lines.",
    source: "scan:eu-enterprise",
    tags: ["process", "Germany", "enterprise"],
  },
  {
    slug: "ui-path-rpa",
    name: "Automation Fabric",
    description:
      "Robotic process automation and AI agents that take repetitive desktop and API work off human queues.",
    businessModel: "Enterprise licenses.",
    teamCountry: "United States",
    teamCity: "New York",
    teamSize: 4000,
    industry: "Enterprise Software",
    sector: "Automation",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 2_000_000_000,
    fundingRoundNote: "Public company",
    website: "https://www.uipath.com/",
    social: [
      { platform: "linkedin", handle: "UiPath", url: "https://www.linkedin.com/company/uipath" },
      { platform: "x", handle: "@UiPath", url: "https://x.com/UiPath" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Ship healthcare claims automation packs as vertical products.",
    source: "scan:us-enterprise",
    tags: ["RPA", "US", "automation"],
  },
  {
    slug: "hashicorp-infra",
    name: "Infrastructure as Code OS",
    description:
      "Terraform and secrets tooling that standardizes cloud provisioning for platform engineering teams.",
    businessModel: "Open core + enterprise.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 2000,
    industry: "DevTools",
    sector: "Infrastructure",
    fundraisingSecured: true,
    fundingStage: "Acquired",
    fundingAmountUsd: 350_000_000,
    fundingRoundNote: "IBM acquisition path",
    website: "https://www.hashicorp.com/",
    social: [
      { platform: "x", handle: "@HashiCorp", url: "https://x.com/HashiCorp" },
      {
        platform: "linkedin",
        handle: "HashiCorp",
        url: "https://www.linkedin.com/company/hashicorp",
      },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Offer managed Terraform Cloud pods to regional MSPs.",
    source: "scan:us-devtools",
    tags: ["infra", "US", "devops"],
  },
  {
    slug: "gitlab-devops",
    name: "Single DevOps Platform",
    description:
      "End-to-end DevSecOps platform from plan to deploy with integrated security scanning.",
    businessModel: "Seat SaaS.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 2000,
    industry: "DevTools",
    sector: "DevSecOps",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 426_000_000,
    fundingRoundNote: "Public company",
    website: "https://about.gitlab.com/",
    social: [
      { platform: "x", handle: "@gitlab", url: "https://x.com/gitlab" },
      { platform: "linkedin", handle: "GitLab", url: "https://www.linkedin.com/company/gitlab-com" },
    ],
    strategy: "partner_founders",
    goForwardSummary: "Partner as regulated-industry GitLab reseller with compliance packs.",
    source: "scan:us-devtools",
    tags: ["devops", "US", "security"],
  },
  {
    slug: "sentry-observability",
    name: "Application Error Radar",
    description:
      "Developer observability that catches production errors and performance regressions before users churn.",
    businessModel: "Usage SaaS.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 800,
    industry: "DevTools",
    sector: "Observability",
    fundraisingSecured: true,
    fundingStage: "Series E",
    fundingAmountUsd: 217_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://sentry.io/",
    social: [
      { platform: "x", handle: "@getsentry", url: "https://x.com/getsentry" },
      { platform: "linkedin", handle: "Sentry", url: "https://www.linkedin.com/company/getsentry" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Ship mobile-game crash packs as a vertical SKU.",
    source: "scan:us-devtools",
    tags: ["observability", "US", "developers"],
  },
  {
    slug: "vercel-frontend",
    name: "Frontend Cloud",
    description:
      "Deploy platform for Next.js and modern frontends with edge networks and preview workflows.",
    businessModel: "Usage + seats.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 600,
    industry: "DevTools",
    sector: "Frontend Cloud",
    fundraisingSecured: true,
    fundingStage: "Series E",
    fundingAmountUsd: 563_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://vercel.com/",
    social: [
      { platform: "x", handle: "@vercel", url: "https://x.com/vercel" },
      { platform: "linkedin", handle: "Vercel", url: "https://www.linkedin.com/company/vercel" },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Sell enterprise frontend platforms to agencies as white-label hosting.",
    source: "scan:us-devtools",
    tags: ["frontend", "US", "cloud"],
  },
  {
    slug: "supabase-backend",
    name: "Open Backend Cloud",
    description:
      "Postgres-backed backend-as-a-service with auth, storage, and realtime for indie and startup builders.",
    businessModel: "Usage SaaS.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 100,
    industry: "DevTools",
    sector: "Backend Platforms",
    fundraisingSecured: true,
    fundingStage: "Series C",
    fundingAmountUsd: 116_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://supabase.com/",
    social: [
      { platform: "x", handle: "@supabase", url: "https://x.com/supabase" },
      { platform: "linkedin", handle: "Supabase", url: "https://www.linkedin.com/company/supabase" },
    ],
    strategy: "partner_founders",
    goForwardSummary: "Partner as regional managed Supabase host for regulated data residency.",
    source: "scan:us-devtools",
    tags: ["backend", "US", "postgres"],
  },
  {
    slug: "pleo-spend",
    name: "Smart Company Cards",
    description:
      "Corporate cards and spend management for European SMEs with automated bookkeeping sync.",
    businessModel: "Interchange + SaaS.",
    teamCountry: "Denmark",
    teamCity: "Copenhagen",
    teamSize: 800,
    industry: "FinTech",
    sector: "Spend Management",
    fundraisingSecured: true,
    fundingStage: "Series C",
    fundingAmountUsd: 428_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://www.pleo.io/",
    social: [
      { platform: "linkedin", handle: "Pleo", url: "https://www.linkedin.com/company/pleo" },
      { platform: "x", handle: "@pleo_io", url: "https://x.com/pleo_io" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Localize spend cards for Singapore/HK multi-entity startups.",
    source: "scan:nordic-fintech",
    tags: ["spend", "Denmark", "SMB"],
  },
  {
    slug: "hopin-events",
    name: "Virtual Event Stage",
    description:
      "Event platform for hybrid conferences with stages, expo halls, and networking rooms.",
    businessModel: "Event SaaS fees.",
    teamCountry: "United Kingdom",
    teamCity: "London",
    teamSize: 200,
    industry: "MarTech",
    sector: "Events",
    fundraisingSecured: true,
    fundingStage: "Series C",
    fundingAmountUsd: 1_000_000_000,
    fundingRoundNote: "Peak private valuation era",
    website: "https://ringcentral.com/events/",
    social: [
      {
        platform: "linkedin",
        handle: "RingCentral Events",
        url: "https://www.linkedin.com/company/ringcentral",
      },
      { platform: "x", handle: "@RingCentral", url: "https://x.com/RingCentral" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Spin investor-day event kits for IR teams.",
    source: "scan:uk-saas",
    tags: ["events", "UK", "hybrid"],
  },
  {
    slug: "checkout-com",
    name: "Global Acquiring Cloud",
    description:
      "Enterprise payment processing for platforms and marketplaces needing global acquiring coverage.",
    businessModel: "Payment fees.",
    teamCountry: "United Kingdom",
    teamCity: "London",
    teamSize: 2000,
    industry: "FinTech",
    sector: "Payments",
    fundraisingSecured: true,
    fundingStage: "Late stage",
    fundingAmountUsd: 1_800_000_000,
    fundingRoundNote: "SoftBank + others",
    website: "https://www.checkout.com/",
    social: [
      { platform: "linkedin", handle: "Checkout.com", url: "https://www.linkedin.com/company/checkout" },
      { platform: "x", handle: "@checkout", url: "https://x.com/checkout" },
    ],
    strategy: "partner_founders",
    goForwardSummary: "Partner as LatAm acquiring specialist under Checkout rails.",
    source: "scan:uk-fintech",
    tags: ["payments", "UK", "enterprise"],
  },
  {
    slug: "adyen-acquiring",
    name: "Unified Commerce Acquiring",
    description:
      "Single platform for online, in-person, and unified commerce payments used by global retailers.",
    businessModel: "Payment fees.",
    teamCountry: "Netherlands",
    teamCity: "Amsterdam",
    teamSize: 4000,
    industry: "FinTech",
    sector: "Payments",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 266_000_000,
    fundingRoundNote: "Public company",
    website: "https://www.adyen.com/",
    social: [
      { platform: "linkedin", handle: "Adyen", url: "https://www.linkedin.com/company/adyen" },
      { platform: "x", handle: "@Adyen", url: "https://x.com/Adyen" },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Package unified-commerce kits for regional retail conglomerates.",
    source: "scan:eu-fintech",
    tags: ["payments", "Netherlands", "retail"],
  },
  {
    slug: "bolt-estonia",
    name: "European Mobility Network",
    description:
      "Ride-hailing and micromobility with food delivery expansion across Europe and Africa.",
    businessModel: "Take-rate.",
    teamCountry: "Estonia",
    teamCity: "Tallinn",
    teamSize: 5000,
    industry: "Mobility",
    sector: "Ride-hailing",
    fundraisingSecured: true,
    fundingStage: "Series F",
    fundingAmountUsd: 1_900_000_000,
    fundingRoundNote: "Late-stage private",
    website: "https://bolt.eu/",
    social: [
      { platform: "x", handle: "@Bolt", url: "https://x.com/Bolt" },
      { platform: "linkedin", handle: "Bolt", url: "https://www.linkedin.com/company/bolteu" },
    ],
    strategy: "franchise_local",
    goForwardSummary: "Franchise city fleets in secondary African metros.",
    source: "scan:eu-mobility",
    tags: ["mobility", "Estonia", "rides"],
  },
  {
    slug: "wolt-delivery",
    name: "Nordic Delivery Graph",
    description:
      "Food and retail delivery platform with strong Nordic and CEE city density, now under DoorDash.",
    businessModel: "Delivery fees + ads.",
    teamCountry: "Finland",
    teamCity: "Helsinki",
    teamSize: 7000,
    industry: "Mobility",
    sector: "Food Delivery",
    fundraisingSecured: true,
    fundingStage: "Acquired",
    fundingAmountUsd: 850_000_000,
    fundingRoundNote: "DoorDash acquisition",
    website: "https://wolt.com/",
    social: [
      { platform: "instagram", handle: "@woltapp", url: "https://www.instagram.com/woltapp/" },
      { platform: "linkedin", handle: "Wolt", url: "https://www.linkedin.com/company/wolt-oy" },
    ],
    strategy: "franchise_local",
    goForwardSummary: "Franchise dark-store pods for grocery in secondary cities.",
    source: "scan:nordic-consumer",
    tags: ["delivery", "Finland", "food"],
  },
  {
    slug: "swan-banking-as-a-service",
    name: "Embedded Banking Rails",
    description:
      "Banking-as-a-service APIs letting European fintechs and platforms embed accounts and cards.",
    businessModel: "BaaS fees + interchange share.",
    teamCountry: "France",
    teamCity: "Paris",
    teamSize: 300,
    industry: "FinTech",
    sector: "Banking-as-a-Service",
    fundraisingSecured: true,
    fundingStage: "Series B",
    fundingAmountUsd: 100_000_000,
    fundingRoundNote: "European fintech funds",
    website: "https://www.swan.io/",
    social: [
      { platform: "linkedin", handle: "Swan", url: "https://www.linkedin.com/company/swan-io" },
      { platform: "x", handle: "@swan_io", url: "https://x.com/swan_io" },
    ],
    strategy: "partner_founders",
    goForwardSummary: "Partner as vertical BaaS integrator for payroll platforms.",
    source: "scan:eu-fintech",
    tags: ["BaaS", "France", "embedded"],
  },
  {
    slug: "qonto-sme-bank",
    name: "SME Neo Bank Europe",
    description:
      "Business accounts, cards, and bookkeeping for European freelancers and SMEs.",
    businessModel: "Subscription + interchange.",
    teamCountry: "France",
    teamCity: "Paris",
    teamSize: 1600,
    industry: "FinTech",
    sector: "Business Banking",
    fundraisingSecured: true,
    fundingStage: "Series D",
    fundingAmountUsd: 622_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://qonto.com/",
    social: [
      { platform: "linkedin", handle: "Qonto", url: "https://www.linkedin.com/company/qonto" },
      { platform: "x", handle: "@qonto_en", url: "https://x.com/qonto_en" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Localize SME banking UX for Singapore/HK freelancers.",
    source: "scan:eu-fintech",
    tags: ["neobank", "France", "SME"],
  },
  {
    slug: "alan-health",
    name: "Digital Health Insurer",
    description:
      "Mobile-first health insurance and care navigation for European employees and freelancers.",
    businessModel: "Insurance premiums + care services.",
    teamCountry: "France",
    teamCity: "Paris",
    teamSize: 1000,
    industry: "Health Tech",
    sector: "InsurTech",
    fundraisingSecured: true,
    fundingStage: "Series F",
    fundingAmountUsd: 483_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://alan.com/",
    social: [
      { platform: "linkedin", handle: "Alan", url: "https://www.linkedin.com/company/alan-eu" },
      { platform: "x", handle: "@AlanAssurance", url: "https://x.com/AlanAssurance" },
    ],
    strategy: "franchise_local",
    goForwardSummary: "Franchise care navigation pods in secondary EU cities.",
    source: "scan:eu-health",
    tags: ["health", "France", "insurance"],
  },
  {
    slug: "doctors-without-wait",
    name: "Async Primary Care",
    description:
      "App-based primary care and mental health visits that reduce clinic wait times for urban professionals.",
    businessModel: "Subscription + visit fees.",
    teamCountry: "United States",
    teamCity: "New York",
    teamSize: 500,
    industry: "Health Tech",
    sector: "Telehealth",
    fundraisingSecured: true,
    fundingStage: "Series D",
    fundingAmountUsd: 500_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://www.teladoc.com/",
    social: [
      { platform: "linkedin", handle: "Teladoc Health", url: "https://www.linkedin.com/company/teladochealth" },
      { platform: "x", handle: "@TeladocHealth", url: "https://x.com/TeladocHealth" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Localize async care for Japan/Korea private hospital groups.",
    source: "scan:us-health",
    tags: ["telehealth", "US", "care"],
  },
  {
    slug: "cognition-devin",
    name: "Autonomous Software Agent",
    description:
      "AI software engineer agents that take tickets from backlog to pull request for product teams.",
    businessModel: "Seat + usage enterprise.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 50,
    industry: "AI",
    sector: "Developer Agents",
    fundraisingSecured: true,
    fundingStage: "Series B",
    fundingAmountUsd: 175_000_000,
    fundingRoundNote: "Founders Fund + others",
    website: "https://www.cognition.ai/",
    social: [
      { platform: "x", handle: "@cognition_labs", url: "https://x.com/cognition_labs" },
      {
        platform: "linkedin",
        handle: "Cognition",
        url: "https://www.linkedin.com/company/cognition-ai",
      },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Sell agents to IT services firms as delivery multipliers.",
    source: "scan:us-ai",
    tags: ["AI", "agents", "US"],
  },
  {
    slug: "runway-ml-video",
    name: "Generative Video Studio",
    description:
      "AI video generation and editing tools used by creators and studios for rapid content iteration.",
    businessModel: "Credits SaaS.",
    teamCountry: "United States",
    teamCity: "New York",
    teamSize: 200,
    industry: "AI",
    sector: "Generative Media",
    fundraisingSecured: true,
    fundingStage: "Series D",
    fundingAmountUsd: 237_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://runwayml.com/",
    social: [
      { platform: "x", handle: "@runwayml", url: "https://x.com/runwayml" },
      { platform: "instagram", handle: "@runwayml", url: "https://www.instagram.com/runwayml/" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Spin ad-only video packs for performance agencies.",
    source: "scan:us-ai",
    tags: ["AI", "video", "US"],
  },
  {
    slug: "elevenlabs-voice",
    name: "Voice Synthesis Studio",
    description:
      "High-fidelity AI voice generation and dubbing for creators, games, and localization teams.",
    businessModel: "Credits SaaS + enterprise.",
    teamCountry: "United States",
    teamCity: "New York",
    teamSize: 200,
    industry: "AI",
    sector: "Voice AI",
    fundraisingSecured: true,
    fundingStage: "Series C",
    fundingAmountUsd: 180_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://elevenlabs.io/",
    social: [
      { platform: "x", handle: "@elevenlabsio", url: "https://x.com/elevenlabsio" },
      {
        platform: "linkedin",
        handle: "ElevenLabs",
        url: "https://www.linkedin.com/company/elevenlabsio",
      },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Build Asian language voice packs with local studio partners.",
    source: "scan:us-ai",
    tags: ["AI", "voice", "US"],
  },
  {
    slug: "perplexity-answer",
    name: "Answer Engine",
    description:
      "Cited answer engine that combines search and generative AI for research and decision workflows.",
    businessModel: "Subscriptions + enterprise.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 200,
    industry: "AI",
    sector: "Search",
    fundraisingSecured: true,
    fundingStage: "Series B",
    fundingAmountUsd: 165_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://www.perplexity.ai/",
    social: [
      { platform: "x", handle: "@perplexity_ai", url: "https://x.com/perplexity_ai" },
      {
        platform: "linkedin",
        handle: "Perplexity",
        url: "https://www.linkedin.com/company/perplexity-ai",
      },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Sell research desks to consulting firms as private answer engines.",
    source: "scan:us-ai",
    tags: ["AI", "search", "US"],
  },
  {
    slug: "cursor-coding",
    name: "AI Pair Programming IDE",
    description:
      "Code editor built around AI pair programming for professional software teams shipping faster.",
    businessModel: "Seat subscriptions.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 100,
    industry: "DevTools",
    sector: "AI Coding",
    fundraisingSecured: true,
    fundingStage: "Series B",
    fundingAmountUsd: 105_000_000,
    fundingRoundNote: "a16z + others",
    website: "https://cursor.com/",
    social: [
      { platform: "x", handle: "@cursor_ai", url: "https://x.com/cursor_ai" },
      {
        platform: "linkedin",
        handle: "Anysphere",
        url: "https://www.linkedin.com/company/anysphere",
      },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Sell org-wide IDE seats via SI partners to enterprises.",
    source: "scan:us-devtools",
    tags: ["AI", "IDE", "US"],
  },
  {
    slug: "loom-async-video",
    name: "Async Video Messaging",
    description:
      "Lightweight screen-and-cam recording for async updates that replace status meetings.",
    businessModel: "Seat SaaS.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 400,
    industry: "Productivity",
    sector: "Async Collaboration",
    fundraisingSecured: true,
    fundingStage: "Acquired",
    fundingAmountUsd: 203_000_000,
    fundingRoundNote: "Atlassian acquisition",
    website: "https://www.loom.com/",
    social: [
      { platform: "x", handle: "@loom", url: "https://x.com/loom" },
      { platform: "linkedin", handle: "Loom", url: "https://www.linkedin.com/company/useloom" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Spin customer-success update packs for SaaS CS teams.",
    source: "scan:us-saas",
    tags: ["video", "US", "async"],
  },
  {
    slug: "miro-whiteboard",
    name: "Infinite Team Canvas",
    description:
      "Online whiteboard for workshops, product discovery, and distributed team facilitation.",
    businessModel: "Seat SaaS.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 1800,
    industry: "Productivity",
    sector: "Collaboration",
    fundraisingSecured: true,
    fundingStage: "Series C",
    fundingAmountUsd: 476_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://miro.com/",
    social: [
      { platform: "x", handle: "@MiroHQ", url: "https://x.com/MiroHQ" },
      { platform: "linkedin", handle: "Miro", url: "https://www.linkedin.com/company/mirohq" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Ship consulting workshop kits as vertical templates.",
    source: "scan:us-saas",
    tags: ["collaboration", "US", "whiteboard"],
  },
  {
    slug: "webflow-sites",
    name: "Visual Web Studio",
    description:
      "Visual development platform for marketing sites and web apps without traditional CMS bottlenecks.",
    businessModel: "Seat + hosting SaaS.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 700,
    industry: "MarTech",
    sector: "Website Builders",
    fundraisingSecured: true,
    fundingStage: "Series C",
    fundingAmountUsd: 335_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://webflow.com/",
    social: [
      { platform: "x", handle: "@webflow", url: "https://x.com/webflow" },
      { platform: "linkedin", handle: "Webflow", url: "https://www.linkedin.com/company/webflow-inc-" },
    ],
    strategy: "franchise_local",
    goForwardSummary: "Franchise Webflow agencies in secondary Asian markets.",
    source: "scan:us-martech",
    tags: ["web", "US", "nocode"],
  },
  {
    slug: "intercom-support",
    name: "Fin Support OS",
    description:
      "Customer support platform blending inbox, help center, and AI agents for product companies.",
    businessModel: "Seat SaaS + AI usage.",
    teamCountry: "United States",
    teamCity: "San Francisco",
    teamSize: 1000,
    industry: "SaaS",
    sector: "Customer Support",
    fundraisingSecured: true,
    fundingStage: "Series D",
    fundingAmountUsd: 240_000_000,
    fundingRoundNote: "Growth equity",
    website: "https://www.intercom.com/",
    social: [
      { platform: "x", handle: "@intercom", url: "https://x.com/intercom" },
      { platform: "linkedin", handle: "Intercom", url: "https://www.linkedin.com/company/intercom" },
    ],
    strategy: "vertical_spinout",
    goForwardSummary: "Spin fintech support agents trained on card/dispute workflows.",
    source: "scan:us-saas",
    tags: ["support", "US", "AI"],
  },
  {
    slug: "hubspot-crm",
    name: "Inbound Growth CRM",
    description:
      "CRM plus marketing, sales, and service hubs for SMBs scaling inbound go-to-market.",
    businessModel: "Seat SaaS.",
    teamCountry: "United States",
    teamCity: "Boston",
    teamSize: 7000,
    industry: "SaaS",
    sector: "CRM",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 100_000_000,
    fundingRoundNote: "Public company",
    website: "https://www.hubspot.com/",
    social: [
      { platform: "x", handle: "@HubSpot", url: "https://x.com/HubSpot" },
      { platform: "linkedin", handle: "HubSpot", url: "https://www.linkedin.com/company/hubspot" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Localize CRM playbooks for SEA SMB agencies.",
    source: "scan:us-saas",
    tags: ["CRM", "US", "SMB"],
  },
  {
    slug: "atlassian-work",
    name: "Software Team OS",
    description:
      "Jira, Confluence, and related tools that organize software delivery for enterprises worldwide.",
    businessModel: "Seat SaaS.",
    teamCountry: "Australia",
    teamCity: "Sydney",
    teamSize: 10000,
    industry: "Enterprise Software",
    sector: "Work Management",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 210_000_000,
    fundingRoundNote: "Public company",
    website: "https://www.atlassian.com/",
    social: [
      { platform: "x", handle: "@Atlassian", url: "https://x.com/Atlassian" },
      {
        platform: "linkedin",
        handle: "Atlassian",
        url: "https://www.linkedin.com/company/atlassian",
      },
    ],
    strategy: "b2b_pivot",
    goForwardSummary: "Package ITSM starter kits for mid-market via partners.",
    source: "scan:oceania-saas",
    tags: ["enterprise", "Australia", "devops"],
  },
  {
    slug: "xero-accounting",
    name: "Cloud Ledger for SMEs",
    description:
      "Online accounting for small businesses with bank feeds, invoicing, and accountant ecosystems.",
    businessModel: "Subscription SaaS.",
    teamCountry: "New Zealand",
    teamCity: "Wellington",
    teamSize: 4000,
    industry: "FinTech",
    sector: "Accounting",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 150_000_000,
    fundingRoundNote: "Public company",
    website: "https://www.xero.com/",
    social: [
      { platform: "x", handle: "@Xero", url: "https://x.com/Xero" },
      { platform: "linkedin", handle: "Xero", url: "https://www.linkedin.com/company/xero" },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Localize GST/VAT packs for SEA SMEs with accounting partners.",
    source: "scan:oceania-fintech",
    tags: ["accounting", "New Zealand", "SMB"],
  },
  {
    slug: "canva-affinity",
    name: "Bootstrapped Design Unicorn Path",
    description:
      "Template-led creative platform path that many regional design tools still emulate for SMB GTM.",
    businessModel: "Freemium SaaS.",
    teamCountry: "Australia",
    teamCity: "Sydney",
    teamSize: 50,
    industry: "MarTech",
    sector: "Creative Tools",
    fundraisingSecured: false,
    fundingStage: "Seed",
    fundingRoundNote: "Open seed for regional clone",
    website: "https://www.canva.com/about/",
    social: [
      { platform: "x", handle: "@canva", url: "https://x.com/canva" },
      { platform: "linkedin", handle: "Canva", url: "https://www.linkedin.com/company/canva" },
    ],
    strategy: "franchise_local",
    goForwardSummary: "Franchise vernacular template studios in secondary markets.",
    source: "scan:oceania-saas",
    tags: ["design", "Australia", "clone-path"],
  },
  {
    slug: "freshworks-crm",
    name: "Affordable CX Suite",
    description:
      "CRM and support suite aimed at mid-market teams that want Salesforce power without Salesforce complexity.",
    businessModel: "Seat SaaS.",
    teamCountry: "United States",
    teamCity: "San Mateo",
    teamSize: 5000,
    industry: "SaaS",
    sector: "CRM",
    fundraisingSecured: true,
    fundingStage: "Public",
    fundingAmountUsd: 409_000_000,
    fundingRoundNote: "Public company",
    website: "https://www.freshworks.com/",
    social: [
      { platform: "x", handle: "@FreshworksInc", url: "https://x.com/FreshworksInc" },
      {
        platform: "linkedin",
        handle: "Freshworks",
        url: "https://www.linkedin.com/company/freshworks-inc",
      },
    ],
    strategy: "localize_asia",
    goForwardSummary: "Double down India/SEA mid-market packs with local SI partners.",
    source: "scan:us-saas",
    tags: ["CRM", "US", "mid-market"],
  },
  {
    slug: "zoho-suite",
    name: "All-in-One Business Suite",
    description:
      "Broad productivity and ops suite from India spanning CRM, email, and finance for cost-sensitive SMEs.",
    businessModel: "Seat SaaS.",
    teamCountry: "India",
    teamCity: "Chennai",
    teamSize: 15000,
    industry: "SaaS",
    sector: "Business Suites",
    fundraisingSecured: false,
    fundingStage: "Bootstrapped",
    fundingRoundNote: "Profit-funded growth",
    website: "https://www.zoho.com/",
    social: [
      { platform: "x", handle: "@zoho", url: "https://x.com/zoho" },
      { platform: "linkedin", handle: "Zoho", url: "https://www.linkedin.com/company/zoho-corporation" },
    ],    strategy: "franchise_local",
    goForwardSummary: "Franchise localized implementation shops for Zoho suites in secondary cities.",
    source: "scan:india-saas",
    tags: ["suite", "India", "SMB"],
  },
];

export const EXPANDED_IDEAS: StartupIdea[] = DRAFTS.map(draftToIdea);

export function allScanIdeas(featured: StartupIdea[]): StartupIdea[] {
  const seen = new Set(featured.map((i) => i.slug));
  return [...featured, ...EXPANDED_IDEAS.filter((i) => !seen.has(i.slug))];
}
