/** Map display country names → ISO 3166-1 alpha-2 codes for flag images. */
const COUNTRY_TO_ISO: Record<string, string> = {
  "United States": "us",
  "United Kingdom": "gb",
  Singapore: "sg",
  Germany: "de",
  India: "in",
  Japan: "jp",
  Brazil: "br",
  Canada: "ca",
  France: "fr",
  Nigeria: "ng",
  "South Korea": "kr",
  Australia: "au",
  "New Zealand": "nz",
  Israel: "il",
  Sweden: "se",
  Denmark: "dk",
  Finland: "fi",
  Norway: "no",
  Iceland: "is",
  Indonesia: "id",
  China: "cn",
  "Hong Kong": "hk",
  Taiwan: "tw",
  Netherlands: "nl",
  Kenya: "ke",
  Mexico: "mx",
  UAE: "ae",
  "United Arab Emirates": "ae",
  Spain: "es",
  Italy: "it",
  Portugal: "pt",
  Poland: "pl",
  Belgium: "be",
  Switzerland: "ch",
  Austria: "at",
  Morocco: "ma",
  Senegal: "sn",
  "South Africa": "za",
  Egypt: "eg",
  Ghana: "gh",
  Rwanda: "rw",
  "Saudi Arabia": "sa",
  Jordan: "jo",
  Lebanon: "lb",
  Colombia: "co",
  Chile: "cl",
  Argentina: "ar",
  Peru: "pe",
  Uruguay: "uy",
  Turkey: "tr",
  Romania: "ro",
  Bulgaria: "bg",
  Greece: "gr",
  Vietnam: "vn",
  Thailand: "th",
  Malaysia: "my",
  Philippines: "ph",
};

export function countryToFlagCode(country: string): string | null {
  return COUNTRY_TO_ISO[country] ?? null;
}
