function term(zh, hi, es, fr, ar, bn, pt) {
  return { zh, hi, es, fr, ar, bn, pt };
}

/** Longer keys first. Keys are lowercase prefixes of catalog genre strings. */
export const GENRE_PHRASES = [
  { key: "musical work/composition", ...term("音乐作品", "संगीत रचना", "obra musical", "œuvre musicale", "عمل موسيقي", "সঙ্গীত রচনা", "obra musical") },
  { key: "music track with vocals", ...term("人声曲目", "गायन ट्रैक", "pista con voz", "piste chantée", "مقطع بغناء", "কণ্ঠস্বরের ট্র্যাক", "faixa com vocais") },
  { key: "electronic dance music", ...term("电子舞曲", "इलेक्ट्रॉनिक डांस", "música dance electrónica", "musique dance électronique", "موسيقى رقص إلكترونية", "ইলেকট্রনিক ড্যান্স", "dance eletrônica") },
  { key: "contemporary folk music", ...term("当代民谣", "समकालीन लोक", "folk contemporáneo", "folk contemporain", "فولك معاصر", "সমসাময়িক লোক", "folk contemporâneo") },
  { key: "middle of the road", ...term("大众流行", "मध्य-मार्ग", "estilo comercial", "variété grand public", "أسلوب جماهيري", "মধ্যম ধারা", "estilo comercial") },
  { key: "rhythm and blues", ...term("节奏布鲁斯", "रिदम एंड ब्लूज़", "rhythm and blues", "rhythm and blues", "ريذم أند بلوز", "রিদম অ্যান্ড ব্লুজ", "rhythm and blues") },
  { key: "singer-songwriter", ...term("唱作人", "गायक-गीतकार", "cantautor", "auteur-compositeur-interprète", "مغنٍّ مؤلف", "গায়ক-গীতিকার", "cantautor") },
  { key: "essential recording", ...term("重要录音", "महत्वपूर्ण रिकॉर्डिंग", "grabación esencial", "enregistrement essentiel", "تسجيل أساسي", "গুরুত্বপূর্ণ রেকর্ডিং", "gravação essencial") },
  { key: "traditional heavy metal", ...term("传统重金属", "पारंपरिक हेवी मेटल", "heavy metal tradicional", "heavy metal traditionnel", "هيفي ميتال تقليدي", "ঐতিহ্যবাহী হেভি মেটাল", "heavy metal tradicional") },
  { key: "brazilian", ...term("巴西音乐", "ब्राज़ीली संगीत", "música brasileña", "musique brésilienne", "موسيقى برازيلية", "ব্রাজিলীয় সঙ্গীত", "música brasileira") },
  { key: "worldwide", ...term("世界音乐", "विश्व संगीत", "música del mundo", "musiques du monde", "موسيقى العالم", "বিশ্ব সঙ্গীত", "música do mundo") },
  { key: "holiday", ...term("节日音乐", "त्योहार संगीत", "música festiva", "musique de fête", "موسيقى احتفالية", "উৎসবের সঙ্গীত", "música festiva") },
  { key: "contemporary r&b", ...term("当代R&B", "समकालीन R&B", "R&B contemporáneo", "R&B contemporain", "آر أند بي معاصر", "সমসাময়িক R&B", "R&B contemporâneo") },
  { key: "east coast hip-hop", ...term("东海岸嘻哈", "ईस्ट कोस्ट हिप-हॉप", "hip-hop de la costa este", "hip-hop East Coast", "هيب هوب الساحل الشرقي", "ইস্ট কোস্ট হিপ-হপ", "hip-hop da costa leste") },
  { key: "west coast hip-hop", ...term("西海岸嘻哈", "वेस्ट कोस्ट हिप-हॉप", "hip-hop de la costa oeste", "hip-hop West Coast", "هيب هوب الساحل الغربي", "ওয়েস্ট কোস্ট হিপ-হপ", "hip-hop da costa oeste") },
  { key: "hardcore hip-hop", ...term("硬核嘻哈", "हार्डकोर हिप-हॉप", "hip-hop hardcore", "hip-hop hardcore", "هيب هوب هاردكور", "হার্ডকোর হিপ-হপ", "hip-hop hardcore") },
  { key: "alternative hip-hop", ...term("另类嘻哈", "वैकल्पिक हिप-हॉप", "hip-hop alternativo", "hip-hop alternatif", "هيب هوب بديل", "বিকল্প হিপ-হপ", "hip-hop alternativo") },
  { key: "political hip-hop", ...term("政治嘻哈", "राजनीतिक हिप-हॉप", "hip-hop político", "hip-hop politique", "هيب هوب سياسي", "রাজনৈতিক হিপ-হপ", "hip-hop político") },
  { key: "comedy hip-hop", ...term("喜剧嘻哈", "कॉमेडी हिप-हॉप", "hip-hop cómico", "hip-hop comique", "هيب هوب كوميدي", "কমেডি হিপ-হপ", "hip-hop cômico") },
  { key: "christian hip-hop", ...term("基督教嘻哈", "ईसाई हिप-हॉप", "hip-hop cristiano", "hip-hop chrétien", "هيب هوب مسيحي", "খ্রিস্টীয় হিপ-হপ", "hip-hop cristão") },
  { key: "french hip-hop", ...term("法语嘻哈", "फ़्रेंच हिप-हॉप", "hip-hop francés", "hip-hop français", "هيب هوب فرنسي", "ফরাসি হিপ-হপ", "hip-hop francês") },
  { key: "hip hop culture", ...term("嘻哈文化", "हिप-हॉप संस्कृति", "cultura hip-hop", "culture hip-hop", "ثقافة الهيب هوب", "হিপ-হপ সংস্কৃতি", "cultura hip-hop") },
  { key: "music of latin america", ...term("拉丁美洲音乐", "लैटिन अमेरिका संगीत", "música de América Latina", "musique d’Amérique latine", "موسيقى أمريكا اللاتينية", "লাতিন আমেরিকার সঙ্গীত", "música da América Latina") },
  { key: "heavy metal music", ...term("重金属", "हेवी मेटल", "heavy metal", "heavy metal", "هيفي ميتال", "হেভি মেটাল", "heavy metal") },
  { key: "new jack swing", ...term("新杰克摇摆", "न्यू जैक स्विंग", "new jack swing", "new jack swing", "نيو جاك سوينغ", "নিউ জ্যাক সুইং", "new jack swing") },
  { key: "blue-eyed soul", ...term("蓝眼灵魂乐", "ब्लू-आइड सोल", "blue-eyed soul", "blue-eyed soul", "سول أزرق العينين", "ব্লু-আইড সোল", "blue-eyed soul") },
  { key: "drum and bass", ...term("鼓打贝斯", "ड्रम एंड बेस", "drum and bass", "drum and bass", "درم آند باس", "ড্রাম অ্যান্ড বেস", "drum and bass") },
  { key: "stage and screen", ...term("舞台与银幕", "मंच और पटल", "escenario y pantalla", "scène et écran", "المسرح والشاشة", "মঞ্চ ও পর্দা", "palco e tela") },
  { key: "urban contemporary", ...term("都市当代", "शहरी समकालीन", "urbano contemporáneo", "urbain contemporain", "حضري معاصر", "শহুরে সমসাময়িক", "urbano contemporâneo") },
  { key: "electronic dance", ...term("电子舞曲", "इलेक्ट्रॉनिक डांस", "dance electrónico", "dance électronique", "رقص إلكتروني", "ইলেকট্রনিক ড্যান্স", "dance eletrônico") },
  { key: "alternative pop", ...term("另类流行", "वैकल्पिक पॉप", "pop alternativo", "pop alternatif", "بوب بديل", "বিকল্প পপ", "pop alternativo") },
  { key: "alternative rock", ...term("另类摇滚", "वैकल्पिक रॉक", "rock alternativo", "rock alternatif", "روك بديل", "বিকল্প রক", "rock alternativo") },
  { key: "alternative r&b", ...term("另类R&B", "वैकल्पिक R&B", "R&B alternativo", "R&B alternatif", "آر أند بي بديل", "বিকল্প R&B", "R&B alternativo") },
  { key: "alternative metal", ...term("另类金属", "वैकल्पिक मेटल", "metal alternativo", "metal alternatif", "ميتال بديل", "বিকল্প মেটাল", "metal alternativo") },
  { key: "alternative dance", ...term("另类舞曲", "वैकल्पिक डांस", "dance alternativo", "dance alternatif", "دانس بديل", "বিকল্প ড্যান্স", "dance alternativo") },
  { key: "electronic music", ...term("电子音乐", "इलेक्ट्रॉनिक संगीत", "música electrónica", "musique électronique", "موسيقى إلكترونية", "ইলেকট্রনিক সঙ্গীত", "música eletrônica") },
  { key: "contemporary folk", ...term("当代民谣", "समकालीन लोक", "folk contemporáneo", "folk contemporain", "فولك معاصر", "সমসাময়িক লোক", "folk contemporâneo") },
  { key: "rock and roll", ...term("摇滚乐", "रॉक एंड रोल", "rock and roll", "rock’n’roll", "روك آند رول", "রক অ্যান্ড রোল", "rock and roll") },
  { key: "hip-hop", ...term("嘻哈", "हिप-हॉप", "hip-hop", "hip-hop", "هيب هوب", "হিপ-হপ", "hip-hop") },
  { key: "hip hop", ...term("嘻哈", "हिप-हॉप", "hip-hop", "hip-hop", "هيب هوب", "হিপ-হপ", "hip-hop") },
  { key: "lo-fi", ...term("低保真", "लो-फाई", "lo-fi", "lo-fi", "لو-فاي", "লো-ফাই", "lo-fi") },
  { key: "doo-wop", ...term("嘟喔普", "डू-वॉप", "doo-wop", "doo-wop", "دو-ووب", "ডু-ওপ", "doo-wop") },
  { key: "pop music", ...term("流行音乐", "पॉप संगीत", "música pop", "musique pop", "موسيقى البوب", "পপ সঙ্গীত", "música pop") },
  { key: "rock music", ...term("摇滚乐", "रॉक संगीत", "música rock", "musique rock", "موسيقى الروك", "রক সঙ্গীত", "música rock") },
  { key: "folk music", ...term("民谣", "लोक संगीत", "música folk", "musique folk", "موسيقى فولك", "লোক সঙ্গীত", "música folk") },
  { key: "soul music", ...term("灵魂乐", "सोल संगीत", "música soul", "musique soul", "موسيقى السول", "সোল সঙ্গীত", "música soul") },
  { key: "dance music", ...term("舞曲", "डांस संगीत", "música dance", "musique dance", "موسيقى الرقص", "ড্যান্স সঙ্গীত", "música dance") },
  { key: "house music", ...term("浩室音乐", "हाउस संगीत", "música house", "musique house", "موسيقى هاوس", "হাউস সঙ্গীত", "música house") },
  { key: "country music", ...term("乡村音乐", "कंट्री संगीत", "música country", "musique country", "موسيقى كانتري", "কান্ট্রি সঙ্গীত", "música country") },
  { key: "latin music", ...term("拉丁音乐", "लैटिन संगीत", "música latina", "musique latine", "موسيقى لاتينية", "লাতিন সঙ্গীত", "música latina") },
  { key: "world music", ...term("世界音乐", "विश्व संगीत", "música del mundo", "musiques du monde", "موسيقى العالم", "বিশ্ব সঙ্গীত", "world music") },
  { key: "gospel music", ...term("福音音乐", "गॉस्पेल", "música gospel", "musique gospel", "موسيقى غوسبل", "গসপেল সঙ্গীত", "música gospel") },
  { key: "ambient music", ...term("氛围音乐", "एम्बिएंट", "música ambient", "musique ambient", "موسيقى أمبينت", "অ্যাম্বিয়েন্ট", "música ambient") },
  { key: "acoustic music", ...term("原声音乐", "अकॉस्टिक", "música acústica", "musique acoustique", "موسيقى صوتية", "অ্যাকোস্টিক", "música acústica") },
  { key: "comedy music", ...term("喜剧音乐", "कॉमेडी संगीत", "música cómica", "musique comique", "موسيقى كوميدية", "কমেডি সঙ্গীত", "música cômica") },
  { key: "novelty music", ...term("新奇音乐", "नॉवेल्टी संगीत", "música novelty", "musique novelty", "موسيقى طريفة", "নভেলটি সঙ্গীত", "música novelty") },
  { key: "christmas music", ...term("圣诞音乐", "क्रिसमस संगीत", "música navideña", "musique de Noël", "موسيقى الميلاد", "বড়দিনের সঙ্গীত", "música natalina") },
  { key: "tropical music", ...term("热带音乐", "उष्णकटिबंधीय संगीत", "música tropical", "musique tropicale", "موسيقى استوائية", "ক্রান্তীয় সঙ্গীত", "música tropical") },
  { key: "psychedelic music", ...term("迷幻音乐", "साइकेडेलिक संगीत", "música psicodélica", "musique psychédélique", "موسيقى سايكدلية", "সাইকেডেলিক সঙ্গীত", "música psicodélica") },
  { key: "symphonic music", ...term("交响音乐", "सिम्फ़ोनिक संगीत", "música sinfónica", "musique symphonique", "موسيقى سيمفونية", "সিমফনিক সঙ্গীত", "música sinfônica") },
  { key: "soca music", ...term("索卡音乐", "सोका", "música soca", "musique soca", "موسيقى السوكا", "সোকা", "música soca") },
  { key: "dub music", ...term("回响乐", "डब संगीत", "música dub", "musique dub", "موسيقى دب", "ডাব সঙ্গীত", "música dub") },
  { key: "plugg music", ...term("插电说唱", "प्लग संगीत", "música plugg", "musique plugg", "موسيقى بلاغ", "প্লাগ সঙ্গীত", "música plugg") },
  { key: "trap music", ...term("陷阱说唱", "ट्रैप संगीत", "música trap", "musique trap", "موسيقى تراب", "ট্র্যাপ সঙ্গীত", "música trap") },
  { key: "funk carioca", ...term("卡里奥卡放克", "फंक कारियोका", "funk carioca", "funk carioca", "فانك كاريوكا", "ফাঙ্ক কারিওকা", "funk carioca") },
  { key: "gabber metal", ...term("加伯金属", "गैबर मेटल", "gabber metal", "gabber metal", "غابر ميتال", "গ্যাবার মেটাল", "gabber metal") },
  { key: "new rave", ...term("新锐舞", "न्यू रेव", "new rave", "new rave", "نيو ريف", "নিউ রেভ", "new rave") },
  { key: "french electro", ...term("法国电子", "फ़्रेंच इलेक्ट्रो", "electro francés", "électro français", "إلكترو فرنسي", "ফরাসি ইলেকট্রো", "electro francês") },
  { key: "bounce music", ...term("弹跳音乐", "बाउंस संगीत", "música bounce", "musique bounce", "موسيقى باونس", "বাউন্স সঙ্গীত", "música bounce") },
  { key: "surf music", ...term("冲浪音乐", "सर्फ़ संगीत", "música surf", "musique surf", "موسيقى سيرف", "সার্ফ সঙ্গীত", "música surf") },
  { key: "beat music", ...term("节拍音乐", "बीट संगीत", "música beat", "musique beat", "موسيقى بيت", "বিট সঙ্গীত", "música beat") },
  { key: "lo-fi music", ...term("低保真音乐", "लो-फाई संगीत", "música lo-fi", "musique lo-fi", "موسيقى لو-فاي", "লো-ফাই সঙ্গীত", "música lo-fi") },
  { key: "new age music", ...term("新世纪音乐", "न्यू एज संगीत", "música new age", "musique new age", "موسيقى العصر الجديد", "নিউ এজ সঙ্গীত", "música new age") },
  { key: "anime song", ...term("动漫歌曲", "एनिमे गीत", "canción anime", "chanson d’anime", "أغنية أنمي", "অ্যানিমে গান", "canção de anime") },
  { key: "protest song", ...term("抗议歌曲", "विरोध गीत", "canción de protesta", "chanson de protestation", "أغنية احتجاج", "প্রতিবাদী গান", "canção de protesto") },
  { key: "patriotic song", ...term("爱国歌曲", "देशभक्ति गीत", "canción patriótica", "chanson patriotique", "أغنية وطنية", "দেশপ্রেমিক গান", "canção patriótica") },
  { key: "denpa song", ...term("电波歌曲", "देनपा गीत", "canción denpa", "chanson denpa", "أغنية دنبا", "ডেনপা গান", "canção denpa") },
  { key: "torch song", ...term("火炬歌曲", "टॉर्च गीत", "canción torch", "torch song", "أغنية شجية", "টর্চ গান", "canção torch") },
  { key: "national anthem", ...term("国歌", "राष्ट्रगान", "himno nacional", "hymne national", "النشيد الوطني", "জাতীয় সঙ্গীত", "hino nacional") },
  { key: "audio recording", ...term("录音", "ऑडियो रिकॉर्डिंग", "grabación de audio", "enregistrement audio", "تسجيل صوتي", "অডিও রেকর্ডিং", "gravação de áudio") },
  { key: "romantic nationalism", ...term("浪漫民族主义", "रोमांटिक राष्ट्रवाद", "nacionalismo romántico", "nationalisme romantique", "قومية رومانسية", "রোমান্টিক জাতীয়তাবাদ", "nacionalismo romântico") },
  { key: "quiet storm", ...term("静谧风暴", "क्वायट स्टॉर्म", "quiet storm", "quiet storm", "كوايت ستورم", "কোয়ায়েট স্টর্ম", "quiet storm") },
  { key: "brooklyn drill", ...term("布鲁克林钻乐", "ब्रुकलिन ड्रिल", "drill de Brooklyn", "drill de Brooklyn", "دريل بروكلين", "ব্রুকলিন ড্রিল", "drill de Brooklyn") },
  { key: "uk drill", ...term("英国钻乐", "यूके ड्रिल", "drill británico", "drill britannique", "دريل بريطاني", "ইউকে ড্রিল", "drill britânico") },
  { key: "uk funky", ...term("英国放克", "यूके फंकी", "funky británico", "funky britannique", "فانكي بريطاني", "ইউকে ফাঙ্কি", "funky britânico") },
  { key: "uk rap", ...term("英国说唱", "यूके रैप", "rap británico", "rap britannique", "راب بريطاني", "ইউকে র‍্যাপ", "rap britânico") },
  { key: "j-pop", ...term("日本流行", "जे-पॉप", "J-pop", "J-pop", "جي-بوب", "জে-পপ", "J-pop") },
  { key: "k-pop", ...term("韩国流行", "के-पॉप", "K-pop", "K-pop", "كي-بوب", "কে-পপ", "K-pop") },
  { key: "r&b", ...term("R&B", "R&B", "R&B", "R&B", "آر أند بي", "R&B", "R&B") },
].sort((a, b) => b.key.length - a.key.length);

export const GENRE_TERMS = {
  pop: term("流行", "पॉप", "pop", "pop", "بوب", "পপ", "pop"),
  rock: term("摇滚", "रॉक", "rock", "rock", "روك", "রক", "rock"),
  jazz: term("爵士", "जैज़", "jazz", "jazz", "جاز", "জ্যাজ", "jazz"),
  soul: term("灵魂乐", "सोल", "soul", "soul", "سول", "সোল", "soul"),
  funk: term("放克", "फंक", "funk", "funk", "فانك", "ফাঙ্ক", "funk"),
  funky: term("放克", "फंकी", "funky", "funky", "فانكي", "ফাঙ্কি", "funky"),
  rap: term("说唱", "रैप", "rap", "rap", "راب", "র‍্যাপ", "rap"),
  rapping: term("说唱", "रैप", "rap", "rap", "راب", "র‍্যাপ", "rap"),
  metal: term("金属", "मेटल", "metal", "metal", "ميتال", "মেটাল", "metal"),
  punk: term("朋克", "पंक", "punk", "punk", "بانك", "পাঙ্ক", "punk"),
  folk: term("民谣", "लोक", "folk", "folk", "فولك", "লোক", "folk"),
  country: term("乡村", "कंट्री", "country", "country", "كانتري", "কান্ট্রি", "country"),
  blues: term("布鲁斯", "ब्लूज़", "blues", "blues", "بلوز", "ব্লুজ", "blues"),
  dance: term("舞曲", "डांस", "dance", "dance", "رقص", "ড্যান্স", "dance"),
  house: term("浩室", "हाउस", "house", "house", "هاوس", "হাউস", "house"),
  disco: term("迪斯科", "डिस्को", "disco", "disco", "ديسكو", "ডিস্কো", "disco"),
  techno: term("科技舞曲", "टेक्नो", "techno", "techno", "تكنو", "টেকনো", "techno"),
  trance: term("迷幻舞曲", "ट्रान्स", "trance", "trance", "ترانس", "ট্রান্স", "trance"),
  reggae: term("雷鬼", "रेगे", "reggae", "reggae", "ريغي", "রেগে", "reggae"),
  reggaeton: term("雷鬼顿", "रेगेटोन", "reggaetón", "reggaeton", "ريغيتون", "রেগেটন", "reggaeton"),
  ska: term("斯卡", "स्का", "ska", "ska", "سكا", "স্কা", "ska"),
  gospel: term("福音", "गॉस्पेल", "gospel", "gospel", "غوسبل", "গসপেল", "gospel"),
  swing: term("摇摆乐", "स्विंग", "swing", "swing", "سوينغ", "সুইং", "swing"),
  ballad: term("民谣曲", "बैलाड", "balada", "ballade", "بالاد", "ব্যালাড", "balada"),
  indie: term("独立", "इंडी", "indie", "indie", "إندي", "ইন্ডি", "indie"),
  alternative: term("另类", "वैकल्पिक", "alternativo", "alternatif", "بديل", "বিকল্প", "alternativo"),
  electronic: term("电子", "इलेक्ट्रॉनिक", "electrónico", "électronique", "إلكتروني", "ইলেকট্রনিক", "eletrônico"),
  electronica: term("电子乐", "इलेक्ट्रॉनिका", "electrónica", "electronica", "إلكترونيكا", "ইলেকট্রনিকা", "eletrônica"),
  electro: term("电子", "इलेक्ट्रो", "electro", "électro", "إلكترو", "ইলেকট্রো", "electro"),
  electropop: term("电子流行", "इलेक्ट्रोपॉप", "electropop", "electropop", "إلكتروبوب", "ইলেকট্রোপপ", "electropop"),
  synth: term("合成器", "सिंथ", "synth", "synth", "سينث", "সিন্থ", "synth"),
  ambient: term("氛围", "एम्बिएंट", "ambient", "ambient", "أمبينت", "অ্যাম্বিয়েন্ট", "ambient"),
  acoustic: term("原声", "अकॉस्टिक", "acústico", "acoustique", "صوتي", "অ্যাকোস্টিক", "acústico"),
  orchestral: term("管弦", "ऑर्केस्ट्रल", "orquestal", "orchestral", "أوركسترالي", "অর্কেস্ট্রাল", "orquestral"),
  piano: term("钢琴", "पियानो", "piano", "piano", "بيانو", "পিয়ানো", "piano"),
  classical: term("古典", "शास्त्रीय", "clásico", "classique", "كلاسيكي", "ধ্রুপদী", "clássico"),
  progressive: term("前卫", "प्रोग्रेसिव", "progresivo", "progressif", "تقدمي", "প্রগ্রেসিভ", "progressivo"),
  psychedelic: term("迷幻", "साइकेडेलिक", "psicodélico", "psychédélique", "سايكدلي", "সাইকেডেলিক", "psicodélico"),
  industrial: term("工业", "इंडस्ट्रियल", "industrial", "industriel", "صناعي", "ইন্ডাস্ট্রিয়াল", "industrial"),
  gothic: term("哥特", "गॉथिक", "gótico", "gothique", "قوطي", "গথিক", "gótico"),
  glam: term("华丽", "ग्लैम", "glam", "glam", "غلام", "গ্ল্যাম", "glam"),
  grunge: term("油渍", "ग्रंज", "grunge", "grunge", "غرنج", "গ্রাঞ্জ", "grunge"),
  emo: term("情绪核", "इमो", "emo", "emo", "إيمو", "ইমো", "emo"),
  trap: term("陷阱说唱", "ट्रैप", "trap", "trap", "تراب", "ট্র্যাপ", "trap"),
  drill: term("钻乐", "ड्रिल", "drill", "drill", "دريل", "ড্রিল", "drill"),
  garage: term("车库", "गैराज", "garage", "garage", "غراج", "গ্যারেজ", "garage"),
  dubstep: term("回响贝斯", "डबस्टेप", "dubstep", "dubstep", "دبستب", "ডাবস্টেপ", "dubstep"),
  dub: term("回响", "डब", "dub", "dub", "دب", "ডাব", "dub"),
  bass: term("贝斯", "बेस", "bass", "basse", "باس", "বেস", "baixo"),
  beat: term("节拍", "बीट", "beat", "beat", "بيت", "বিট", "beat"),
  wave: term("浪潮", "वेव", "ola", "wave", "موجة", "ওয়েভ", "wave"),
  dream: term("梦幻", "ड्रीम", "dream", "dream", "حلم", "ড্রিম", "dream"),
  dark: term("暗黑", "डार्क", "oscuro", "sombre", "داكن", "ডার্ক", "escuro"),
  soft: term("轻柔", "सॉफ्ट", "suave", "doux", "ناعم", "সফট", "suave"),
  hard: term("硬核", "हार्ड", "duro", "hard", "قاسي", "হার্ড", "hard"),
  hardcore: term("硬核", "हार्डकोर", "hardcore", "hardcore", "هاردكور", "হার্ডকোর", "hardcore"),
  power: term("强力", "पावर", "power", "power", "باور", "পাওয়ার", "power"),
  teen: term("青少年", "टीन", "adolescente", "ado", "مراهق", "টিন", "teen"),
  art: term("艺术", "आर्ट", "arte", "art", "فن", "আর্ট", "arte"),
  baroque: term("巴洛克", "बारोक", "barroco", "baroque", "باروكي", "বারোক", "barroco"),
  chamber: term("室内", "चैंबर", "de cámara", "de chambre", "حجرة", "চেম্বার", "de câmara"),
  sunshine: term("阳光", "सनशाइन", "sunshine", "sunshine", "شمس", "সানশাইন", "sunshine"),
  bedroom: term("卧室", "बेडरूम", "bedroom", "bedroom", "غرفة نوم", "বেডরুম", "quarto"),
  city: term("都市", "सिटी", "city", "city", "مدينة", "সিটি", "city"),
  dancehall: term("舞厅", "डांसहॉल", "dancehall", "dancehall", "دانسهول", "ড্যান্সহল", "dancehall"),
  bubblegum: term("泡泡糖", "बबलगम", "bubblegum", "bubblegum", "بابلغَم", "বাবলগাম", "bubblegum"),
  latin: term("拉丁", "लैटिन", "latino", "latin", "لاتيني", "লাতিন", "latino"),
  french: term("法语", "फ़्रेंच", "francés", "français", "فرنسي", "ফরাসি", "francês"),
  indian: term("印度", "भारतीय", "indio", "indien", "هندي", "ভারতীয়", "indiano"),
  russian: term("俄罗斯", "रूसी", "ruso", "russe", "روسي", "রাশিয়ান", "russo"),
  tropical: term("热带", "उष्णकटिबंधीय", "tropical", "tropical", "استوائي", "ক্রান্তীয়", "tropical"),
  southern: term("南方", "साउदर्न", "sureño", "sudiste", "جنوبي", "সাউদার্ন", "sulista"),
  christian: term("基督教", "ईसाई", "cristiano", "chrétien", "مسيحي", "খ্রিস্টীয়", "cristão"),
  christmas: term("圣诞", "क्रिसमस", "navideño", "de Noël", "ميلادي", "বড়দিন", "natalino"),
  anime: term("动漫", "एनिमे", "anime", "anime", "أنمي", "অ্যানিমে", "anime"),
  soundtrack: term("原声带", "साउंडट्रैक", "banda sonora", "bande originale", "موسيقى تصويرية", "সাউন্ডট্র্যাক", "trilha sonora"),
  musical: term("音乐剧", "संगीत नाटक", "musical", "comédie musicale", "موسيقي", "মিউজিক্যাল", "musical"),
  song: term("歌曲", "गीत", "canción", "chanson", "أغنية", "গান", "canção"),
  chanson: term("香颂", "शांसोन", "chanson", "chanson", "شانسون", "শঁসোঁ", "chanson"),
  single: term("单曲", "सिंगल", "sencillo", "single", "أغنية منفردة", "সিঙ্গেল", "single"),
  music: term("音乐", "संगीत", "música", "musique", "موسيقى", "সঙ্গীত", "música"),
  popular: term("大众", "लोकप्रिय", "popular", "populaire", "شعبي", "জনপ্রিয়", "popular"),
  contemporary: term("当代", "समकालीन", "contemporáneo", "contemporain", "معاصر", "সমসাময়িক", "contemporâneo"),
  traditional: term("传统", "पारंपरिक", "tradicional", "traditionnel", "تقليدي", "ঐতিহ্যবাহী", "tradicional"),
  neo: term("新", "नियो", "neo", "néo", "نيو", "নিও", "neo"),
  nu: term("新", "न्यू", "nu", "nu", "نو", "নু", "nu"),
  post: term("后", "पोस्ट", "post", "post", "ما بعد", "পোস্ট", "pós"),
  future: term("未来", "फ्यूचर", "futuro", "future", "مستقبل", "ফিউচার", "future"),
  deep: term("深", "डीप", "deep", "deep", "عميق", "ডিপ", "deep"),
  leftfield: term("左野", "लेफ्टफ़ील्ड", "leftfield", "leftfield", "ليفتفيلد", "লেফটফিল্ড", "leftfield"),
  microhouse: term("微型浩室", "माइक्रोहाउस", "microhouse", "microhouse", "مايكروهاوس", "মাইক্রোহাউস", "microhouse"),
  hyperpop: term("超流行", "हाइपरपॉप", "hyperpop", "hyperpop", "هايبربوب", "হাইপারপপ", "hyperpop"),
  britpop: term("英伦流行", "ब्रिटपॉप", "britpop", "britpop", "بريتبوب", "ব্রিটপপ", "britpop"),
  europop: term("欧洲流行", "यूरोपॉप", "europop", "europop", "يوروبوب", "ইউরোপপ", "europop"),
  eurodance: term("欧陆舞曲", "यूरोडांस", "eurodance", "eurodance", "يورودانس", "ইউরোড্যান্স", "eurodance"),
  nederpop: term("荷兰流行", "नेडरपॉप", "nederpop", "nederpop", "نيدربوب", "নেডারপপ", "nederpop"),
  futurepop: term("未来流行", "फ्यूचरपॉप", "futurepop", "futurepop", "فيوتشربوب", "ফিউচারপপ", "futurepop"),
  folktronica: term("民谣电子", "फोक्ट्रॉनिका", "folktrónica", "folktronica", "فولكترونيكا", "ফোকট্রনিকা", "folktronica"),
  electroclash: term("电子碰撞", "इलेक्ट्रोक्लैश", "electroclash", "electroclash", "إلكتروكلاش", "ইলেকট্রোক্ল্যাশ", "electroclash"),
  electronicore: term("电子核", "इलेक्ट्रॉनिकोर", "electronicore", "electronicore", "إلكترونيكور", "ইলেকট্রনিকোর", "electronicore"),
  italo: term("意大利", "इटालो", "ítalo", "italo", "إيطالي", "ইতালো", "ítalo"),
  afrobeats: term("非洲节拍", "अफ्रोबीट्स", "afrobeats", "afrobeats", "أفروبيتس", "আফ্রোবিটস", "afrobeats"),
  bhangra: term("邦格拉", "भांगड़ा", "bhangra", "bhangra", "بهانغرا", "ভাংড়া", "bhangra"),
  bachata: term("巴查塔", "बचाटा", "bachata", "bachata", "باتشاتا", "বাচাটা", "bachata"),
  cumbia: term("昆比亚", "कुम्बिया", "cumbia", "cumbia", "كومبيا", "কুম্বিয়া", "cumbia"),
  mambo: term("曼波", "माम्बो", "mambo", "mambo", "مامبو", "ম্যাম্বো", "mambo"),
  rumba: term("伦巴", "रुम्बा", "rumba", "rumba", "رومبا", "রুম্বা", "rumba"),
  calypso: term("卡利普索", "कैलिप्सो", "calipso", "calypso", "كاليبسو", "ক্যালিপসো", "calipso"),
  flamenco: term("弗拉门戈", "फ्लेमेंको", "flamenco", "flamenco", "فلامنكو", "ফ্ল্যামেনকো", "flamenco"),
  bossa: term("波萨", "बोसा", "bossa", "bossa", "بوسا", "বোসা", "bossa"),
  nova: term("诺瓦", "नोवा", "nova", "nova", "نوفا", "নোভা", "nova"),
  kuduro: term("库杜罗", "कुदुरो", "kuduro", "kuduro", "كودورو", "কুদুরো", "kuduro"),
  plena: term("普莱纳", "प्लेना", "plena", "plena", "بلينا", "প্লেনা", "plena"),
  sertanejo: term("塞尔塔内若", "सर्टानेजो", "sertanejo", "sertanejo", "سيرتانيجو", "সের্তানেজো", "sertanejo"),
  moombahton: term("蒙巴顿", "मूम्बाटन", "moombahton", "moombahton", "مومباهتون", "মুমবাটন", "moombahton"),
  vinahouse: term("越南浩室", "विनाहाउस", "vinahouse", "vinahouse", "فيناهاوس", "ভিনাহাউস", "vinahouse"),
  chiptune: term("芯片音乐", "चिपट्यून", "chiptune", "chiptune", "تشيبتون", "চিপটিউন", "chiptune"),
  gabber: term("加伯", "गैबर", "gabber", "gabber", "غابر", "গ্যাবার", "gabber"),
  hyphy: term("海菲", "हाइफ़ी", "hyphy", "hyphy", "هايفي", "হাইফি", "hyphy"),
  crunk: term("克朗克", "क्रंक", "crunk", "crunk", "كرنك", "ক্রাঙ্ক", "crunk"),
  plugg: term("插电", "प्लग", "plugg", "plugg", "بلاغ", "প্লাগ", "plugg"),
  rage: term("怒火", "रेज", "rage", "rage", "ريج", "রেজ", "rage"),
  rave: term("锐舞", "रेव", "rave", "rave", "ريف", "রেভ", "rave"),
  carioca: term("卡里奥卡", "कारियोका", "carioca", "carioca", "كاريوكا", "কারিওকা", "carioca"),
  cloud: term("云", "क्लाउड", "nube", "cloud", "سحاب", "ক্লাউড", "cloud"),
  gangsta: term("匪帮", "गैंगस्टा", "gangsta", "gangsta", "غانغستا", "গ্যাংস্টা", "gangsta"),
  dirty: term("粗口", "डर्टी", "sucio", "dirty", "فاحش", "ডার্টি", "dirty"),
  comedy: term("喜剧", "कॉमेडी", "cómico", "comique", "كوميدي", "কমেডি", "cômico"),
  novelty: term("新奇", "नॉवेल्टी", "novedad", "novelty", "طريف", "নভেলটি", "novelty"),
  protest: term("抗议", "विरोध", "protesta", "protestation", "احتجاج", "প্রতিবাদ", "protesto"),
  patriotic: term("爱国", "देशभक्ति", "patriótico", "patriotique", "وطني", "দেশপ্রেমিক", "patriótico"),
  political: term("政治", "राजनीतिक", "político", "politique", "سياسي", "রাজনৈতিক", "político"),
  romantic: term("浪漫", "रोमांटिक", "romántico", "romantique", "رومانسي", "রোমান্টিক", "romântico"),
  nationalism: term("民族主义", "राष्ट्रवाद", "nacionalismo", "nationalisme", "قومية", "জাতীয়তাবাদ", "nacionalismo"),
  march: term("进行曲", "मार्च", "marcha", "marche", "مسير", "মার্চ", "marcha"),
  operatic: term("歌剧", "ओपेरा", "operístico", "opératique", "أوبرالي", "অপারেটিক", "operístico"),
  sophisti: term("精致", "सोफिस्टि", "sofisticado", "sophisti", "راقي", "সফিস্টি", "sofisticado"),
  smooth: term("流畅", "स्मूथ", "suave", "lisse", "سلس", "মসৃণ", "suave"),
  jangle: term("铃响", "जैंगल", "jangle", "jangle", "جانغل", "জ্যাঙ্গল", "jangle"),
  acid: term("迷幻酸", "एसिड", "ácido", "acid", "أسيد", "অ্যাসিড", "acid"),
  downtempo: term("慢节奏", "डाउनटेम्पो", "downtempo", "downtempo", "داونتمبو", "ডাউনটেম্পো", "downtempo"),
  trip: term("迷离", "ट्रिप", "trip", "trip", "ترب", "ট্রিপ", "trip"),
  space: term("太空", "स्पेस", "espacial", "space", "فضاء", "স্পেস", "espacial"),
  surf: term("冲浪", "सर्फ़", "surf", "surf", "سيرف", "সার্ফ", "surf"),
  rockabilly: term("乡村摇滚", "रॉकेबिली", "rockabilly", "rockabilly", "روكابيلي", "রকাবিলি", "rockabilly"),
  thrash: term("鞭笞", "थ्रैश", "thrash", "thrash", "ثراش", "থ্র্যাশ", "thrash"),
  groove: term("律动", "ग्रूव", "groove", "groove", "غروف", "গ্রুভ", "groove"),
  bounce: term("弹跳", "बाउंस", "bounce", "bounce", "باونس", "বাউন্স", "bounce"),
  fusion: term("融合", "फ्यूजन", "fusión", "fusion", "فيوجن", "ফিউশন", "fusão"),
  chipmunk: term("花栗鼠", "चिपमंक", "ardilla", "chipmunk", "سنجاب", "চিপমাঙ্ক", "esquilo"),
  jack: term("杰克", "जैक", "jack", "jack", "جاك", "জ্যাক", "jack"),
  new: term("新", "न्यू", "nuevo", "new", "جديد", "নতুন", "novo"),
  big: term("大", "बिग", "big", "big", "كبير", "বিগ", "big"),
  age: term("时代", "एज", "era", "âge", "عصر", "যুগ", "era"),
  coast: term("海岸", "कोस्ट", "costa", "côte", "ساحل", "কোস্ট", "costa"),
  east: term("东", "ईस्ट", "este", "est", "شرق", "পূর্ব", "leste"),
  west: term("西", "वेस्ट", "oeste", "ouest", "غرب", "পশ্চিম", "oeste"),
  uk: term("英国", "यूके", "Reino Unido", "britannique", "بريطاني", "ইউকে", "britânico"),
  america: term("美洲", "अमेरिका", "América", "Amérique", "أمريكا", "আমেরিকা", "América"),
  brooklyn: term("布鲁克林", "ब्रुकलिन", "Brooklyn", "Brooklyn", "بروكلين", "ব্রুকলিন", "Brooklyn"),
  culture: term("文化", "संस्कृति", "cultura", "culture", "ثقافة", "সংস্কৃতি", "cultura"),
  recording: term("录音", "रिकॉर्डिंग", "grabación", "enregistrement", "تسجيل", "রেকর্ডিং", "gravação"),
  play: term("戏剧", "नाटक", "obra", "pièce", "مسرحية", "নাটক", "peça"),
  screen: term("银幕", "पटल", "pantalla", "écran", "شاشة", "পর্দা", "tela"),
  stage: term("舞台", "मंच", "escenario", "scène", "مسرح", "মঞ্চ", "palco"),
  singer: term("歌手", "गायक", "cantante", "chanteur", "مغنٍّ", "গায়ক", "cantor"),
  songwriter: term("词曲作者", "गीतकार", "compositor", "auteur", "مؤلف أغاني", "গীতিকার", "compositor"),
  roll: term("滚", "रोल", "roll", "roll", "رول", "রোল", "roll"),
  eyed: term("眼", "आइड", "eyed", "eyed", "العين", "আইড", "eyed"),
  blue: term("蓝", "ब्लू", "azul", "bleu", "أزرق", "নীল", "azul"),
  storm: term("风暴", "स्टॉर्म", "tormenta", "tempête", "عاصفة", "ঝড়", "tempestade"),
  quiet: term("静谧", "शांत", "tranquilo", "calme", "هادئ", "শান্ত", "quieto"),
  middle: term("中间", "मध्य", "medio", "milieu", "وسط", "মধ্য", "meio"),
  road: term("路", "रोड", "camino", "route", "طريق", "পথ", "estrada"),
  of: term("的", "का", "de", "de", "من", "এর", "de"),
  and: term("与", "और", "y", "et", "و", "এবং", "e"),
  the: term("", "", "", "", "", "", ""),
  edm: term("电子舞曲", "ईडीएम", "EDM", "EDM", "إي دي إم", "ইডিএম", "EDM"),
  g: term("G", "G", "G", "G", "G", "G", "G"),
  j: term("J", "J", "J", "J", "J", "J", "J"),
  k: term("K", "K", "K", "K", "K", "K", "K"),
  lofi: term("低保真", "लोफाई", "lofi", "lofi", "لوفاي", "লোফাই", "lofi"),
  hop: term("哈", "हॉप", "hop", "hop", "هوب", "হপ", "hop"),
  hip: term("嘻", "हिप", "hip", "hip", "هيب", "হিপ", "hip"),
};
