import type { ProductInput } from "./types";

const u = (id: string, extra = "") =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=80${extra}`;

function spark(values: number[]): number[] {
  return values;
}

export const CATALOG_AS_OF = "2026-09-05";

export const products: ProductInput[] = [
  {
    slug: "rack-wardrobe",
    name: "Curtain-front rack wardrobe",
    nameZh: "货架衣柜",
    category: "Home storage",
    summary:
      "Industrial metal clothing rack hidden behind a floor-length curtain. Xiaohongshu’s breakout small-apartment storage system — still rare as a finished kit in North America and Europe.",
    whyNow:
      "Xiaohongshu notes on 货架衣柜 jumped +1,584% in H1 2026. 1688 factories in Foshan and Yiwu are shipping 10w+ units into China’s rental market. Western marketplaces still sell open IKEA-style rails, not the curtain-kit SKU.",
    image: u("photo-1631679706909-1844bbd07221"),
    imageAlt: "Open metal clothing rack in a small apartment",
    tags: ["whitespace", "xiaohongshu", "rental"],
    factory: [
      {
        platform: "1688",
        listingCount: 18600,
        supplierCount: 940,
        verifiedFactories: 310,
        unitPriceUsd: 28.4,
        unitPriceCny: 204,
        moq: 2,
        cluster: "Foshan · Yiwu",
        orders30d: 112000,
        velocityWoW: 22,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%BB%F5%BC%DC%D2%C2%B9%F1",
      },
      {
        platform: "pinduoduo",
        listingCount: 4200,
        supplierCount: 380,
        verifiedFactories: 40,
        unitPriceUsd: 24.9,
        unitPriceCny: 179,
        moq: 1,
        cluster: "Guangzhou",
        orders30d: 64000,
        velocityWoW: 14,
        searchUrl: "https://mobile.yangkeduo.com/",
      },
    ],
    social: [
      {
        platform: "xiaohongshu",
        mentions7d: 18400,
        views7d: 9_200_000,
        engagementRate: 6.4,
        hashtags: ["货架衣柜", "出租屋改造", "适我主义"],
        trend: "rising",
        samplePosts: [
          {
            author: "@微风租房记",
            text: "花了 199 把卧室改成货架衣柜，帘子一拉酒店感，搬家还能带走。",
            likes: 12800,
            time: "2026-09-03",
          },
          {
            author: "@loft_mini",
            text: "不要再买实木衣柜了。金属货架+遮光帘才是 2026 小户型正解。",
            likes: 6400,
            time: "2026-09-01",
          },
        ],
      },
      {
        platform: "tiktok",
        mentions7d: 2100,
        views7d: 4_800_000,
        engagementRate: 3.1,
        hashtags: ["#apartmenthack", "#openwardrobe", "#rentalfriendly"],
        trend: "rising",
        samplePosts: [
          {
            author: "@studio.squareft",
            text: "Chinese rental hack: warehouse rack + linen curtain = closet. No holes in the wall.",
            likes: 91000,
            time: "2026-09-02",
          },
        ],
      },
      {
        platform: "instagram",
        mentions7d: 860,
        views7d: 1_100_000,
        engagementRate: 2.4,
        hashtags: ["#smallspace", "#wardrobestyling"],
        trend: "rising",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "open rack wardrobe curtain",
      related: ["metal garment rack with cover", "rental closet no drill", "industrial wardrobe kit"],
      globalIndex: 44,
      risingPct: 210,
      sparkline: spark([12, 14, 16, 18, 21, 24, 29, 34, 38, 42, 48, 54]),
      byCountry: {
        US: 38, CA: 34, MX: 18, SG: 72, MY: 58, TH: 41, ID: 36, PH: 29, VN: 33,
        GB: 31, DE: 22, FR: 19, IT: 17, ES: 16, NL: 28, PL: 14, SE: 21,
      },
    },
    markets: [
      {
        region: "na",
        exists: false,
        status: "whitespace",
        listings: 4,
        sellerCount: 3,
        avgRetailUsd: 0,
        lowRetailUsd: 0,
        projectedRetailUsd: 129,
        platforms: [
          { name: "Amazon US", listings: 2, avgPrice: 149 },
          { name: "Wayfair", listings: 1, avgPrice: 189 },
          { name: "Walmart", listings: 1, avgPrice: 99 },
        ],
        landedCostUsd: 46,
        marginPct: null,
        notes: "Open garment rails exist; the curtain-front kit sold as one SKU is effectively absent. Projected DTC price $119–149.",
      },
      {
        region: "sea",
        exists: true,
        status: "competitive",
        listings: 1260,
        sellerCount: 340,
        avgRetailUsd: 52,
        lowRetailUsd: 29,
        projectedRetailUsd: 52,
        platforms: [
          { name: "Shopee", listings: 820, avgPrice: 48 },
          { name: "Lazada", listings: 310, avgPrice: 55 },
          { name: "TikTok Shop SEA", listings: 130, avgPrice: 59 },
        ],
        landedCostUsd: 34,
        marginPct: 35,
        notes: "Shopee already carries Chinese factory kits. Price gap is real but seller density is high.",
      },
      {
        region: "eu",
        exists: false,
        status: "whitespace",
        listings: 9,
        sellerCount: 6,
        avgRetailUsd: 0,
        lowRetailUsd: 0,
        projectedRetailUsd: 139,
        platforms: [
          { name: "Amazon DE", listings: 5, avgPrice: 119 },
          { name: "Amazon UK", listings: 3, avgPrice: 129 },
          { name: "Bol", listings: 1, avgPrice: 99 },
        ],
        landedCostUsd: 51,
        marginPct: null,
        notes: "IKEA open wardrobes dominate. No concentrated factory-kit sellers. Strong rental-market story in DE/NL/UK.",
      },
    ],
  },
  {
    slug: "enamel-pegboard",
    name: "Magnetic enamel wall panel",
    nameZh: "珐琅板 / 洞洞板",
    category: "Home storage",
    summary:
      "Full-height magnetic enamel panels that turn a wall into tool-free storage. Exploding on Xiaohongshu as the ‘Lego wall’; almost no branded kits in NA/EU general ecommerce.",
    whyNow:
      "Xiaohongshu new notes on enamel panels +266% in 2026. Chinese factories in Zhongshan already sell 1.2×2.4m sheets under $18 FOB. Western ‘pegboard’ search is rising but listings are still hobby pegboard, not enamel magnetic systems.",
    image: u("photo-1556912173-46c336c7fd55"),
    imageAlt: "Organized wall storage in a compact kitchen",
    tags: ["whitespace", "xiaohongshu", "diy"],
    factory: [
      {
        platform: "1688",
        listingCount: 6400,
        supplierCount: 210,
        verifiedFactories: 88,
        unitPriceUsd: 16.8,
        unitPriceCny: 121,
        moq: 5,
        cluster: "Zhongshan · Cixi",
        orders30d: 28600,
        velocityWoW: 19,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%B7%A8%C0%C5%B0%E5",
      },
      {
        platform: "alibaba",
        listingCount: 380,
        supplierCount: 64,
        verifiedFactories: 41,
        unitPriceUsd: 24.5,
        unitPriceCny: 176,
        moq: 50,
        cluster: "Zhongshan",
        orders30d: 4100,
        velocityWoW: 8,
        searchUrl: "https://www.alibaba.com/trade/search?SearchText=enamel+magnetic+wall+panel",
      },
    ],
    social: [
      {
        platform: "xiaohongshu",
        mentions7d: 9200,
        views7d: 4_100_000,
        engagementRate: 7.1,
        hashtags: ["珐琅板", "洞洞板改造", "厨房收纳"],
        trend: "rising",
        samplePosts: [
          {
            author: "@厨房即兴",
            text: "整面珐琅板代替置物架，磁吸挂钩随手换，租房党不用打孔。",
            likes: 22100,
            time: "2026-09-04",
          },
        ],
      },
      {
        platform: "tiktok",
        mentions7d: 640,
        views7d: 1_900_000,
        engagementRate: 2.8,
        hashtags: ["#pegboard", "#kitchenorganization", "#renterfriendly"],
        trend: "rising",
        samplePosts: [
          {
            author: "@organize.with.mara",
            text: "This magnetic enamel wall is everywhere on RedNote. Why can’t I buy a kit on Amazon?",
            likes: 34000,
            time: "2026-08-29",
          },
        ],
      },
    ],
    search: {
      keyword: "magnetic enamel pegboard",
      related: ["magnetic wall panel kitchen", "renter pegboard no drill", "enamel memo wall"],
      globalIndex: 29,
      risingPct: 180,
      sparkline: spark([8, 9, 10, 11, 13, 15, 18, 21, 24, 28, 33, 39]),
      byCountry: {
        US: 27, CA: 24, MX: 9, SG: 61, MY: 33, TH: 22, ID: 18, PH: 14, VN: 19,
        GB: 26, DE: 31, FR: 18, IT: 12, ES: 11, NL: 29, PL: 10, SE: 34,
      },
    },
    markets: [
      {
        region: "na",
        exists: false,
        status: "whitespace",
        listings: 7,
        sellerCount: 5,
        avgRetailUsd: 0,
        lowRetailUsd: 0,
        projectedRetailUsd: 79,
        platforms: [
          { name: "Amazon US", listings: 4, avgPrice: 54 },
          { name: "Etsy", listings: 2, avgPrice: 120 },
          { name: "Home Depot", listings: 1, avgPrice: 39 },
        ],
        landedCostUsd: 29,
        marginPct: null,
        notes: "Hobby pegboards exist. Full enamel magnetic sheet kits with hardware are missing. Kit-of-3 panels is the SKU to list.",
      },
      {
        region: "sea",
        exists: true,
        status: "thin",
        listings: 46,
        sellerCount: 19,
        avgRetailUsd: 42,
        lowRetailUsd: 24,
        projectedRetailUsd: 42,
        platforms: [
          { name: "Shopee", listings: 31, avgPrice: 39 },
          { name: "Lazada", listings: 15, avgPrice: 48 },
        ],
        landedCostUsd: 22,
        marginPct: 48,
        notes: "Singapore and Malaysia early adopters. Thin seller set, 48% gap vs landed cost.",
      },
      {
        region: "eu",
        exists: false,
        status: "whitespace",
        listings: 11,
        sellerCount: 8,
        avgRetailUsd: 0,
        lowRetailUsd: 0,
        projectedRetailUsd: 89,
        platforms: [
          { name: "Amazon DE", listings: 6, avgPrice: 69 },
          { name: "Amazon UK", listings: 4, avgPrice: 75 },
          { name: "Fnac", listings: 1, avgPrice: 99 },
        ],
        landedCostUsd: 33,
        marginPct: null,
        notes: "German ‘Metall-Pinnwand’ is office memo, not kitchen enamel storage. Design-led DTC would land.",
      },
    ],
  },
  {
    slug: "retractable-laundry-rack",
    name: "Ceiling-mount retractable laundry rack",
    nameZh: "手摇升降晾衣架",
    category: "Home / laundry",
    summary:
      "Hand-crank or motorized ceiling drying rack — default in Chinese and SEA apartments, still a curiosity in North American laundry rooms.",
    whyNow:
      "1688 Guangdong cluster ships these as a staple SKU. Google queries for ‘ceiling clothes drying rack’ are breakout in dense US/UK cities while Amazon listings remain sparse and expensive.",
    image: u("photo-1610557892470-55d9e80c0bce"),
    imageAlt: "Laundry hanging in a compact utility room",
    tags: ["whitespace", "evergreen", "apartment"],
    factory: [
      {
        platform: "1688",
        listingCount: 22100,
        supplierCount: 1280,
        verifiedFactories: 460,
        unitPriceUsd: 19.6,
        unitPriceCny: 141,
        moq: 2,
        cluster: "Foshan · Zhaoqing",
        orders30d: 87000,
        velocityWoW: 9,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%C1%B4%D2%C2%BC%DC",
      },
    ],
    social: [
      {
        platform: "xiaohongshu",
        mentions7d: 5400,
        views7d: 2_400_000,
        engagementRate: 4.8,
        hashtags: ["晾衣架", "阳台改造"],
        trend: "peak",
        samplePosts: [
          {
            author: "@ balconyliving",
            text: "手摇晾衣架装好以后再也不把湿衣服挂在门后了。",
            likes: 4300,
            time: "2026-08-30",
          },
        ],
      },
      {
        platform: "tiktok",
        mentions7d: 1800,
        views7d: 6_200_000,
        engagementRate: 3.6,
        hashtags: ["#laundryhack", "#apartmentlaundry", "#dryingrack"],
        trend: "rising",
        samplePosts: [
          {
            author: "@nyc.studio.tour",
            text: "Every Hong Kong apartment has this. My NYC laundry closet does not. Why?",
            likes: 210000,
            time: "2026-09-01",
          },
        ],
      },
      {
        platform: "youtube",
        mentions7d: 120,
        views7d: 890000,
        engagementRate: 4.0,
        hashtags: ["ceiling drying rack install"],
        trend: "rising",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "ceiling clothes drying rack",
      related: ["retractable laundry rack", "apartment drying rack ceiling", "pulley clothes airer"],
      globalIndex: 51,
      risingPct: 95,
      sparkline: spark([28, 30, 31, 33, 36, 38, 41, 44, 47, 52, 58, 61]),
      byCountry: {
        US: 48, CA: 44, MX: 21, SG: 88, MY: 76, TH: 69, ID: 64, PH: 58, VN: 71,
        GB: 67, DE: 41, FR: 29, IT: 26, ES: 33, NL: 39, PL: 22, SE: 36,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "thin",
        listings: 28,
        sellerCount: 11,
        avgRetailUsd: 89,
        lowRetailUsd: 54,
        projectedRetailUsd: 89,
        platforms: [
          { name: "Amazon US", listings: 19, avgPrice: 92 },
          { name: "Walmart", listings: 4, avgPrice: 79 },
          { name: "Home Depot", listings: 5, avgPrice: 119 },
        ],
        landedCostUsd: 34,
        marginPct: 62,
        notes: "Thin catalog, 62% gap vs landed. Install-video content is the unlock. Watch ceiling-mount liability copy.",
      },
      {
        region: "sea",
        exists: true,
        status: "saturated",
        listings: 4100,
        sellerCount: 980,
        avgRetailUsd: 29,
        lowRetailUsd: 14,
        projectedRetailUsd: 29,
        platforms: [
          { name: "Shopee", listings: 2600, avgPrice: 27 },
          { name: "Lazada", listings: 1500, avgPrice: 32 },
        ],
        landedCostUsd: 24,
        marginPct: 17,
        notes: "Default household SKU. Do not enter SEA on price.",
      },
      {
        region: "eu",
        exists: true,
        status: "competitive",
        listings: 340,
        sellerCount: 90,
        avgRetailUsd: 64,
        lowRetailUsd: 39,
        projectedRetailUsd: 64,
        platforms: [
          { name: "Amazon UK", listings: 160, avgPrice: 59 },
          { name: "Amazon DE", listings: 120, avgPrice: 69 },
          { name: "Leroy Merlin", listings: 60, avgPrice: 74 },
        ],
        landedCostUsd: 37,
        marginPct: 42,
        notes: "UK ‘pulley airer’ is known; motorized versions still sparse. 42% gap on electric SKUs.",
      },
    ],
  },
  {
    slug: "pdrn-ampoule",
    name: "PDRN repair ampoule",
    nameZh: "PDRN 修护次抛",
    category: "Beauty",
    summary:
      "Korean-origin salmon-DNA skincare moving from clinic to drugstore. Search is hot in Singapore and starting to break in the US and UK — China OEM can undercut Korean prestige bottles.",
    whyNow:
      "Google Trends shows a synchronized climb for PDRN cream/toner/mask into 2026. SEA already sells it; NA/EU prestige shelves are expensive and thin at the $18–28 mass price.",
    image: u("photo-1620916566398-39f1143ab7be"),
    imageAlt: "Dropper skincare bottles on a linen surface",
    tags: ["beauty", "search-breakout", "oem"],
    factory: [
      {
        platform: "1688",
        listingCount: 3100,
        supplierCount: 140,
        verifiedFactories: 52,
        unitPriceUsd: 3.4,
        unitPriceCny: 24,
        moq: 50,
        cluster: "Guangzhou Baiyun · Qingdao OEM",
        orders30d: 41000,
        velocityWoW: 16,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=PDRN",
      },
      {
        platform: "alibaba",
        listingCount: 220,
        supplierCount: 48,
        verifiedFactories: 29,
        unitPriceUsd: 5.8,
        unitPriceCny: 42,
        moq: 500,
        cluster: "Guangzhou",
        orders30d: 6200,
        velocityWoW: 11,
        searchUrl: "https://www.alibaba.com/trade/search?SearchText=PDRN+ampoule+OEM",
      },
    ],
    social: [
      {
        platform: "xiaohongshu",
        mentions7d: 15600,
        views7d: 7_800_000,
        engagementRate: 5.9,
        hashtags: ["PDRN", "皮肤修复", "医美成分"],
        trend: "peak",
        samplePosts: [
          {
            author: "@皮肤科笔记",
            text: "PDRN 从院线走到次抛，早 C 晚 A 之后的第三步。",
            likes: 18900,
            time: "2026-09-02",
          },
        ],
      },
      {
        platform: "tiktok",
        mentions7d: 8700,
        views7d: 21_000_000,
        engagementRate: 4.4,
        hashtags: ["#pdrn", "#kbeauty", "#skinbarrier"],
        trend: "rising",
        samplePosts: [
          {
            author: "@derm.explained",
            text: "PDRN is what Korean clinics used before it hit Sephora. The drugstore versions are coming.",
            likes: 156000,
            time: "2026-09-04",
          },
        ],
      },
      {
        platform: "instagram",
        mentions7d: 2400,
        views7d: 3_300_000,
        engagementRate: 3.2,
        hashtags: ["#glassskin", "#pdrnserum"],
        trend: "rising",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "PDRN serum",
      related: ["PDRN ampoule", "salmon DNA skincare", "PDRN toner"],
      globalIndex: 68,
      risingPct: 260,
      sparkline: spark([10, 12, 14, 18, 22, 29, 36, 44, 52, 61, 70, 78]),
      byCountry: {
        US: 54, CA: 49, MX: 18, SG: 100, MY: 71, TH: 48, ID: 33, PH: 41, VN: 29,
        GB: 47, DE: 22, FR: 19, IT: 16, ES: 14, NL: 24, PL: 11, SE: 21,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "thin",
        listings: 62,
        sellerCount: 24,
        avgRetailUsd: 42,
        lowRetailUsd: 24,
        projectedRetailUsd: 42,
        platforms: [
          { name: "Amazon US", listings: 38, avgPrice: 36 },
          { name: "Sephora", listings: 9, avgPrice: 68 },
          { name: "iHerb", listings: 15, avgPrice: 29 },
        ],
        landedCostUsd: 8.5,
        marginPct: 80,
        notes: "Listings exist at prestige prices. Mass $22–28 single-dose kits are thin. Cosmetics compliance is the gate, not demand.",
      },
      {
        region: "sea",
        exists: true,
        status: "competitive",
        listings: 980,
        sellerCount: 260,
        avgRetailUsd: 19,
        lowRetailUsd: 9,
        projectedRetailUsd: 19,
        platforms: [
          { name: "Shopee", listings: 540, avgPrice: 17 },
          { name: "Lazada", listings: 280, avgPrice: 21 },
          { name: "Watsons/Guardian", listings: 160, avgPrice: 24 },
        ],
        landedCostUsd: 6.8,
        marginPct: 64,
        notes: "Singapore is the demand peak. Competitive, but 64% gap remains for a clean brand story.",
      },
      {
        region: "eu",
        exists: true,
        status: "thin",
        listings: 41,
        sellerCount: 17,
        avgRetailUsd: 38,
        lowRetailUsd: 21,
        projectedRetailUsd: 38,
        platforms: [
          { name: "Amazon UK", listings: 18, avgPrice: 34 },
          { name: "Amazon DE", listings: 11, avgPrice: 41 },
          { name: "Notino", listings: 12, avgPrice: 39 },
        ],
        landedCostUsd: 9.4,
        marginPct: 75,
        notes: "CPNP / EU cosmetics file required. Demand is ahead of assortment — classic whitespace-adjacent play.",
      },
    ],
  },
  {
    slug: "foldable-tpu-bathtub",
    name: "Foldable TPU soaking tub",
    nameZh: "可折叠泡澡桶",
    category: "Home wellness",
    summary:
      "TPU portable bathtub that packs to 15cm. Factory $18–30, Amazon soaking-tub comps $80–110. Cold-plunge and small-space bathing are both pulling search up.",
    whyNow:
      "Chinese cross-border sellers already treat this as a 2026 independent-site blue ocean. Ice-bath summer + soak winter keeps the SKU year-round.",
    image: u("photo-1507652313519-d4e9174996dd"),
    imageAlt: "Freestanding soaking tub in a bright bathroom",
    tags: ["wellness", "high-margin", "visual"],
    factory: [
      {
        platform: "1688",
        listingCount: 8900,
        supplierCount: 360,
        verifiedFactories: 120,
        unitPriceUsd: 22.0,
        unitPriceCny: 158,
        moq: 5,
        cluster: "Taizhou · Lin'an",
        orders30d: 19000,
        velocityWoW: 12,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%D5%DB%B5%FE%D4%A1%B8%D6",
      },
    ],
    social: [
      {
        platform: "tiktok",
        mentions7d: 6400,
        views7d: 18_400_000,
        engagementRate: 5.2,
        hashtags: ["#coldplunge", "#foldablebathtub", "#apartmentbath"],
        trend: "rising",
        samplePosts: [
          {
            author: "@ice.protocol",
            text: "No backyard. No $5k plunge. This folds under the bed. 3 minutes of ice water and I am a different person.",
            likes: 402000,
            time: "2026-09-03",
          },
        ],
      },
      {
        platform: "xiaohongshu",
        mentions7d: 4100,
        views7d: 2_200_000,
        engagementRate: 4.1,
        hashtags: ["折叠浴缸", "租房泡澡"],
        trend: "peak",
        samplePosts: [],
      },
      {
        platform: "youtube",
        mentions7d: 210,
        views7d: 1_400_000,
        engagementRate: 3.8,
        hashtags: ["portable bathtub review"],
        trend: "rising",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "foldable bathtub",
      related: ["portable soaking tub", "apartment bathtub", "ice bath tub portable"],
      globalIndex: 57,
      risingPct: 120,
      sparkline: spark([22, 24, 26, 30, 34, 36, 40, 44, 49, 53, 58, 63]),
      byCountry: {
        US: 64, CA: 58, MX: 27, SG: 49, MY: 38, TH: 44, ID: 41, PH: 36, VN: 33,
        GB: 61, DE: 48, FR: 39, IT: 34, ES: 31, NL: 42, PL: 22, SE: 40,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "competitive",
        listings: 420,
        sellerCount: 110,
        avgRetailUsd: 96,
        lowRetailUsd: 59,
        projectedRetailUsd: 96,
        platforms: [
          { name: "Amazon US", listings: 280, avgPrice: 94 },
          { name: "Walmart", listings: 60, avgPrice: 79 },
          { name: "Shopify DTC", listings: 80, avgPrice: 129 },
        ],
        landedCostUsd: 38,
        marginPct: 60,
        notes: "Category exists. TPU (not PVC) plus ice-bath positioning still clears ~60% vs landed. Returns are the risk.",
      },
      {
        region: "sea",
        exists: true,
        status: "thin",
        listings: 88,
        sellerCount: 31,
        avgRetailUsd: 54,
        lowRetailUsd: 32,
        projectedRetailUsd: 54,
        platforms: [
          { name: "Shopee", listings: 54, avgPrice: 49 },
          { name: "Lazada", listings: 34, avgPrice: 61 },
        ],
        landedCostUsd: 29,
        marginPct: 46,
        notes: "Heat + small bathrooms help, but ice-plunge narrative is weaker. Thin and workable.",
      },
      {
        region: "eu",
        exists: true,
        status: "competitive",
        listings: 210,
        sellerCount: 64,
        avgRetailUsd: 89,
        lowRetailUsd: 55,
        projectedRetailUsd: 89,
        platforms: [
          { name: "Amazon DE", listings: 90, avgPrice: 92 },
          { name: "Amazon UK", listings: 70, avgPrice: 85 },
          { name: "Allegro", listings: 50, avgPrice: 72 },
        ],
        landedCostUsd: 41,
        marginPct: 54,
        notes: "UK/DE search is strong. REACH on TPU/PVC claims needed. Margin still healthy.",
      },
    ],
  },
  {
    slug: "sauna-blanket",
    name: "Infrared sauna blanket",
    nameZh: "远红外汗蒸毯",
    category: "Wellness",
    summary:
      "At-home infrared blanket. Factory $30–60, Western retail $100–200. Search climbed from late 2024 and is holding through 2026.",
    whyNow:
      "Wellness TikTok keeps the demo format alive (zip-up, sweat, weigh-in). Competition is real, but landed-to-retail gap is still one of the widest in the catalog.",
    image: u("photo-1544161515-4ab6ce6db874"),
    imageAlt: "Spa treatment room with warm lighting",
    tags: ["wellness", "high-margin", "tiktok"],
    factory: [
      {
        platform: "1688",
        listingCount: 2700,
        supplierCount: 96,
        verifiedFactories: 34,
        unitPriceUsd: 38.0,
        unitPriceCny: 274,
        moq: 5,
        cluster: "Shenzhen · Dongguan",
        orders30d: 9800,
        velocityWoW: 6,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%BA%B1%D5%F4%CC%B1",
      },
      {
        platform: "alibaba",
        listingCount: 410,
        supplierCount: 70,
        verifiedFactories: 44,
        unitPriceUsd: 49.0,
        unitPriceCny: 353,
        moq: 20,
        cluster: "Shenzhen",
        orders30d: 2400,
        velocityWoW: 3,
        searchUrl: "https://www.alibaba.com/trade/search?SearchText=infrared+sauna+blanket",
      },
    ],
    social: [
      {
        platform: "tiktok",
        mentions7d: 11200,
        views7d: 32_000_000,
        engagementRate: 3.9,
        hashtags: ["#saunablanket", "#infraredsauna", "#wellnesstok"],
        trend: "peak",
        samplePosts: [
          {
            author: "@recover.club",
            text: "Bought the blanket instead of a $8k sauna. 40 minutes after leg day. I get it now.",
            likes: 288000,
            time: "2026-08-28",
          },
        ],
      },
      {
        platform: "instagram",
        mentions7d: 3600,
        views7d: 5_100_000,
        engagementRate: 2.7,
        hashtags: ["#infrared", "#homespa"],
        trend: "peak",
        samplePosts: [],
      },
      {
        platform: "youtube",
        mentions7d: 340,
        views7d: 2_600_000,
        engagementRate: 4.5,
        hashtags: ["sauna blanket review"],
        trend: "peak",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "sauna blanket",
      related: ["infrared sauna blanket", "portable sauna", "sweat blanket"],
      globalIndex: 73,
      risingPct: 40,
      sparkline: spark([30, 38, 46, 55, 62, 70, 74, 71, 69, 72, 75, 77]),
      byCountry: {
        US: 86, CA: 74, MX: 22, SG: 41, MY: 28, TH: 24, ID: 19, PH: 21, VN: 17,
        GB: 68, DE: 54, FR: 33, IT: 29, ES: 31, NL: 48, PL: 27, SE: 51,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "competitive",
        listings: 860,
        sellerCount: 210,
        avgRetailUsd: 149,
        lowRetailUsd: 79,
        projectedRetailUsd: 149,
        platforms: [
          { name: "Amazon US", listings: 520, avgPrice: 139 },
          { name: "Walmart", listings: 90, avgPrice: 99 },
          { name: "Shopify DTC", listings: 250, avgPrice: 189 },
        ],
        landedCostUsd: 58,
        marginPct: 61,
        notes: "Crowded creative, still 61% gap. Differentiation is fabric grade, controller, and safety certs (ETL).",
      },
      {
        region: "sea",
        exists: true,
        status: "thin",
        listings: 70,
        sellerCount: 24,
        avgRetailUsd: 79,
        lowRetailUsd: 49,
        projectedRetailUsd: 79,
        platforms: [
          { name: "Shopee", listings: 44, avgPrice: 72 },
          { name: "Lazada", listings: 26, avgPrice: 88 },
        ],
        landedCostUsd: 49,
        marginPct: 38,
        notes: "Climate works against daily sauna use. Treat as a premium import, not a volume SKU.",
      },
      {
        region: "eu",
        exists: true,
        status: "competitive",
        listings: 310,
        sellerCount: 80,
        avgRetailUsd: 139,
        lowRetailUsd: 85,
        projectedRetailUsd: 139,
        platforms: [
          { name: "Amazon DE", listings: 140, avgPrice: 149 },
          { name: "Amazon UK", listings: 110, avgPrice: 129 },
          { name: "Bol", listings: 60, avgPrice: 119 },
        ],
        landedCostUsd: 64,
        marginPct: 54,
        notes: "CE + overheat protection copy is mandatory. Margin still holds on mid-tier units.",
      },
    ],
  },
  {
    slug: "blue-light-wand",
    name: "Blue-light acne wand",
    nameZh: "蓝光祛痘仪",
    category: "Beauty devices",
    summary:
      "Handheld blue-light device riding the same curve as red-light therapy, from a much lower competition base. Factory $10–25, retail $50–120.",
    whyNow:
      "Red light is saturated. Search for blue-light acne devices is compounding without the same listing density — a classic ‘second-wave device’ window.",
    image: u("photo-1487412947147-5cebf100ffc2"),
    imageAlt: "Facial beauty device on a bathroom shelf",
    tags: ["beauty", "devices", "second-wave"],
    factory: [
      {
        platform: "1688",
        listingCount: 1540,
        supplierCount: 88,
        verifiedFactories: 31,
        unitPriceUsd: 14.2,
        unitPriceCny: 102,
        moq: 10,
        cluster: "Shenzhen Bao'an",
        orders30d: 12600,
        velocityWoW: 14,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%C0%B6%B9%E2%C8%A6%B6%B7",
      },
    ],
    social: [
      {
        platform: "tiktok",
        mentions7d: 5300,
        views7d: 14_600_000,
        engagementRate: 4.8,
        hashtags: ["#bluelighttherapy", "#acnedevice", "#dermgadget"],
        trend: "rising",
        samplePosts: [
          {
            author: "@spot.check",
            text: "Red light didn’t do anything for my breakouts. Blue light wand in 7 days. I’m annoyed it worked.",
            likes: 176000,
            time: "2026-09-01",
          },
        ],
      },
      {
        platform: "xiaohongshu",
        mentions7d: 2900,
        views7d: 1_600_000,
        engagementRate: 4.0,
        hashtags: ["蓝光美容仪", "痘痘"],
        trend: "rising",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "blue light acne device",
      related: ["blue light therapy wand", "LED acne pen", "blue light vs red light acne"],
      globalIndex: 48,
      risingPct: 155,
      sparkline: spark([14, 16, 18, 20, 24, 28, 32, 36, 41, 46, 52, 57]),
      byCountry: {
        US: 61, CA: 52, MX: 24, SG: 44, MY: 31, TH: 27, ID: 22, PH: 29, VN: 18,
        GB: 58, DE: 34, FR: 36, IT: 30, ES: 28, NL: 33, PL: 19, SE: 31,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "thin",
        listings: 94,
        sellerCount: 40,
        avgRetailUsd: 69,
        lowRetailUsd: 29,
        projectedRetailUsd: 69,
        platforms: [
          { name: "Amazon US", listings: 70, avgPrice: 64 },
          { name: "Ulta/Sephora", listings: 8, avgPrice: 98 },
          { name: "TikTok Shop US", listings: 16, avgPrice: 49 },
        ],
        landedCostUsd: 22,
        marginPct: 68,
        notes: "Thin versus red-light wands (2,000+ listings). FDA-language caution. 68% gap.",
      },
      {
        region: "sea",
        exists: true,
        status: "competitive",
        listings: 260,
        sellerCount: 90,
        avgRetailUsd: 28,
        lowRetailUsd: 12,
        projectedRetailUsd: 28,
        platforms: [
          { name: "Shopee", listings: 180, avgPrice: 26 },
          { name: "Lazada", listings: 80, avgPrice: 32 },
        ],
        landedCostUsd: 18,
        marginPct: 36,
        notes: "Price compression already started. Brand + before/after still works.",
      },
      {
        region: "eu",
        exists: true,
        status: "thin",
        listings: 55,
        sellerCount: 22,
        avgRetailUsd: 59,
        lowRetailUsd: 32,
        projectedRetailUsd: 59,
        platforms: [
          { name: "Amazon UK", listings: 24, avgPrice: 55 },
          { name: "Amazon DE", listings: 18, avgPrice: 64 },
          { name: "Notino", listings: 13, avgPrice: 69 },
        ],
        landedCostUsd: 24,
        marginPct: 59,
        notes: "CE medical-claim line is thin ice. Cosmetic ‘blemish light’ positioning is safer.",
      },
    ],
  },
  {
    slug: "heated-towel-rail",
    name: "Electric heated towel rail",
    nameZh: "电热毛巾架",
    category: "Bathroom",
    summary:
      "Plug-in or hardwired heated towel rack. Amazon sweet spot $80–100 with reported gross over 67%. Factory cost sits far below that.",
    whyNow:
      "Hugo 2026 bathroom category notes heated rails as a comfort SKU with health/comfort demand, not just hardware. Easy demo video: wet towel in, dry towel out.",
    image: u("photo-1552321554-5fefe8c9ef14"),
    imageAlt: "Modern bathroom with towel storage",
    tags: ["bathroom", "high-margin", "evergreen"],
    factory: [
      {
        platform: "1688",
        listingCount: 5600,
        supplierCount: 240,
        verifiedFactories: 90,
        unitPriceUsd: 21.5,
        unitPriceCny: 155,
        moq: 10,
        cluster: "Wenzhou · Zhongshan",
        orders30d: 15200,
        velocityWoW: 7,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%B5%E7%C8%C8%C3%AB%BD%EB%BC%DC",
      },
    ],
    social: [
      {
        platform: "tiktok",
        mentions7d: 1900,
        views7d: 5_400_000,
        engagementRate: 3.3,
        hashtags: ["#bathroomupgrade", "#heatedtowelrail", "#homedecor"],
        trend: "rising",
        samplePosts: [
          {
            author: "@reno.on.a.budget",
            text: "The most expensive-feeling $90 I have spent. Warm towels in a rental.",
            likes: 67000,
            time: "2026-08-27",
          },
        ],
      },
      {
        platform: "xiaohongshu",
        mentions7d: 1600,
        views7d: 900000,
        engagementRate: 3.5,
        hashtags: ["电热毛巾架", "卫浴改造"],
        trend: "peak",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "heated towel rack",
      related: ["electric towel rail", "plug in towel warmer", "bathroom towel heater"],
      globalIndex: 60,
      risingPct: 48,
      sparkline: spark([40, 42, 41, 44, 46, 48, 51, 53, 55, 58, 62, 64]),
      byCountry: {
        US: 58, CA: 66, MX: 14, SG: 37, MY: 22, TH: 18, ID: 15, PH: 17, VN: 14,
        GB: 84, DE: 49, FR: 38, IT: 28, ES: 24, NL: 46, PL: 21, SE: 72,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "competitive",
        listings: 640,
        sellerCount: 150,
        avgRetailUsd: 92,
        lowRetailUsd: 49,
        projectedRetailUsd: 92,
        platforms: [
          { name: "Amazon US", listings: 410, avgPrice: 89 },
          { name: "Home Depot / Lowe’s", listings: 80, avgPrice: 129 },
          { name: "Wayfair", listings: 150, avgPrice: 99 },
        ],
        landedCostUsd: 36,
        marginPct: 61,
        notes: "Plug-in SKUs avoid electrician friction. UL listing is the moat. 61% gap on factory-direct.",
      },
      {
        region: "sea",
        exists: true,
        status: "thin",
        listings: 40,
        sellerCount: 16,
        avgRetailUsd: 55,
        lowRetailUsd: 29,
        projectedRetailUsd: 55,
        platforms: [
          { name: "Shopee", listings: 24, avgPrice: 49 },
          { name: "Lazada", listings: 16, avgPrice: 64 },
        ],
        landedCostUsd: 28,
        marginPct: 49,
        notes: "Climate reduces need. Singapore condos with AC bathrooms are the pocket of demand.",
      },
      {
        region: "eu",
        exists: true,
        status: "competitive",
        listings: 890,
        sellerCount: 200,
        avgRetailUsd: 79,
        lowRetailUsd: 39,
        projectedRetailUsd: 79,
        platforms: [
          { name: "Amazon UK", listings: 320, avgPrice: 69 },
          { name: "Amazon DE", listings: 280, avgPrice: 85 },
          { name: "B&Q / Leroy", listings: 290, avgPrice: 99 },
        ],
        landedCostUsd: 39,
        marginPct: 51,
        notes: "Category is native in UK/Nordics. Compete on design (matte black, brushed gold) not on being first.",
      },
    ],
  },
  {
    slug: "neck-pov-camera",
    name: "Neck-wear POV camera",
    nameZh: "挂脖运动相机",
    category: "Electronics",
    summary:
      "Hands-free necklace / magnetic POV cam for cooking, cycling, parenting. Search has climbed with short-form video; listings have not caught the form factor.",
    whyNow:
      "TikTok and YouTube shorts made first-person footage a default language. Cheap Shenzhen CMOS modules make a $29–49 retail possible against GoPro’s $200+.",
    image: u("photo-1526170375885-4d8ecf77b99f"),
    imageAlt: "Compact action camera on a desk",
    tags: ["electronics", "creators", "rising-search"],
    factory: [
      {
        platform: "1688",
        listingCount: 980,
        supplierCount: 64,
        verifiedFactories: 22,
        unitPriceUsd: 18.9,
        unitPriceCny: 136,
        moq: 10,
        cluster: "Shenzhen Huaqiangbei",
        orders30d: 7400,
        velocityWoW: 17,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%B9%D2%B2%BB%D4%CB%B6%AF%CF%E0%BB%FA",
      },
    ],
    social: [
      {
        platform: "tiktok",
        mentions7d: 4100,
        views7d: 19_200_000,
        engagementRate: 5.5,
        hashtags: ["#povcamera", "#neckcamera", "#handsfreetok"],
        trend: "rising",
        samplePosts: [
          {
            author: "@bike.commute.logs",
            text: "I look insane wearing a camera on my chest. The footage does not look insane.",
            likes: 510000,
            time: "2026-09-04",
          },
        ],
      },
      {
        platform: "youtube",
        mentions7d: 280,
        views7d: 3_100_000,
        engagementRate: 4.2,
        hashtags: ["POV necklace camera"],
        trend: "rising",
        samplePosts: [],
      },
      {
        platform: "x",
        mentions7d: 620,
        views7d: 1_400_000,
        engagementRate: 1.8,
        hashtags: ["POV cam"],
        trend: "rising",
        samplePosts: [
          {
            author: "@gadgetaf",
            text: "The $35 Shenzhen neck cam is going to eat the ‘I should vlog’ guilt market.",
            likes: 4200,
            time: "2026-09-02",
          },
        ],
      },
    ],
    search: {
      keyword: "POV necklace camera",
      related: ["hands free vlog camera", "neck wearable camera", "chest mount mini camera"],
      globalIndex: 42,
      risingPct: 190,
      sparkline: spark([11, 12, 14, 16, 19, 22, 26, 30, 34, 39, 45, 51]),
      byCountry: {
        US: 55, CA: 42, MX: 20, SG: 36, MY: 28, TH: 30, ID: 34, PH: 38, VN: 27,
        GB: 44, DE: 33, FR: 29, IT: 26, ES: 25, NL: 31, PL: 18, SE: 27,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "thin",
        listings: 48,
        sellerCount: 21,
        avgRetailUsd: 79,
        lowRetailUsd: 39,
        projectedRetailUsd: 79,
        platforms: [
          { name: "Amazon US", listings: 32, avgPrice: 74 },
          { name: "TikTok Shop US", listings: 11, avgPrice: 45 },
          { name: "eBay", listings: 5, avgPrice: 59 },
        ],
        landedCostUsd: 29,
        marginPct: 63,
        notes: "Action cameras are saturated; necklace form factor is not. FCC + privacy copy required.",
      },
      {
        region: "sea",
        exists: true,
        status: "thin",
        listings: 36,
        sellerCount: 15,
        avgRetailUsd: 34,
        lowRetailUsd: 18,
        projectedRetailUsd: 34,
        platforms: [
          { name: "Shopee", listings: 22, avgPrice: 32 },
          { name: "Lazada", listings: 14, avgPrice: 37 },
        ],
        landedCostUsd: 23,
        marginPct: 32,
        notes: "Creator economy in ID/PH is huge; ASP is lower. Bundle with SD card.",
      },
      {
        region: "eu",
        exists: true,
        status: "thin",
        listings: 27,
        sellerCount: 12,
        avgRetailUsd: 69,
        lowRetailUsd: 35,
        projectedRetailUsd: 69,
        platforms: [
          { name: "Amazon DE", listings: 12, avgPrice: 72 },
          { name: "Amazon UK", listings: 10, avgPrice: 65 },
          { name: "Fnac", listings: 5, avgPrice: 79 },
        ],
        landedCostUsd: 31,
        marginPct: 55,
        notes: "GDPR recording-notice in the listing. Thin and high-intent.",
      },
    ],
  },
  {
    slug: "collapsible-shower-bucket",
    name: "Collapsible shower / soak bucket",
    nameZh: "可折叠淋浴桶",
    category: "Travel / home",
    summary:
      "Fold-flat soaking bucket for dorms, camping, and apartments without a tub. 1688 wholesale around ¥15; Western camping retail has not really noticed.",
    whyNow:
      "1688 back-to-school 2026 listings are everywhere. Combines camping, dorm, and ‘no bathtub’ urban living — three channels, one SKU.",
    image: u("photo-1478131143081-80f7f84ca84d"),
    imageAlt: "Camping wash setup outdoors",
    tags: ["whitespace", "low-ticket", "camping"],
    factory: [
      {
        platform: "1688",
        listingCount: 12400,
        supplierCount: 620,
        verifiedFactories: 150,
        unitPriceUsd: 4.8,
        unitPriceCny: 35,
        moq: 10,
        cluster: "Linyi · Yiwu",
        orders30d: 54000,
        velocityWoW: 11,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%D5%DB%B5%FE%C1%E4%D4%A1%CD%B0",
      },
    ],
    social: [
      {
        platform: "xiaohongshu",
        mentions7d: 2200,
        views7d: 980000,
        engagementRate: 3.6,
        hashtags: ["折叠浴桶", "宿舍神器"],
        trend: "rising",
        samplePosts: [
          {
            author: "@宿舍改造日记",
            text: "开学折叠淋浴桶，澡堂排队再见。",
            likes: 5600,
            time: "2026-08-31",
          },
        ],
      },
      {
        platform: "tiktok",
        mentions7d: 740,
        views7d: 2_100_000,
        engagementRate: 2.9,
        hashtags: ["#dormhack", "#vanlife", "#campshower"],
        trend: "rising",
        samplePosts: [
          {
            author: "@van.maple",
            text: "Collapsible bucket bath in a parking lot. Not glamorous. Extremely useful.",
            likes: 28000,
            time: "2026-09-02",
          },
        ],
      },
    ],
    search: {
      keyword: "collapsible bath bucket",
      related: ["portable soaking bucket", "camping bath bucket", "dorm bath tub folding"],
      globalIndex: 24,
      risingPct: 88,
      sparkline: spark([10, 11, 11, 12, 13, 14, 16, 17, 19, 21, 24, 27]),
      byCountry: {
        US: 22, CA: 19, MX: 12, SG: 28, MY: 34, TH: 31, ID: 29, PH: 33, VN: 36,
        GB: 26, DE: 18, FR: 14, IT: 13, ES: 15, NL: 17, PL: 12, SE: 16,
      },
    },
    markets: [
      {
        region: "na",
        exists: false,
        status: "whitespace",
        listings: 6,
        sellerCount: 5,
        avgRetailUsd: 0,
        lowRetailUsd: 0,
        projectedRetailUsd: 29,
        platforms: [
          { name: "Amazon US", listings: 4, avgPrice: 24 },
          { name: "REI / camping", listings: 2, avgPrice: 39 },
        ],
        landedCostUsd: 11,
        marginPct: null,
        notes: "Camping collapsible sinks exist; dedicated soak-bucket with insulation does not. Low AOV, easy TikTok demo.",
      },
      {
        region: "sea",
        exists: true,
        status: "competitive",
        listings: 720,
        sellerCount: 210,
        avgRetailUsd: 11,
        lowRetailUsd: 5,
        projectedRetailUsd: 11,
        platforms: [
          { name: "Shopee", listings: 510, avgPrice: 10 },
          { name: "Lazada", listings: 210, avgPrice: 13 },
        ],
        landedCostUsd: 7,
        marginPct: 36,
        notes: "Already a dorm staple. Skip as a hero SKU in SEA.",
      },
      {
        region: "eu",
        exists: true,
        status: "thin",
        listings: 22,
        sellerCount: 11,
        avgRetailUsd: 24,
        lowRetailUsd: 14,
        projectedRetailUsd: 24,
        platforms: [
          { name: "Amazon UK", listings: 10, avgPrice: 22 },
          { name: "Amazon DE", listings: 8, avgPrice: 26 },
          { name: "Decathlon", listings: 4, avgPrice: 29 },
        ],
        landedCostUsd: 12,
        marginPct: 50,
        notes: "Festival + van-life angle. Thin listings, 50% gap.",
      },
    ],
  },
  {
    slug: "hydrogen-bottle",
    name: "Hydrogen water bottle",
    nameZh: "富氢水杯",
    category: "Wellness",
    summary:
      "Electrolysis bottle that markets hydrogen-rich water. Steady Google climb, strong demo video, but Amazon is filling in fast.",
    whyNow:
      "Still a 50%+ gap to factory, but social is at peak not rising. Treat as a cashflow SKU, not a whitespace bet.",
    image: u("photo-1602143407151-7111542de6e8"),
    imageAlt: "Reusable water bottle on a wooden table",
    tags: ["wellness", "crowded", "tiktok"],
    factory: [
      {
        platform: "1688",
        listingCount: 4300,
        supplierCount: 190,
        verifiedFactories: 60,
        unitPriceUsd: 18.5,
        unitPriceCny: 133,
        moq: 10,
        cluster: "Shenzhen · Yongkang",
        orders30d: 21000,
        velocityWoW: 4,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%B8%BB%C7%E1%CB%AE%B1%AD",
      },
    ],
    social: [
      {
        platform: "tiktok",
        mentions7d: 9800,
        views7d: 24_000_000,
        engagementRate: 3.1,
        hashtags: ["#hydrogenwater", "#wellnessbottle"],
        trend: "peak",
        samplePosts: [
          {
            author: "@gym.stack",
            text: "Is hydrogen water real or a $70 light show? I bought one anyway.",
            likes: 99000,
            time: "2026-08-26",
          },
        ],
      },
      {
        platform: "xiaohongshu",
        mentions7d: 3100,
        views7d: 1_400_000,
        engagementRate: 3.0,
        hashtags: ["富氢水杯"],
        trend: "fading",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "hydrogen water bottle",
      related: ["hydrogen water generator", "SPE PEM bottle"],
      globalIndex: 66,
      risingPct: 18,
      sparkline: spark([40, 44, 48, 52, 58, 64, 68, 70, 69, 67, 66, 65]),
      byCountry: {
        US: 72, CA: 60, MX: 25, SG: 48, MY: 36, TH: 30, ID: 28, PH: 27, VN: 22,
        GB: 55, DE: 42, FR: 33, IT: 29, ES: 27, NL: 38, PL: 20, SE: 34,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "competitive",
        listings: 720,
        sellerCount: 190,
        avgRetailUsd: 69,
        lowRetailUsd: 32,
        projectedRetailUsd: 69,
        platforms: [
          { name: "Amazon US", listings: 480, avgPrice: 64 },
          { name: "TikTok Shop US", listings: 140, avgPrice: 49 },
          { name: "Walmart", listings: 100, avgPrice: 55 },
        ],
        landedCostUsd: 31,
        marginPct: 55,
        notes: "Works if you have a brand and ads already. New sellers will fight CAC.",
      },
      {
        region: "sea",
        exists: true,
        status: "competitive",
        listings: 390,
        sellerCount: 120,
        avgRetailUsd: 32,
        lowRetailUsd: 16,
        projectedRetailUsd: 32,
        platforms: [
          { name: "Shopee", listings: 250, avgPrice: 30 },
          { name: "Lazada", listings: 140, avgPrice: 35 },
        ],
        landedCostUsd: 24,
        marginPct: 25,
        notes: "Margin after ads is tight.",
      },
      {
        region: "eu",
        exists: true,
        status: "competitive",
        listings: 260,
        sellerCount: 80,
        avgRetailUsd: 74,
        lowRetailUsd: 39,
        projectedRetailUsd: 74,
        platforms: [
          { name: "Amazon DE", listings: 120, avgPrice: 79 },
          { name: "Amazon UK", listings: 90, avgPrice: 69 },
          { name: "Bol", listings: 50, avgPrice: 72 },
        ],
        landedCostUsd: 34,
        marginPct: 54,
        notes: "Health-claim enforcement is stricter. Sell as a bottle, not a therapy.",
      },
    ],
  },
  {
    slug: "portable-blender-cup",
    name: "USB portable blender cup",
    nameZh: "便携榨汁杯",
    category: "Kitchen",
    summary:
      "The 2025–26 TikTok Shop appliance breakout. Chinese brands already proved product-market fit; NA and EU Amazon are now crowded.",
    whyNow:
      "Useful as a cautionary card: factory is still cheap, but social is at peak and marketplaces are stacked. Better as a bundle add-on than a hero.",
    image: u("photo-1559339352-11d035aa65de"),
    imageAlt: "Fresh smoothie in a glass jar",
    tags: ["saturated", "tiktok", "impulse"],
    factory: [
      {
        platform: "1688",
        listingCount: 9800,
        supplierCount: 410,
        verifiedFactories: 130,
        unitPriceUsd: 8.6,
        unitPriceCny: 62,
        moq: 10,
        cluster: "Zhongshan · Shenzhen",
        orders30d: 67000,
        velocityWoW: -6,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%B1%E3%D0%A1%D5%A9%D6%AC%B1%AD",
      },
    ],
    social: [
      {
        platform: "tiktok",
        mentions7d: 14200,
        views7d: 48_000_000,
        engagementRate: 2.6,
        hashtags: ["#portableblender", "#smoothietok", "#tiktokmademebuyit"],
        trend: "peak",
        samplePosts: [
          {
            author: "@monasty24",
            text: "Watermelon, pineapple, ice, 40 seconds. This is why the portable blender prints money.",
            likes: 890000,
            time: "2026-07-12",
          },
        ],
      },
      {
        platform: "xiaohongshu",
        mentions7d: 1800,
        views7d: 700000,
        engagementRate: 2.2,
        hashtags: ["榨汁杯"],
        trend: "fading",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "portable blender",
      related: ["USB blender bottle", "personal blender cup"],
      globalIndex: 80,
      risingPct: -12,
      sparkline: spark([48, 52, 58, 66, 74, 82, 88, 90, 86, 80, 76, 72]),
      byCountry: {
        US: 78, CA: 70, MX: 48, SG: 66, MY: 72, TH: 69, ID: 74, PH: 70, VN: 64,
        GB: 68, DE: 55, FR: 52, IT: 49, ES: 51, NL: 54, PL: 40, SE: 47,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "saturated",
        listings: 2400,
        sellerCount: 640,
        avgRetailUsd: 29,
        lowRetailUsd: 14,
        projectedRetailUsd: 29,
        platforms: [
          { name: "Amazon US", listings: 1600, avgPrice: 28 },
          { name: "TikTok Shop US", listings: 500, avgPrice: 24 },
          { name: "Walmart", listings: 300, avgPrice: 26 },
        ],
        landedCostUsd: 16,
        marginPct: 45,
        notes: "Headline margin lies. After ads and returns, net is thin. Do not lead with this.",
      },
      {
        region: "sea",
        exists: true,
        status: "saturated",
        listings: 3100,
        sellerCount: 820,
        avgRetailUsd: 14,
        lowRetailUsd: 7,
        projectedRetailUsd: 14,
        platforms: [
          { name: "Shopee", listings: 2100, avgPrice: 13 },
          { name: "TikTok Shop SEA", listings: 1000, avgPrice: 15 },
        ],
        landedCostUsd: 11,
        marginPct: 21,
        notes: "Origin market. Avoid.",
      },
      {
        region: "eu",
        exists: true,
        status: "saturated",
        listings: 1100,
        sellerCount: 280,
        avgRetailUsd: 32,
        lowRetailUsd: 16,
        projectedRetailUsd: 32,
        platforms: [
          { name: "Amazon DE", listings: 480, avgPrice: 34 },
          { name: "Amazon UK", listings: 390, avgPrice: 29 },
          { name: "Allegro", listings: 230, avgPrice: 27 },
        ],
        landedCostUsd: 18,
        marginPct: 44,
        notes: "Same story as NA, with CE blender-blade rules.",
      },
    ],
  },
  {
    slug: "charging-desk-lamp",
    name: "Wireless charging desk lamp",
    nameZh: "无线充电台灯",
    category: "Home office",
    summary:
      "Lamp + Qi charger. Search spikes around back-to-school and gifting. Easy factory SKU, moderate competition.",
    whyNow:
      "Not a whitespace story. Reliable seasonal cashflow with 45–55% gap if you win a colorway or USB-C GaN version.",
    image: u("photo-1513506003901-1e6a229e2d15"),
    imageAlt: "Minimal desk lamp on a workspace",
    tags: ["seasonal", "home-office", "evergreen"],
    factory: [
      {
        platform: "1688",
        listingCount: 7200,
        supplierCount: 300,
        verifiedFactories: 110,
        unitPriceUsd: 12.4,
        unitPriceCny: 89,
        moq: 20,
        cluster: "Zhongshan lighting cluster",
        orders30d: 18400,
        velocityWoW: 5,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%CE%DE%CF%DF%B3%E4%B5%E7%CC%A8%B5%C6",
      },
    ],
    social: [
      {
        platform: "tiktok",
        mentions7d: 1600,
        views7d: 4_200_000,
        engagementRate: 2.8,
        hashtags: ["#desksetup", "#studytok", "#edc"],
        trend: "peak",
        samplePosts: [],
      },
      {
        platform: "xiaohongshu",
        mentions7d: 2400,
        views7d: 1_100_000,
        engagementRate: 3.4,
        hashtags: ["台灯", "桌搭"],
        trend: "peak",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "wireless charging lamp",
      related: ["qi desk lamp", "LED lamp wireless charger"],
      globalIndex: 52,
      risingPct: 22,
      sparkline: spark([30, 28, 27, 32, 40, 48, 44, 38, 36, 42, 50, 55]),
      byCountry: {
        US: 54, CA: 48, MX: 22, SG: 60, MY: 44, TH: 36, ID: 31, PH: 34, VN: 29,
        GB: 50, DE: 46, FR: 33, IT: 28, ES: 26, NL: 41, PL: 24, SE: 38,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "competitive",
        listings: 980,
        sellerCount: 240,
        avgRetailUsd: 49,
        lowRetailUsd: 24,
        projectedRetailUsd: 49,
        platforms: [
          { name: "Amazon US", listings: 700, avgPrice: 47 },
          { name: "Target", listings: 80, avgPrice: 59 },
          { name: "Walmart", listings: 200, avgPrice: 39 },
        ],
        landedCostUsd: 22,
        marginPct: 55,
        notes: "Compete on GaN + USB-C + night-light, not on being a lamp.",
      },
      {
        region: "sea",
        exists: true,
        status: "competitive",
        listings: 640,
        sellerCount: 180,
        avgRetailUsd: 22,
        lowRetailUsd: 11,
        projectedRetailUsd: 22,
        platforms: [
          { name: "Shopee", listings: 420, avgPrice: 21 },
          { name: "Lazada", listings: 220, avgPrice: 24 },
        ],
        landedCostUsd: 16,
        marginPct: 27,
        notes: "Tight.",
      },
      {
        region: "eu",
        exists: true,
        status: "competitive",
        listings: 410,
        sellerCount: 110,
        avgRetailUsd: 46,
        lowRetailUsd: 22,
        projectedRetailUsd: 46,
        platforms: [
          { name: "Amazon DE", listings: 180, avgPrice: 49 },
          { name: "Amazon UK", listings: 150, avgPrice: 42 },
          { name: "Bol", listings: 80, avgPrice: 44 },
        ],
        landedCostUsd: 24,
        marginPct: 48,
        notes: "ERP lighting regs. Fine as a catalog extender.",
      },
    ],
  },
  {
    slug: "heated-eyelash-curler",
    name: "Cordless heated eyelash curler",
    nameZh: "电动烫睫毛器",
    category: "Beauty tools",
    summary:
      "USB-C heated lash curler that replaced the metal squeeze tool on TikTok beauty. Strong visual demo, mid competition, easy shipping.",
    whyNow:
      "Beauty-tool TikTok still converts. Factory sub-$6, retail $18–32. Not whitespace, but operationally simple with healthy gap.",
    image: u("photo-1522337660859-02fbefca4702"),
    imageAlt: "Makeup tools arranged on a vanity",
    tags: ["beauty", "impulse", "tiktok"],
    factory: [
      {
        platform: "1688",
        listingCount: 3600,
        supplierCount: 170,
        verifiedFactories: 48,
        unitPriceUsd: 5.6,
        unitPriceCny: 40,
        moq: 20,
        cluster: "Yiwu · Shenzhen",
        orders30d: 33000,
        velocityWoW: 8,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%B5%E7%B6%AF%CC%CF%BD%DB%C3%AB%C6%F7",
      },
    ],
    social: [
      {
        platform: "tiktok",
        mentions7d: 7600,
        views7d: 22_000_000,
        engagementRate: 4.7,
        hashtags: ["#heatedeyelashcurler", "#lashtok", "#makeuptool"],
        trend: "rising",
        samplePosts: [
          {
            author: "@lash.lab",
            text: "Throw the metal curler away. 8 seconds of heat and my lashes actually stay.",
            likes: 340000,
            time: "2026-09-03",
          },
        ],
      },
      {
        platform: "xiaohongshu",
        mentions7d: 4800,
        views7d: 2_000_000,
        engagementRate: 5.0,
        hashtags: ["电烫睫毛", "眼妆工具"],
        trend: "peak",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "heated eyelash curler",
      related: ["electric lash curler", "USB eyelash curler"],
      globalIndex: 58,
      risingPct: 72,
      sparkline: spark([20, 22, 25, 28, 32, 36, 40, 45, 49, 54, 59, 63]),
      byCountry: {
        US: 70, CA: 61, MX: 34, SG: 55, MY: 48, TH: 42, ID: 46, PH: 52, VN: 38,
        GB: 64, DE: 40, FR: 44, IT: 41, ES: 39, NL: 36, PL: 24, SE: 33,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "competitive",
        listings: 520,
        sellerCount: 160,
        avgRetailUsd: 24,
        lowRetailUsd: 12,
        projectedRetailUsd: 24,
        platforms: [
          { name: "Amazon US", listings: 300, avgPrice: 23 },
          { name: "TikTok Shop US", listings: 150, avgPrice: 18 },
          { name: "Ulta", listings: 70, avgPrice: 28 },
        ],
        landedCostUsd: 11,
        marginPct: 54,
        notes: "Crowded creative. Win with a metal comb + heat safety auto-shutoff.",
      },
      {
        region: "sea",
        exists: true,
        status: "competitive",
        listings: 680,
        sellerCount: 210,
        avgRetailUsd: 9,
        lowRetailUsd: 4,
        projectedRetailUsd: 9,
        platforms: [
          { name: "Shopee", listings: 470, avgPrice: 8 },
          { name: "Lazada", listings: 210, avgPrice: 11 },
        ],
        landedCostUsd: 7,
        marginPct: 22,
        notes: "Low ASP. Better as a Shopee volume play than a brand.",
      },
      {
        region: "eu",
        exists: true,
        status: "competitive",
        listings: 190,
        sellerCount: 60,
        avgRetailUsd: 22,
        lowRetailUsd: 11,
        projectedRetailUsd: 22,
        platforms: [
          { name: "Amazon UK", listings: 80, avgPrice: 21 },
          { name: "Amazon DE", listings: 70, avgPrice: 24 },
          { name: "Notino", listings: 40, avgPrice: 26 },
        ],
        landedCostUsd: 12,
        marginPct: 45,
        notes: "Still room on premium packaging.",
      },
    ],
  },
  {
    slug: "smart-bidet-seat",
    name: "Slim electric bidet seat",
    nameZh: "智能马桶盖",
    category: "Bathroom",
    summary:
      "Drop-in bidet lid for existing toilets. $80–150 Western retail, 40%+ reported profit, factory far lower. Heavy, certified, and already known — but still under-penetrated in NA rentals.",
    whyNow:
      "Hugo 2026 bathroom internal notes call out easy-install lids for EU/US rentals. Not sexy social, high intent search.",
    image: u("photo-1584622650111-993a426fbf0a"),
    imageAlt: "Modern bathroom interior",
    tags: ["bathroom", "high-intent", "cert-heavy"],
    factory: [
      {
        platform: "1688",
        listingCount: 2100,
        supplierCount: 86,
        verifiedFactories: 40,
        unitPriceUsd: 42.0,
        unitPriceCny: 302,
        moq: 20,
        cluster: "Taizhou · Xiaoshan",
        orders30d: 6100,
        velocityWoW: 5,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%D6%C7%C4%DC%C2%ED%CD%B0%B8%C7",
      },
    ],
    social: [
      {
        platform: "youtube",
        mentions7d: 190,
        views7d: 2_200_000,
        engagementRate: 5.1,
        hashtags: ["bidet seat install"],
        trend: "rising",
        samplePosts: [],
      },
      {
        platform: "tiktok",
        mentions7d: 1100,
        views7d: 3_800_000,
        engagementRate: 2.4,
        hashtags: ["#bidet", "#bathroomtok"],
        trend: "rising",
        samplePosts: [
          {
            author: "@rental.fixes",
            text: "Installed a bidet seat with a wrench. Landlord did not care. I will never go back.",
            likes: 54000,
            time: "2026-08-22",
          },
        ],
      },
      {
        platform: "xiaohongshu",
        mentions7d: 900,
        views7d: 400000,
        engagementRate: 2.8,
        hashtags: ["智能马桶盖"],
        trend: "peak",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "bidet toilet seat",
      related: ["electric bidet seat", "attachable bidet", "non electric bidet"],
      globalIndex: 71,
      risingPct: 28,
      sparkline: spark([48, 50, 52, 54, 55, 57, 60, 62, 64, 67, 70, 73]),
      byCountry: {
        US: 88, CA: 70, MX: 18, SG: 52, MY: 34, TH: 40, ID: 28, PH: 22, VN: 20,
        GB: 44, DE: 36, FR: 58, IT: 42, ES: 39, NL: 34, PL: 20, SE: 31,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "competitive",
        listings: 780,
        sellerCount: 120,
        avgRetailUsd: 119,
        lowRetailUsd: 49,
        projectedRetailUsd: 119,
        platforms: [
          { name: "Amazon US", listings: 420, avgPrice: 109 },
          { name: "Home Depot", listings: 80, avgPrice: 159 },
          { name: "Costco / wholesale", listings: 40, avgPrice: 139 },
          { name: "Walmart", listings: 240, avgPrice: 89 },
        ],
        landedCostUsd: 64,
        marginPct: 46,
        notes: "Known category, still 46% gap on slim electric. UL + GFCI copy. Heavy shipping.",
      },
      {
        region: "sea",
        exists: true,
        status: "competitive",
        listings: 310,
        sellerCount: 70,
        avgRetailUsd: 72,
        lowRetailUsd: 28,
        projectedRetailUsd: 72,
        platforms: [
          { name: "Shopee", listings: 180, avgPrice: 65 },
          { name: "Lazada", listings: 130, avgPrice: 80 },
        ],
        landedCostUsd: 52,
        marginPct: 28,
        notes: "Washlets already common in SG/TH. Tighter gap.",
      },
      {
        region: "eu",
        exists: true,
        status: "thin",
        listings: 95,
        sellerCount: 28,
        avgRetailUsd: 129,
        lowRetailUsd: 69,
        projectedRetailUsd: 129,
        platforms: [
          { name: "Amazon DE", listings: 40, avgPrice: 139 },
          { name: "Amazon UK", listings: 30, avgPrice: 119 },
          { name: "Leroy Merlin", listings: 25, avgPrice: 149 },
        ],
        landedCostUsd: 70,
        marginPct: 46,
        notes: "France has bidet culture; electric seats are still thin vs NA. Good EU wedge.",
      },
    ],
  },
  {
    slug: "no-drill-bath-hardware",
    name: "No-drill matte-black bath hardware set",
    nameZh: "免打孔卫浴挂件套装",
    category: "Bathroom",
    summary:
      "Adhesive/vacuum matte-black towel bar + hooks + paper holder as a matching set. TikTok rental content loves it; Amazon sells pieces, not cohesive kits at factory prices.",
    whyNow:
      "Social demo is 15 seconds. Factory sets under $8. Matching-finish kits are thinner than single hooks, especially in EU design-led marketplaces.",
    image: u("photo-1600566752355-35792bedcfea"),
    imageAlt: "Matte black bathroom fixtures",
    tags: ["rental", "impulse", "kit"],
    factory: [
      {
        platform: "1688",
        listingCount: 15000,
        supplierCount: 780,
        verifiedFactories: 200,
        unitPriceUsd: 6.9,
        unitPriceCny: 50,
        moq: 20,
        cluster: "Wenzhou hardware · Yiwu",
        orders30d: 91000,
        velocityWoW: 6,
        searchUrl: "https://s.1688.com/selloffer/offer_search.htm?keywords=%C3%E2%B4%F2%BF%D7%CE%C0%D4%A1%B9%D2%BC%FE",
      },
    ],
    social: [
      {
        platform: "tiktok",
        mentions7d: 4300,
        views7d: 11_000_000,
        engagementRate: 3.8,
        hashtags: ["#renterfriendly", "#bathroommakeover", "#nodrill"],
        trend: "rising",
        samplePosts: [
          {
            author: "@lease.and.leave",
            text: "Matte black, no holes, $22, and my 2014 rental bathroom looks finished.",
            likes: 121000,
            time: "2026-09-01",
          },
        ],
      },
      {
        platform: "xiaohongshu",
        mentions7d: 6700,
        views7d: 3_000_000,
        engagementRate: 4.4,
        hashtags: ["免打孔", "卫浴五金"],
        trend: "peak",
        samplePosts: [],
      },
    ],
    search: {
      keyword: "no drill bathroom hardware",
      related: ["adhesive towel bar black", "renter bathroom hooks", "vacuum bathroom shelf"],
      globalIndex: 47,
      risingPct: 54,
      sparkline: spark([22, 24, 25, 28, 30, 33, 36, 38, 41, 44, 48, 51]),
      byCountry: {
        US: 58, CA: 50, MX: 20, SG: 40, MY: 36, TH: 30, ID: 28, PH: 32, VN: 24,
        GB: 49, DE: 37, FR: 34, IT: 29, ES: 31, NL: 36, PL: 18, SE: 33,
      },
    },
    markets: [
      {
        region: "na",
        exists: true,
        status: "competitive",
        listings: 1100,
        sellerCount: 280,
        avgRetailUsd: 28,
        lowRetailUsd: 12,
        projectedRetailUsd: 28,
        platforms: [
          { name: "Amazon US", listings: 760, avgPrice: 27 },
          { name: "Walmart", listings: 180, avgPrice: 22 },
          { name: "Target", listings: 160, avgPrice: 32 },
        ],
        landedCostUsd: 13,
        marginPct: 54,
        notes: "Piece listings are crowded. 4–6 piece matching kits in one box still photograph better and raise AOV.",
      },
      {
        region: "sea",
        exists: true,
        status: "saturated",
        listings: 2200,
        sellerCount: 540,
        avgRetailUsd: 8,
        lowRetailUsd: 3,
        projectedRetailUsd: 8,
        platforms: [
          { name: "Shopee", listings: 1500, avgPrice: 7 },
          { name: "Lazada", listings: 700, avgPrice: 9 },
        ],
        landedCostUsd: 8,
        marginPct: 0,
        notes: "Commodity. Skip.",
      },
      {
        region: "eu",
        exists: true,
        status: "thin",
        listings: 140,
        sellerCount: 45,
        avgRetailUsd: 32,
        lowRetailUsd: 16,
        projectedRetailUsd: 32,
        platforms: [
          { name: "Amazon DE", listings: 60, avgPrice: 34 },
          { name: "Amazon UK", listings: 50, avgPrice: 29 },
          { name: "IKEA comps", listings: 30, avgPrice: 25 },
        ],
        landedCostUsd: 15,
        marginPct: 53,
        notes: "Design-led kits (brushed gold, stainless) are thinner than NA. 53% gap.",
      },
    ],
  },
];
