import type { ScoredProduct } from "./types";
import type { FactoryExtras, FactoryLogistics, FactoryTerms, PriceTier } from "./storefront-types";
import { charmPrice, zoneForRegion } from "./price-zone";

const u = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=80`;

export const FACTORY_EXTRAS: Record<string, FactoryExtras> = {
  "rack-wardrobe": {
    offerId: "768812045001",
    vendor: "Foshan Linxin Storage Co., Ltd.",
    vendorZh: "佛山市林鑫收纳制品有限公司",
    gallery: [u("photo-1631679706909-1844bbd07221"), u("photo-1616486338812-3dadae4b4ace"), u("photo-1594026112284-02bb6f3352fe"), u("photo-1616628188550-808682f3926d")],
    specs: [
      { name: "Frame", value: "20×40mm powder-coated steel" },
      { name: "Curtain", value: "Blackout polyester, machine washable" },
      { name: "Height", value: "180 cm adjustable" },
      { name: "Load", value: "80 kg distributed" },
      { name: "Install", value: "No-drill, 15 min, hex key included" },
    ],
    optionNames: ["Color", "Width"],
    variants: [
      { sku: "RW-BK-120", options: { Color: "Matte black", Width: "120 cm" }, priceUsd: 28.4, stock: 2400 },
      { sku: "RW-WH-120", options: { Color: "Warm white", Width: "120 cm" }, priceUsd: 28.4, stock: 1800 },
      { sku: "RW-BK-160", options: { Color: "Matte black", Width: "160 cm" }, priceUsd: 34.9, stock: 960 },
    ],
    leadTime: "3–7 days after payment (in-stock SKUs)",
    warranty: "12 months on welds and coating",
    customMoq: 50,
    unit: "set",
    weightGrams: 12500,
    packing: "1 set / carton, 0.12 CBM, 13.8 kg gross",
    certifications: ["ISO 9001 factory", "REACH coating"],
  },
  "enamel-pegboard": {
    offerId: "768812045002",
    vendor: "Zhongshan Enamel Homeware Factory",
    vendorZh: "中山市珐琅家居制品厂",
    gallery: [u("photo-1556912173-46c336c7fd55"), u("photo-1556911220-e15b29be8c8f"), u("photo-1616486338812-3dadae4b4ace")],
    specs: [
      { name: "Panel", value: "0.6 mm steel + porcelain enamel" },
      { name: "Magnet", value: "Compatible with N35+ neodymium hooks" },
      { name: "Size", value: "60×90 cm / 90×120 cm" },
      { name: "Fixing", value: "Wall anchors or rail hangers; renter kit uses rails" },
    ],
    optionNames: ["Finish", "Size"],
    variants: [
      { sku: "EP-WH-6090", options: { Finish: "Gloss white", Size: "60×90 cm" }, priceUsd: 16.8, stock: 3200 },
      { sku: "EP-GR-6090", options: { Finish: "Sage enamel", Size: "60×90 cm" }, priceUsd: 18.2, stock: 1400 },
      { sku: "EP-WH-90120", options: { Finish: "Gloss white", Size: "90×120 cm" }, priceUsd: 24.5, stock: 800 },
    ],
    leadTime: "5–10 days",
    warranty: "24 months against enamel chip in normal use",
    customMoq: 100,
    unit: "panel",
    weightGrams: 4200,
    packing: "Corner protectors + carton, 0.04 CBM",
    certifications: ["RoHS", "Food-contact enamel glaze"],
  },
  "retractable-laundry-rack": {
    offerId: "768812045003",
    vendor: "Zhaoqing Lifting Hardware Co.",
    vendorZh: "肇庆市升降五金有限公司",
    gallery: [u("photo-1610557892470-55d9e80c0bce"), u("photo-1581578731548-c64695cc6952"), u("photo-1616628188550-808682f3926d")],
    specs: [
      { name: "Type", value: "Hand-crank ceiling mount (motor optional)" },
      { name: "Bars", value: "4 stainless rods, 1.5 m" },
      { name: "Load", value: "30 kg wet laundry" },
      { name: "Ceiling", value: "Concrete or wood joist kit included" },
    ],
    optionNames: ["Drive", "Finish"],
    variants: [
      { sku: "LR-MAN-WH", options: { Drive: "Manual crank", Finish: "White" }, priceUsd: 19.6, stock: 5000 },
      { sku: "LR-MOT-WH", options: { Drive: "Electric 110/220V", Finish: "White" }, priceUsd: 42.0, stock: 700 },
    ],
    leadTime: "3–5 days manual / 10 days electric",
    warranty: "18 months mechanism",
    customMoq: 30,
    unit: "set",
    weightGrams: 6800,
    packing: "Knock-down carton, 0.08 CBM",
    certifications: ["CE (electric SKU)", "RoHS"],
  },
  "pdrn-ampoule": {
    offerId: "768812045004",
    vendor: "Guangzhou Baiyun Cosmetics OEM",
    vendorZh: "广州白云区化妆品OEM厂",
    gallery: [u("photo-1620916566398-39f1143ab7be"), u("photo-1556228720-195a672e8a03"), u("photo-1556228578-8c89e6adf883")],
    specs: [
      { name: "INCI highlight", value: "Sodium DNA (PDRN analog), panthenol, HA" },
      { name: "Fill", value: "2 ml × 10 vials / box" },
      { name: "pH", value: "5.5–6.2" },
      { name: "Shelf life", value: "24 months unopened" },
    ],
    optionNames: ["Set"],
    variants: [
      { sku: "PD-10", options: { Set: "10 × 2 ml" }, priceUsd: 3.4, stock: 8000 },
      { sku: "PD-30", options: { Set: "30 × 2 ml" }, priceUsd: 8.9, stock: 2000 },
    ],
    leadTime: "7–15 days with private label",
    warranty: "Unopened shelf-life guarantee",
    customMoq: 500,
    unit: "box",
    weightGrams: 180,
    packing: "Paper sleeve + inner tray",
    certifications: ["ISO 22716 GMP", "COA per batch — buyer files CPNP/FDA"],
  },
  "foldable-tpu-bathtub": {
    offerId: "768812045005",
    vendor: "Taizhou Aqua Fold Plastics",
    vendorZh: "台州市折叠加倍塑胶厂",
    gallery: [u("photo-1507652313519-d4e9174996dd"), u("photo-1584622650111-993a426fbf0a"), u("photo-1600566753190-17f0baa2a6c3")],
    specs: [
      { name: "Material", value: "Food-grade TPU inner + Oxford shell" },
      { name: "Capacity", value: "Adult soak ~300 L" },
      { name: "Folded", value: "15 cm thick" },
      { name: "Load", value: "200 kg" },
    ],
    optionNames: ["Size", "Color"],
    variants: [
      { sku: "TB-ADU-GY", options: { Size: "Adult 80×50×70", Color: "Grey" }, priceUsd: 22.0, stock: 1500 },
      { sku: "TB-ICE-NV", options: { Size: "Ice bath 90×50×75", Color: "Navy" }, priceUsd: 26.5, stock: 900 },
    ],
    leadTime: "5–8 days",
    warranty: "6 months seams / 12 months TPU puncture (fair use)",
    customMoq: 50,
    unit: "pc",
    weightGrams: 4500,
    packing: "Vacuum bag + carton, 0.06 CBM",
    certifications: ["REACH TPU", "CA Prop 65 statement available"],
  },
  "sauna-blanket": {
    offerId: "768812045006",
    vendor: "Shenzhen Heatwell Electronics",
    vendorZh: "深圳市热维电子有限公司",
    gallery: [u("photo-1544161515-4ab6ce6db874"), u("photo-1600334129128-685c5582fd35"), u("photo-1540555700478-4be289fbecef")],
    specs: [
      { name: "Heat", value: "Far infrared carbon fiber, 3 zones" },
      { name: "Temp", value: "35–75 °C, auto shutoff" },
      { name: "Power", value: "110V / 220V dual, 180 W" },
      { name: "Fabric", value: "Oxford + PU inner, zipper" },
    ],
    optionNames: ["Voltage", "Controller"],
    variants: [
      { sku: "SB-110-B", options: { Voltage: "110V", Controller: "Basic timer" }, priceUsd: 38.0, stock: 600 },
      { sku: "SB-220-P", options: { Voltage: "220V", Controller: "App + timer" }, priceUsd: 46.0, stock: 400 },
    ],
    leadTime: "7–12 days with ETL run",
    warranty: "12 months electronics",
    customMoq: 20,
    unit: "pc",
    weightGrams: 3200,
    packing: "Carry bag + carton",
    certifications: ["CE", "ETL available on 110V run"],
  },
  "blue-light-wand": {
    offerId: "768812045007",
    vendor: "Shenzhen Bao'an Beauty Devices",
    vendorZh: "深圳宝安美容仪器厂",
    gallery: [u("photo-1487412947147-5cebf100ffc2"), u("photo-1598440947619-2c35fc9aa908"), u("photo-1556228578-8c89e6adf883")],
    specs: [
      { name: "LED", value: "415 nm blue, 10 min session timer" },
      { name: "Battery", value: "USB-C, 90 min runtime" },
      { name: "Body", value: "ABS + 304 steel head" },
    ],
    optionNames: ["Color"],
    variants: [
      { sku: "BL-WH", options: { Color: "White" }, priceUsd: 14.2, stock: 4000 },
      { sku: "BL-PK", options: { Color: "Blush" }, priceUsd: 14.2, stock: 2200 },
    ],
    leadTime: "5–10 days",
    warranty: "12 months",
    customMoq: 100,
    unit: "pc",
    weightGrams: 220,
    packing: "Gift box, 0.002 CBM",
    certifications: ["CE", "FCC", "RoHS — cosmetic device, not a medical claim"],
  },
  "heated-towel-rail": {
    offerId: "768812045008",
    vendor: "Wenzhou Bath Heat Electrical",
    vendorZh: "温州浴热电器有限公司",
    gallery: [u("photo-1552321554-5fefe8c9ef14"), u("photo-1600566752355-35792bedcfea"), u("photo-1584622781564-1d987f7333c1")],
    specs: [
      { name: "Power", value: "Plug-in 80 W, IPX4" },
      { name: "Bars", value: "5 round, 304 stainless or powder coat" },
      { name: "Size", value: "50×80 cm wall mount" },
    ],
    optionNames: ["Finish", "Plug"],
    variants: [
      { sku: "HT-BK-US", options: { Finish: "Matte black", Plug: "US 110V" }, priceUsd: 21.5, stock: 1800 },
      { sku: "HT-BK-EU", options: { Finish: "Matte black", Plug: "EU/UK 220V" }, priceUsd: 21.5, stock: 1600 },
      { sku: "HT-GD-US", options: { Finish: "Brushed gold", Plug: "US 110V" }, priceUsd: 24.8, stock: 500 },
    ],
    leadTime: "7–12 days",
    warranty: "24 months heating element",
    customMoq: 50,
    unit: "pc",
    weightGrams: 4100,
    packing: "Foam + carton, 0.05 CBM",
    certifications: ["UL pending / ETL on US SKU", "CE on EU SKU"],
  },
  "neck-pov-camera": {
    offerId: "768812045009",
    vendor: "Shenzhen Huaqiang Imaging OEM",
    vendorZh: "深圳华强北影像OEM",
    gallery: [u("photo-1526170375885-4d8ecf77b99f"), u("photo-1502920917128-1aa500764cbd"), u("photo-1513506003901-1e6a229e2d15")],
    specs: [
      { name: "Sensor", value: "1080p 30fps CMOS" },
      { name: "Wear", value: "Necklace + magnetic clip" },
      { name: "Storage", value: "MicroSD to 128 GB" },
      { name: "Battery", value: "90 min, USB-C" },
    ],
    optionNames: ["Bundle"],
    variants: [
      { sku: "PV-CAM", options: { Bundle: "Camera only" }, priceUsd: 18.9, stock: 2200 },
      { sku: "PV-KIT", options: { Bundle: "Camera + 64GB + case" }, priceUsd: 24.5, stock: 900 },
    ],
    leadTime: "5–8 days",
    warranty: "12 months",
    customMoq: 50,
    unit: "pc",
    weightGrams: 85,
    packing: "Retail box",
    certifications: ["FCC", "CE", "recording-notice copy required in EU/NA"],
  },
  "collapsible-shower-bucket": {
    offerId: "768812045010",
    vendor: "Linyi Foldware Plastics",
    vendorZh: "临沂市折叠塑业",
    gallery: [u("photo-1478131143081-80f7f84ca84d"), u("photo-1478131143081-80f7f84ca84d"), u("photo-1504280390367-361c6d9f38f4")],
    specs: [
      { name: "Material", value: "PP + TPE seal, insulated jacket optional" },
      { name: "Volume", value: "40 L soak / camp wash" },
      { name: "Folded", value: "8 cm" },
    ],
    optionNames: ["Jacket"],
    variants: [
      { sku: "CB-40", options: { Jacket: "Bare PP" }, priceUsd: 4.8, stock: 9000 },
      { sku: "CB-40I", options: { Jacket: "Insulated Oxford" }, priceUsd: 7.2, stock: 2500 },
    ],
    leadTime: "3–5 days",
    warranty: "6 months",
    customMoq: 100,
    unit: "pc",
    weightGrams: 900,
    packing: "20 pcs / master carton",
    certifications: ["Food-contact PP"],
  },
  "hydrogen-bottle": {
    offerId: "768812045011",
    vendor: "Yongkang Hydrogen Drinkware",
    vendorZh: "永康市富氢杯厂",
    gallery: [u("photo-1602143407151-7111542de6e8"), u("photo-1523362628745-0c100150b504"), u("photo-1571019613454-1cb2f99b2d8b")],
    specs: [
      { name: "Tech", value: "SPE/PEM electrolysis" },
      { name: "Capacity", value: "420 ml Tritan" },
      { name: "Cycle", value: "3 / 5 / 10 min" },
    ],
    optionNames: ["Color"],
    variants: [
      { sku: "HB-BK", options: { Color: "Black" }, priceUsd: 18.5, stock: 1600 },
      { sku: "HB-SV", options: { Color: "Silver" }, priceUsd: 18.5, stock: 1100 },
    ],
    leadTime: "7 days",
    warranty: "12 months generator",
    customMoq: 50,
    unit: "pc",
    weightGrams: 480,
    packing: "Gift box",
    certifications: ["CE", "FDA food-contact cup — no therapy claims"],
  },
  "portable-blender-cup": {
    offerId: "768812045012",
    vendor: "Zhongshan Mini Appliance Co.",
    vendorZh: "中山小家电有限公司",
    gallery: [u("photo-1559339352-11d035aa65de"), u("photo-1570197788417-0e82375c9371"), u("photo-1546173159-315724a31696")],
    specs: [
      { name: "Motor", value: "USB-C, 6 blades" },
      { name: "Jar", value: "350 ml Tritan" },
    ],
    optionNames: ["Color"],
    variants: [
      { sku: "PB-WH", options: { Color: "White" }, priceUsd: 8.6, stock: 12000 },
      { sku: "PB-GN", options: { Color: "Matcha" }, priceUsd: 8.6, stock: 4000 },
    ],
    leadTime: "5 days",
    warranty: "6 months",
    customMoq: 100,
    unit: "pc",
    weightGrams: 420,
    packing: "Color box",
    certifications: ["CE", "FCC charger"],
  },
  "charging-desk-lamp": {
    offerId: "768812045013",
    vendor: "Zhongshan Lighting Cluster OEM",
    vendorZh: "中山灯具产业带OEM",
    gallery: [u("photo-1513506003901-1e6a229e2d15"), u("photo-1497366216548-37526070297c"), u("photo-1616486338812-3dadae4b4ace")],
    specs: [
      { name: "Light", value: "LED 3000–5000 K, 3 steps" },
      { name: "Charge", value: "15 W Qi + USB-A" },
    ],
    optionNames: ["Finish"],
    variants: [
      { sku: "DL-BK", options: { Finish: "Black" }, priceUsd: 12.4, stock: 3000 },
      { sku: "DL-WD", options: { Finish: "Wood grain" }, priceUsd: 13.9, stock: 900 },
    ],
    leadTime: "7–10 days",
    warranty: "12 months",
    customMoq: 100,
    unit: "pc",
    weightGrams: 1100,
    packing: "Retail box",
    certifications: ["CE", "Qi certified coil option"],
  },
  "heated-eyelash-curler": {
    offerId: "768812045014",
    vendor: "Yiwu Beauty Tools Factory",
    vendorZh: "义乌美妆工具厂",
    gallery: [u("photo-1522337660859-02fbefca4702"), u("photo-1487412947147-5cebf100ffc2"), u("photo-1596462502278-27bfdc403348")],
    specs: [
      { name: "Heat", value: "PTC, auto-off 8 s" },
      { name: "Power", value: "USB-C" },
    ],
    optionNames: ["Color"],
    variants: [
      { sku: "EC-BK", options: { Color: "Black" }, priceUsd: 5.6, stock: 8000 },
      { sku: "EC-PK", options: { Color: "Pink" }, priceUsd: 5.6, stock: 6000 },
    ],
    leadTime: "3–5 days",
    warranty: "6 months",
    customMoq: 200,
    unit: "pc",
    weightGrams: 65,
    packing: "Blister or gift box",
    certifications: ["CE", "RoHS"],
  },
  "smart-bidet-seat": {
    offerId: "768812045015",
    vendor: "Taizhou Smart Sanitary OEM",
    vendorZh: "台州智能卫浴OEM",
    gallery: [u("photo-1584622650111-993a426fbf0a"), u("photo-1552321554-5fefe8c9ef14"), u("photo-1600566753086-00f18fb6b3ea")],
    specs: [
      { name: "Fit", value: "Elongated / round adapter plates" },
      { name: "Functions", value: "Rear/front wash, warm seat, night light" },
      { name: "Power", value: "110V or 220V, GFCI recommended" },
    ],
    optionNames: ["Shape", "Voltage"],
    variants: [
      { sku: "BD-EL-110", options: { Shape: "Elongated", Voltage: "110V" }, priceUsd: 42.0, stock: 400 },
      { sku: "BD-EL-220", options: { Shape: "Elongated", Voltage: "220V" }, priceUsd: 42.0, stock: 350 },
    ],
    leadTime: "10–18 days",
    warranty: "24 months electronics",
    customMoq: 20,
    unit: "pc",
    weightGrams: 5200,
    packing: "Double carton, 0.14 CBM",
    certifications: ["UL / ETL on 110V", "CE on 220V"],
  },
  "no-drill-bath-hardware": {
    offerId: "768812045016",
    vendor: "Wenzhou Renter Hardware",
    vendorZh: "温州免打孔卫浴五金",
    gallery: [u("photo-1600566752355-35792bedcfea"), u("photo-1552321554-5fefe8c9ef14"), u("photo-1584622781564-1d987f7333c1")],
    specs: [
      { name: "Set", value: "Towel bar, paper holder, 2 hooks, shelf" },
      { name: "Fixing", value: "VHB adhesive + vacuum backup" },
      { name: "Finish", value: "304 stainless, PVD matte black" },
    ],
    optionNames: ["Finish", "Kit"],
    variants: [
      { sku: "NH-BK-4", options: { Finish: "Matte black", Kit: "4-piece" }, priceUsd: 6.9, stock: 7000 },
      { sku: "NH-GD-4", options: { Finish: "Brushed gold", Kit: "4-piece" }, priceUsd: 8.4, stock: 1800 },
      { sku: "NH-BK-6", options: { Finish: "Matte black", Kit: "6-piece" }, priceUsd: 9.8, stock: 1200 },
    ],
    leadTime: "5 days",
    warranty: "12 months finish; adhesive not warranted on dirty tile",
    customMoq: 100,
    unit: "set",
    weightGrams: 780,
    packing: "Color box, 20 sets / carton",
    certifications: ["304 mill cert", "salt-spray 24 h"],
  },
};

const LOGISTICS: Record<string, FactoryLogistics> = {
  "rack-wardrobe": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 50,
    customNotes: "Curtain print, frame color, and retail carton from 50 sets. Small logo hangtag from 20.",
    overseasRecipient: false,
    overseasMode: "agent-ddp",
    overseasNotes: "12+ kg / 0.12 CBM — factory will not book a residential overseas address. They truck to your Shenzhen/Ningbo forwarder; agent DDP to NA/EU warehouse.",
    sampleToOverseas: true,
    dropshipParcel: false,
  },
  "enamel-pegboard": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 100,
    customNotes: "Pantone enamel, silk-screen logo, hook kit SKU mix from 100 panels.",
    overseasRecipient: false,
    overseasMode: "agent-ddp",
    overseasNotes: "Fragile enamel — factory packs for export but hands off at China port. Agent DDP recommended; no door-to-door from the mill.",
    sampleToOverseas: true,
    dropshipParcel: false,
  },
  "retractable-laundry-rack": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 30,
    customNotes: "Manual SKU: color + logo from 30. Electric SKU: voltage + plug + CE/ETL run from 50.",
    overseasRecipient: false,
    overseasMode: "agent-ddp",
    overseasNotes: "Ceiling hardware + optional motor. Factory ships EXW Zhaoqing; agent DDP. Electric SKU needs destination plug/cert — factory cooperates, buyer files.",
    sampleToOverseas: true,
    dropshipParcel: false,
  },
  "pdrn-ampoule": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 500,
    customNotes: "Private label formula lock, box, and vial print from 500 boxes. Formula change is a new GMP batch.",
    overseasRecipient: false,
    overseasMode: "exw-only",
    overseasNotes: "Cosmetics: factory will not ship to a consumer overseas address. Buyer (or licensed importer) must file CPNP/FDA and book the lane. Samples can go courier with MSDS.",
    sampleToOverseas: true,
    dropshipParcel: false,
  },
  "foldable-tpu-bathtub": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 50,
    customNotes: "Oxford color, logo print, ice-bath vs soak size from 50 pcs.",
    overseasRecipient: false,
    overseasMode: "agent-ddp",
    overseasNotes: "Bulky even folded. Factory loads cartons to your forwarder; DDP via agent. Not a letter-box dropship SKU.",
    sampleToOverseas: true,
    dropshipParcel: false,
  },
  "sauna-blanket": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 20,
    customNotes: "Voltage, controller, and logo from 20 pcs. ETL 110V run quoted separately.",
    overseasRecipient: true,
    overseasMode: "agent-ddp",
    overseasNotes: "Factory can consign a sample or small carton to an overseas warehouse via 4PX/YunExpress. Residential DDP for bulk still goes through your agent.",
    sampleToOverseas: true,
    dropshipParcel: true,
  },
  "blue-light-wand": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 100,
    customNotes: "ABS color, gift box, and CE/FCC mark from 100 pcs. No medical claims on OEM copy.",
    overseasRecipient: true,
    overseasMode: "factory-ddp",
    overseasNotes: "Small parcel: factory quotes Cainiao / 4PX DDP to NA/EU/SEA addresses on 100+ units. Residential dropship after first carton is in a 3PL.",
    sampleToOverseas: true,
    dropshipParcel: true,
  },
  "heated-towel-rail": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 50,
    customNotes: "Finish, plug standard, and logo from 50. US SKU waits on ETL lot.",
    overseasRecipient: false,
    overseasMode: "agent-ddp",
    overseasNotes: "Mains electrical — factory will not DDP a plug-in heater to a home address. EXW + agent; destination cert is buyer-owned.",
    sampleToOverseas: true,
    dropshipParcel: false,
  },
  "neck-pov-camera": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 50,
    customNotes: "Silicone color, box, and firmware splash from 50. Recording-notice card required for EU/NA.",
    overseasRecipient: true,
    overseasMode: "factory-ddp",
    overseasNotes: "Huaqiang OEM will DDP samples and small lots via ePacket-class. Bulk still cheaper as agent DDP to a 3PL.",
    sampleToOverseas: true,
    dropshipParcel: true,
  },
  "collapsible-shower-bucket": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 100,
    customNotes: "Jacket color and logo from 100 pcs.",
    overseasRecipient: true,
    overseasMode: "factory-ddp",
    overseasNotes: "Light PP — factory routinely DDP cartons to SEA/NA warehouses and can parcel-sample to a residential address.",
    sampleToOverseas: true,
    dropshipParcel: true,
  },
  "hydrogen-bottle": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 50,
    customNotes: "Tritan color, box, and silent firmware (no therapy claims) from 50.",
    overseasRecipient: true,
    overseasMode: "agent-ddp",
    overseasNotes: "Battery + electrolysis. Samples courier OK. Bulk DDP via agent; some couriers treat SPE/PEM units as dangerous goods — confirm the lane.",
    sampleToOverseas: true,
    dropshipParcel: true,
  },
  "portable-blender-cup": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 100,
    customNotes: "Color and color-box from 100. Motor tooling is shared — no exclusive housing under 5k.",
    overseasRecipient: true,
    overseasMode: "factory-ddp",
    overseasNotes: "Classic 1688 dropship SKU. Factory DDP to overseas 3PL and can ship individual parcels after you warehouse.",
    sampleToOverseas: true,
    dropshipParcel: true,
  },
  "charging-desk-lamp": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 100,
    customNotes: "Finish, Qi coil, and box from 100. Qi-certified coil is a paid option.",
    overseasRecipient: true,
    overseasMode: "agent-ddp",
    overseasNotes: "Li-ion + Qi. Factory packs for export; overseas residential DDP via agent. Samples go courier.",
    sampleToOverseas: true,
    dropshipParcel: true,
  },
  "heated-eyelash-curler": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 200,
    customNotes: "Color, blister vs gift box from 200 pcs.",
    overseasRecipient: true,
    overseasMode: "factory-ddp",
    overseasNotes: "Yiwu factory DDP samples and small lots to NA/EU/SEA addresses. Easy 3PL dropship after first carton.",
    sampleToOverseas: true,
    dropshipParcel: true,
  },
  "smart-bidet-seat": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 20,
    customNotes: "Shape plate, voltage, and logo from 20. UL/ETL 110V is a separate production lot.",
    overseasRecipient: false,
    overseasMode: "exw-only",
    overseasNotes: "5+ kg sanitary electrical. Factory EXW Taizhou only — they will not accept an overseas residential consignee. Agent DDP + GFCI copy required.",
    sampleToOverseas: true,
    dropshipParcel: false,
  },
  "no-drill-bath-hardware": {
    oemLogo: true,
    oemColor: true,
    oemPackaging: true,
    customMoq: 100,
    customNotes: "PVD color and kit mix from 100 sets.",
    overseasRecipient: true,
    overseasMode: "factory-ddp",
    overseasNotes: "Light hardware. Factory DDP cartons to overseas warehouses and will courier a sample set to a residential address.",
    sampleToOverseas: true,
    dropshipParcel: true,
  },
};

const DEFAULT_LOGISTICS: FactoryLogistics = {
  oemLogo: true,
  oemColor: true,
  oemPackaging: false,
  customMoq: 100,
  customNotes: "Logo / color from listed custom MOQ. Confirm each PO.",
  overseasRecipient: false,
  overseasMode: "agent-ddp",
  overseasNotes: "EXW to your China forwarder. International DDP via agent — not in the unit price.",
  sampleToOverseas: true,
  dropshipParcel: false,
};

export function logisticsFor(slug: string): FactoryLogistics {
  return LOGISTICS[slug] ?? { ...DEFAULT_LOGISTICS };
}

export function priceTiers(unitUsd: number, unitCny: number, moq: number): PriceTier[] {
  return [
    { minQty: Math.max(1, moq), priceUsd: unitUsd, priceCny: unitCny },
    { minQty: Math.max(moq, 20), priceUsd: round2(unitUsd * 0.92), priceCny: Math.round(unitCny * 0.92) },
    { minQty: 100, priceUsd: round2(unitUsd * 0.82), priceCny: Math.round(unitCny * 0.82) },
  ];
}

export function factoryTerms(product: ScoredProduct, extras: FactoryExtras): FactoryTerms {
  const f = product.factory[0];
  const log = logisticsFor(product.slug);
  const ship =
    log.overseasMode === "factory-ddp"
      ? `Factory can DDP small lots to an overseas warehouse or (on request) a commercial address. ${log.overseasNotes}`
      : log.overseasMode === "agent-ddp"
        ? `EXW ${f.cluster}. Factory trucks to your China forwarder; international DDP is via agent, not in the unit price. ${log.overseasNotes}`
        : `EXW ${f.cluster} only — factory will not take an overseas consignee. ${log.overseasNotes}`;
  const customBits = [
    log.oemLogo ? "logo" : null,
    log.oemColor ? "color" : null,
    log.oemPackaging ? "retail box" : null,
  ].filter(Boolean);
  return {
    moq: f.moq,
    unit: extras.unit,
    leadTime: extras.leadTime,
    payment: "Alipay / T/T. 30% deposit, 70% before shipment. Samples prepaid.",
    sample: log.sampleToOverseas
      ? `Sample ships to an overseas address (buyer pays freight). Fee often credited against bulk ≥ ${log.customMoq} ${extras.unit}.`
      : `Domestic China sample only. Overseas sample must go through your forwarder.`,
    warranty: extras.warranty,
    returns: "Quality issues within 7 days of receipt with unboxing photos. Cosmetic damage after delivery is not covered unless QC video was requested.",
    shipping: ship,
    customization: customBits.length
      ? `${customBits.join(" / ")} from ${log.customMoq} ${extras.unit}. ${log.customNotes}`
      : `No OEM on this mill. ${log.customNotes}`,
    inspection: "SGS / QIMA welcome. Buyer books and pays. Factory cooperates on-site.",
    packing: extras.packing,
  };
}

export function retailTarget(product: ScoredProduct): { retail: number; compare: number } {
  const zone = zoneForRegion(product.priceZones, product.bestRegion);
  const retail = zone?.recommendedUsd ?? product.factory[0].unitPriceUsd * 3.2;
  return { retail: charmPrice(retail), compare: charmPrice(retail * 1.15) };
}

export function descriptionHtml(product: ScoredProduct, extras: FactoryExtras): { en: string; zh: string; plain: string } {
  const f = product.factory[0];
  const en = `
<p>${product.summary}</p>
<p>${product.whyNow}</p>
<p>Factory-direct from <strong>${extras.vendor}</strong> (${extras.vendorZh}) in ${f.cluster}. 1688 offer ${extras.offerId}. MOQ ${f.moq} ${extras.unit}. Certifications: ${extras.certifications.join(", ")}.</p>
<ul>${extras.specs.map((s) => `<li><strong>${s.name}:</strong> ${s.value}</li>`).join("")}</ul>
<p>Use this listing as the storefront master: retail copy above, factory terms and cost in the merchant panel. Do not paste 1688 Chinese invoices into the customer package.</p>`;
  const zh = `<p>${product.nameZh}，${extras.vendorZh} 货源，1688 单号 ${extras.offerId}。起订 ${f.moq} ${extras.unit}。${product.summary}</p>`;
  return { en: en.trim(), zh, plain: `${product.summary} ${product.whyNow}` };
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
