/**
 * Display labels for preference chips and gallery filters.
 * Stored preference values stay English for matching; UI shows localized text.
 */

const zh: Record<string, string> = {
  // Genres / traditions
  portrait: '肖像',
  'landscape painting': '风景画',
  'religious art': '宗教艺术',
  'mythological painting': '神话画',
  'history painting': '历史画',
  'genre art': '风俗画',
  'still life': '静物',
  'animal art': '动物画',
  'abstract art': '抽象艺术',
  'figure painting': '人物画',
  'self-portrait': '自画像',
  allegory: '寓意画',
  'marine art': '海景画',
  cityscape: '城市风景',
  nude: '裸体画',
  Painting: '绘画',
  painting: '绘画',
  'group portrait': '群像',
  'historiated portrait': '叙事肖像',
  'battle painting': '战争画',
  'family portrait': '家庭肖像',
  'floral painting': '花卉画',
  'double portrait': '双人肖像',
  'interior view': '室内景',
  tronie: '特罗尼头像',
  'equestrian portrait': '骑马肖像',
  'Arthurian painting': '亚瑟王题材',
  'French Realism': '法国现实主义',
  schutterstuk: '民兵群像',
  Naturalism: '自然主义',
  Expressionism: '表现主义',
  realism: '现实主义',
  Realism: '现实主义',
  'catafalque portrait': '灵柩肖像',
  vanitas: '虚空派',
  'Post-impressionism': '后印象派',
  'Fête galante': '游乐画',
  satire: '讽刺画',
  'donor portrait': '捐赠者肖像',
  figure: '人物',
  Baroque: '巴洛克',
  Romanticism: '浪漫主义',
  Impressionism: '印象派',
  Surrealism: '超现实主义',
  Cubism: '立体主义',
  Fauvism: '野兽派',
  Symbolism: '象征主义',
  'ink wash painting': '水墨画',
  'shan shui': '山水',
  'literati painting': '文人画',
  handscroll: '手卷',
  'hanging scroll': '立轴',
  'ukiyo-e': '浮世绘',
  nihonga: '日本画',
  'yamato-e': '大和绘',
  'screen painting': '屏风画',
  'bird-and-flower painting': '花鸟画',
  'Chinese painting': '中国画',
  'Japanese painting': '日本绘画',
  'Korean painting': '韩国绘画',
  'Mughal miniature': '莫卧儿细密画',
  'Persian miniature': '波斯细密画',
  'Rajput painting': '拉杰普特绘画',
  'Pahari painting': '帕哈里绘画',
  'Indian painting': '印度绘画',
  thangka: '唐卡',
  'miniature painting': '细密画',
  'Company style': '公司画派',
  'Southeast Asian painting': '东南亚绘画',
  'Balinese painting': '巴厘绘画',
  'Indonesian painting': '印尼绘画',
  'Thai painting': '泰国绘画',
  'Vietnamese painting': '越南绘画',
  'Aboriginal Australian art': '澳大利亚原住民艺术',
  'Oceanic art': '大洋洲艺术',
  'Pacific Islander art': '太平洋岛民艺术',
  'Maori art': '毛利艺术',
  'African art': '非洲艺术',
  'Ethiopian art': '埃塞俄比亚艺术',
  'Egyptian painting': '埃及绘画',
  'Coptic art': '科普特艺术',
  'Islamic miniature': '伊斯兰细密画',
  'Ottoman miniature': '奥斯曼细密画',
  'Arabic calligraphy painting': '阿拉伯书法绘画',
  'North African art': '北非艺术',
  'West African art': '西非艺术',
  'Contemporary African art': '当代非洲艺术',
  'Mesoamerican art': '中美洲艺术',
  'pre-Columbian art': '前哥伦布艺术',
  'Indigenous American art': '美洲原住民艺术',
  'Native American art': '美洲原住民艺术',
  'Latin American art': '拉丁美洲艺术',
  'Mexican muralism': '墨西哥壁画运动',
  'Caribbean art': '加勒比艺术',
  'Andean art': '安第斯艺术',
  'Brazilian painting': '巴西绘画',
  'American painting': '美国绘画',

  // Eras
  ancient: '古代',
  'classical-antiquity': '古典时代',
  medieval: '中世纪',
  'islamic-golden-age': '伊斯兰黄金时代',
  'song-yuan': '宋元',
  'ming-qing': '明清',
  'edo-period': '江户时代',
  'mughal-era': '莫卧儿时代',
  renaissance: '文艺复兴',
  baroque: '巴洛克',
  'neoclassical-romantic': '新古典与浪漫主义',
  'impressionist-era': '印象派时代',
  modern: '现代',
  contemporary: '当代',

  // Moods
  contemplative: '沉思',
  dramatic: '戏剧性',
  intimate: '亲密',
  epic: '史诗',

  // Countries / civilizations (prefs + common dataset)
  Egypt: '埃及',
  Ethiopia: '埃塞俄比亚',
  Nigeria: '尼日利亚',
  Ghana: '加纳',
  Senegal: '塞内加尔',
  Mali: '马里',
  Morocco: '摩洛哥',
  Algeria: '阿尔及利亚',
  Tunisia: '突尼斯',
  'South Africa': '南非',
  Kenya: '肯尼亚',
  Congo: '刚果',
  Sudan: '苏丹',
  'Kingdom of Benin': '贝宁王国',
  'Mali Empire': '马里帝国',
  'United States': '美国',
  Mexico: '墨西哥',
  Canada: '加拿大',
  Brazil: '巴西',
  Argentina: '阿根廷',
  Peru: '秘鲁',
  Chile: '智利',
  Colombia: '哥伦比亚',
  Cuba: '古巴',
  Haiti: '海地',
  Jamaica: '牙买加',
  'Trinidad and Tobago': '特立尼达和多巴哥',
  'Aztec Empire': '阿兹特克帝国',
  'Maya civilization': '玛雅文明',
  'Inca Empire': '印加帝国',
  Caribbean: '加勒比',
  China: '中国',
  Japan: '日本',
  Korea: '朝鲜/韩国',
  Mongolia: '蒙古',
  Taiwan: '台湾',
  'Tang dynasty': '唐朝',
  'Song dynasty': '宋朝',
  'Yuan dynasty': '元朝',
  'Ming dynasty': '明朝',
  'Qing dynasty': '清朝',
  'Edo period': '江户时代',
  Joseon: '朝鲜王朝',
  India: '印度',
  Pakistan: '巴基斯坦',
  Bangladesh: '孟加拉国',
  'Sri Lanka': '斯里兰卡',
  Nepal: '尼泊尔',
  Tibet: '西藏',
  Indonesia: '印度尼西亚',
  Malaysia: '马来西亚',
  Thailand: '泰国',
  Vietnam: '越南',
  Philippines: '菲律宾',
  Cambodia: '柬埔寨',
  Myanmar: '缅甸',
  'Mughal Empire': '莫卧儿帝国',
  Iran: '伊朗',
  Persia: '波斯',
  Turkey: '土耳其',
  'Ottoman Empire': '奥斯曼帝国',
  Iraq: '伊拉克',
  Syria: '叙利亚',
  Lebanon: '黎巴嫩',
  Israel: '以色列',
  Palestine: '巴勒斯坦',
  'Saudi Arabia': '沙特阿拉伯',
  Yemen: '也门',
  Afghanistan: '阿富汗',
  Uzbekistan: '乌兹别克斯坦',
  Kazakhstan: '哈萨克斯坦',
  Azerbaijan: '阿塞拜疆',
  Armenia: '亚美尼亚',
  Georgia: '格鲁吉亚',
  'Safavid Empire': '萨法维帝国',
  Australia: '澳大利亚',
  'New Zealand': '新西兰',
  'Papua New Guinea': '巴布亚新几内亚',
  Fiji: '斐济',
  Samoa: '萨摩亚',
  Tonga: '汤加',
  Hawaii: '夏威夷',
  Polynesia: '波利尼西亚',
  Melanesia: '美拉尼西亚',
  Micronesia: '密克罗尼西亚',
  France: '法国',
  Italy: '意大利',
  Spain: '西班牙',
  Germany: '德国',
  Netherlands: '荷兰',
  'Kingdom of the Netherlands': '荷兰王国',
  'United Kingdom': '英国',
  Belgium: '比利时',
  Austria: '奥地利',
  Switzerland: '瑞士',
  Portugal: '葡萄牙',
  Russia: '俄罗斯',
  Poland: '波兰',
  Greece: '希腊',
  Sweden: '瑞典',
  Norway: '挪威',
  Denmark: '丹麦',
  Ireland: '爱尔兰',
  'Czech Republic': '捷克',
  Hungary: '匈牙利',
  Ukraine: '乌克兰',
  'Republic of Florence': '佛罗伦萨共和国',
  'Republic of Venice': '威尼斯共和国',
  'Dutch Republic': '荷兰共和国',
  'Holy Roman Empire': '神圣罗马帝国',
  'Papal States': '教皇国',
  Unknown: '未知',
  'Spanish Netherlands': '西属尼德兰',
  'Southern Netherlands': '南尼德兰',
  'Northern Low Countries': '北低地国家',
  'Burgundian Netherlands': '勃艮第尼德兰',
  'Habsburg Netherlands': '哈布斯堡尼德兰',
  'Austrian Empire': '奥地利帝国',
  'Russian Empire': '俄罗斯帝国',
  'Kingdom of Prussia': '普鲁士王国',
  'Duchy of Milan': '米兰公国',
  'Duchy of Bavaria': '巴伐利亚公国',
  'Duchy of Brabant': '布拉班特公国',
  'Kingdom of Italy': '意大利王国',
  'Kingdom of Great Britain': '大不列颠王国',
  'United Kingdom of Great Britain and Ireland': '大不列颠及爱尔兰联合王国',
  'Free City of Kraków': '克拉科夫自由市',
  Cisleithania: '内莱塔尼亚',
  'Crown of Castile': '卡斯蒂利亚王室',
  'Crown of Aragon': '阿拉贡王室',
  'Duchy of Lorraine': '洛林公国',
  'Signoria di Correggio': '科雷焦领主国',
}

const zhTW: Record<string, string> = {
  ...zh,
  portrait: '肖像',
  'landscape painting': '風景畫',
  'religious art': '宗教藝術',
  'mythological painting': '神話畫',
  'history painting': '歷史畫',
  'genre art': '風俗畫',
  'still life': '靜物',
  'animal art': '動物畫',
  'abstract art': '抽象藝術',
  'figure painting': '人物畫',
  'self-portrait': '自畫像',
  allegory: '寓意畫',
  'marine art': '海景畫',
  cityscape: '城市風景',
  nude: '裸體畫',
  contemplative: '沉思',
  dramatic: '戲劇性',
  intimate: '親密',
  epic: '史詩',
  ancient: '古代',
  medieval: '中世紀',
  renaissance: '文藝復興',
  modern: '現代',
  contemporary: '當代',
  China: '中國',
  Taiwan: '臺灣',
  'Kingdom of the Netherlands': '荷蘭王國',
  'Dutch Republic': '荷蘭共和國',
  'United States': '美國',
  France: '法國',
  Italy: '義大利',
  Unknown: '未知',
}

const maps: Record<string, Record<string, string>> = {
  zh,
  'zh-TW': zhTW,
}

/** Translate a preference/filter option for display. Values stay English for storage. */
export function optionLabel(lang: string, value: string): string {
  if (!value) return value
  const map = maps[lang]
  if (!map) return value
  if (map[value]) return map[value]

  // Historical compound labels: "Holy Roman Empire / Italy"
  if (value.includes(' / ')) {
    return value
      .split(' / ')
      .map((part) => map[part.trim()] || part.trim())
      .join(' / ')
  }
  return value
}
