/** Curated global preference catalogs — not limited to the Western core dataset. */

export type OptionGroup = {
  id: string
  labelKey: string
  options: string[]
}

/** Genre / tradition chips spanning world art histories. */
export const GENRE_GROUPS: OptionGroup[] = [
  {
    id: 'universal',
    labelKey: 'prefsGroupUniversal',
    options: [
      'portrait',
      'landscape painting',
      'religious art',
      'mythological painting',
      'history painting',
      'genre art',
      'still life',
      'animal art',
      'abstract art',
      'figure painting',
      'self-portrait',
      'allegory',
      'marine art',
      'cityscape',
      'nude',
    ],
  },
  {
    id: 'east-asia',
    labelKey: 'prefsGroupEastAsia',
    options: [
      'ink wash painting',
      'shan shui',
      'literati painting',
      'handscroll',
      'hanging scroll',
      'ukiyo-e',
      'nihonga',
      'yamato-e',
      'screen painting',
      'bird-and-flower painting',
      'Chinese painting',
      'Japanese painting',
      'Korean painting',
    ],
  },
  {
    id: 'south-asia',
    labelKey: 'prefsGroupSouthAsia',
    options: [
      'Mughal miniature',
      'Persian miniature',
      'Rajput painting',
      'Pahari painting',
      'Indian painting',
      'thangka',
      'miniature painting',
      'Company style',
    ],
  },
  {
    id: 'se-asia-oceania',
    labelKey: 'prefsGroupSeAsiaOceania',
    options: [
      'Southeast Asian painting',
      'Balinese painting',
      'Indonesian painting',
      'Thai painting',
      'Vietnamese painting',
      'Aboriginal Australian art',
      'Oceanic art',
      'Pacific Islander art',
      'Maori art',
    ],
  },
  {
    id: 'africa-mena',
    labelKey: 'prefsGroupAfricaMena',
    options: [
      'African art',
      'Ethiopian art',
      'Egyptian painting',
      'Coptic art',
      'Islamic miniature',
      'Ottoman miniature',
      'Arabic calligraphy painting',
      'North African art',
      'West African art',
      'Contemporary African art',
    ],
  },
  {
    id: 'americas',
    labelKey: 'prefsGroupAmericas',
    options: [
      'Mesoamerican art',
      'pre-Columbian art',
      'Indigenous American art',
      'Native American art',
      'Latin American art',
      'Mexican muralism',
      'Caribbean art',
      'Andean art',
      'Brazilian painting',
      'American painting',
    ],
  },
  {
    id: 'europe-modern',
    labelKey: 'prefsGroupEuropeModern',
    options: [
      'Baroque',
      'Romanticism',
      'Impressionism',
      'Post-impressionism',
      'Expressionism',
      'Surrealism',
      'Cubism',
      'Realism',
      'Fauvism',
      'Symbolism',
    ],
  },
]

/** Painter country / civilization chips by world region. */
export const COUNTRY_GROUPS: OptionGroup[] = [
  {
    id: 'africa',
    labelKey: 'prefsRegionAfrica',
    options: [
      'Egypt',
      'Ethiopia',
      'Nigeria',
      'Ghana',
      'Senegal',
      'Mali',
      'Morocco',
      'Algeria',
      'Tunisia',
      'South Africa',
      'Kenya',
      'Congo',
      'Sudan',
      'Kingdom of Benin',
      'Mali Empire',
    ],
  },
  {
    id: 'americas',
    labelKey: 'prefsRegionAmericas',
    options: [
      'United States',
      'Mexico',
      'Canada',
      'Brazil',
      'Argentina',
      'Peru',
      'Chile',
      'Colombia',
      'Cuba',
      'Haiti',
      'Jamaica',
      'Trinidad and Tobago',
      'Aztec Empire',
      'Maya civilization',
      'Inca Empire',
      'Caribbean',
    ],
  },
  {
    id: 'east-asia',
    labelKey: 'prefsRegionEastAsia',
    options: [
      'China',
      'Japan',
      'Korea',
      'Mongolia',
      'Taiwan',
      'Tang dynasty',
      'Song dynasty',
      'Yuan dynasty',
      'Ming dynasty',
      'Qing dynasty',
      'Edo period',
      'Joseon',
    ],
  },
  {
    id: 'south-se-asia',
    labelKey: 'prefsRegionSouthSeAsia',
    options: [
      'India',
      'Pakistan',
      'Bangladesh',
      'Sri Lanka',
      'Nepal',
      'Tibet',
      'Indonesia',
      'Malaysia',
      'Thailand',
      'Vietnam',
      'Philippines',
      'Cambodia',
      'Myanmar',
      'Mughal Empire',
    ],
  },
  {
    id: 'mena-central',
    labelKey: 'prefsRegionMenaCentral',
    options: [
      'Iran',
      'Persia',
      'Turkey',
      'Ottoman Empire',
      'Iraq',
      'Syria',
      'Lebanon',
      'Israel',
      'Palestine',
      'Saudi Arabia',
      'Yemen',
      'Afghanistan',
      'Uzbekistan',
      'Kazakhstan',
      'Azerbaijan',
      'Armenia',
      'Georgia',
      'Safavid Empire',
    ],
  },
  {
    id: 'oceania',
    labelKey: 'prefsRegionOceania',
    options: [
      'Australia',
      'New Zealand',
      'Papua New Guinea',
      'Fiji',
      'Samoa',
      'Tonga',
      'Hawaii',
      'Polynesia',
      'Melanesia',
      'Micronesia',
    ],
  },
  {
    id: 'europe',
    labelKey: 'prefsRegionEurope',
    options: [
      'France',
      'Italy',
      'Spain',
      'Germany',
      'Netherlands',
      'United Kingdom',
      'Belgium',
      'Austria',
      'Switzerland',
      'Portugal',
      'Russia',
      'Poland',
      'Greece',
      'Sweden',
      'Norway',
      'Denmark',
      'Ireland',
      'Czech Republic',
      'Hungary',
      'Ukraine',
      'Republic of Florence',
      'Republic of Venice',
      'Dutch Republic',
      'Holy Roman Empire',
      'Papal States',
    ],
  },
]

/** Global eras — Western + major non-Western periods. */
export const ERA_OPTIONS = [
  'ancient',
  'classical-antiquity',
  'medieval',
  'islamic-golden-age',
  'song-yuan',
  'ming-qing',
  'edo-period',
  'mughal-era',
  'renaissance',
  'baroque',
  'neoclassical-romantic',
  'impressionist-era',
  'modern',
  'contemporary',
]

export const MOOD_OPTIONS = ['contemplative', 'dramatic', 'intimate', 'epic']

/** Expand a selected country/civilization chip into SPARQL/search synonyms. */
export function countrySearchTerms(label: string): string[] {
  const key = label.trim().toLowerCase()
  const map: Record<string, string[]> = {
    china: ['china', 'chinese', "people's republic of china", 'republic of china'],
    japan: ['japan', 'japanese'],
    korea: ['korea', 'korean', 'joseon', 'south korea', 'north korea'],
    joseon: ['joseon', 'korea', 'korean'],
    mongolia: ['mongolia', 'mongol'],
    taiwan: ['taiwan', 'republic of china'],
    'tang dynasty': ['tang', 'china', 'chinese'],
    'song dynasty': ['song dynasty', 'song', 'china'],
    'yuan dynasty': ['yuan', 'china', 'mongol'],
    'ming dynasty': ['ming', 'china'],
    'qing dynasty': ['qing', 'china'],
    'edo period': ['edo', 'japan', 'tokugawa'],
    india: ['india', 'indian', 'british raj'],
    pakistan: ['pakistan', 'pakistani'],
    bangladesh: ['bangladesh', 'bengali'],
    'sri lanka': ['sri lanka', 'ceylon'],
    nepal: ['nepal', 'nepalese'],
    tibet: ['tibet', 'tibetan'],
    indonesia: ['indonesia', 'indonesian', 'dutch east indies'],
    malaysia: ['malaysia', 'malay'],
    thailand: ['thailand', 'siam', 'thai'],
    vietnam: ['vietnam', 'vietnamese'],
    philippines: ['philippines', 'filipino'],
    cambodia: ['cambodia', 'khmer'],
    myanmar: ['myanmar', 'burma', 'burmese'],
    'mughal empire': ['mughal', 'mogul', 'india'],
    iran: ['iran', 'iranian', 'persia', 'persian'],
    persia: ['persia', 'persian', 'iran'],
    turkey: ['turkey', 'turkish', 'ottoman'],
    'ottoman empire': ['ottoman', 'turkey'],
    iraq: ['iraq', 'iraqi', 'mesopotamia'],
    syria: ['syria', 'syrian'],
    lebanon: ['lebanon', 'lebanese'],
    israel: ['israel', 'israeli'],
    palestine: ['palestine', 'palestinian'],
    'saudi arabia': ['saudi', 'arabia'],
    yemen: ['yemen', 'yemeni'],
    afghanistan: ['afghanistan', 'afghan'],
    uzbekistan: ['uzbekistan', 'uzbek'],
    kazakhstan: ['kazakhstan', 'kazakh'],
    azerbaijan: ['azerbaijan', 'azerbaijani'],
    armenia: ['armenia', 'armenian'],
    georgia: ['georgia', 'georgian'],
    'safavid empire': ['safavid', 'persia', 'iran'],
    egypt: ['egypt', 'egyptian'],
    ethiopia: ['ethiopia', 'ethiopian', 'abyssinia'],
    nigeria: ['nigeria', 'nigerian'],
    ghana: ['ghana', 'ghanaian'],
    senegal: ['senegal', 'senegalese'],
    mali: ['mali', 'malian'],
    morocco: ['morocco', 'moroccan'],
    algeria: ['algeria', 'algerian'],
    tunisia: ['tunisia', 'tunisian'],
    'south africa': ['south africa', 'south african'],
    kenya: ['kenya', 'kenyan'],
    congo: ['congo', 'congolese', 'zaire'],
    sudan: ['sudan', 'sudanese'],
    'kingdom of benin': ['benin', 'edo'],
    'mali empire': ['mali', 'mandé', 'mande'],
    'united states': ['united states', 'american', 'u.s.'],
    mexico: ['mexico', 'mexican'],
    canada: ['canada', 'canadian'],
    brazil: ['brazil', 'brazilian'],
    argentina: ['argentina', 'argentine'],
    peru: ['peru', 'peruvian'],
    chile: ['chile', 'chilean'],
    colombia: ['colombia', 'colombian'],
    cuba: ['cuba', 'cuban'],
    haiti: ['haiti', 'haitian'],
    jamaica: ['jamaica', 'jamaican'],
    'trinidad and tobago': ['trinidad', 'tobago'],
    'aztec empire': ['aztec', 'mexico'],
    'maya civilization': ['maya', 'mayan'],
    'inca empire': ['inca', 'peru'],
    caribbean: ['caribbean', 'west indies'],
    australia: ['australia', 'australian'],
    'new zealand': ['new zealand', 'aotearoa', 'māori', 'maori'],
    'papua new guinea': ['papua', 'new guinea'],
    fiji: ['fiji', 'fijian'],
    samoa: ['samoa', 'samoan'],
    tonga: ['tonga', 'tongan'],
    hawaii: ['hawaii', 'hawaiian'],
    polynesia: ['polynesia', 'polynesian'],
    melanesia: ['melanesia', 'melanesian'],
    micronesia: ['micronesia', 'micronesian'],
  }
  return map[key] || [key]
}

/** Expand a genre chip into search synonyms for SPARQL CONTAINS. */
export function genreSearchTerms(label: string): string[] {
  const key = label.trim().toLowerCase()
  const map: Record<string, string[]> = {
    'ink wash painting': ['ink wash', 'shuimo', 'sumi-e', 'ink painting', '水墨'],
    'shan shui': [
      'shan shui',
      'shanshui',
      'chinese landscape',
      'ink landscape',
      '山水',
      '山水画',
    ],
    'literati painting': ['literati', 'wenren', '文人', '文人画'],
    'chinese painting': [
      'chinese painting',
      'chinese art',
      'hanging scroll',
      'handscroll',
      '国画',
    ],
    'bird-and-flower painting': ['bird-and-flower', 'flower and bird', '花鸟', '花鳥'],
    handscroll: ['handscroll', '手卷'],
    'hanging scroll': ['hanging scroll', '立轴', '立軸'],
    'ukiyo-e': ['ukiyo-e', 'ukiyo'],
    nihonga: ['nihonga'],
    'yamato-e': ['yamato-e'],
    'japanese painting': ['japanese painting', 'japan'],
    'korean painting': ['korean painting', 'korea'],
    'mughal miniature': ['mughal', 'miniature'],
    'persian miniature': ['persian miniature', 'miniature'],
    'rajput painting': ['rajput'],
    'pahari painting': ['pahari'],
    'indian painting': ['indian painting', 'india'],
    thangka: ['thangka', 'tangka'],
    'miniature painting': ['miniature'],
    'aboriginal australian art': ['aboriginal', 'indigenous australian'],
    'oceanic art': ['oceanic', 'pacific'],
    'african art': ['african'],
    'ethiopian art': ['ethiopian'],
    'egyptian painting': ['egyptian'],
    'islamic miniature': ['islamic miniature', 'miniature'],
    'ottoman miniature': ['ottoman miniature', 'miniature'],
    'mesoamerican art': ['mesoamerican', 'aztec', 'maya'],
    'pre-columbian art': ['pre-columbian', 'precolumbian'],
    'indigenous american art': ['indigenous', 'native american'],
    'native american art': ['native american'],
    'latin american art': ['latin american'],
    'mexican muralism': ['muralism', 'mural'],
    'caribbean art': ['caribbean'],
    'american painting': ['american'],
    impressionism: ['impressionism', 'impressionist'],
    'post-impressionism': ['post-impression'],
    surrealism: ['surreal'],
    cubism: ['cubism', 'cubist'],
  }
  return map[key] || [key]
}

/** Birth-year ranges for global + Western eras. */
export function eraYearRanges(era: string): [number, number] | null {
  const ranges: Record<string, [number, number]> = {
    ancient: [-4000, 499],
    'classical-antiquity': [-800, 600],
    medieval: [500, 1399],
    'islamic-golden-age': [700, 1299],
    'song-yuan': [960, 1368],
    'ming-qing': [1368, 1912],
    'edo-period': [1603, 1868],
    'mughal-era': [1526, 1857],
    renaissance: [1400, 1599],
    baroque: [1550, 1749],
    'neoclassical-romantic': [1700, 1849],
    'impressionist-era': [1800, 1899],
    modern: [1850, 1949],
    contemporary: [1900, 2100],
  }
  return ranges[era] || null
}

export function allGenreOptions(): string[] {
  return GENRE_GROUPS.flatMap((g) => g.options)
}

export function allCountryOptions(): string[] {
  return COUNTRY_GROUPS.flatMap((g) => g.options)
}
